Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = [] 

mtd_nor = ['mtd_nor.c']

mtd_nand = ['mtd_nand.c']

if GetDepend(['RT_USING_MTD_NOR']):
    src = src + mtd_nor
if GetDepend(['RT_USING_MTD_NAND']):
    src = src + mtd_nand

CPPPATH = [cwd + '/../include']
group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
