from building import *

cwd = GetCurrentDir()
src = ['drv_lcd.c']
CPPPATH = [cwd]

if GetDepend(['BSP_USING_LCD_QRCODE']):
    src = src + ['lcd_qrcode.c']

if GetDepend(['BSP_USING_LCD_SAMPLE']):
    src = src + ['demo/lcd_sample.c']

group = DefineGroup('Drivers', src, depend = ['BSP_USING_SPI_LCD'], CPPPATH = CPPPATH)

Return('group')
