Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend(['UTEST_MM_API_TC', 'RT_USING_SMART']):
    src += ['mm_api_tc.c', 'mm_libcpu_tc.c']

if GetDepend(['UTEST_MM_LWP_TC', 'RT_USING_SMART']):
    src += ['mm_lwp_tc.c']

group = DefineGroup('utestcases', src, depend = ['RT_USING_UTESTCASES'], CPPPATH = CPPPATH)

Return('group')
