import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

# The set of source files associated with this SConscript file.
if GetDepend('RT_USING_USB_DEVICE'):
    src += ['src/usbd_core.c', 'src/usbd_int.c', 'src/usbd_sdr.c']

CPPPATH = [cwd + '/inc']

group = DefineGroup('usbd_library', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
