from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

if GetDepend(['RT_INPUT_MISC_PWRKEY_RK8XX']):
    src += ['pwrkey-rk8xx.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
