# for board compiling
import os
import rtconfig
from building import *
from buildutil import *

cwd = GetCurrentDir()
BOARD_NAME = GetStringFromConfig(cwd + '/..', 'RT_BOARD_NAME')
objs = SConscript(os.path.join(cwd, BOARD_NAME + '/SConscript'), variant_dir = 'board/' + BOARD_NAME, duplicate = 0)
objs += SConscript(os.path.join(cwd, 'common/SConscript'), variant_dir = 'board/common', duplicate = 0)

Return('objs')
