# RT-Thread building script for component

from building import *


Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split("""
NuPinConfig/nutool_pincfg.c
""")

src += Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd, cwd + '/NuPinConfig']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
