Import('RTT_ROOT')
Import('rtconfig')
from building import *

src	= Split('''
adler32.c
compress.c
crc32.c
deflate.c
gzio.c
infback.c
inffast.c
inflate.c
inftrees.c
trees.c
uncompr.c
zutil.c
''')
CPPPATH = [RTT_ROOT + '/components/rtgui/common/libz']

group = DefineGroup('libz', src, depend = ['RTGUI_IMAGE_PNG'], CPPPATH = CPPPATH)

Return('group')
