Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c') + Glob('*.cpp')
CPPPATH = cwd

group = DefineGroup('Platform', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
