from building import *

cwd = GetCurrentDir()
src = [] 

CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['RT_USING_RTC']):
    src = src + ['rtc.c']
    if GetDepend(['RT_USING_ALARM']): 
        src = src + ['alarm.c']
    if GetDepend(['RT_USING_SOFT_RTC']): 
        src = src + ['soft_rtc.c']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_RTC'], CPPPATH = CPPPATH)

Return('group')