Import('RTT_ROOT')
from building import *

src	= Glob('*.c')
CPPPATH = [RTT_ROOT + '/components/libc/minilibc']
CPPDEFINES = ['RT_USING_MINILIBC']
group = DefineGroup('minilibc', src, 
	depend = ['RT_USING_MINILIBC'], 
	CPPPATH = CPPPATH,
	CPPDEFINES = CPPDEFINES
	)

Return('group')
