Import('RTT_ROOT')
from building import *

src	= Glob('*.c')
CPPPATH = [RTT_ROOT + '/components/libc/minilibc']
group = DefineGroup('minilibc', src, depend = ['RT_USING_MINILIBC'], CPPPATH = CPPPATH)

Return('group')
