import os
from building import *

src = Split("""
    src/rt-thread_balance_stub.c
    src/x509_crt_bundle.S
    src/port.c
    src/port_common.c
""")

CPPPATH = Split(
    """
    include
    include/freertos
""")

group = DefineGroup('idf_port', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
