import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
CMSIS/Device/ST/STM32L1xx/Source/Templates/system_stm32L1xx.c
STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_dma.c
STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_cortex.c
STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_crc.c
STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_pwr.c
STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_rcc.c
STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_rcc_ex.c
STM32L1xx_HAL_Driver/Src/stm32L1xx_hal.c
STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cryp.c
STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cryp_ex.c
STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_sram.c
STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_gpio.c
""")



if GetDepend(['RT_USING_SERIAL']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_uart.c']
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_usart.c']

if GetDepend(['RT_USING_I2C']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_spi.c']
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_ll_spi.c']

if GetDepend(['RT_USING_USB']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_pcd.c']
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_pcd_ex.c']
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_ll_usb.c']


if GetDepend(['RT_USING_CAN']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_can.c']

if GetDepend(['RT_USING_HWTIMER']) or GetDepend(['RT_USING_PWM']) or GetDepend(['RT_USING_PULSE_ENCODER']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_tim.c']
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_tim_ex.c']

if GetDepend(['RT_USING_ADC']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_adc.c']
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_adc_ex.c']

if GetDepend(['RT_USING_RTC']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_rtc.c']
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_rtc_ex.c']

if GetDepend(['RT_USING_WDT']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_iwdg.c']
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_wwdg.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_ll_sdmmc.c']
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_sd.c']

if GetDepend(['RT_USING_AUDIO']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_i2s.c']

if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_flash.c']
    src += ['STM32L1xx_HAL_Driver/Src/stm32L1xx_hal_flash_ex.c']

path = [cwd + '/CMSIS/Device/ST/STM32L1xx/Include',
    cwd + '/STM32L1xx_HAL_Driver/Inc']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
