arm_convolution_example_f32.c File Reference
GCC/arm_convolution_example_f32.c File Reference
Macros
#define MAX_BLOCKSIZE
#define DELTA
#define SNR_THRESHOLD
Functions
int32_t main (void)
Variables
float32_t Ak [MAX_BLOCKSIZE]
float32_t Bk [MAX_BLOCKSIZE]
float32_t AxB [MAX_BLOCKSIZE *2]
float32_t testInputA_f32 [64]
float32_t testInputB_f32 [64]
const float testRefOutput_f32 [127]
uint32_t srcALen
uint32_t srcBLen
uint32_t outLen
float32_t snr
Macro Definition Documentation
#define DELTA
#define MAX_BLOCKSIZE
Referenced by main().
#define SNR_THRESHOLD
Referenced by main().
Function Documentation
int32_t main (void)
References Ak, arm_cfft_radix4_f32(), arm_cfft_radix4_init_f32(), arm_cmplx_mult_cmplx_f32(), arm_copy_f32(), arm_fill_f32(), ARM_MATH_SUCCESS, arm_snr_f32(), AxB, Bk, MAX_BLOCKSIZE, outLen, snr, SNR_THRESHOLD, srcALen, srcBLen, status, testInputA_f32, testInputB_f32, and testRefOutput_f32.
Variable Documentation
float32_t Ak[MAX_BLOCKSIZE]
float32_t AxB[MAX_BLOCKSIZE *2]
float32_t Bk[MAX_BLOCKSIZE]
uint32_t outLen
float32_t snr
uint32_t srcALen
uint32_t srcBLen
float32_t testInputA_f32[64]
float32_t testInputB_f32[64]
const float testRefOutput_f32[127]