import rtconfig
from building import *

if rtconfig.EFM32_BOARD == 'EFM32_GXXX_DK':
    src = Glob('*.c')
    CPPPATH = [GetCurrentDir()]

    group = DefineGroup('EFM32_GXXX_DK', src, depend = [''], CPPPATH = CPPPATH)
    Return('group')
else:
    empty = []
    Return('empty')
