from building import *

group = []

if not GetDepend(['RT_USING_DM', 'RT_USING_LED']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['led.c']

if GetDepend(['RT_LED_GPIO']):
    src += ['led-gpio.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
