Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

#remove other no use files
#SrcRemove(src, '*.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')