import rtconfig
Import('RTT_ROOT')
from building import *

src_bsp = ['application.c', 'startup.c', 'board.c']
src_drv = ['console.c', 'led.c']

if GetDepend('RT_USING_DFS'):
	src_drv += ['sdcard.c']

if GetDepend('RT_USING_LWIP'):
	src_drv += ['dm9000.c']

if GetDepend('RT_USING_RTGUI'):
    src_drv += ['touch.c', 'key.c', 'calibration.c']

if GetDepend('RT_USING_FTK'):
    src_drv += ['touch.c', 'key.c']

if GetDepend('RT_USING_RTI'):
    src_drv += ['rti_stub.c']
		
if GetDepend('RT_USING_RTGUI') or GetDepend('RT_USING_FTK'):
	if rtconfig.RT_USING_LCD_TYPE == 'PNL_A70':
		src_drv += ['lcd_a70.c']
	elif rtconfig.RT_USING_LCD_TYPE == 'PNL_N35':
		src_drv += ['lcd_n35.c']
	elif rtconfig.RT_USING_LCD_TYPE == 'PNL_T35':
		src_drv += ['lcd_t35.c']
	elif rtconfig.RT_USING_LCD_TYPE == 'PNL_X35':
                src_drv += ['lcd_x35.c']

src	= File(src_bsp + src_drv)
CPPPATH = [GetCurrentDir()]
group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
