from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src =  ['irq.c']
src += ['irq_port.c']
src += ['sys_clk.c']
src += ['tick.c']
src += ['target_get.c']
src += ['devices.c']

group = DefineGroup('sys', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
