Import('RTT_ROOT')
Import('rtconfig')
from building import *
import copy

cwd     = os.path.join(str(Dir('#')), 'drivers')
src = Glob('*.c')
CPPPATH = [cwd]

# remove no need file.
if GetDepend('RT_USING_LWIP') == False:
    SrcRemove(src, ['luminaryif.c']) # need remove file list.

if GetDepend('RT_USING_DFS') == False:
    SrcRemove(src, ['sdcard.c']) # need remove file list.

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
