Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split("""
core/rt_core.c
core/rt_driver.c
core/rt_usbhost.c
core/rt_hub.c
""")

if GetDepend('RT_USBH_ADK'):
	src += Glob('class/rt_adk.c')
	src += Glob('class/rt_adkapp.c')

if GetDepend('RT_USBH_MSTORAGE'):
	src += Glob('class/rt_mass.c')
	src += Glob('class/rt_udisk.c')

if GetDepend('RT_USBH_HID'):
	src += Glob('class/rt_hid.c')

if GetDepend('RT_USBH_HID_MOUSE'):
	src += Glob('class/rt_umouse.c')

if GetDepend('RT_USBH_HID_KEYBOARD'):
	src += Glob('class/rt_ukbd.c')

CPPPATH = [cwd, cwd + '/class', cwd + '/core', \
	cwd + '/include', cwd + '../../../include']

group = DefineGroup('rt_usbh', src, depend = ['RT_USING_USB_HOST'], CPPPATH = CPPPATH)

Return('group')
