# RT-Thread building script for component

Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split('''
''')
src += [cwd + '/../system_LPC54608.c']
CPPPATH = [cwd + '/../../../CMSIS/Include']
CPPPATH = [cwd + '/..']
CPPDEFINES = ['CORE_M4']
CPPDEFINES += ['CPU_LPC54608']
CPPDEFINES += ['CPU_LPC54608J512ET180=1']

# add for startup script 
if rtconfig.CROSS_TOOL == 'keil':
    src += ['startup_LPC54608.s']
	
group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LIBS=['keil_lib_power'], LIBPATH=[cwd])

Return('group')
