import os
from building import *

cwd = GetCurrentDir()
objs = []

for name in os.listdir(cwd):
    path = os.path.join(cwd, name)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs += SConscript(os.path.join(name, 'SConscript'))

Return('objs')
