# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
""")

if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_uart.c']
if GetDepend(['RT_USING_PIN']):
    src += ['drv_pin.c']
if GetDepend(['RT_USING_SPI']):
    src += ['drv_spi.c']
if GetDepend(['RT_USING_I2C']):
    src += ['drv_i2c.c']
if GetDepend(['BSP_USING_EXT_SRAM']):
    src += ['drv_sram.c']
if GetDepend(['BSP_USING_NOR_FLASH']):
    src += ['drv_nor_flash.c']
if GetDepend(['RT_USING_PWM']):
    src += ['drv_pwm.c']
if GetDepend(['RT_USING_RTC']):
    src += ['drv_rtc.c']
if GetDepend(['RT_USING_HWTIMER']):
    src += ['drv_timer.c']
if GetDepend(['RT_USING_WDT']):
    src += ['drv_wdt.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
