# for module compiling
import os
Import('RTT_ROOT')
Import('env')
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

# STM32F756xx || STM32F746xx || STM32F745xx || STM32F767xx  ||
# STM32F769xx || STM32F777xx || STM32F779xx || STM32F722xx  ||
# STM32F723xx || STM32F732xx || STM32F733xx || STM32F730xx  || STM32F750xx
# You can select chips from the list above
env.Append(CPPDEFINES = ['STM32F769xx'])

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
