Import('RTT_ROOT')
Import('rtconfig')
from building import *

# The set of source files associated with this SConscript file.
cwd     = GetCurrentDir()
src = Glob('driverlib/*.c')

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
	src += ['startup/gcc/startup_LPC17xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
	src += ['startup/arm/start_rvds.S']
elif rtconfig.CROSS_TOOL == 'iar':
	src += ['startup/iar/start_iar.S']

CPPPATH = [cwd]

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
