# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = ['termios.c']
CPPPATH = [cwd]

group = DefineGroup('Libc', src, depend = ['RT_USING_POSIX_TERMIOS'], CPPPATH = CPPPATH)

Return('group')
