# RT-Thread building script for gui

from building import *
import rtconfig

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

if rtconfig.ARCH == 'sim':
    group = DefineGroup('GuiEngine', src, depend = ['RTGUI_IMAGE_LODEPNG'], CPPPATH = CPPPATH)
else:
    group = DefineGroup('GuiEngine', src, depend = ['RTGUI_IMAGE_LODEPNG', 'RT_USING_LIBC'], CPPPATH = CPPPATH)

Return('group')
