from building import *

cwd     = GetCurrentDir()
list    = os.listdir(cwd)
objs    = []

if GetDepend('RT_USING_DM_FIRMWARE'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')

