Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
path = [cwd + '/inc']
libs = ['']
libpath = [cwd + '/libs']

if rtconfig.PLATFORM in ['gcc']:
    libs += ['libsmartconfig_armcm4_gcc']
elif rtconfig.PLATFORM in ['iccarm']:
    libs += ['libsmartconfig_armcm4_iar']

group = DefineGroup('Libraries', src, depend = ['RT_USING_SMARTCONFIG_LIB'], CPPPATH = path, LIBS = libs, LIBPATH = libpath)

Return('group')

