import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
system_ch32f20x.c
board.c
''')

path =  [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)
Return('group')
