# RT-Thread building script for component
Import('RTT_ROOT')

from building import *

cwd = GetCurrentDir()
group = []
if GetDepend('NU_PKG_USING_ADC_TOUCH'):
    src = Glob('*.c') + Glob('*.cpp')
    CPPPATH = [cwd]
    group = DefineGroup('nu_pkgs_adc_touch', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
