import os
import rtconfig
Import('RTT_ROOT')
from building import *

CPPDEFINES = []
# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Glob('src/*.c')
# Remove retarget.c As there is a HardFaultHandler in it
for src_f in src:
    if 'retarget.c' in src_f.path:
        src.remove(src_f)
        
path = [cwd + '/inc']

group = DefineGroup('StdDriver', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')

