from building import *
cwd  = GetCurrentDir()
objs = []
list = os.listdir(cwd)

# for d in list:
#     path = os.path.join(cwd, d)
#     if os.path.isfile(os.path.join(path, 'SConscript')):
#         objs = objs + SConscript(os.path.join(d, 'SConscript'))


src     = Glob('*.c')
CPPPATH = [cwd + '/include']

group   = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SDHCI'], CPPPATH = CPPPATH)

Return('group')
