from building import *

group = []

if not GetDepend(['RT_USING_SDHCI']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/include']

src = []
src += Glob('*.c')
src += Glob('src/*.c')
src += Glob('sdhci-platform/*.c')

group = DefineGroup('sdhci-drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
