# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

src += Glob('*.S')

group = DefineGroup('Libcpu', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
