# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]


if rtconfig.PLATFORM == 'gcc':
    src += Glob('*_gcc.S')

group = DefineGroup('cpu', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
