from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')

# remove no need file.
if GetDepend('RT_USING_DFS_WINSHAREDIR') == False:
    SrcRemove(src, 'dfs_win32.c')
if GetDepend('RT_USING_MODULE') == False:
    SrcRemove(src, ['module_win32.c'])
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
