Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend('RT_UTEST_TC_USING_DFS_V2_AF_UNIX'):
    cases = []
    if GetDepend('RT_UTEST_DFS_V2_AF_UNIX_NODE'):
        cases += ['tc_af_unix_node.c']
    if GetDepend('RT_UTEST_DFS_V2_AF_UNIX_IPC'):
        cases += ['tc_af_unix_ipc.c']
    if GetDepend('RT_UTEST_DFS_V2_AF_UNIX_POLL'):
        cases += ['tc_af_unix_poll.c']
    if GetDepend('RT_UTEST_DFS_V2_AF_UNIX_NAMESPACE'):
        cases += ['tc_af_unix_namespace.c']
    if GetDepend('RT_UTEST_DFS_V2_AF_UNIX_RIGHTS'):
        cases += ['tc_af_unix_rights.c']
    if cases:
        src += ['tc_af_unix_common.c'] + cases

group = DefineGroup('utestcases', src,
                    depend = ['RT_USING_UTESTCASES', 'RT_USING_DFS_V2', 'RT_USING_AF_UNIX'],
                    CPPPATH = CPPPATH)

Return('group')
