from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

if GetDepend('RT_USING_DFS_ELMFAT') == False:
    SrcRemove(src, 'dwc_ahsata.c')
    SrcRemove(src, 'libata.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
