# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Split('''
context_gcc.S
cpu.c
cpu_gcc.S
mmu.c
startup_gcc.S
vector_gcc.S
''')
CPPPATH = [cwd]

group = DefineGroup('CPU', src, depend = [''], CPPPATH = CPPPATH)

# build for sub-directory
list = os.listdir(cwd)
objs = []

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
group = group + objs


Return('group')
