# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('*.S')
CPPPATH = [cwd, cwd + '/include']
bsp_path = Dir('#').abspath

if GetDepend('RT_USING_SMP'):
    core_model = 'mp'
else:
    core_model = 'up'

src += Glob(core_model + '/*.S')

if GetDepend('RT_USING_OFW') == False:
    SrcRemove(src, ['setup.c', 'cpu_psci.c', 'psci.c'])
else:
    if GetDepend('RT_BUILTIN_FDT_PATH'):
        dtb_path = os.path.join(bsp_path, GetDepend('RT_BUILTIN_FDT_PATH').strip('"'))
        obj_path = os.path.join(os.getcwd(), 'builtin_fdt_gcc.o')
        if os.path.exists(dtb_path) and os.path.exists(obj_path):
            dtb_mtime = os.path.getmtime(dtb_path)
            obj_mtime = os.path.getmtime(obj_path)
            if dtb_mtime > obj_mtime:
                os.remove(obj_path)

if GetDepend('RT_USING_PIC') == True:
    SrcRemove(src, ['gicv3.c', 'gic.c', 'gtimer.c', 'interrupt.c'])

if GetDepend('RT_CLOCK_TIME_ARM_ARCH') == True:
    SrcRemove(src, ['gtimer.c'])

group = DefineGroup('CPU', src, depend = [''], CPPPATH = CPPPATH)

# build for sub-directory
list = os.listdir(cwd)
objs = []

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
group = group + objs


Return('group')
