import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = Glob('src/*.c')

path = [cwd + '/inc']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
