import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

path = [cwd, cwd + '/MK64F12']
src = Glob('MK64F12/*.c')

src += ['system_MK64F12.c']

#add for startup script
if rtconfig.PLATFORM in ['gcc']:
     src = src + ['TOOLCHAIN_GCC_ARM/startup_MK64F12.S']
     src = src + ['TOOLCHAIN_GCC_ARM/startup.c']
     path += [cwd + 'TOOLCHAIN_GCC_ARM']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
     src = src + ['TOOLCHAIN_ARM_STD/startup_MK64F12.s']
# elif rtconfig.PLATFORM in ['iccarm']:

CPPDEFINES = ['CPU_MK64FN1M0VLL12']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES=CPPDEFINES)
#CPPDEFINES = CPPDEFINES)

Return('group')
