# Sunxi Read/Write Platform Codec
obj-$(SND_CODEC_SUNXI_RWFUNC) += sunxi_rw_func.o

# Sun8iw19p1 Platform Codec
obj-$(CONFIG_SND_CODEC_SUN8IW18_AUDIOCODEC) += sun8iw18-codec.o

# Sun8iw19p1 Platform Codec
obj-$(CONFIG_SND_CODEC_SUN8IW19_AUDIOCODEC) += sun8iw19-codec.o

# Sun8iw20p1 Platform Codec
obj-$(CONFIG_SND_CODEC_SUN8IW20_AUDIOCODEC) += sun8iw20-codec.o

# Common dummy_codec
obj-y += dummy_codec.o

# AC108 Codec
obj-$(CONFIG_SND_CODEC_AC108) += ac108.o
