from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd + '/../include']

if GetDepend(['RT_HWCRYPTO_RNG_ROCKCHIP']):
    src += ['hw-rng-rockchip.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
