import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]

src = []
if GetDepend(['RT_USING_LWIP']):
	src += Split('''
		amebaz_wlan.c
		''')

group = DefineGroup('amebaz_wlan', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
