import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]

src = []
if GetDepend(['RT_USING_LWIP']):
        src += ['drv_wifi.c', 'drv_wlan.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
