# RT-Thread building script for component

from building import *


Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split("""
nutool_pincfg/nutool_pincfg.c
""")
src += Glob('*.c') + Glob('*.cpp') + Glob('*.S')
CPPPATH = [cwd, cwd + '/nutool_pincfg']

group = DefineGroup('board', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
