Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
stm32f4xx_it.c
usart.c
""")

if GetDepend(['RT_USING_EXT_SDRAM']):
    src += ['drv_sdram.c']

if GetDepend(['RT_USING_I2C']):
    src += ['drv_i2c.c']

if GetDepend(['RT_USING_ILI9341_LCD']):
    src += ['drv_lcd.c']

if GetDepend(['RT_USING_STMPE811_TOUCH']):
    src += ['drv_touch.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
