import copy
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Glob('*.c')

src += ['system_config/armv7a/cache.c']
if rtconfig.PLATFORM in ['gcc']:
    src += ['system_config/armv7a/gcc/cp15.S']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['system_config/armv7a/ewarm/cp15.S']

if GetDepend(['RT_USING_CPSW0_PORT1']) or GetDepend(['RT_USING_CPSW0_PORT2']):
    src += ['drivers/cpsw.c']
    src += ['drivers/phy.c']
    src += ['drivers/mdio.c']
    src += ['third_party/lwip-1.4.0/ports/cpsw/netif/cpswif.c']
    CPPPATH += [cwd + '/third_party/lwip-1.4.0']

CPPPATH += [
    cwd + '/include',
    cwd + '/include/hw',
]

group = DefineGroup('StarterWare', src, depend = [''], CPPPATH = CPPPATH)

if GetDepend(['RT_USING_CPSW0_PORT1']) or GetDepend(['RT_USING_CPSW0_PORT2']):
    src = ['platform/evmAM335x/cpsw.c']
    group += DefineGroup('Platform', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
