import os
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
''')

path =  [cwd]

# FT32F072x8 || FT32F072xB
# You can select chips from the list above
CPPDEFINES = ['FT32F072xB']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
