# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []

CPPPATH = [cwd]
CPPDEFINES = []

src += Split("""
    std/startup/start.S
    std/startup/start_load.c
    std/startup/system_bl702.c
    std/startup/interrupt.c
""")

src += Split("""
    std/src/bl702_aon.c
    std/src/bl702_common.c
    std/src/bl702_clock.c
    std/src/bl702_ef_cfg.c
    std/src/bl702_glb.c
    std/src/bl702_hbn.c
    std/src/bl702_l1c.c
    std/src/bl702_pds.c 
    std/src/bl702_sflash_ext.c
    std/src/bl702_xip_sflash_ext.c
    std/src/bl702_sf_cfg_ext.c
""")
src += ['std/port/bl702_clock.c']

CPPPATH += [cwd + r'/std/include',
        cwd + r'/std/include/hardware']

if GetDepend('BSP_USING_ROMAPI'):
    src += Split("""
        std/src/bl702_romapi.c
    """)
    CPPDEFINES += ['BFLB_USE_ROM_DRIVER']

CPPDEFINES += ['CONFIG_IRQ_NUM=80', 'BFLB_USE_HAL_DRIVER', 'BL702', 'default_interrupt_handler=SW_handler']
LOCAL_CFLAGS = ' -DARCH_RISCV'

group = DefineGroup('bl702', src, depend = ['BSP_USING_BL70X'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LOCAL_CFLAGS = LOCAL_CFLAGS)

Return('group')

