from building import *

cwd = GetCurrentDir()
group = []
src = Glob('*.c')
CPPPATH = [cwd]

group = group + DefineGroup('LVGL-demo', src, depend = ['BSP_USING_LVGL', 'BSP_USING_LVGL_DEMO'], CPPPATH = CPPPATH)

Return('group')
