Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
drv_irq.c
""")

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']

if GetDepend(['RT_USING_SERIAL']):
    if GetDepend(['RT_USING_SERIAL_V2']):
        src += ['drv_usart_v2.c']
    else:
        src += ['drv_usart.c']

if GetDepend(['RT_USING_SPI']):
    src += ['drv_spi.c']

if GetDepend(['RT_USING_QSPI']):
    src += ['drv_qspi.c']

if GetDepend(['RT_USING_I2C']):
    src += ['drv_i2c.c']
    if GetDepend(['RT_USING_I2C_BITOPS']):
        src += ['drv_soft_i2c.c']

if GetDepend(['BSP_USING_ETH', 'RT_USING_LWIP']):
    src += ['drv_eth.c']

if GetDepend(['RT_USING_ADC']):
    src += ['drv_adc.c']

if GetDepend(['RT_USING_DAC']):
    src += ['drv_dac.c']

if GetDepend(['RT_USING_CAN']):
    src += ['drv_can.c']

if GetDepend(['RT_USING_RTC']):
    src += ['drv_rtc.c']

if GetDepend(['RT_USING_WDT']):
    src += ['drv_wdt.c']

if GetDepend(['RT_USING_HWTIMER']):
    src += ['drv_hwtimer.c']

if GetDepend(['RT_USING_PULSE_ENCODER']):
    src += ['drv_pulse_encoder.c']

if GetDepend(['RT_USING_PWM']):
    src += ['drv_pwm.c']

if GetDepend(['RT_USING_PM']):
    src += ['drv_pm.c']
    src += ['drv_wktm.c']

src += ['drv_common.c']

if GetDepend('RT_USING_HWCRYPTO'):
    src += ['drv_crypto.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['drv_sdio.c']

if GetDepend(['BSP_USING_EXMC', 'BSP_USING_SDRAM']):
    src += ['drv_sdram.c']

if GetDepend(['BSP_USING_EXMC', 'BSP_USING_NAND']):
    src += ['drv_nand.c']
    
if GetDepend(['BSP_USING_USBD']):
    src += ['drv_usbd.c']

if GetDepend(['BSP_USING_USBH']):
    src += ['drv_usbh.c']

if GetDepend(['BSP_USING_ON_CHIP_FLASH', 'SOC_SERIES_HC32F4']):
    src += ['drv_flash/drv_flash_f4.c']

path = [cwd]

if GetDepend('BSP_USING_ON_CHIP_FLASH'):
    path += [cwd + '/drv_flash']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
