Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
drv_irq.c
""")

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']

if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_usart.c']

if GetDepend(['RT_USING_HWTIMER']):
    src += ['drv_hwtimer.c']

if GetDepend(['RT_USING_PWM']):
    src += ['drv_pwm.c']

if GetDepend(['RT_USING_PULSE_ENCODER']):
    src += ['drv_pulse_encoder.c']

if GetDepend(['RT_USING_SPI']):
    src += ['drv_spi.c']

if GetDepend(['RT_USING_QSPI']):
    src += ['drv_qspi.c']

if GetDepend(['RT_USING_I2C', 'RT_USING_I2C_BITOPS']):
    src += ['drv_soft_i2c.c']

if GetDepend(['BSP_USING_ETH', 'RT_USING_LWIP']):
    src += ['drv_eth.c']

if GetDepend(['RT_USING_ADC']):
    src += ['drv_adc.c']

if GetDepend(['RT_USING_DAC']):
    src += ['drv_dac.c']

if GetDepend(['RT_USING_CAN']):
    src += ['drv_can.c']

if GetDepend(['RT_USING_PM']):
    src += ['drv_pm.c']

if GetDepend(['RT_USING_RTC']):
    src += ['drv_rtc.c']

if GetDepend(['RT_USING_ON_CHIP_FLASH']):
    src += ['drv_flash.c']

if GetDepend(['RT_USING_WDT']):
    src += ['drv_wdt.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['drv_sdio.c']

if GetDepend(['RT_USING_USBD']):
    src += ['drv_usbd.c']

if GetDepend(['RT_USING_USBH']):
    src += ['drv_usbh.c']


path = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
