import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
application.c
startup.c
""")

# add UI engine demo.
if GetDepend('PKG_USING_GUIENGINE'):
    src += ['rtgui_demo.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
