from building import *
import rtconfig
cwd     = GetCurrentDir()
src = ['MM32L3xx/Source/system_MM32L3xx.c']
CPPPATH = [cwd + '/CMSIS/KEIL_CORE', cwd + '/MM32L3xx/Include',  cwd + '/MM32L3xx/Source', cwd + '/MM32L3xx/HAL_lib/inc']

src += Glob('MM32L3xx/HAL_lib/src/*.c')
CPPDEFINES = ['USE_STDPERIPH_DRIVER']

if rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['MM32L3xx/Source/KEIL_StartAsm/startup_MM32L3xx.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['MM32L3xx/Source/IAR_StartAsm/startup_MM32L3xx.s']
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
