arm_fft_bin_example_f32.c File Reference
GCC/arm_fft_bin_example_f32.c File Reference
Macros
#define TEST_LENGTH_SAMPLES
Functions
int32_t main (void)
Variables
float32_t testInput_f32_10khz [TEST_LENGTH_SAMPLES]
static float32_t testOutput [TEST_LENGTH_SAMPLES/2]
uint32_t fftSize
uint32_t ifftFlag
uint32_t doBitReverse
uint32_t refIndex
uint32_t testIndex
Macro Definition Documentation
#define TEST_LENGTH_SAMPLES
Function Documentation
int32_t main (void)
References arm_cfft_f32(), arm_cfft_sR_f32_len1024, arm_cmplx_mag_f32(), ARM_MATH_SUCCESS, ARM_MATH_TEST_FAILURE, arm_max_f32(), doBitReverse, fftSize, ifftFlag, refIndex, status, testIndex, testInput_f32_10khz, and testOutput.
Variable Documentation
uint32_t doBitReverse
uint32_t fftSize
uint32_t ifftFlag
uint32_t refIndex
uint32_t testIndex
float32_t testInput_f32_10khz[TEST_LENGTH_SAMPLES]
Referenced by main().
float32_t testOutput[TEST_LENGTH_SAMPLES/2] static