/*
 * Copyright (c) 2021-2024 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */


#ifndef HPM_PMIC_IOMUX_H
#define HPM_PMIC_IOMUX_H

/* PIOC_PY00_FUNC_CTL function mux definitions */
#define PIOC_PY00_FUNC_CTL_PGPIO_Y_00          IOC_PAD_FUNC_CTL_ALT_SELECT_SET(0)
#define PIOC_PY00_FUNC_CTL_PURT_TXD            IOC_PAD_FUNC_CTL_ALT_SELECT_SET(1)
#define PIOC_PY00_FUNC_CTL_PTMR_COMP_0         IOC_PAD_FUNC_CTL_ALT_SELECT_SET(2)
#define PIOC_PY00_FUNC_CTL_SOC_PY_00           IOC_PAD_FUNC_CTL_ALT_SELECT_SET(3)

/* PIOC_PY01_FUNC_CTL function mux definitions */
#define PIOC_PY01_FUNC_CTL_PGPIO_Y_01          IOC_PAD_FUNC_CTL_ALT_SELECT_SET(0)
#define PIOC_PY01_FUNC_CTL_PURT_RXD            IOC_PAD_FUNC_CTL_ALT_SELECT_SET(1)
#define PIOC_PY01_FUNC_CTL_PTMR_COMP_1         IOC_PAD_FUNC_CTL_ALT_SELECT_SET(2)
#define PIOC_PY01_FUNC_CTL_SOC_PY_01           IOC_PAD_FUNC_CTL_ALT_SELECT_SET(3)

/* PIOC_PY02_FUNC_CTL function mux definitions */
#define PIOC_PY02_FUNC_CTL_PGPIO_Y_02          IOC_PAD_FUNC_CTL_ALT_SELECT_SET(0)
#define PIOC_PY02_FUNC_CTL_PURT_RTS            IOC_PAD_FUNC_CTL_ALT_SELECT_SET(1)
#define PIOC_PY02_FUNC_CTL_PTMR_COMP_2         IOC_PAD_FUNC_CTL_ALT_SELECT_SET(2)
#define PIOC_PY02_FUNC_CTL_SOC_PY_02           IOC_PAD_FUNC_CTL_ALT_SELECT_SET(3)

/* PIOC_PY03_FUNC_CTL function mux definitions */
#define PIOC_PY03_FUNC_CTL_PGPIO_Y_03          IOC_PAD_FUNC_CTL_ALT_SELECT_SET(0)
#define PIOC_PY03_FUNC_CTL_PURT_CTS            IOC_PAD_FUNC_CTL_ALT_SELECT_SET(1)
#define PIOC_PY03_FUNC_CTL_PTMR_COMP_3         IOC_PAD_FUNC_CTL_ALT_SELECT_SET(2)
#define PIOC_PY03_FUNC_CTL_SOC_PY_03           IOC_PAD_FUNC_CTL_ALT_SELECT_SET(3)

/* PIOC_PY04_FUNC_CTL function mux definitions */
#define PIOC_PY04_FUNC_CTL_PGPIO_Y_04          IOC_PAD_FUNC_CTL_ALT_SELECT_SET(0)
#define PIOC_PY04_FUNC_CTL_PTMR_COMP_0         IOC_PAD_FUNC_CTL_ALT_SELECT_SET(2)
#define PIOC_PY04_FUNC_CTL_SOC_PY_04           IOC_PAD_FUNC_CTL_ALT_SELECT_SET(3)

/* PIOC_PY05_FUNC_CTL function mux definitions */
#define PIOC_PY05_FUNC_CTL_PGPIO_Y_05          IOC_PAD_FUNC_CTL_ALT_SELECT_SET(0)
#define PIOC_PY05_FUNC_CTL_PWDG_RSTN           IOC_PAD_FUNC_CTL_ALT_SELECT_SET(1)
#define PIOC_PY05_FUNC_CTL_PTMR_CAPT_0         IOC_PAD_FUNC_CTL_ALT_SELECT_SET(2)
#define PIOC_PY05_FUNC_CTL_SOC_PY_05           IOC_PAD_FUNC_CTL_ALT_SELECT_SET(3)

/* PIOC_PY06_FUNC_CTL function mux definitions */
#define PIOC_PY06_FUNC_CTL_PGPIO_Y_06          IOC_PAD_FUNC_CTL_ALT_SELECT_SET(0)
#define PIOC_PY06_FUNC_CTL_PTMR_COMP_1         IOC_PAD_FUNC_CTL_ALT_SELECT_SET(2)
#define PIOC_PY06_FUNC_CTL_SOC_PY_06           IOC_PAD_FUNC_CTL_ALT_SELECT_SET(3)

/* PIOC_PY07_FUNC_CTL function mux definitions */
#define PIOC_PY07_FUNC_CTL_PGPIO_Y_07          IOC_PAD_FUNC_CTL_ALT_SELECT_SET(0)
#define PIOC_PY07_FUNC_CTL_PTMR_CAPT_1         IOC_PAD_FUNC_CTL_ALT_SELECT_SET(2)
#define PIOC_PY07_FUNC_CTL_SOC_PY_07           IOC_PAD_FUNC_CTL_ALT_SELECT_SET(3)


#endif /* HPM_PMIC_IOMUX_H */
