from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src =  ['startup.S']
src += ['system.c']
src += ['trap_c.c']
src += ['vectors.S']

group = DefineGroup('sys', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
