# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()

src = Glob('src/*.c')

CPPPATH = [cwd + '/include']

group = DefineGroup('SAL', src, depend = ['RT_USING_NETDEV'], CPPPATH = CPPPATH)

Return('group')
