Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drivers.
src = Split("""
board.c
usart.c
""")

CPPPATH = [cwd]
CPPDEFINES = []

if GetDepend('RT_USING_SDIO'):
    src += ['drv_sdio.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
