# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = ['epoll.c']

group = DefineGroup('POSIX', src, depend = ['RT_USING_POSIX_EPOLL'])

Return('group')
