# for module compiling
import os
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')

src	+= ['adc/gd_adc.c']
src	+= ['audio/gd_audio.c']
src	+= ['crypto/gd_crypto.c']
src	+= ['dma/gd_dma.c']

src	+= ['emac/gd_eth_emac.c']
src	+= ['emac/gd_eth_ephy.c']
src	+= ['emac/gd_eth_phy.c']
src	+= ['emac/gd_eth_phy_ar8032.c']
src	+= ['emac/gd_eth_phy_lan8700.c']
src	+= ['emac/gd_eth_phy_rtl8201.c']
src	+= ['emac/gd_ethernet.c']

src	+= ['gpio/gd_gpio.c']
src	+= ['i2c/gd_i2c.c']
src	+= ['i2s/gd_i2s.c']
src	+= ['vo_i80/gd_vo_i80.c']
src	+= ['int/gd_int.c']
src	+= ['int/gd_int_handler.c']
src	+= ['int/gd_int_priv.c']
src	+= ['ir/gd_ir.c']
src	+= ['pwm/gd_pwm.c']
src	+= ['sdio/gd_sdio.c']
src	+= ['sflash/gd_sflash.c']
src	+= ['sflash/gd_spi_sflash.c']
src	+= ['spi/gd_spi.c']
src	+= ['spieeprom/gd_spieeprom.c']
src	+= ['timer/gd_timer.c']
src	+= ['uart/gd_uart.c']
src	+= ['usb/gd_usb.c']
src	+= ['wdog/gd_wdog.c']

path = [cwd, cwd + '/../inc']

group = DefineGroup('gd', src, depend = [''], CPPPATH = path)

Return('group')