# RT-Thread building script for component

from building import *
cwd     = GetCurrentDir()
src     = []
CPPPATH = []

CPPPATH += [cwd + '/rvv-1.0']

group = DefineGroup('CPU', src, depend = ['ARCH_RISCV_VECTOR'], CPPPATH = CPPPATH)

Return('group')
