import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Nuvoton/NUC472_442/Source/system_NUC472_442.c
""")

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    src = src + ['Nuvoton/NUC472_442/Source/GCC/startup.c']
elif rtconfig.CROSS_TOOL == 'keil':
    src = src + ['Nuvoton/NUC472_442/Source/ARM/startup_NUC472_442.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src = src + ['Nuvoton/NUC472_442/Source/IAR/startup_NUC472_442.s']

path = [cwd + '/Nuvoton/NUC472_442/Include',]

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = path)

Return('group')
