/**
  ******************************************************************************
  * @file    dsi_reg.h
  * @version V1.0
  * @date    2021-09-10
  * @brief   This file is the description of.IP register
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; COPYRIGHT(c) 2020 Bouffalo Lab</center></h2>
  *
  * Redistribution and use in source and binary forms, with or without modification,
  * are permitted provided that the following conditions are met:
  *   1. Redistributions of source code must retain the above copyright notice,
  *      this list of conditions and the following disclaimer.
  *   2. Redistributions in binary form must reproduce the above copyright notice,
  *      this list of conditions and the following disclaimer in the documentation
  *      and/or other materials provided with the distribution.
  *   3. Neither the name of Bouffalo Lab nor the names of its contributors
  *      may be used to endorse or promote products derived from this software
  *      without specific prior written permission.
  *
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  *
  ******************************************************************************
  */
#ifndef __DSI_REG_H__
#define __DSI_REG_H__

#include "bl808.h"

/* 0x0 : dsi_config */
#define DSI_CONFIG_OFFSET        (0x0)
#define DSI_CR_HSTX_EN           DSI_CR_HSTX_EN
#define DSI_CR_HSTX_EN_POS       (0U)
#define DSI_CR_HSTX_EN_LEN       (1U)
#define DSI_CR_HSTX_EN_MSK       (((1U << DSI_CR_HSTX_EN_LEN) - 1) << DSI_CR_HSTX_EN_POS)
#define DSI_CR_HSTX_EN_UMSK      (~(((1U << DSI_CR_HSTX_EN_LEN) - 1) << DSI_CR_HSTX_EN_POS))
#define DSI_CR_LANE_NUM          DSI_CR_LANE_NUM
#define DSI_CR_LANE_NUM_POS      (1U)
#define DSI_CR_LANE_NUM_LEN      (2U)
#define DSI_CR_LANE_NUM_MSK      (((1U << DSI_CR_LANE_NUM_LEN) - 1) << DSI_CR_LANE_NUM_POS)
#define DSI_CR_LANE_NUM_UMSK     (~(((1U << DSI_CR_LANE_NUM_LEN) - 1) << DSI_CR_LANE_NUM_POS))
#define DSI_CR_HSTX_MODE         DSI_CR_HSTX_MODE
#define DSI_CR_HSTX_MODE_POS     (4U)
#define DSI_CR_HSTX_MODE_LEN     (1U)
#define DSI_CR_HSTX_MODE_MSK     (((1U << DSI_CR_HSTX_MODE_LEN) - 1) << DSI_CR_HSTX_MODE_POS)
#define DSI_CR_HSTX_MODE_UMSK    (~(((1U << DSI_CR_HSTX_MODE_LEN) - 1) << DSI_CR_HSTX_MODE_POS))
#define DSI_CR_LSE_PKT_EN        DSI_CR_LSE_PKT_EN
#define DSI_CR_LSE_PKT_EN_POS    (5U)
#define DSI_CR_LSE_PKT_EN_LEN    (1U)
#define DSI_CR_LSE_PKT_EN_MSK    (((1U << DSI_CR_LSE_PKT_EN_LEN) - 1) << DSI_CR_LSE_PKT_EN_POS)
#define DSI_CR_LSE_PKT_EN_UMSK   (~(((1U << DSI_CR_LSE_PKT_EN_LEN) - 1) << DSI_CR_LSE_PKT_EN_POS))
#define DSI_CR_LANE_MUX_SEL      DSI_CR_LANE_MUX_SEL
#define DSI_CR_LANE_MUX_SEL_POS  (6U)
#define DSI_CR_LANE_MUX_SEL_LEN  (2U)
#define DSI_CR_LANE_MUX_SEL_MSK  (((1U << DSI_CR_LANE_MUX_SEL_LEN) - 1) << DSI_CR_LANE_MUX_SEL_POS)
#define DSI_CR_LANE_MUX_SEL_UMSK (~(((1U << DSI_CR_LANE_MUX_SEL_LEN) - 1) << DSI_CR_LANE_MUX_SEL_POS))
#define DSI_CR_DT                DSI_CR_DT
#define DSI_CR_DT_POS            (8U)
#define DSI_CR_DT_LEN            (6U)
#define DSI_CR_DT_MSK            (((1U << DSI_CR_DT_LEN) - 1) << DSI_CR_DT_POS)
#define DSI_CR_DT_UMSK           (~(((1U << DSI_CR_DT_LEN) - 1) << DSI_CR_DT_POS))
#define DSI_CR_VC                DSI_CR_VC
#define DSI_CR_VC_POS            (14U)
#define DSI_CR_VC_LEN            (2U)
#define DSI_CR_VC_MSK            (((1U << DSI_CR_VC_LEN) - 1) << DSI_CR_VC_POS)
#define DSI_CR_VC_UMSK           (~(((1U << DSI_CR_VC_LEN) - 1) << DSI_CR_VC_POS))
#define DSI_CR_HSTX_VFP          DSI_CR_HSTX_VFP
#define DSI_CR_HSTX_VFP_POS      (16U)
#define DSI_CR_HSTX_VFP_LEN      (8U)
#define DSI_CR_HSTX_VFP_MSK      (((1U << DSI_CR_HSTX_VFP_LEN) - 1) << DSI_CR_HSTX_VFP_POS)
#define DSI_CR_HSTX_VFP_UMSK     (~(((1U << DSI_CR_HSTX_VFP_LEN) - 1) << DSI_CR_HSTX_VFP_POS))
#define DSI_CR_HSTX_VSA          DSI_CR_HSTX_VSA
#define DSI_CR_HSTX_VSA_POS      (24U)
#define DSI_CR_HSTX_VSA_LEN      (8U)
#define DSI_CR_HSTX_VSA_MSK      (((1U << DSI_CR_HSTX_VSA_LEN) - 1) << DSI_CR_HSTX_VSA_POS)
#define DSI_CR_HSTX_VSA_UMSK     (~(((1U << DSI_CR_HSTX_VSA_LEN) - 1) << DSI_CR_HSTX_VSA_POS))

/* 0x4 : dsi_esc_config */
#define DSI_ESC_CONFIG_OFFSET        (0x4)
#define DSI_CR_ESC_TX_EN             DSI_CR_ESC_TX_EN
#define DSI_CR_ESC_TX_EN_POS         (0U)
#define DSI_CR_ESC_TX_EN_LEN         (1U)
#define DSI_CR_ESC_TX_EN_MSK         (((1U << DSI_CR_ESC_TX_EN_LEN) - 1) << DSI_CR_ESC_TX_EN_POS)
#define DSI_CR_ESC_TX_EN_UMSK        (~(((1U << DSI_CR_ESC_TX_EN_LEN) - 1) << DSI_CR_ESC_TX_EN_POS))
#define DSI_CR_ESC_TX_MODE           DSI_CR_ESC_TX_MODE
#define DSI_CR_ESC_TX_MODE_POS       (1U)
#define DSI_CR_ESC_TX_MODE_LEN       (2U)
#define DSI_CR_ESC_TX_MODE_MSK       (((1U << DSI_CR_ESC_TX_MODE_LEN) - 1) << DSI_CR_ESC_TX_MODE_POS)
#define DSI_CR_ESC_TX_MODE_UMSK      (~(((1U << DSI_CR_ESC_TX_MODE_LEN) - 1) << DSI_CR_ESC_TX_MODE_POS))
#define DSI_CR_ESC_TX_ULPS_EXIT      DSI_CR_ESC_TX_ULPS_EXIT
#define DSI_CR_ESC_TX_ULPS_EXIT_POS  (3U)
#define DSI_CR_ESC_TX_ULPS_EXIT_LEN  (1U)
#define DSI_CR_ESC_TX_ULPS_EXIT_MSK  (((1U << DSI_CR_ESC_TX_ULPS_EXIT_LEN) - 1) << DSI_CR_ESC_TX_ULPS_EXIT_POS)
#define DSI_CR_ESC_TX_ULPS_EXIT_UMSK (~(((1U << DSI_CR_ESC_TX_ULPS_EXIT_LEN) - 1) << DSI_CR_ESC_TX_ULPS_EXIT_POS))
#define DSI_CR_ESC_TX_TRIG           DSI_CR_ESC_TX_TRIG
#define DSI_CR_ESC_TX_TRIG_POS       (4U)
#define DSI_CR_ESC_TX_TRIG_LEN       (4U)
#define DSI_CR_ESC_TX_TRIG_MSK       (((1U << DSI_CR_ESC_TX_TRIG_LEN) - 1) << DSI_CR_ESC_TX_TRIG_POS)
#define DSI_CR_ESC_TX_TRIG_UMSK      (~(((1U << DSI_CR_ESC_TX_TRIG_LEN) - 1) << DSI_CR_ESC_TX_TRIG_POS))
#define DSI_CR_ESC_RX_EN             DSI_CR_ESC_RX_EN
#define DSI_CR_ESC_RX_EN_POS         (16U)
#define DSI_CR_ESC_RX_EN_LEN         (1U)
#define DSI_CR_ESC_RX_EN_MSK         (((1U << DSI_CR_ESC_RX_EN_LEN) - 1) << DSI_CR_ESC_RX_EN_POS)
#define DSI_CR_ESC_RX_EN_UMSK        (~(((1U << DSI_CR_ESC_RX_EN_LEN) - 1) << DSI_CR_ESC_RX_EN_POS))
#define DSI_ST_ESC_RX_LEN            DSI_ST_ESC_RX_LEN
#define DSI_ST_ESC_RX_LEN_POS        (24U)
#define DSI_ST_ESC_RX_LEN_LEN        (8U)
#define DSI_ST_ESC_RX_LEN_MSK        (((1U << DSI_ST_ESC_RX_LEN_LEN) - 1) << DSI_ST_ESC_RX_LEN_POS)
#define DSI_ST_ESC_RX_LEN_UMSK       (~(((1U << DSI_ST_ESC_RX_LEN_LEN) - 1) << DSI_ST_ESC_RX_LEN_POS))

/* 0x8 : dsi_lpdt_tx_config */
#define DSI_LPDT_TX_CONFIG_OFFSET (0x8)
#define DSI_CR_LPDT_PDLEN         DSI_CR_LPDT_PDLEN
#define DSI_CR_LPDT_PDLEN_POS     (0U)
#define DSI_CR_LPDT_PDLEN_LEN     (8U)
#define DSI_CR_LPDT_PDLEN_MSK     (((1U << DSI_CR_LPDT_PDLEN_LEN) - 1) << DSI_CR_LPDT_PDLEN_POS)
#define DSI_CR_LPDT_PDLEN_UMSK    (~(((1U << DSI_CR_LPDT_PDLEN_LEN) - 1) << DSI_CR_LPDT_PDLEN_POS))
#define DSI_CR_LPDT_VC            DSI_CR_LPDT_VC
#define DSI_CR_LPDT_VC_POS        (8U)
#define DSI_CR_LPDT_VC_LEN        (2U)
#define DSI_CR_LPDT_VC_MSK        (((1U << DSI_CR_LPDT_VC_LEN) - 1) << DSI_CR_LPDT_VC_POS)
#define DSI_CR_LPDT_VC_UMSK       (~(((1U << DSI_CR_LPDT_VC_LEN) - 1) << DSI_CR_LPDT_VC_POS))
#define DSI_CR_LPDT_DI            DSI_CR_LPDT_DI
#define DSI_CR_LPDT_DI_POS        (10U)
#define DSI_CR_LPDT_DI_LEN        (6U)
#define DSI_CR_LPDT_DI_MSK        (((1U << DSI_CR_LPDT_DI_LEN) - 1) << DSI_CR_LPDT_DI_POS)
#define DSI_CR_LPDT_DI_UMSK       (~(((1U << DSI_CR_LPDT_DI_LEN) - 1) << DSI_CR_LPDT_DI_POS))
#define DSI_CR_LPDT_WORD0         DSI_CR_LPDT_WORD0
#define DSI_CR_LPDT_WORD0_POS     (16U)
#define DSI_CR_LPDT_WORD0_LEN     (8U)
#define DSI_CR_LPDT_WORD0_MSK     (((1U << DSI_CR_LPDT_WORD0_LEN) - 1) << DSI_CR_LPDT_WORD0_POS)
#define DSI_CR_LPDT_WORD0_UMSK    (~(((1U << DSI_CR_LPDT_WORD0_LEN) - 1) << DSI_CR_LPDT_WORD0_POS))
#define DSI_CR_LPDT_WORD1         DSI_CR_LPDT_WORD1
#define DSI_CR_LPDT_WORD1_POS     (24U)
#define DSI_CR_LPDT_WORD1_LEN     (8U)
#define DSI_CR_LPDT_WORD1_MSK     (((1U << DSI_CR_LPDT_WORD1_LEN) - 1) << DSI_CR_LPDT_WORD1_POS)
#define DSI_CR_LPDT_WORD1_UMSK    (~(((1U << DSI_CR_LPDT_WORD1_LEN) - 1) << DSI_CR_LPDT_WORD1_POS))

/* 0xC : dsi_hstx_config */
#define DSI_HSTX_CONFIG_OFFSET  (0xC)
#define DSI_CR_HSTX_PC          DSI_CR_HSTX_PC
#define DSI_CR_HSTX_PC_POS      (0U)
#define DSI_CR_HSTX_PC_LEN      (11U)
#define DSI_CR_HSTX_PC_MSK      (((1U << DSI_CR_HSTX_PC_LEN) - 1) << DSI_CR_HSTX_PC_POS)
#define DSI_CR_HSTX_PC_UMSK     (~(((1U << DSI_CR_HSTX_PC_LEN) - 1) << DSI_CR_HSTX_PC_POS))
#define DSI_CR_HSTX_OUT_TH      DSI_CR_HSTX_OUT_TH
#define DSI_CR_HSTX_OUT_TH_POS  (16U)
#define DSI_CR_HSTX_OUT_TH_LEN  (11U)
#define DSI_CR_HSTX_OUT_TH_MSK  (((1U << DSI_CR_HSTX_OUT_TH_LEN) - 1) << DSI_CR_HSTX_OUT_TH_POS)
#define DSI_CR_HSTX_OUT_TH_UMSK (~(((1U << DSI_CR_HSTX_OUT_TH_LEN) - 1) << DSI_CR_HSTX_OUT_TH_POS))

/* 0x10 : dsi_int_status */
#define DSI_INT_STATUS_OFFSET (0x10)
#define DSI_INT_STATUS        DSI_INT_STATUS
#define DSI_INT_STATUS_POS    (0U)
#define DSI_INT_STATUS_LEN    (14U)
#define DSI_INT_STATUS_MSK    (((1U << DSI_INT_STATUS_LEN) - 1) << DSI_INT_STATUS_POS)
#define DSI_INT_STATUS_UMSK   (~(((1U << DSI_INT_STATUS_LEN) - 1) << DSI_INT_STATUS_POS))

/* 0x14 : dsi_int_mask */
#define DSI_INT_MASK_OFFSET (0x14)
#define DSI_INT_MASK        DSI_INT_MASK
#define DSI_INT_MASK_POS    (0U)
#define DSI_INT_MASK_LEN    (14U)
#define DSI_INT_MASK_MSK    (((1U << DSI_INT_MASK_LEN) - 1) << DSI_INT_MASK_POS)
#define DSI_INT_MASK_UMSK   (~(((1U << DSI_INT_MASK_LEN) - 1) << DSI_INT_MASK_POS))

/* 0x18 : dsi_int_clear */
#define DSI_INT_CLEAR_OFFSET (0x18)
#define DSI_INT_CLEAR        DSI_INT_CLEAR
#define DSI_INT_CLEAR_POS    (0U)
#define DSI_INT_CLEAR_LEN    (14U)
#define DSI_INT_CLEAR_MSK    (((1U << DSI_INT_CLEAR_LEN) - 1) << DSI_INT_CLEAR_POS)
#define DSI_INT_CLEAR_UMSK   (~(((1U << DSI_INT_CLEAR_LEN) - 1) << DSI_INT_CLEAR_POS))

/* 0x1C : dsi_int_enable */
#define DSI_INT_ENABLE_OFFSET (0x1C)
#define DSI_INT_ENABLE        DSI_INT_ENABLE
#define DSI_INT_ENABLE_POS    (0U)
#define DSI_INT_ENABLE_LEN    (14U)
#define DSI_INT_ENABLE_MSK    (((1U << DSI_INT_ENABLE_LEN) - 1) << DSI_INT_ENABLE_POS)
#define DSI_INT_ENABLE_UMSK   (~(((1U << DSI_INT_ENABLE_LEN) - 1) << DSI_INT_ENABLE_POS))

/* 0x20 : dsi_frame_num */
#define DSI_FRAME_NUM_OFFSET  (0x20)
#define DSI_CR_FRAME_NUM      DSI_CR_FRAME_NUM
#define DSI_CR_FRAME_NUM_POS  (0U)
#define DSI_CR_FRAME_NUM_LEN  (16U)
#define DSI_CR_FRAME_NUM_MSK  (((1U << DSI_CR_FRAME_NUM_LEN) - 1) << DSI_CR_FRAME_NUM_POS)
#define DSI_CR_FRAME_NUM_UMSK (~(((1U << DSI_CR_FRAME_NUM_LEN) - 1) << DSI_CR_FRAME_NUM_POS))
#define DSI_CR_FRAME_UPD      DSI_CR_FRAME_UPD
#define DSI_CR_FRAME_UPD_POS  (31U)
#define DSI_CR_FRAME_UPD_LEN  (1U)
#define DSI_CR_FRAME_UPD_MSK  (((1U << DSI_CR_FRAME_UPD_LEN) - 1) << DSI_CR_FRAME_UPD_POS)
#define DSI_CR_FRAME_UPD_UMSK (~(((1U << DSI_CR_FRAME_UPD_LEN) - 1) << DSI_CR_FRAME_UPD_POS))

/* 0x60 : dsi_fifo_config_0 */
#define DSI_FIFO_CONFIG_0_OFFSET   (0x60)
#define DSI_DMA_TX_EN              DSI_DMA_TX_EN
#define DSI_DMA_TX_EN_POS          (0U)
#define DSI_DMA_TX_EN_LEN          (1U)
#define DSI_DMA_TX_EN_MSK          (((1U << DSI_DMA_TX_EN_LEN) - 1) << DSI_DMA_TX_EN_POS)
#define DSI_DMA_TX_EN_UMSK         (~(((1U << DSI_DMA_TX_EN_LEN) - 1) << DSI_DMA_TX_EN_POS))
#define DSI_DMA_RX_EN              DSI_DMA_RX_EN
#define DSI_DMA_RX_EN_POS          (1U)
#define DSI_DMA_RX_EN_LEN          (1U)
#define DSI_DMA_RX_EN_MSK          (((1U << DSI_DMA_RX_EN_LEN) - 1) << DSI_DMA_RX_EN_POS)
#define DSI_DMA_RX_EN_UMSK         (~(((1U << DSI_DMA_RX_EN_LEN) - 1) << DSI_DMA_RX_EN_POS))
#define DSI_TX_FIFO_CLR            DSI_TX_FIFO_CLR
#define DSI_TX_FIFO_CLR_POS        (2U)
#define DSI_TX_FIFO_CLR_LEN        (1U)
#define DSI_TX_FIFO_CLR_MSK        (((1U << DSI_TX_FIFO_CLR_LEN) - 1) << DSI_TX_FIFO_CLR_POS)
#define DSI_TX_FIFO_CLR_UMSK       (~(((1U << DSI_TX_FIFO_CLR_LEN) - 1) << DSI_TX_FIFO_CLR_POS))
#define DSI_RX_FIFO_CLR            DSI_RX_FIFO_CLR
#define DSI_RX_FIFO_CLR_POS        (3U)
#define DSI_RX_FIFO_CLR_LEN        (1U)
#define DSI_RX_FIFO_CLR_MSK        (((1U << DSI_RX_FIFO_CLR_LEN) - 1) << DSI_RX_FIFO_CLR_POS)
#define DSI_RX_FIFO_CLR_UMSK       (~(((1U << DSI_RX_FIFO_CLR_LEN) - 1) << DSI_RX_FIFO_CLR_POS))
#define DSI_TX_FIFO_OVERFLOW       DSI_TX_FIFO_OVERFLOW
#define DSI_TX_FIFO_OVERFLOW_POS   (4U)
#define DSI_TX_FIFO_OVERFLOW_LEN   (1U)
#define DSI_TX_FIFO_OVERFLOW_MSK   (((1U << DSI_TX_FIFO_OVERFLOW_LEN) - 1) << DSI_TX_FIFO_OVERFLOW_POS)
#define DSI_TX_FIFO_OVERFLOW_UMSK  (~(((1U << DSI_TX_FIFO_OVERFLOW_LEN) - 1) << DSI_TX_FIFO_OVERFLOW_POS))
#define DSI_TX_FIFO_UNDERFLOW      DSI_TX_FIFO_UNDERFLOW
#define DSI_TX_FIFO_UNDERFLOW_POS  (5U)
#define DSI_TX_FIFO_UNDERFLOW_LEN  (1U)
#define DSI_TX_FIFO_UNDERFLOW_MSK  (((1U << DSI_TX_FIFO_UNDERFLOW_LEN) - 1) << DSI_TX_FIFO_UNDERFLOW_POS)
#define DSI_TX_FIFO_UNDERFLOW_UMSK (~(((1U << DSI_TX_FIFO_UNDERFLOW_LEN) - 1) << DSI_TX_FIFO_UNDERFLOW_POS))
#define DSI_RX_FIFO_OVERFLOW       DSI_RX_FIFO_OVERFLOW
#define DSI_RX_FIFO_OVERFLOW_POS   (6U)
#define DSI_RX_FIFO_OVERFLOW_LEN   (1U)
#define DSI_RX_FIFO_OVERFLOW_MSK   (((1U << DSI_RX_FIFO_OVERFLOW_LEN) - 1) << DSI_RX_FIFO_OVERFLOW_POS)
#define DSI_RX_FIFO_OVERFLOW_UMSK  (~(((1U << DSI_RX_FIFO_OVERFLOW_LEN) - 1) << DSI_RX_FIFO_OVERFLOW_POS))
#define DSI_RX_FIFO_UNDERFLOW      DSI_RX_FIFO_UNDERFLOW
#define DSI_RX_FIFO_UNDERFLOW_POS  (7U)
#define DSI_RX_FIFO_UNDERFLOW_LEN  (1U)
#define DSI_RX_FIFO_UNDERFLOW_MSK  (((1U << DSI_RX_FIFO_UNDERFLOW_LEN) - 1) << DSI_RX_FIFO_UNDERFLOW_POS)
#define DSI_RX_FIFO_UNDERFLOW_UMSK (~(((1U << DSI_RX_FIFO_UNDERFLOW_LEN) - 1) << DSI_RX_FIFO_UNDERFLOW_POS))

/* 0x64 : dsi_fifo_config_1 */
#define DSI_FIFO_CONFIG_1_OFFSET (0x64)
#define DSI_TX_FIFO_CNT          DSI_TX_FIFO_CNT
#define DSI_TX_FIFO_CNT_POS      (0U)
#define DSI_TX_FIFO_CNT_LEN      (3U)
#define DSI_TX_FIFO_CNT_MSK      (((1U << DSI_TX_FIFO_CNT_LEN) - 1) << DSI_TX_FIFO_CNT_POS)
#define DSI_TX_FIFO_CNT_UMSK     (~(((1U << DSI_TX_FIFO_CNT_LEN) - 1) << DSI_TX_FIFO_CNT_POS))
#define DSI_RX_FIFO_CNT          DSI_RX_FIFO_CNT
#define DSI_RX_FIFO_CNT_POS      (8U)
#define DSI_RX_FIFO_CNT_LEN      (3U)
#define DSI_RX_FIFO_CNT_MSK      (((1U << DSI_RX_FIFO_CNT_LEN) - 1) << DSI_RX_FIFO_CNT_POS)
#define DSI_RX_FIFO_CNT_UMSK     (~(((1U << DSI_RX_FIFO_CNT_LEN) - 1) << DSI_RX_FIFO_CNT_POS))
#define DSI_TX_FIFO_TH           DSI_TX_FIFO_TH
#define DSI_TX_FIFO_TH_POS       (16U)
#define DSI_TX_FIFO_TH_LEN       (2U)
#define DSI_TX_FIFO_TH_MSK       (((1U << DSI_TX_FIFO_TH_LEN) - 1) << DSI_TX_FIFO_TH_POS)
#define DSI_TX_FIFO_TH_UMSK      (~(((1U << DSI_TX_FIFO_TH_LEN) - 1) << DSI_TX_FIFO_TH_POS))
#define DSI_RX_FIFO_TH           DSI_RX_FIFO_TH
#define DSI_RX_FIFO_TH_POS       (24U)
#define DSI_RX_FIFO_TH_LEN       (2U)
#define DSI_RX_FIFO_TH_MSK       (((1U << DSI_RX_FIFO_TH_LEN) - 1) << DSI_RX_FIFO_TH_POS)
#define DSI_RX_FIFO_TH_UMSK      (~(((1U << DSI_RX_FIFO_TH_LEN) - 1) << DSI_RX_FIFO_TH_POS))

/* 0x68 : dsi_fifo_wdata */
#define DSI_FIFO_WDATA_OFFSET (0x68)
#define DSI_FIFO_WDATA        DSI_FIFO_WDATA
#define DSI_FIFO_WDATA_POS    (0U)
#define DSI_FIFO_WDATA_LEN    (32U)
#define DSI_FIFO_WDATA_MSK    (((1U << DSI_FIFO_WDATA_LEN) - 1) << DSI_FIFO_WDATA_POS)
#define DSI_FIFO_WDATA_UMSK   (~(((1U << DSI_FIFO_WDATA_LEN) - 1) << DSI_FIFO_WDATA_POS))

/* 0x6C : dsi_fifo_rdata */
#define DSI_FIFO_RDATA_OFFSET (0x6C)
#define DSI_FIFO_RDATA        DSI_FIFO_RDATA
#define DSI_FIFO_RDATA_POS    (0U)
#define DSI_FIFO_RDATA_LEN    (32U)
#define DSI_FIFO_RDATA_MSK    (((1U << DSI_FIFO_RDATA_LEN) - 1) << DSI_FIFO_RDATA_POS)
#define DSI_FIFO_RDATA_UMSK   (~(((1U << DSI_FIFO_RDATA_LEN) - 1) << DSI_FIFO_RDATA_POS))

/* 0x80 : dphy_config_0 */
#define DSI_DPHY_CONFIG_0_OFFSET     (0x80)
#define DSI_CL_ENABLE                DSI_CL_ENABLE
#define DSI_CL_ENABLE_POS            (0U)
#define DSI_CL_ENABLE_LEN            (1U)
#define DSI_CL_ENABLE_MSK            (((1U << DSI_CL_ENABLE_LEN) - 1) << DSI_CL_ENABLE_POS)
#define DSI_CL_ENABLE_UMSK           (~(((1U << DSI_CL_ENABLE_LEN) - 1) << DSI_CL_ENABLE_POS))
#define DSI_CL_TXREQUESTHS           DSI_CL_TXREQUESTHS
#define DSI_CL_TXREQUESTHS_POS       (1U)
#define DSI_CL_TXREQUESTHS_LEN       (1U)
#define DSI_CL_TXREQUESTHS_MSK       (((1U << DSI_CL_TXREQUESTHS_LEN) - 1) << DSI_CL_TXREQUESTHS_POS)
#define DSI_CL_TXREQUESTHS_UMSK      (~(((1U << DSI_CL_TXREQUESTHS_LEN) - 1) << DSI_CL_TXREQUESTHS_POS))
#define DSI_CL_TXULPSCLK             DSI_CL_TXULPSCLK
#define DSI_CL_TXULPSCLK_POS         (2U)
#define DSI_CL_TXULPSCLK_LEN         (1U)
#define DSI_CL_TXULPSCLK_MSK         (((1U << DSI_CL_TXULPSCLK_LEN) - 1) << DSI_CL_TXULPSCLK_POS)
#define DSI_CL_TXULPSCLK_UMSK        (~(((1U << DSI_CL_TXULPSCLK_LEN) - 1) << DSI_CL_TXULPSCLK_POS))
#define DSI_CL_TXULPSEXIT            DSI_CL_TXULPSEXIT
#define DSI_CL_TXULPSEXIT_POS        (3U)
#define DSI_CL_TXULPSEXIT_LEN        (1U)
#define DSI_CL_TXULPSEXIT_MSK        (((1U << DSI_CL_TXULPSEXIT_LEN) - 1) << DSI_CL_TXULPSEXIT_POS)
#define DSI_CL_TXULPSEXIT_UMSK       (~(((1U << DSI_CL_TXULPSEXIT_LEN) - 1) << DSI_CL_TXULPSEXIT_POS))
#define DSI_CL_STOPSTATE             DSI_CL_STOPSTATE
#define DSI_CL_STOPSTATE_POS         (4U)
#define DSI_CL_STOPSTATE_LEN         (1U)
#define DSI_CL_STOPSTATE_MSK         (((1U << DSI_CL_STOPSTATE_LEN) - 1) << DSI_CL_STOPSTATE_POS)
#define DSI_CL_STOPSTATE_UMSK        (~(((1U << DSI_CL_STOPSTATE_LEN) - 1) << DSI_CL_STOPSTATE_POS))
#define DSI_CL_ULPSACTIVENOT         DSI_CL_ULPSACTIVENOT
#define DSI_CL_ULPSACTIVENOT_POS     (5U)
#define DSI_CL_ULPSACTIVENOT_LEN     (1U)
#define DSI_CL_ULPSACTIVENOT_MSK     (((1U << DSI_CL_ULPSACTIVENOT_LEN) - 1) << DSI_CL_ULPSACTIVENOT_POS)
#define DSI_CL_ULPSACTIVENOT_UMSK    (~(((1U << DSI_CL_ULPSACTIVENOT_LEN) - 1) << DSI_CL_ULPSACTIVENOT_POS))
#define DSI_DL0_ENABLE               DSI_DL0_ENABLE
#define DSI_DL0_ENABLE_POS           (8U)
#define DSI_DL0_ENABLE_LEN           (1U)
#define DSI_DL0_ENABLE_MSK           (((1U << DSI_DL0_ENABLE_LEN) - 1) << DSI_DL0_ENABLE_POS)
#define DSI_DL0_ENABLE_UMSK          (~(((1U << DSI_DL0_ENABLE_LEN) - 1) << DSI_DL0_ENABLE_POS))
#define DSI_DL1_ENABLE               DSI_DL1_ENABLE
#define DSI_DL1_ENABLE_POS           (9U)
#define DSI_DL1_ENABLE_LEN           (1U)
#define DSI_DL1_ENABLE_MSK           (((1U << DSI_DL1_ENABLE_LEN) - 1) << DSI_DL1_ENABLE_POS)
#define DSI_DL1_ENABLE_UMSK          (~(((1U << DSI_DL1_ENABLE_LEN) - 1) << DSI_DL1_ENABLE_POS))
#define DSI_DL2_ENABLE               DSI_DL2_ENABLE
#define DSI_DL2_ENABLE_POS           (10U)
#define DSI_DL2_ENABLE_LEN           (1U)
#define DSI_DL2_ENABLE_MSK           (((1U << DSI_DL2_ENABLE_LEN) - 1) << DSI_DL2_ENABLE_POS)
#define DSI_DL2_ENABLE_UMSK          (~(((1U << DSI_DL2_ENABLE_LEN) - 1) << DSI_DL2_ENABLE_POS))
#define DSI_DL3_ENABLE               DSI_DL3_ENABLE
#define DSI_DL3_ENABLE_POS           (11U)
#define DSI_DL3_ENABLE_LEN           (1U)
#define DSI_DL3_ENABLE_MSK           (((1U << DSI_DL3_ENABLE_LEN) - 1) << DSI_DL3_ENABLE_POS)
#define DSI_DL3_ENABLE_UMSK          (~(((1U << DSI_DL3_ENABLE_LEN) - 1) << DSI_DL3_ENABLE_POS))
#define DSI_DL0_STOPSTATE            DSI_DL0_STOPSTATE
#define DSI_DL0_STOPSTATE_POS        (12U)
#define DSI_DL0_STOPSTATE_LEN        (1U)
#define DSI_DL0_STOPSTATE_MSK        (((1U << DSI_DL0_STOPSTATE_LEN) - 1) << DSI_DL0_STOPSTATE_POS)
#define DSI_DL0_STOPSTATE_UMSK       (~(((1U << DSI_DL0_STOPSTATE_LEN) - 1) << DSI_DL0_STOPSTATE_POS))
#define DSI_DL1_STOPSTATE            DSI_DL1_STOPSTATE
#define DSI_DL1_STOPSTATE_POS        (13U)
#define DSI_DL1_STOPSTATE_LEN        (1U)
#define DSI_DL1_STOPSTATE_MSK        (((1U << DSI_DL1_STOPSTATE_LEN) - 1) << DSI_DL1_STOPSTATE_POS)
#define DSI_DL1_STOPSTATE_UMSK       (~(((1U << DSI_DL1_STOPSTATE_LEN) - 1) << DSI_DL1_STOPSTATE_POS))
#define DSI_DL2_STOPSTATE            DSI_DL2_STOPSTATE
#define DSI_DL2_STOPSTATE_POS        (14U)
#define DSI_DL2_STOPSTATE_LEN        (1U)
#define DSI_DL2_STOPSTATE_MSK        (((1U << DSI_DL2_STOPSTATE_LEN) - 1) << DSI_DL2_STOPSTATE_POS)
#define DSI_DL2_STOPSTATE_UMSK       (~(((1U << DSI_DL2_STOPSTATE_LEN) - 1) << DSI_DL2_STOPSTATE_POS))
#define DSI_DL3_STOPSTATE            DSI_DL3_STOPSTATE
#define DSI_DL3_STOPSTATE_POS        (15U)
#define DSI_DL3_STOPSTATE_LEN        (1U)
#define DSI_DL3_STOPSTATE_MSK        (((1U << DSI_DL3_STOPSTATE_LEN) - 1) << DSI_DL3_STOPSTATE_POS)
#define DSI_DL3_STOPSTATE_UMSK       (~(((1U << DSI_DL3_STOPSTATE_LEN) - 1) << DSI_DL3_STOPSTATE_POS))
#define DSI_DL0_ULPSACTIVENOT        DSI_DL0_ULPSACTIVENOT
#define DSI_DL0_ULPSACTIVENOT_POS    (16U)
#define DSI_DL0_ULPSACTIVENOT_LEN    (1U)
#define DSI_DL0_ULPSACTIVENOT_MSK    (((1U << DSI_DL0_ULPSACTIVENOT_LEN) - 1) << DSI_DL0_ULPSACTIVENOT_POS)
#define DSI_DL0_ULPSACTIVENOT_UMSK   (~(((1U << DSI_DL0_ULPSACTIVENOT_LEN) - 1) << DSI_DL0_ULPSACTIVENOT_POS))
#define DSI_DL1_ULPSACTIVENOT        DSI_DL1_ULPSACTIVENOT
#define DSI_DL1_ULPSACTIVENOT_POS    (17U)
#define DSI_DL1_ULPSACTIVENOT_LEN    (1U)
#define DSI_DL1_ULPSACTIVENOT_MSK    (((1U << DSI_DL1_ULPSACTIVENOT_LEN) - 1) << DSI_DL1_ULPSACTIVENOT_POS)
#define DSI_DL1_ULPSACTIVENOT_UMSK   (~(((1U << DSI_DL1_ULPSACTIVENOT_LEN) - 1) << DSI_DL1_ULPSACTIVENOT_POS))
#define DSI_DL2_ULPSACTIVENOT        DSI_DL2_ULPSACTIVENOT
#define DSI_DL2_ULPSACTIVENOT_POS    (18U)
#define DSI_DL2_ULPSACTIVENOT_LEN    (1U)
#define DSI_DL2_ULPSACTIVENOT_MSK    (((1U << DSI_DL2_ULPSACTIVENOT_LEN) - 1) << DSI_DL2_ULPSACTIVENOT_POS)
#define DSI_DL2_ULPSACTIVENOT_UMSK   (~(((1U << DSI_DL2_ULPSACTIVENOT_LEN) - 1) << DSI_DL2_ULPSACTIVENOT_POS))
#define DSI_DL3_ULPSACTIVENOT        DSI_DL3_ULPSACTIVENOT
#define DSI_DL3_ULPSACTIVENOT_POS    (19U)
#define DSI_DL3_ULPSACTIVENOT_LEN    (1U)
#define DSI_DL3_ULPSACTIVENOT_MSK    (((1U << DSI_DL3_ULPSACTIVENOT_LEN) - 1) << DSI_DL3_ULPSACTIVENOT_POS)
#define DSI_DL3_ULPSACTIVENOT_UMSK   (~(((1U << DSI_DL3_ULPSACTIVENOT_LEN) - 1) << DSI_DL3_ULPSACTIVENOT_POS))
#define DSI_DL0_FORCERXMODE          DSI_DL0_FORCERXMODE
#define DSI_DL0_FORCERXMODE_POS      (20U)
#define DSI_DL0_FORCERXMODE_LEN      (1U)
#define DSI_DL0_FORCERXMODE_MSK      (((1U << DSI_DL0_FORCERXMODE_LEN) - 1) << DSI_DL0_FORCERXMODE_POS)
#define DSI_DL0_FORCERXMODE_UMSK     (~(((1U << DSI_DL0_FORCERXMODE_LEN) - 1) << DSI_DL0_FORCERXMODE_POS))
#define DSI_DL1_FORCERXMODE          DSI_DL1_FORCERXMODE
#define DSI_DL1_FORCERXMODE_POS      (21U)
#define DSI_DL1_FORCERXMODE_LEN      (1U)
#define DSI_DL1_FORCERXMODE_MSK      (((1U << DSI_DL1_FORCERXMODE_LEN) - 1) << DSI_DL1_FORCERXMODE_POS)
#define DSI_DL1_FORCERXMODE_UMSK     (~(((1U << DSI_DL1_FORCERXMODE_LEN) - 1) << DSI_DL1_FORCERXMODE_POS))
#define DSI_DL2_FORCERXMODE          DSI_DL2_FORCERXMODE
#define DSI_DL2_FORCERXMODE_POS      (22U)
#define DSI_DL2_FORCERXMODE_LEN      (1U)
#define DSI_DL2_FORCERXMODE_MSK      (((1U << DSI_DL2_FORCERXMODE_LEN) - 1) << DSI_DL2_FORCERXMODE_POS)
#define DSI_DL2_FORCERXMODE_UMSK     (~(((1U << DSI_DL2_FORCERXMODE_LEN) - 1) << DSI_DL2_FORCERXMODE_POS))
#define DSI_DL3_FORCERXMODE          DSI_DL3_FORCERXMODE
#define DSI_DL3_FORCERXMODE_POS      (23U)
#define DSI_DL3_FORCERXMODE_LEN      (1U)
#define DSI_DL3_FORCERXMODE_MSK      (((1U << DSI_DL3_FORCERXMODE_LEN) - 1) << DSI_DL3_FORCERXMODE_POS)
#define DSI_DL3_FORCERXMODE_UMSK     (~(((1U << DSI_DL3_FORCERXMODE_LEN) - 1) << DSI_DL3_FORCERXMODE_POS))
#define DSI_DL0_FORCETXSTOPMODE      DSI_DL0_FORCETXSTOPMODE
#define DSI_DL0_FORCETXSTOPMODE_POS  (24U)
#define DSI_DL0_FORCETXSTOPMODE_LEN  (1U)
#define DSI_DL0_FORCETXSTOPMODE_MSK  (((1U << DSI_DL0_FORCETXSTOPMODE_LEN) - 1) << DSI_DL0_FORCETXSTOPMODE_POS)
#define DSI_DL0_FORCETXSTOPMODE_UMSK (~(((1U << DSI_DL0_FORCETXSTOPMODE_LEN) - 1) << DSI_DL0_FORCETXSTOPMODE_POS))
#define DSI_DL1_FORCETXSTOPMODE      DSI_DL1_FORCETXSTOPMODE
#define DSI_DL1_FORCETXSTOPMODE_POS  (25U)
#define DSI_DL1_FORCETXSTOPMODE_LEN  (1U)
#define DSI_DL1_FORCETXSTOPMODE_MSK  (((1U << DSI_DL1_FORCETXSTOPMODE_LEN) - 1) << DSI_DL1_FORCETXSTOPMODE_POS)
#define DSI_DL1_FORCETXSTOPMODE_UMSK (~(((1U << DSI_DL1_FORCETXSTOPMODE_LEN) - 1) << DSI_DL1_FORCETXSTOPMODE_POS))
#define DSI_DL2_FORCETXSTOPMODE      DSI_DL2_FORCETXSTOPMODE
#define DSI_DL2_FORCETXSTOPMODE_POS  (26U)
#define DSI_DL2_FORCETXSTOPMODE_LEN  (1U)
#define DSI_DL2_FORCETXSTOPMODE_MSK  (((1U << DSI_DL2_FORCETXSTOPMODE_LEN) - 1) << DSI_DL2_FORCETXSTOPMODE_POS)
#define DSI_DL2_FORCETXSTOPMODE_UMSK (~(((1U << DSI_DL2_FORCETXSTOPMODE_LEN) - 1) << DSI_DL2_FORCETXSTOPMODE_POS))
#define DSI_DL3_FORCETXSTOPMODE      DSI_DL3_FORCETXSTOPMODE
#define DSI_DL3_FORCETXSTOPMODE_POS  (27U)
#define DSI_DL3_FORCETXSTOPMODE_LEN  (1U)
#define DSI_DL3_FORCETXSTOPMODE_MSK  (((1U << DSI_DL3_FORCETXSTOPMODE_LEN) - 1) << DSI_DL3_FORCETXSTOPMODE_POS)
#define DSI_DL3_FORCETXSTOPMODE_UMSK (~(((1U << DSI_DL3_FORCETXSTOPMODE_LEN) - 1) << DSI_DL3_FORCETXSTOPMODE_POS))
#define DSI_DL0_TURNESC              DSI_DL0_TURNESC
#define DSI_DL0_TURNESC_POS          (30U)
#define DSI_DL0_TURNESC_LEN          (1U)
#define DSI_DL0_TURNESC_MSK          (((1U << DSI_DL0_TURNESC_LEN) - 1) << DSI_DL0_TURNESC_POS)
#define DSI_DL0_TURNESC_UMSK         (~(((1U << DSI_DL0_TURNESC_LEN) - 1) << DSI_DL0_TURNESC_POS))
#define DSI_RESET_N                  DSI_RESET_N
#define DSI_RESET_N_POS              (31U)
#define DSI_RESET_N_LEN              (1U)
#define DSI_RESET_N_MSK              (((1U << DSI_RESET_N_LEN) - 1) << DSI_RESET_N_POS)
#define DSI_RESET_N_UMSK             (~(((1U << DSI_RESET_N_LEN) - 1) << DSI_RESET_N_POS))

/* 0x84 : dphy_config_1 */
#define DSI_DPHY_CONFIG_1_OFFSET     (0x84)
#define DSI_REG_TIME_CK_ZERO         DSI_REG_TIME_CK_ZERO
#define DSI_REG_TIME_CK_ZERO_POS     (0U)
#define DSI_REG_TIME_CK_ZERO_LEN     (8U)
#define DSI_REG_TIME_CK_ZERO_MSK     (((1U << DSI_REG_TIME_CK_ZERO_LEN) - 1) << DSI_REG_TIME_CK_ZERO_POS)
#define DSI_REG_TIME_CK_ZERO_UMSK    (~(((1U << DSI_REG_TIME_CK_ZERO_LEN) - 1) << DSI_REG_TIME_CK_ZERO_POS))
#define DSI_REG_TIME_CK_TRAIL        DSI_REG_TIME_CK_TRAIL
#define DSI_REG_TIME_CK_TRAIL_POS    (8U)
#define DSI_REG_TIME_CK_TRAIL_LEN    (8U)
#define DSI_REG_TIME_CK_TRAIL_MSK    (((1U << DSI_REG_TIME_CK_TRAIL_LEN) - 1) << DSI_REG_TIME_CK_TRAIL_POS)
#define DSI_REG_TIME_CK_TRAIL_UMSK   (~(((1U << DSI_REG_TIME_CK_TRAIL_LEN) - 1) << DSI_REG_TIME_CK_TRAIL_POS))
#define DSI_REG_TIME_CK_EXIT         DSI_REG_TIME_CK_EXIT
#define DSI_REG_TIME_CK_EXIT_POS     (16U)
#define DSI_REG_TIME_CK_EXIT_LEN     (8U)
#define DSI_REG_TIME_CK_EXIT_MSK     (((1U << DSI_REG_TIME_CK_EXIT_LEN) - 1) << DSI_REG_TIME_CK_EXIT_POS)
#define DSI_REG_TIME_CK_EXIT_UMSK    (~(((1U << DSI_REG_TIME_CK_EXIT_LEN) - 1) << DSI_REG_TIME_CK_EXIT_POS))
#define DSI_REG_EN_LPRX_AT_ULPS      DSI_REG_EN_LPRX_AT_ULPS
#define DSI_REG_EN_LPRX_AT_ULPS_POS  (24U)
#define DSI_REG_EN_LPRX_AT_ULPS_LEN  (1U)
#define DSI_REG_EN_LPRX_AT_ULPS_MSK  (((1U << DSI_REG_EN_LPRX_AT_ULPS_LEN) - 1) << DSI_REG_EN_LPRX_AT_ULPS_POS)
#define DSI_REG_EN_LPRX_AT_ULPS_UMSK (~(((1U << DSI_REG_EN_LPRX_AT_ULPS_LEN) - 1) << DSI_REG_EN_LPRX_AT_ULPS_POS))

/* 0x88 : dphy_config_2 */
#define DSI_DPHY_CONFIG_2_OFFSET   (0x88)
#define DSI_REG_TIME_HS_ZERO       DSI_REG_TIME_HS_ZERO
#define DSI_REG_TIME_HS_ZERO_POS   (0U)
#define DSI_REG_TIME_HS_ZERO_LEN   (8U)
#define DSI_REG_TIME_HS_ZERO_MSK   (((1U << DSI_REG_TIME_HS_ZERO_LEN) - 1) << DSI_REG_TIME_HS_ZERO_POS)
#define DSI_REG_TIME_HS_ZERO_UMSK  (~(((1U << DSI_REG_TIME_HS_ZERO_LEN) - 1) << DSI_REG_TIME_HS_ZERO_POS))
#define DSI_REG_TIME_HS_TRAIL      DSI_REG_TIME_HS_TRAIL
#define DSI_REG_TIME_HS_TRAIL_POS  (8U)
#define DSI_REG_TIME_HS_TRAIL_LEN  (8U)
#define DSI_REG_TIME_HS_TRAIL_MSK  (((1U << DSI_REG_TIME_HS_TRAIL_LEN) - 1) << DSI_REG_TIME_HS_TRAIL_POS)
#define DSI_REG_TIME_HS_TRAIL_UMSK (~(((1U << DSI_REG_TIME_HS_TRAIL_LEN) - 1) << DSI_REG_TIME_HS_TRAIL_POS))
#define DSI_REG_TIME_HS_PREP       DSI_REG_TIME_HS_PREP
#define DSI_REG_TIME_HS_PREP_POS   (16U)
#define DSI_REG_TIME_HS_PREP_LEN   (8U)
#define DSI_REG_TIME_HS_PREP_MSK   (((1U << DSI_REG_TIME_HS_PREP_LEN) - 1) << DSI_REG_TIME_HS_PREP_POS)
#define DSI_REG_TIME_HS_PREP_UMSK  (~(((1U << DSI_REG_TIME_HS_PREP_LEN) - 1) << DSI_REG_TIME_HS_PREP_POS))
#define DSI_REG_TIME_HS_EXIT       DSI_REG_TIME_HS_EXIT
#define DSI_REG_TIME_HS_EXIT_POS   (24U)
#define DSI_REG_TIME_HS_EXIT_LEN   (8U)
#define DSI_REG_TIME_HS_EXIT_MSK   (((1U << DSI_REG_TIME_HS_EXIT_LEN) - 1) << DSI_REG_TIME_HS_EXIT_POS)
#define DSI_REG_TIME_HS_EXIT_UMSK  (~(((1U << DSI_REG_TIME_HS_EXIT_LEN) - 1) << DSI_REG_TIME_HS_EXIT_POS))

/* 0x8C : dphy_config_3 */
#define DSI_DPHY_CONFIG_3_OFFSET (0x8C)
#define DSI_REG_TIME_TA_GO       DSI_REG_TIME_TA_GO
#define DSI_REG_TIME_TA_GO_POS   (0U)
#define DSI_REG_TIME_TA_GO_LEN   (8U)
#define DSI_REG_TIME_TA_GO_MSK   (((1U << DSI_REG_TIME_TA_GO_LEN) - 1) << DSI_REG_TIME_TA_GO_POS)
#define DSI_REG_TIME_TA_GO_UMSK  (~(((1U << DSI_REG_TIME_TA_GO_LEN) - 1) << DSI_REG_TIME_TA_GO_POS))
#define DSI_REG_TIME_TA_GET      DSI_REG_TIME_TA_GET
#define DSI_REG_TIME_TA_GET_POS  (8U)
#define DSI_REG_TIME_TA_GET_LEN  (8U)
#define DSI_REG_TIME_TA_GET_MSK  (((1U << DSI_REG_TIME_TA_GET_LEN) - 1) << DSI_REG_TIME_TA_GET_POS)
#define DSI_REG_TIME_TA_GET_UMSK (~(((1U << DSI_REG_TIME_TA_GET_LEN) - 1) << DSI_REG_TIME_TA_GET_POS))
#define DSI_REG_TIME_REQRDY      DSI_REG_TIME_REQRDY
#define DSI_REG_TIME_REQRDY_POS  (16U)
#define DSI_REG_TIME_REQRDY_LEN  (8U)
#define DSI_REG_TIME_REQRDY_MSK  (((1U << DSI_REG_TIME_REQRDY_LEN) - 1) << DSI_REG_TIME_REQRDY_POS)
#define DSI_REG_TIME_REQRDY_UMSK (~(((1U << DSI_REG_TIME_REQRDY_LEN) - 1) << DSI_REG_TIME_REQRDY_POS))
#define DSI_REG_TIME_LPX         DSI_REG_TIME_LPX
#define DSI_REG_TIME_LPX_POS     (24U)
#define DSI_REG_TIME_LPX_LEN     (8U)
#define DSI_REG_TIME_LPX_MSK     (((1U << DSI_REG_TIME_LPX_LEN) - 1) << DSI_REG_TIME_LPX_POS)
#define DSI_REG_TIME_LPX_UMSK    (~(((1U << DSI_REG_TIME_LPX_LEN) - 1) << DSI_REG_TIME_LPX_POS))

/* 0x90 : dphy_config_4 */
#define DSI_DPHY_CONFIG_4_OFFSET (0x90)
#define DSI_REG_TIME_WAKEUP      DSI_REG_TIME_WAKEUP
#define DSI_REG_TIME_WAKEUP_POS  (0U)
#define DSI_REG_TIME_WAKEUP_LEN  (16U)
#define DSI_REG_TIME_WAKEUP_MSK  (((1U << DSI_REG_TIME_WAKEUP_LEN) - 1) << DSI_REG_TIME_WAKEUP_POS)
#define DSI_REG_TIME_WAKEUP_UMSK (~(((1U << DSI_REG_TIME_WAKEUP_LEN) - 1) << DSI_REG_TIME_WAKEUP_POS))

/* 0x94 : dphy_config_5 */
#define DSI_DPHY_CONFIG_5_OFFSET (0x94)
#define DSI_REG_TRIG3_CODE       DSI_REG_TRIG3_CODE
#define DSI_REG_TRIG3_CODE_POS   (0U)
#define DSI_REG_TRIG3_CODE_LEN   (8U)
#define DSI_REG_TRIG3_CODE_MSK   (((1U << DSI_REG_TRIG3_CODE_LEN) - 1) << DSI_REG_TRIG3_CODE_POS)
#define DSI_REG_TRIG3_CODE_UMSK  (~(((1U << DSI_REG_TRIG3_CODE_LEN) - 1) << DSI_REG_TRIG3_CODE_POS))
#define DSI_REG_TRIG2_CODE       DSI_REG_TRIG2_CODE
#define DSI_REG_TRIG2_CODE_POS   (8U)
#define DSI_REG_TRIG2_CODE_LEN   (8U)
#define DSI_REG_TRIG2_CODE_MSK   (((1U << DSI_REG_TRIG2_CODE_LEN) - 1) << DSI_REG_TRIG2_CODE_POS)
#define DSI_REG_TRIG2_CODE_UMSK  (~(((1U << DSI_REG_TRIG2_CODE_LEN) - 1) << DSI_REG_TRIG2_CODE_POS))
#define DSI_REG_TRIG1_CODE       DSI_REG_TRIG1_CODE
#define DSI_REG_TRIG1_CODE_POS   (16U)
#define DSI_REG_TRIG1_CODE_LEN   (8U)
#define DSI_REG_TRIG1_CODE_MSK   (((1U << DSI_REG_TRIG1_CODE_LEN) - 1) << DSI_REG_TRIG1_CODE_POS)
#define DSI_REG_TRIG1_CODE_UMSK  (~(((1U << DSI_REG_TRIG1_CODE_LEN) - 1) << DSI_REG_TRIG1_CODE_POS))
#define DSI_REG_TRIG0_CODE       DSI_REG_TRIG0_CODE
#define DSI_REG_TRIG0_CODE_POS   (24U)
#define DSI_REG_TRIG0_CODE_LEN   (8U)
#define DSI_REG_TRIG0_CODE_MSK   (((1U << DSI_REG_TRIG0_CODE_LEN) - 1) << DSI_REG_TRIG0_CODE_POS)
#define DSI_REG_TRIG0_CODE_UMSK  (~(((1U << DSI_REG_TRIG0_CODE_LEN) - 1) << DSI_REG_TRIG0_CODE_POS))

/* 0x98 : dphy_config_6 */
#define DSI_DPHY_CONFIG_6_OFFSET (0x98)
#define DSI_REG_ULPS_CODE        DSI_REG_ULPS_CODE
#define DSI_REG_ULPS_CODE_POS    (0U)
#define DSI_REG_ULPS_CODE_LEN    (8U)
#define DSI_REG_ULPS_CODE_MSK    (((1U << DSI_REG_ULPS_CODE_LEN) - 1) << DSI_REG_ULPS_CODE_POS)
#define DSI_REG_ULPS_CODE_UMSK   (~(((1U << DSI_REG_ULPS_CODE_LEN) - 1) << DSI_REG_ULPS_CODE_POS))
#define DSI_REG_LPDT_CODE        DSI_REG_LPDT_CODE
#define DSI_REG_LPDT_CODE_POS    (8U)
#define DSI_REG_LPDT_CODE_LEN    (8U)
#define DSI_REG_LPDT_CODE_MSK    (((1U << DSI_REG_LPDT_CODE_LEN) - 1) << DSI_REG_LPDT_CODE_POS)
#define DSI_REG_LPDT_CODE_UMSK   (~(((1U << DSI_REG_LPDT_CODE_LEN) - 1) << DSI_REG_LPDT_CODE_POS))

/* 0x9C : dphy_config_7 */
#define DSI_DPHY_CONFIG_7_OFFSET                 (0x9C)
#define DSI_REG_ANA_TEST_EN                      DSI_REG_ANA_TEST_EN
#define DSI_REG_ANA_TEST_EN_POS                  (0U)
#define DSI_REG_ANA_TEST_EN_LEN                  (1U)
#define DSI_REG_ANA_TEST_EN_MSK                  (((1U << DSI_REG_ANA_TEST_EN_LEN) - 1) << DSI_REG_ANA_TEST_EN_POS)
#define DSI_REG_ANA_TEST_EN_UMSK                 (~(((1U << DSI_REG_ANA_TEST_EN_LEN) - 1) << DSI_REG_ANA_TEST_EN_POS))
#define DSI_REG_PT_EN                            DSI_REG_PT_EN
#define DSI_REG_PT_EN_POS                        (1U)
#define DSI_REG_PT_EN_LEN                        (1U)
#define DSI_REG_PT_EN_MSK                        (((1U << DSI_REG_PT_EN_LEN) - 1) << DSI_REG_PT_EN_POS)
#define DSI_REG_PT_EN_UMSK                       (~(((1U << DSI_REG_PT_EN_LEN) - 1) << DSI_REG_PT_EN_POS))
#define DSI_REG_PT_LP_MODE                       DSI_REG_PT_LP_MODE
#define DSI_REG_PT_LP_MODE_POS                   (2U)
#define DSI_REG_PT_LP_MODE_LEN                   (1U)
#define DSI_REG_PT_LP_MODE_MSK                   (((1U << DSI_REG_PT_LP_MODE_LEN) - 1) << DSI_REG_PT_LP_MODE_POS)
#define DSI_REG_PT_LP_MODE_UMSK                  (~(((1U << DSI_REG_PT_LP_MODE_LEN) - 1) << DSI_REG_PT_LP_MODE_POS))
#define DSI_REG_PT_PRBS_OR_JITT                  DSI_REG_PT_PRBS_OR_JITT
#define DSI_REG_PT_PRBS_OR_JITT_POS              (3U)
#define DSI_REG_PT_PRBS_OR_JITT_LEN              (1U)
#define DSI_REG_PT_PRBS_OR_JITT_MSK              (((1U << DSI_REG_PT_PRBS_OR_JITT_LEN) - 1) << DSI_REG_PT_PRBS_OR_JITT_POS)
#define DSI_REG_PT_PRBS_OR_JITT_UMSK             (~(((1U << DSI_REG_PT_PRBS_OR_JITT_LEN) - 1) << DSI_REG_PT_PRBS_OR_JITT_POS))
#define DSI_REG_FORCE_HIZ_LP                     DSI_REG_FORCE_HIZ_LP
#define DSI_REG_FORCE_HIZ_LP_POS                 (4U)
#define DSI_REG_FORCE_HIZ_LP_LEN                 (4U)
#define DSI_REG_FORCE_HIZ_LP_MSK                 (((1U << DSI_REG_FORCE_HIZ_LP_LEN) - 1) << DSI_REG_FORCE_HIZ_LP_POS)
#define DSI_REG_FORCE_HIZ_LP_UMSK                (~(((1U << DSI_REG_FORCE_HIZ_LP_LEN) - 1) << DSI_REG_FORCE_HIZ_LP_POS))
#define DSI_REG_FORCE_HIZ_HS                     DSI_REG_FORCE_HIZ_HS
#define DSI_REG_FORCE_HIZ_HS_POS                 (8U)
#define DSI_REG_FORCE_HIZ_HS_LEN                 (4U)
#define DSI_REG_FORCE_HIZ_HS_MSK                 (((1U << DSI_REG_FORCE_HIZ_HS_LEN) - 1) << DSI_REG_FORCE_HIZ_HS_POS)
#define DSI_REG_FORCE_HIZ_HS_UMSK                (~(((1U << DSI_REG_FORCE_HIZ_HS_LEN) - 1) << DSI_REG_FORCE_HIZ_HS_POS))
#define DSI_REG_FORCE_CLK_HIZ_LP                 DSI_REG_FORCE_CLK_HIZ_LP
#define DSI_REG_FORCE_CLK_HIZ_LP_POS             (12U)
#define DSI_REG_FORCE_CLK_HIZ_LP_LEN             (1U)
#define DSI_REG_FORCE_CLK_HIZ_LP_MSK             (((1U << DSI_REG_FORCE_CLK_HIZ_LP_LEN) - 1) << DSI_REG_FORCE_CLK_HIZ_LP_POS)
#define DSI_REG_FORCE_CLK_HIZ_LP_UMSK            (~(((1U << DSI_REG_FORCE_CLK_HIZ_LP_LEN) - 1) << DSI_REG_FORCE_CLK_HIZ_LP_POS))
#define DSI_REG_FORCE_CLK_HIZ_HS                 DSI_REG_FORCE_CLK_HIZ_HS
#define DSI_REG_FORCE_CLK_HIZ_HS_POS             (13U)
#define DSI_REG_FORCE_CLK_HIZ_HS_LEN             (1U)
#define DSI_REG_FORCE_CLK_HIZ_HS_MSK             (((1U << DSI_REG_FORCE_CLK_HIZ_HS_LEN) - 1) << DSI_REG_FORCE_CLK_HIZ_HS_POS)
#define DSI_REG_FORCE_CLK_HIZ_HS_UMSK            (~(((1U << DSI_REG_FORCE_CLK_HIZ_HS_LEN) - 1) << DSI_REG_FORCE_CLK_HIZ_HS_POS))
#define DSI_REG_ANA_LP_TXEN_CLKLANE_ESC          DSI_REG_ANA_LP_TXEN_CLKLANE_ESC
#define DSI_REG_ANA_LP_TXEN_CLKLANE_ESC_POS      (14U)
#define DSI_REG_ANA_LP_TXEN_CLKLANE_ESC_LEN      (1U)
#define DSI_REG_ANA_LP_TXEN_CLKLANE_ESC_MSK      (((1U << DSI_REG_ANA_LP_TXEN_CLKLANE_ESC_LEN) - 1) << DSI_REG_ANA_LP_TXEN_CLKLANE_ESC_POS)
#define DSI_REG_ANA_LP_TXEN_CLKLANE_ESC_UMSK     (~(((1U << DSI_REG_ANA_LP_TXEN_CLKLANE_ESC_LEN) - 1) << DSI_REG_ANA_LP_TXEN_CLKLANE_ESC_POS))
#define DSI_REG_ANA_LP_DPTXDATA_CLKLANE_ESC      DSI_REG_ANA_LP_DPTXDATA_CLKLANE_ESC
#define DSI_REG_ANA_LP_DPTXDATA_CLKLANE_ESC_POS  (15U)
#define DSI_REG_ANA_LP_DPTXDATA_CLKLANE_ESC_LEN  (1U)
#define DSI_REG_ANA_LP_DPTXDATA_CLKLANE_ESC_MSK  (((1U << DSI_REG_ANA_LP_DPTXDATA_CLKLANE_ESC_LEN) - 1) << DSI_REG_ANA_LP_DPTXDATA_CLKLANE_ESC_POS)
#define DSI_REG_ANA_LP_DPTXDATA_CLKLANE_ESC_UMSK (~(((1U << DSI_REG_ANA_LP_DPTXDATA_CLKLANE_ESC_LEN) - 1) << DSI_REG_ANA_LP_DPTXDATA_CLKLANE_ESC_POS))
#define DSI_REG_ANA_LP_DNTXDATA_CLKLANE_ESC      DSI_REG_ANA_LP_DNTXDATA_CLKLANE_ESC
#define DSI_REG_ANA_LP_DNTXDATA_CLKLANE_ESC_POS  (16U)
#define DSI_REG_ANA_LP_DNTXDATA_CLKLANE_ESC_LEN  (1U)
#define DSI_REG_ANA_LP_DNTXDATA_CLKLANE_ESC_MSK  (((1U << DSI_REG_ANA_LP_DNTXDATA_CLKLANE_ESC_LEN) - 1) << DSI_REG_ANA_LP_DNTXDATA_CLKLANE_ESC_POS)
#define DSI_REG_ANA_LP_DNTXDATA_CLKLANE_ESC_UMSK (~(((1U << DSI_REG_ANA_LP_DNTXDATA_CLKLANE_ESC_LEN) - 1) << DSI_REG_ANA_LP_DNTXDATA_CLKLANE_ESC_POS))
#define DSI_REG_ANA_HS_TXEN_CLKLANE_ESC          DSI_REG_ANA_HS_TXEN_CLKLANE_ESC
#define DSI_REG_ANA_HS_TXEN_CLKLANE_ESC_POS      (17U)
#define DSI_REG_ANA_HS_TXEN_CLKLANE_ESC_LEN      (1U)
#define DSI_REG_ANA_HS_TXEN_CLKLANE_ESC_MSK      (((1U << DSI_REG_ANA_HS_TXEN_CLKLANE_ESC_LEN) - 1) << DSI_REG_ANA_HS_TXEN_CLKLANE_ESC_POS)
#define DSI_REG_ANA_HS_TXEN_CLKLANE_ESC_UMSK     (~(((1U << DSI_REG_ANA_HS_TXEN_CLKLANE_ESC_LEN) - 1) << DSI_REG_ANA_HS_TXEN_CLKLANE_ESC_POS))
#define DSI_REG_ANA_CLK_EN_ESC                   DSI_REG_ANA_CLK_EN_ESC
#define DSI_REG_ANA_CLK_EN_ESC_POS               (18U)
#define DSI_REG_ANA_CLK_EN_ESC_LEN               (1U)
#define DSI_REG_ANA_CLK_EN_ESC_MSK               (((1U << DSI_REG_ANA_CLK_EN_ESC_LEN) - 1) << DSI_REG_ANA_CLK_EN_ESC_POS)
#define DSI_REG_ANA_CLK_EN_ESC_UMSK              (~(((1U << DSI_REG_ANA_CLK_EN_ESC_LEN) - 1) << DSI_REG_ANA_CLK_EN_ESC_POS))
#define DSI_REG_ANA_BYTE_REV                     DSI_REG_ANA_BYTE_REV
#define DSI_REG_ANA_BYTE_REV_POS                 (19U)
#define DSI_REG_ANA_BYTE_REV_LEN                 (1U)
#define DSI_REG_ANA_BYTE_REV_MSK                 (((1U << DSI_REG_ANA_BYTE_REV_LEN) - 1) << DSI_REG_ANA_BYTE_REV_POS)
#define DSI_REG_ANA_BYTE_REV_UMSK                (~(((1U << DSI_REG_ANA_BYTE_REV_LEN) - 1) << DSI_REG_ANA_BYTE_REV_POS))

/* 0xA0 : dphy_config_8 */
#define DSI_DPHY_CONFIG_8_OFFSET         (0xA0)
#define DSI_REG_ANA_LPTXP_DATA           DSI_REG_ANA_LPTXP_DATA
#define DSI_REG_ANA_LPTXP_DATA_POS       (0U)
#define DSI_REG_ANA_LPTXP_DATA_LEN       (4U)
#define DSI_REG_ANA_LPTXP_DATA_MSK       (((1U << DSI_REG_ANA_LPTXP_DATA_LEN) - 1) << DSI_REG_ANA_LPTXP_DATA_POS)
#define DSI_REG_ANA_LPTXP_DATA_UMSK      (~(((1U << DSI_REG_ANA_LPTXP_DATA_LEN) - 1) << DSI_REG_ANA_LPTXP_DATA_POS))
#define DSI_REG_ANA_LPTXN_DATA           DSI_REG_ANA_LPTXN_DATA
#define DSI_REG_ANA_LPTXN_DATA_POS       (4U)
#define DSI_REG_ANA_LPTXN_DATA_LEN       (4U)
#define DSI_REG_ANA_LPTXN_DATA_MSK       (((1U << DSI_REG_ANA_LPTXN_DATA_LEN) - 1) << DSI_REG_ANA_LPTXN_DATA_POS)
#define DSI_REG_ANA_LPTXN_DATA_UMSK      (~(((1U << DSI_REG_ANA_LPTXN_DATA_LEN) - 1) << DSI_REG_ANA_LPTXN_DATA_POS))
#define DSI_REG_ANA_LPTXEN               DSI_REG_ANA_LPTXEN
#define DSI_REG_ANA_LPTXEN_POS           (8U)
#define DSI_REG_ANA_LPTXEN_LEN           (4U)
#define DSI_REG_ANA_LPTXEN_MSK           (((1U << DSI_REG_ANA_LPTXEN_LEN) - 1) << DSI_REG_ANA_LPTXEN_POS)
#define DSI_REG_ANA_LPTXEN_UMSK          (~(((1U << DSI_REG_ANA_LPTXEN_LEN) - 1) << DSI_REG_ANA_LPTXEN_POS))
#define DSI_REG_ANA_LPRXEN               DSI_REG_ANA_LPRXEN
#define DSI_REG_ANA_LPRXEN_POS           (12U)
#define DSI_REG_ANA_LPRXEN_LEN           (4U)
#define DSI_REG_ANA_LPRXEN_MSK           (((1U << DSI_REG_ANA_LPRXEN_LEN) - 1) << DSI_REG_ANA_LPRXEN_POS)
#define DSI_REG_ANA_LPRXEN_UMSK          (~(((1U << DSI_REG_ANA_LPRXEN_LEN) - 1) << DSI_REG_ANA_LPRXEN_POS))
#define DSI_REG_ANA_HSTXEN               DSI_REG_ANA_HSTXEN
#define DSI_REG_ANA_HSTXEN_POS           (16U)
#define DSI_REG_ANA_HSTXEN_LEN           (4U)
#define DSI_REG_ANA_HSTXEN_MSK           (((1U << DSI_REG_ANA_HSTXEN_LEN) - 1) << DSI_REG_ANA_HSTXEN_POS)
#define DSI_REG_ANA_HSTXEN_UMSK          (~(((1U << DSI_REG_ANA_HSTXEN_LEN) - 1) << DSI_REG_ANA_HSTXEN_POS))
#define DSI_REG_ANA_HS_TRAIL_BYTE        DSI_REG_ANA_HS_TRAIL_BYTE
#define DSI_REG_ANA_HS_TRAIL_BYTE_POS    (20U)
#define DSI_REG_ANA_HS_TRAIL_BYTE_LEN    (4U)
#define DSI_REG_ANA_HS_TRAIL_BYTE_MSK    (((1U << DSI_REG_ANA_HS_TRAIL_BYTE_LEN) - 1) << DSI_REG_ANA_HS_TRAIL_BYTE_POS)
#define DSI_REG_ANA_HS_TRAIL_BYTE_UMSK   (~(((1U << DSI_REG_ANA_HS_TRAIL_BYTE_LEN) - 1) << DSI_REG_ANA_HS_TRAIL_BYTE_POS))
#define DSI_REG_ANA_HS_SYNC_LD_BYTE      DSI_REG_ANA_HS_SYNC_LD_BYTE
#define DSI_REG_ANA_HS_SYNC_LD_BYTE_POS  (24U)
#define DSI_REG_ANA_HS_SYNC_LD_BYTE_LEN  (4U)
#define DSI_REG_ANA_HS_SYNC_LD_BYTE_MSK  (((1U << DSI_REG_ANA_HS_SYNC_LD_BYTE_LEN) - 1) << DSI_REG_ANA_HS_SYNC_LD_BYTE_POS)
#define DSI_REG_ANA_HS_SYNC_LD_BYTE_UMSK (~(((1U << DSI_REG_ANA_HS_SYNC_LD_BYTE_LEN) - 1) << DSI_REG_ANA_HS_SYNC_LD_BYTE_POS))
#define DSI_REG_ANA_HS_P2S_SEL_BYTE      DSI_REG_ANA_HS_P2S_SEL_BYTE
#define DSI_REG_ANA_HS_P2S_SEL_BYTE_POS  (28U)
#define DSI_REG_ANA_HS_P2S_SEL_BYTE_LEN  (4U)
#define DSI_REG_ANA_HS_P2S_SEL_BYTE_MSK  (((1U << DSI_REG_ANA_HS_P2S_SEL_BYTE_LEN) - 1) << DSI_REG_ANA_HS_P2S_SEL_BYTE_POS)
#define DSI_REG_ANA_HS_P2S_SEL_BYTE_UMSK (~(((1U << DSI_REG_ANA_HS_P2S_SEL_BYTE_LEN) - 1) << DSI_REG_ANA_HS_P2S_SEL_BYTE_POS))

/* 0xA4 : dphy_config_9 */
#define DSI_DPHY_CONFIG_9_OFFSET          (0xA4)
#define DSI_REG_ANA_HS_DATA_OUT_BYTE      DSI_REG_ANA_HS_DATA_OUT_BYTE
#define DSI_REG_ANA_HS_DATA_OUT_BYTE_POS  (0U)
#define DSI_REG_ANA_HS_DATA_OUT_BYTE_LEN  (32U)
#define DSI_REG_ANA_HS_DATA_OUT_BYTE_MSK  (((1U << DSI_REG_ANA_HS_DATA_OUT_BYTE_LEN) - 1) << DSI_REG_ANA_HS_DATA_OUT_BYTE_POS)
#define DSI_REG_ANA_HS_DATA_OUT_BYTE_UMSK (~(((1U << DSI_REG_ANA_HS_DATA_OUT_BYTE_LEN) - 1) << DSI_REG_ANA_HS_DATA_OUT_BYTE_POS))

/* 0xA8 : dphy_config_10 */
#define DSI_DPHY_CONFIG_10_OFFSET           (0xA8)
#define DSI_REG_TESTBUS_SEL_LO              DSI_REG_TESTBUS_SEL_LO
#define DSI_REG_TESTBUS_SEL_LO_POS          (0U)
#define DSI_REG_TESTBUS_SEL_LO_LEN          (4U)
#define DSI_REG_TESTBUS_SEL_LO_MSK          (((1U << DSI_REG_TESTBUS_SEL_LO_LEN) - 1) << DSI_REG_TESTBUS_SEL_LO_POS)
#define DSI_REG_TESTBUS_SEL_LO_UMSK         (~(((1U << DSI_REG_TESTBUS_SEL_LO_LEN) - 1) << DSI_REG_TESTBUS_SEL_LO_POS))
#define DSI_REG_TESTBUS_SEL_HI              DSI_REG_TESTBUS_SEL_HI
#define DSI_REG_TESTBUS_SEL_HI_POS          (4U)
#define DSI_REG_TESTBUS_SEL_HI_LEN          (4U)
#define DSI_REG_TESTBUS_SEL_HI_MSK          (((1U << DSI_REG_TESTBUS_SEL_HI_LEN) - 1) << DSI_REG_TESTBUS_SEL_HI_POS)
#define DSI_REG_TESTBUS_SEL_HI_UMSK         (~(((1U << DSI_REG_TESTBUS_SEL_HI_LEN) - 1) << DSI_REG_TESTBUS_SEL_HI_POS))
#define DSI_REG_TESTBUS_HI8BSEL_8BMODE      DSI_REG_TESTBUS_HI8BSEL_8BMODE
#define DSI_REG_TESTBUS_HI8BSEL_8BMODE_POS  (8U)
#define DSI_REG_TESTBUS_HI8BSEL_8BMODE_LEN  (1U)
#define DSI_REG_TESTBUS_HI8BSEL_8BMODE_MSK  (((1U << DSI_REG_TESTBUS_HI8BSEL_8BMODE_LEN) - 1) << DSI_REG_TESTBUS_HI8BSEL_8BMODE_POS)
#define DSI_REG_TESTBUS_HI8BSEL_8BMODE_UMSK (~(((1U << DSI_REG_TESTBUS_HI8BSEL_8BMODE_LEN) - 1) << DSI_REG_TESTBUS_HI8BSEL_8BMODE_POS))
#define DSI_REG_IMP_PU_CODE                 DSI_REG_IMP_PU_CODE
#define DSI_REG_IMP_PU_CODE_POS             (9U)
#define DSI_REG_IMP_PU_CODE_LEN             (5U)
#define DSI_REG_IMP_PU_CODE_MSK             (((1U << DSI_REG_IMP_PU_CODE_LEN) - 1) << DSI_REG_IMP_PU_CODE_POS)
#define DSI_REG_IMP_PU_CODE_UMSK            (~(((1U << DSI_REG_IMP_PU_CODE_LEN) - 1) << DSI_REG_IMP_PU_CODE_POS))
#define DSI_REG_IMP_PD_CODE                 DSI_REG_IMP_PD_CODE
#define DSI_REG_IMP_PD_CODE_POS             (14U)
#define DSI_REG_IMP_PD_CODE_LEN             (5U)
#define DSI_REG_IMP_PD_CODE_MSK             (((1U << DSI_REG_IMP_PD_CODE_LEN) - 1) << DSI_REG_IMP_PD_CODE_POS)
#define DSI_REG_IMP_PD_CODE_UMSK            (~(((1U << DSI_REG_IMP_PD_CODE_LEN) - 1) << DSI_REG_IMP_PD_CODE_POS))
#define DSI_REG_DPHY_VREG400MV_TRIM         DSI_REG_DPHY_VREG400MV_TRIM
#define DSI_REG_DPHY_VREG400MV_TRIM_POS     (19U)
#define DSI_REG_DPHY_VREG400MV_TRIM_LEN     (3U)
#define DSI_REG_DPHY_VREG400MV_TRIM_MSK     (((1U << DSI_REG_DPHY_VREG400MV_TRIM_LEN) - 1) << DSI_REG_DPHY_VREG400MV_TRIM_POS)
#define DSI_REG_DPHY_VREG400MV_TRIM_UMSK    (~(((1U << DSI_REG_DPHY_VREG400MV_TRIM_LEN) - 1) << DSI_REG_DPHY_VREG400MV_TRIM_POS))
#define DSI_REG_DPHY_BG_VREF_EN             DSI_REG_DPHY_BG_VREF_EN
#define DSI_REG_DPHY_BG_VREF_EN_POS         (22U)
#define DSI_REG_DPHY_BG_VREF_EN_LEN         (1U)
#define DSI_REG_DPHY_BG_VREF_EN_MSK         (((1U << DSI_REG_DPHY_BG_VREF_EN_LEN) - 1) << DSI_REG_DPHY_BG_VREF_EN_POS)
#define DSI_REG_DPHY_BG_VREF_EN_UMSK        (~(((1U << DSI_REG_DPHY_BG_VREF_EN_LEN) - 1) << DSI_REG_DPHY_BG_VREF_EN_POS))
#define DSI_REG_ANA_BG_VREF_EN              DSI_REG_ANA_BG_VREF_EN
#define DSI_REG_ANA_BG_VREF_EN_POS          (23U)
#define DSI_REG_ANA_BG_VREF_EN_LEN          (1U)
#define DSI_REG_ANA_BG_VREF_EN_MSK          (((1U << DSI_REG_ANA_BG_VREF_EN_LEN) - 1) << DSI_REG_ANA_BG_VREF_EN_POS)
#define DSI_REG_ANA_BG_VREF_EN_UMSK         (~(((1U << DSI_REG_ANA_BG_VREF_EN_LEN) - 1) << DSI_REG_ANA_BG_VREF_EN_POS))
#define DSI_REG_ANA_VREG400MV_TRIM          DSI_REG_ANA_VREG400MV_TRIM
#define DSI_REG_ANA_VREG400MV_TRIM_POS      (24U)
#define DSI_REG_ANA_VREG400MV_TRIM_LEN      (3U)
#define DSI_REG_ANA_VREG400MV_TRIM_MSK      (((1U << DSI_REG_ANA_VREG400MV_TRIM_LEN) - 1) << DSI_REG_ANA_VREG400MV_TRIM_POS)
#define DSI_REG_ANA_VREG400MV_TRIM_UMSK     (~(((1U << DSI_REG_ANA_VREG400MV_TRIM_LEN) - 1) << DSI_REG_ANA_VREG400MV_TRIM_POS))
#define DSI_REG_ANA_VREF_EN                 DSI_REG_ANA_VREF_EN
#define DSI_REG_ANA_VREF_EN_POS             (27U)
#define DSI_REG_ANA_VREF_EN_LEN             (1U)
#define DSI_REG_ANA_VREF_EN_MSK             (((1U << DSI_REG_ANA_VREF_EN_LEN) - 1) << DSI_REG_ANA_VREF_EN_POS)
#define DSI_REG_ANA_VREF_EN_UMSK            (~(((1U << DSI_REG_ANA_VREF_EN_LEN) - 1) << DSI_REG_ANA_VREF_EN_POS))

/* 0xAC : dphy_config_11 */
#define DSI_DPHY_CONFIG_11_OFFSET (0xAC)
#define DSI_REG_DSI_ANA_0         DSI_REG_DSI_ANA_0
#define DSI_REG_DSI_ANA_0_POS     (0U)
#define DSI_REG_DSI_ANA_0_LEN     (16U)
#define DSI_REG_DSI_ANA_0_MSK     (((1U << DSI_REG_DSI_ANA_0_LEN) - 1) << DSI_REG_DSI_ANA_0_POS)
#define DSI_REG_DSI_ANA_0_UMSK    (~(((1U << DSI_REG_DSI_ANA_0_LEN) - 1) << DSI_REG_DSI_ANA_0_POS))
#define DSI_REG_DSI_ANA_1         DSI_REG_DSI_ANA_1
#define DSI_REG_DSI_ANA_1_POS     (16U)
#define DSI_REG_DSI_ANA_1_LEN     (16U)
#define DSI_REG_DSI_ANA_1_MSK     (((1U << DSI_REG_DSI_ANA_1_LEN) - 1) << DSI_REG_DSI_ANA_1_POS)
#define DSI_REG_DSI_ANA_1_UMSK    (~(((1U << DSI_REG_DSI_ANA_1_LEN) - 1) << DSI_REG_DSI_ANA_1_POS))

/* 0xB0 : dphy_config_12 */
#define DSI_DPHY_CONFIG_12_OFFSET (0xB0)
#define DSI_REG_DSI_ANA_2         DSI_REG_DSI_ANA_2
#define DSI_REG_DSI_ANA_2_POS     (0U)
#define DSI_REG_DSI_ANA_2_LEN     (16U)
#define DSI_REG_DSI_ANA_2_MSK     (((1U << DSI_REG_DSI_ANA_2_LEN) - 1) << DSI_REG_DSI_ANA_2_POS)
#define DSI_REG_DSI_ANA_2_UMSK    (~(((1U << DSI_REG_DSI_ANA_2_LEN) - 1) << DSI_REG_DSI_ANA_2_POS))

/* 0xB4 : dphy_config_13 */
#define DSI_DPHY_CONFIG_13_OFFSET    (0xB4)
#define DSI_REG_RD_DIG_TEST_BUS      DSI_REG_RD_DIG_TEST_BUS
#define DSI_REG_RD_DIG_TEST_BUS_POS  (0U)
#define DSI_REG_RD_DIG_TEST_BUS_LEN  (16U)
#define DSI_REG_RD_DIG_TEST_BUS_MSK  (((1U << DSI_REG_RD_DIG_TEST_BUS_LEN) - 1) << DSI_REG_RD_DIG_TEST_BUS_POS)
#define DSI_REG_RD_DIG_TEST_BUS_UMSK (~(((1U << DSI_REG_RD_DIG_TEST_BUS_LEN) - 1) << DSI_REG_RD_DIG_TEST_BUS_POS))

/* 0xB8 : dphy_config_14 */
#define DSI_DPHY_CONFIG_14_OFFSET    (0xB8)
#define DSI_REG_PT_FREE_REP_PAT      DSI_REG_PT_FREE_REP_PAT
#define DSI_REG_PT_FREE_REP_PAT_POS  (0U)
#define DSI_REG_PT_FREE_REP_PAT_LEN  (32U)
#define DSI_REG_PT_FREE_REP_PAT_MSK  (((1U << DSI_REG_PT_FREE_REP_PAT_LEN) - 1) << DSI_REG_PT_FREE_REP_PAT_POS)
#define DSI_REG_PT_FREE_REP_PAT_UMSK (~(((1U << DSI_REG_PT_FREE_REP_PAT_LEN) - 1) << DSI_REG_PT_FREE_REP_PAT_POS))

/* 0xBC : dphy_config_15 */
#define DSI_DPHY_CONFIG_15_OFFSET      (0xBC)
#define DSI_REG_DSI_DC_TP_OUT_EN       DSI_REG_DSI_DC_TP_OUT_EN
#define DSI_REG_DSI_DC_TP_OUT_EN_POS   (0U)
#define DSI_REG_DSI_DC_TP_OUT_EN_LEN   (1U)
#define DSI_REG_DSI_DC_TP_OUT_EN_MSK   (((1U << DSI_REG_DSI_DC_TP_OUT_EN_LEN) - 1) << DSI_REG_DSI_DC_TP_OUT_EN_POS)
#define DSI_REG_DSI_DC_TP_OUT_EN_UMSK  (~(((1U << DSI_REG_DSI_DC_TP_OUT_EN_LEN) - 1) << DSI_REG_DSI_DC_TP_OUT_EN_POS))
#define DSI_REG_DSI_PW_AVDD1815        DSI_REG_DSI_PW_AVDD1815
#define DSI_REG_DSI_PW_AVDD1815_POS    (4U)
#define DSI_REG_DSI_PW_AVDD1815_LEN    (1U)
#define DSI_REG_DSI_PW_AVDD1815_MSK    (((1U << DSI_REG_DSI_PW_AVDD1815_LEN) - 1) << DSI_REG_DSI_PW_AVDD1815_POS)
#define DSI_REG_DSI_PW_AVDD1815_UMSK   (~(((1U << DSI_REG_DSI_PW_AVDD1815_LEN) - 1) << DSI_REG_DSI_PW_AVDD1815_POS))
#define DSI_REG_DPHY_PU_LDO11          DSI_REG_DPHY_PU_LDO11
#define DSI_REG_DPHY_PU_LDO11_POS      (8U)
#define DSI_REG_DPHY_PU_LDO11_LEN      (1U)
#define DSI_REG_DPHY_PU_LDO11_MSK      (((1U << DSI_REG_DPHY_PU_LDO11_LEN) - 1) << DSI_REG_DPHY_PU_LDO11_POS)
#define DSI_REG_DPHY_PU_LDO11_UMSK     (~(((1U << DSI_REG_DPHY_PU_LDO11_LEN) - 1) << DSI_REG_DPHY_PU_LDO11_POS))
#define DSI_REG_DPHY_SHORT_LDO11       DSI_REG_DPHY_SHORT_LDO11
#define DSI_REG_DPHY_SHORT_LDO11_POS   (12U)
#define DSI_REG_DPHY_SHORT_LDO11_LEN   (1U)
#define DSI_REG_DPHY_SHORT_LDO11_MSK   (((1U << DSI_REG_DPHY_SHORT_LDO11_LEN) - 1) << DSI_REG_DPHY_SHORT_LDO11_POS)
#define DSI_REG_DPHY_SHORT_LDO11_UMSK  (~(((1U << DSI_REG_DPHY_SHORT_LDO11_LEN) - 1) << DSI_REG_DPHY_SHORT_LDO11_POS))
#define DSI_REG_DPHY_LDO11_RFB_SW      DSI_REG_DPHY_LDO11_RFB_SW
#define DSI_REG_DPHY_LDO11_RFB_SW_POS  (16U)
#define DSI_REG_DPHY_LDO11_RFB_SW_LEN  (3U)
#define DSI_REG_DPHY_LDO11_RFB_SW_MSK  (((1U << DSI_REG_DPHY_LDO11_RFB_SW_LEN) - 1) << DSI_REG_DPHY_LDO11_RFB_SW_POS)
#define DSI_REG_DPHY_LDO11_RFB_SW_UMSK (~(((1U << DSI_REG_DPHY_LDO11_RFB_SW_LEN) - 1) << DSI_REG_DPHY_LDO11_RFB_SW_POS))
#define DSI_REG_TEN_DSI_LDO            DSI_REG_TEN_DSI_LDO
#define DSI_REG_TEN_DSI_LDO_POS        (20U)
#define DSI_REG_TEN_DSI_LDO_LEN        (1U)
#define DSI_REG_TEN_DSI_LDO_MSK        (((1U << DSI_REG_TEN_DSI_LDO_LEN) - 1) << DSI_REG_TEN_DSI_LDO_POS)
#define DSI_REG_TEN_DSI_LDO_UMSK       (~(((1U << DSI_REG_TEN_DSI_LDO_LEN) - 1) << DSI_REG_TEN_DSI_LDO_POS))
#define DSI_REG_MIPI_LDO_FAST          DSI_REG_MIPI_LDO_FAST
#define DSI_REG_MIPI_LDO_FAST_POS      (24U)
#define DSI_REG_MIPI_LDO_FAST_LEN      (1U)
#define DSI_REG_MIPI_LDO_FAST_MSK      (((1U << DSI_REG_MIPI_LDO_FAST_LEN) - 1) << DSI_REG_MIPI_LDO_FAST_POS)
#define DSI_REG_MIPI_LDO_FAST_UMSK     (~(((1U << DSI_REG_MIPI_LDO_FAST_LEN) - 1) << DSI_REG_MIPI_LDO_FAST_POS))
#define DSI_REG_DSI_RST_N_PRE          DSI_REG_DSI_RST_N_PRE
#define DSI_REG_DSI_RST_N_PRE_POS      (28U)
#define DSI_REG_DSI_RST_N_PRE_LEN      (1U)
#define DSI_REG_DSI_RST_N_PRE_MSK      (((1U << DSI_REG_DSI_RST_N_PRE_LEN) - 1) << DSI_REG_DSI_RST_N_PRE_POS)
#define DSI_REG_DSI_RST_N_PRE_UMSK     (~(((1U << DSI_REG_DSI_RST_N_PRE_LEN) - 1) << DSI_REG_DSI_RST_N_PRE_POS))
#define DSI_REG_CSI_RST_N_PRE          DSI_REG_CSI_RST_N_PRE
#define DSI_REG_CSI_RST_N_PRE_POS      (29U)
#define DSI_REG_CSI_RST_N_PRE_LEN      (1U)
#define DSI_REG_CSI_RST_N_PRE_MSK      (((1U << DSI_REG_CSI_RST_N_PRE_LEN) - 1) << DSI_REG_CSI_RST_N_PRE_POS)
#define DSI_REG_CSI_RST_N_PRE_UMSK     (~(((1U << DSI_REG_CSI_RST_N_PRE_LEN) - 1) << DSI_REG_CSI_RST_N_PRE_POS))

/* 0xC0 : dphy_config_16 */
#define DSI_DPHY_CONFIG_16_OFFSET     (0xC0)
#define DSI_REG_DSI_BYTE_CLK_INV      DSI_REG_DSI_BYTE_CLK_INV
#define DSI_REG_DSI_BYTE_CLK_INV_POS  (0U)
#define DSI_REG_DSI_BYTE_CLK_INV_LEN  (1U)
#define DSI_REG_DSI_BYTE_CLK_INV_MSK  (((1U << DSI_REG_DSI_BYTE_CLK_INV_LEN) - 1) << DSI_REG_DSI_BYTE_CLK_INV_POS)
#define DSI_REG_DSI_BYTE_CLK_INV_UMSK (~(((1U << DSI_REG_DSI_BYTE_CLK_INV_LEN) - 1) << DSI_REG_DSI_BYTE_CLK_INV_POS))
#define DSI_REG_DSI_LPRX_CLK_INV      DSI_REG_DSI_LPRX_CLK_INV
#define DSI_REG_DSI_LPRX_CLK_INV_POS  (1U)
#define DSI_REG_DSI_LPRX_CLK_INV_LEN  (1U)
#define DSI_REG_DSI_LPRX_CLK_INV_MSK  (((1U << DSI_REG_DSI_LPRX_CLK_INV_LEN) - 1) << DSI_REG_DSI_LPRX_CLK_INV_POS)
#define DSI_REG_DSI_LPRX_CLK_INV_UMSK (~(((1U << DSI_REG_DSI_LPRX_CLK_INV_LEN) - 1) << DSI_REG_DSI_LPRX_CLK_INV_POS))

/* 0xFC : dummy_reg */
#define DSI_DUMMY_REG_OFFSET (0xFC)
#define DSI_DUMMY_REG        DSI_DUMMY_REG
#define DSI_DUMMY_REG_POS    (0U)
#define DSI_DUMMY_REG_LEN    (32U)
#define DSI_DUMMY_REG_MSK    (((1U << DSI_DUMMY_REG_LEN) - 1) << DSI_DUMMY_REG_POS)
#define DSI_DUMMY_REG_UMSK   (~(((1U << DSI_DUMMY_REG_LEN) - 1) << DSI_DUMMY_REG_POS))

struct dsi_reg {
    /* 0x0 : dsi_config */
    union {
        struct {
            uint32_t cr_hstx_en      : 1; /* [    0],        r/w,        0x0 */
            uint32_t cr_lane_num     : 2; /* [ 2: 1],        r/w,        0x0 */
            uint32_t reserved_3      : 1; /* [    3],       rsvd,        0x0 */
            uint32_t cr_hstx_mode    : 1; /* [    4],        r/w,        0x1 */
            uint32_t cr_lse_pkt_en   : 1; /* [    5],        r/w,        0x0 */
            uint32_t cr_lane_mux_sel : 2; /* [ 7: 6],        r/w,        0x0 */
            uint32_t cr_dt           : 6; /* [13: 8],        r/w,       0x3e */
            uint32_t cr_vc           : 2; /* [15:14],        r/w,        0x0 */
            uint32_t cr_hstx_vfp     : 8; /* [23:16],        r/w,        0x2 */
            uint32_t cr_hstx_vsa     : 8; /* [31:24],        r/w,        0x2 */
        } BF;
        uint32_t WORD;
    } dsi_config;

    /* 0x4 : dsi_esc_config */
    union {
        struct {
            uint32_t cr_esc_tx_en        : 1; /* [    0],        w1p,        0x0 */
            uint32_t cr_esc_tx_mode      : 2; /* [ 2: 1],        r/w,        0x0 */
            uint32_t cr_esc_tx_ulps_exit : 1; /* [    3],        w1p,        0x0 */
            uint32_t cr_esc_tx_trig      : 4; /* [ 7: 4],        r/w,        0x0 */
            uint32_t reserved_8_15       : 8; /* [15: 8],       rsvd,        0x0 */
            uint32_t cr_esc_rx_en        : 1; /* [   16],        r/w,        0x0 */
            uint32_t reserved_17_23      : 7; /* [23:17],       rsvd,        0x0 */
            uint32_t st_esc_rx_len       : 8; /* [31:24],          r,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_esc_config;

    /* 0x8 : dsi_lpdt_tx_config */
    union {
        struct {
            uint32_t cr_lpdt_pdlen : 8; /* [ 7: 0],        r/w,        0x0 */
            uint32_t cr_lpdt_vc    : 2; /* [ 9: 8],        r/w,        0x0 */
            uint32_t cr_lpdt_di    : 6; /* [15:10],        r/w,        0x0 */
            uint32_t cr_lpdt_word0 : 8; /* [23:16],        r/w,        0x0 */
            uint32_t cr_lpdt_word1 : 8; /* [31:24],        r/w,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_lpdt_tx_config;

    /* 0xC : dsi_hstx_config */
    union {
        struct {
            uint32_t cr_hstx_pc     : 11; /* [10: 0],        r/w,      0x500 */
            uint32_t reserved_11_15 : 5;  /* [15:11],       rsvd,        0x0 */
            uint32_t cr_hstx_out_th : 11; /* [26:16],        r/w,      0x348 */
            uint32_t reserved_27_31 : 5;  /* [31:27],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_hstx_config;

    /* 0x10 : dsi_int_status */
    union {
        struct {
            uint32_t dsi_int_status : 14; /* [13: 0],          r,        0x0 */
            uint32_t reserved_14_31 : 18; /* [31:14],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_int_status;

    /* 0x14 : dsi_int_mask */
    union {
        struct {
            uint32_t dsi_int_mask   : 14; /* [13: 0],        r/w,     0x3fff */
            uint32_t reserved_14_31 : 18; /* [31:14],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_int_mask;

    /* 0x18 : dsi_int_clear */
    union {
        struct {
            uint32_t dsi_int_clear  : 14; /* [13: 0],        w1p,        0x0 */
            uint32_t reserved_14_31 : 18; /* [31:14],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_int_clear;

    /* 0x1C : dsi_int_enable */
    union {
        struct {
            uint32_t dsi_int_enable : 14; /* [13: 0],        r/w,     0x3fff */
            uint32_t reserved_14_31 : 18; /* [31:14],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_int_enable;

    /* 0x20 : dsi_frame_num */
    union {
        struct {
            uint32_t cr_frame_num   : 16; /* [15: 0],        r/w,        0x0 */
            uint32_t reserved_16_30 : 15; /* [30:16],       rsvd,        0x0 */
            uint32_t cr_frame_upd   : 1;  /* [   31],        w1p,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_frame_num;

    /* 0x24  reserved */
    uint8_t RESERVED0x24[60];

    /* 0x60 : dsi_fifo_config_0 */
    union {
        struct {
            uint32_t dsi_dma_tx_en     : 1;  /* [    0],        r/w,        0x0 */
            uint32_t dsi_dma_rx_en     : 1;  /* [    1],        r/w,        0x0 */
            uint32_t tx_fifo_clr       : 1;  /* [    2],        w1p,        0x0 */
            uint32_t rx_fifo_clr       : 1;  /* [    3],        w1p,        0x0 */
            uint32_t tx_fifo_overflow  : 1;  /* [    4],          r,        0x0 */
            uint32_t tx_fifo_underflow : 1;  /* [    5],          r,        0x0 */
            uint32_t rx_fifo_overflow  : 1;  /* [    6],          r,        0x0 */
            uint32_t rx_fifo_underflow : 1;  /* [    7],          r,        0x0 */
            uint32_t reserved_8_31     : 24; /* [31: 8],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_fifo_config_0;

    /* 0x64 : dsi_fifo_config_1 */
    union {
        struct {
            uint32_t tx_fifo_cnt    : 3; /* [ 2: 0],          r,        0x4 */
            uint32_t reserved_3_7   : 5; /* [ 7: 3],       rsvd,        0x0 */
            uint32_t rx_fifo_cnt    : 3; /* [10: 8],          r,        0x0 */
            uint32_t reserved_11_15 : 5; /* [15:11],       rsvd,        0x0 */
            uint32_t tx_fifo_th     : 2; /* [17:16],        r/w,        0x0 */
            uint32_t reserved_18_23 : 6; /* [23:18],       rsvd,        0x0 */
            uint32_t rx_fifo_th     : 2; /* [25:24],        r/w,        0x0 */
            uint32_t reserved_26_31 : 6; /* [31:26],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_fifo_config_1;

    /* 0x68 : dsi_fifo_wdata */
    union {
        struct {
            uint32_t dsi_fifo_wdata : 32; /* [31: 0],          w,          x */
        } BF;
        uint32_t WORD;
    } dsi_fifo_wdata;

    /* 0x6C : dsi_fifo_rdata */
    union {
        struct {
            uint32_t dsi_fifo_rdata : 32; /* [31: 0],          r,        0x0 */
        } BF;
        uint32_t WORD;
    } dsi_fifo_rdata;

    /* 0x70  reserved */
    uint8_t RESERVED0x70[16];

    /* 0x80 : dphy_config_0 */
    union {
        struct {
            uint32_t cl_enable           : 1; /* [    0],        r/w,        0x0 */
            uint32_t cl_txrequesths      : 1; /* [    1],        r/w,        0x0 */
            uint32_t cl_txulpsclk        : 1; /* [    2],        r/w,        0x0 */
            uint32_t cl_txulpsexit       : 1; /* [    3],        w1p,        0x0 */
            uint32_t cl_stopstate        : 1; /* [    4],          r,        0x1 */
            uint32_t cl_ulpsactivenot    : 1; /* [    5],          r,        0x1 */
            uint32_t reserved_6_7        : 2; /* [ 7: 6],       rsvd,        0x0 */
            uint32_t dl0_enable          : 1; /* [    8],        r/w,        0x0 */
            uint32_t dl1_enable          : 1; /* [    9],        r/w,        0x0 */
            uint32_t dl2_enable          : 1; /* [   10],        r/w,        0x0 */
            uint32_t dl3_enable          : 1; /* [   11],        r/w,        0x0 */
            uint32_t dl0_stopstate       : 1; /* [   12],          r,        0x1 */
            uint32_t dl1_stopstate       : 1; /* [   13],          r,        0x1 */
            uint32_t dl2_stopstate       : 1; /* [   14],          r,        0x1 */
            uint32_t dl3_stopstate       : 1; /* [   15],          r,        0x1 */
            uint32_t dl0_ulpsactivenot   : 1; /* [   16],          r,        0x1 */
            uint32_t dl1_ulpsactivenot   : 1; /* [   17],          r,        0x1 */
            uint32_t dl2_ulpsactivenot   : 1; /* [   18],          r,        0x1 */
            uint32_t dl3_ulpsactivenot   : 1; /* [   19],          r,        0x1 */
            uint32_t dl0_forcerxmode     : 1; /* [   20],        r/w,        0x0 */
            uint32_t dl1_forcerxmode     : 1; /* [   21],        r/w,        0x0 */
            uint32_t dl2_forcerxmode     : 1; /* [   22],        r/w,        0x0 */
            uint32_t dl3_forcerxmode     : 1; /* [   23],        r/w,        0x0 */
            uint32_t dl0_forcetxstopmode : 1; /* [   24],        r/w,        0x0 */
            uint32_t dl1_forcetxstopmode : 1; /* [   25],        r/w,        0x0 */
            uint32_t dl2_forcetxstopmode : 1; /* [   26],        r/w,        0x0 */
            uint32_t dl3_forcetxstopmode : 1; /* [   27],        r/w,        0x0 */
            uint32_t reserved_28_29      : 2; /* [29:28],       rsvd,        0x0 */
            uint32_t dl0_turnesc         : 1; /* [   30],        w1p,        0x0 */
            uint32_t dsi_reset_n         : 1; /* [   31],        r/w,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_0;

    /* 0x84 : dphy_config_1 */
    union {
        struct {
            uint32_t reg_time_ck_zero    : 8; /* [ 7: 0],        r/w,        0xf */
            uint32_t reg_time_ck_trail   : 8; /* [15: 8],        r/w,        0x3 */
            uint32_t reg_time_ck_exit    : 8; /* [23:16],        r/w,        0x5 */
            uint32_t reg_en_lprx_at_ulps : 1; /* [   24],        r/w,        0x0 */
            uint32_t reserved_25_31      : 7; /* [31:25],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_1;

    /* 0x88 : dphy_config_2 */
    union {
        struct {
            uint32_t reg_time_hs_zero  : 8; /* [ 7: 0],        r/w,        0x5 */
            uint32_t reg_time_hs_trail : 8; /* [15: 8],        r/w,        0x3 */
            uint32_t reg_time_hs_prep  : 8; /* [23:16],        r/w,        0x2 */
            uint32_t reg_time_hs_exit  : 8; /* [31:24],        r/w,        0x5 */
        } BF;
        uint32_t WORD;
    } dphy_config_2;

    /* 0x8C : dphy_config_3 */
    union {
        struct {
            uint32_t reg_time_ta_go  : 8; /* [ 7: 0],        r/w,        0xc */
            uint32_t reg_time_ta_get : 8; /* [15: 8],        r/w,        0xf */
            uint32_t reg_time_reqrdy : 8; /* [23:16],        r/w,        0x0 */
            uint32_t reg_time_lpx    : 8; /* [31:24],        r/w,        0x3 */
        } BF;
        uint32_t WORD;
    } dphy_config_3;

    /* 0x90 : dphy_config_4 */
    union {
        struct {
            uint32_t reg_time_wakeup : 16; /* [15: 0],        r/w,     0x9c41 */
            uint32_t reserved_16_31  : 16; /* [31:16],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_4;

    /* 0x94 : dphy_config_5 */
    union {
        struct {
            uint32_t reg_trig3_code : 8; /* [ 7: 0],        r/w,        0x5 */
            uint32_t reg_trig2_code : 8; /* [15: 8],        r/w,       0x84 */
            uint32_t reg_trig1_code : 8; /* [23:16],        r/w,       0xba */
            uint32_t reg_trig0_code : 8; /* [31:24],        r/w,       0x46 */
        } BF;
        uint32_t WORD;
    } dphy_config_5;

    /* 0x98 : dphy_config_6 */
    union {
        struct {
            uint32_t reg_ulps_code  : 8;  /* [ 7: 0],        r/w,       0x78 */
            uint32_t reg_lpdt_code  : 8;  /* [15: 8],        r/w,       0x87 */
            uint32_t reserved_16_31 : 16; /* [31:16],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_6;

    /* 0x9C : dphy_config_7 */
    union {
        struct {
            uint32_t reg_ana_test_en                 : 1;  /* [    0],        r/w,        0x0 */
            uint32_t reg_pt_en                       : 1;  /* [    1],        r/w,        0x0 */
            uint32_t reg_pt_lp_mode                  : 1;  /* [    2],        r/w,        0x0 */
            uint32_t reg_pt_prbs_or_jitt             : 1;  /* [    3],        r/w,        0x0 */
            uint32_t reg_force_hiz_lp                : 4;  /* [ 7: 4],        r/w,        0x0 */
            uint32_t reg_force_hiz_hs                : 4;  /* [11: 8],        r/w,        0x0 */
            uint32_t reg_force_clk_hiz_lp            : 1;  /* [   12],        r/w,        0x0 */
            uint32_t reg_force_clk_hiz_hs            : 1;  /* [   13],        r/w,        0x0 */
            uint32_t reg_ana_lp_txen_clklane_esc     : 1;  /* [   14],        r/w,        0x0 */
            uint32_t reg_ana_lp_dptxdata_clklane_esc : 1;  /* [   15],        r/w,        0x0 */
            uint32_t reg_ana_lp_dntxdata_clklane_esc : 1;  /* [   16],        r/w,        0x0 */
            uint32_t reg_ana_hs_txen_clklane_esc     : 1;  /* [   17],        r/w,        0x0 */
            uint32_t reg_ana_clk_en_esc              : 1;  /* [   18],        r/w,        0x0 */
            uint32_t reg_ana_byte_rev                : 1;  /* [   19],        r/w,        0x0 */
            uint32_t reserved_20_31                  : 12; /* [31:20],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_7;

    /* 0xA0 : dphy_config_8 */
    union {
        struct {
            uint32_t reg_ana_lptxp_data      : 4; /* [ 3: 0],        r/w,        0x0 */
            uint32_t reg_ana_lptxn_data      : 4; /* [ 7: 4],        r/w,        0x0 */
            uint32_t reg_ana_lptxen          : 4; /* [11: 8],        r/w,        0x0 */
            uint32_t reg_ana_lprxen          : 4; /* [15:12],        r/w,        0x0 */
            uint32_t reg_ana_hstxen          : 4; /* [19:16],        r/w,        0x0 */
            uint32_t reg_ana_hs_trail_byte   : 4; /* [23:20],        r/w,        0x0 */
            uint32_t reg_ana_hs_sync_ld_byte : 4; /* [27:24],        r/w,        0x0 */
            uint32_t reg_ana_hs_p2s_sel_byte : 4; /* [31:28],        r/w,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_8;

    /* 0xA4 : dphy_config_9 */
    union {
        struct {
            uint32_t reg_ana_hs_data_out_byte : 32; /* [31: 0],        r/w,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_9;

    /* 0xA8 : dphy_config_10 */
    union {
        struct {
            uint32_t reg_testbus_sel_lo         : 4; /* [ 3: 0],        r/w,        0x0 */
            uint32_t reg_testbus_sel_hi         : 4; /* [ 7: 4],        r/w,        0x0 */
            uint32_t reg_testbus_hi8bsel_8bmode : 1; /* [    8],        r/w,        0x0 */
            uint32_t reg_imp_pu_code            : 5; /* [13: 9],        r/w,        0x8 */
            uint32_t reg_imp_pd_code            : 5; /* [18:14],        r/w,        0x9 */
            uint32_t reg_dphy_vreg400mv_trim    : 3; /* [21:19],        r/w,        0x0 */
            uint32_t reg_dphy_bg_vref_en        : 1; /* [   22],        r/w,        0x0 */
            uint32_t reg_ana_bg_vref_en         : 1; /* [   23],        r/w,        0x0 */
            uint32_t reg_ana_vreg400mv_trim     : 3; /* [26:24],        r/w,        0x0 */
            uint32_t reg_ana_vref_en            : 1; /* [   27],        r/w,        0x0 */
            uint32_t reserved_28_31             : 4; /* [31:28],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_10;

    /* 0xAC : dphy_config_11 */
    union {
        struct {
            uint32_t reg_dsi_ana_0 : 16; /* [15: 0],        r/w,      0xc14 */
            uint32_t reg_dsi_ana_1 : 16; /* [31:16],        r/w,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_11;

    /* 0xB0 : dphy_config_12 */
    union {
        struct {
            uint32_t reg_dsi_ana_2  : 16; /* [15: 0],        r/w,        0x0 */
            uint32_t reserved_16_31 : 16; /* [31:16],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_12;

    /* 0xB4 : dphy_config_13 */
    union {
        struct {
            uint32_t reg_rd_dig_test_bus : 16; /* [15: 0],          r,        0x0 */
            uint32_t reserved_16_31      : 16; /* [31:16],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_13;

    /* 0xB8 : dphy_config_14 */
    union {
        struct {
            uint32_t reg_pt_free_rep_pat : 32; /* [31: 0],        r/w, 0x87654321 */
        } BF;
        uint32_t WORD;
    } dphy_config_14;

    /* 0xBC : dphy_config_15 */
    union {
        struct {
            uint32_t reg_dsi_dc_tp_out_en  : 1; /* [    0],        r/w,        0x0 */
            uint32_t reserved_1_3          : 3; /* [ 3: 1],       rsvd,        0x0 */
            uint32_t reg_dsi_pw_avdd1815   : 1; /* [    4],        r/w,        0x0 */
            uint32_t reserved_5_7          : 3; /* [ 7: 5],       rsvd,        0x0 */
            uint32_t reg_dphy_pu_ldo11     : 1; /* [    8],        r/w,        0x1 */
            uint32_t reserved_9_11         : 3; /* [11: 9],       rsvd,        0x0 */
            uint32_t reg_dphy_short_ldo11  : 1; /* [   12],        r/w,        0x0 */
            uint32_t reserved_13_15        : 3; /* [15:13],       rsvd,        0x0 */
            uint32_t reg_dphy_ldo11_rfb_sw : 3; /* [18:16],        r/w,        0x4 */
            uint32_t reserved_19           : 1; /* [   19],       rsvd,        0x0 */
            uint32_t reg_ten_dsi_ldo       : 1; /* [   20],        r/w,        0x0 */
            uint32_t reserved_21_23        : 3; /* [23:21],       rsvd,        0x0 */
            uint32_t reg_mipi_ldo_fast     : 1; /* [   24],        r/w,        0x0 */
            uint32_t reserved_25_27        : 3; /* [27:25],       rsvd,        0x0 */
            uint32_t reg_dsi_rst_n_pre     : 1; /* [   28],        r/w,        0x0 */
            uint32_t reg_csi_rst_n_pre     : 1; /* [   29],        r/w,        0x0 */
            uint32_t reserved_30_31        : 2; /* [31:30],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_15;

    /* 0xC0 : dphy_config_16 */
    union {
        struct {
            uint32_t reg_dsi_byte_clk_inv : 1;  /* [    0],        r/w,        0x0 */
            uint32_t reg_dsi_lprx_clk_inv : 1;  /* [    1],        r/w,        0x0 */
            uint32_t reserved_2_31        : 30; /* [31: 2],       rsvd,        0x0 */
        } BF;
        uint32_t WORD;
    } dphy_config_16;

    /* 0xc4  reserved */
    uint8_t RESERVED0xc4[56];

    /* 0xFC : dummy_reg */
    union {
        struct {
            uint32_t dummy_reg : 32; /* [31: 0],        r/w,        0x0 */
        } BF;
        uint32_t WORD;
    } dummy_reg;
};

typedef volatile struct dsi_reg dsi_reg_t;

#endif /* __DSI_REG_H__ */
