import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Nuvoton/M031/Source/system_M031Series.c
""")

# add for startup script
if rtconfig.PLATFORM in ['gcc']:
    src = src + ['Nuvoton/M031/Source/GCC/startup_M031Series.S']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src = src + ['Nuvoton/M031/Source/ARM/startup_M031Series.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src = src + ['Nuvoton/M031/Source/IAR/startup_M031Series.s']

path = [cwd + '/Nuvoton/M031/Include',]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
