subdir-ccflags-y +=	-I$(srctree)/ekernel/drivers/include \
			-I$(srctree)/ekernel/core/rt-thread/include \
			-I$(srctree)/ekernel/drivers/drv/source/disp2/soc
obj-y += disp_mem.o disp_layer_cfg.o

obj-y += disp_layer_alpha_test.o
obj-y += disp_layer_scal_test.o
obj-y += disp_layer_format_test.o
obj-y += disp_lbc_test.o
