Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split("""
dev_block.c
dev_mmcsd_core.c
dev_sd.c
dev_sdio.c
dev_mmc.c
""")

# The set of source files associated with this SConscript file.
path = [cwd + '/../include']

if GetDepend(['RT_USING_DM']):
    src += ['dev_sdio_dm.c']

    if GetDepend(['RT_USING_REGULATOR']):
        src += ['dev_regulator.c']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SDIO'], CPPPATH = path)

Return('group')
