from building import *

group = []
objs = []

if not GetDepend(['RT_USING_SDIO']):
    Return('group')

cwd = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd + '/../include']

src = ['dev_block.c', 'dev_mmcsd_core.c', 'dev_sd.c', 'dev_sdio.c', 'dev_mmc.c']

if GetDepend(['RT_USING_DM']):
    src += ['dev_sdio_dm.c']

    if GetDepend('RT_USING_SDHCI'):
        src += ['dev_sdhci.c', 'dev_sdhci_dm.c', 'dev_sdhci_host.c']

    if GetDepend(['RT_USING_REGULATOR']):
        src += ['dev_regulator.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
