from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

if GetDepend(['RT_MBOX_BCM2835']):
    src += ['mailbox-bcm2835.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
