Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

# add pin drivers.
if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']

# add usart drivers.
if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_usart.c']

# add spi drivers.
if GetDepend('RT_USING_SPI'):
    src += ['drv_spi.c']

# add spi flash drivers.
if GetDepend('RT_USING_SFUD'):
    src += ['drv_spi_flash.c', 'drv_spi.c']

# add wdt drivers.
if GetDepend('RT_USING_WDT'):
    src += ['drv_wdt.c']

# add rtc drivers.
if GetDepend('RT_USING_RTC'):
    src += ['drv_rtc.c']

# add timer drivers.
if GetDepend('RT_USING_HWTIMER'):
    src += ['drv_hwtimer.c']

# add adc drivers.
if GetDepend('RT_USING_ADC'):
    src += ['drv_adc.c']

path = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
