#Import('RTT_ROOT')
#Import('rtconfig')
from building import *

#cwd = os.path.join(str(Dir('#')),'drivers')
cwd = GetCurrentDir()
src = Glob('*.c')

# remove no need file.
if GetDepend('RT_USING_LWIP') == False:
    SrcRemove(src, 'drv_emac.c')

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
