Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = Glob('*.c')

if GetDepend(['PKG_USING_RTDUINO']) and not GetDepend(['RTDUINO_NO_SETUP_LOOP']):
    src += ['arduino_main.cpp']

cwd = GetCurrentDir()
CPPPATH = [cwd]
group = DefineGroup('applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
