# for module compiling
import os
Import('RTT_ROOT')
Import('env')
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

# STM32L052xx || STM32L053xx || STM32L062xx
# STM32L063xx || STM32L072xx || STM32L073xx
# STM32L082xx ||  STM32L083xx
# You can select chips from the list above
env.Append(CPPDEFINES = ['STM32L053xx'])

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
