from building import *

objs = []

cwd = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd + '/../../include']

src = []

if GetDepend(['RT_PCI_HOST_COMMON']):
    src += ['pci-host-common.c']

if GetDepend(['RT_PCI_HOST_GENERIC']):
    src += ['pci-host-generic.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
