Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')
path = [cwd]

#remove other no use files
#SrcRemove(src, 'i2c_iomaster.c')
#SrcRemove(src, 'delay.c')

if rtconfig.DEVICE_SERIES == 'SAMD20':
	path += [cwd + '/../asflib_config', cwd + '/../asflib_config/clock_samd20']
elif rtconfig.DEVICE_SERIES == 'SAMD21':
	path += [cwd + '/../asflib_config', cwd + '/../asflib_config/clock_samd21_r21_da_ha1']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
