# for module compiling
import os
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

for item in list:
    path = os.path.join(cwd, item)
    if item == 'libraries' or not os.path.isdir(path):
        continue

    sconscript_path = os.path.join(path, 'SConscript')
    if os.path.isfile(sconscript_path):
        objs.extend(SConscript(os.path.join(item, 'SConscript')))

Return('objs')
