import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
Cube_Config/USER/src/n32h7xx_cfg.c
''')

path =  [cwd]
path += [os.path.join(cwd, 'Cube_Config', 'USER', 'inc')]

CPPDEFINES = ['N32H76x', 'CORE_CM7', 'USING_TCM', '__ICACHE_PRESENT=1', '__DCACHE_PRESENT=1']

# --entry is an armlink flag; GCC uses ENTRY() in the linker script instead
if rtconfig.PLATFORM != 'gcc':
    group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES,
        LINKFLAGS = '--entry Reset_Handler')
else:
    group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

# if os.path.isfile(os.path.join(cwd, "ports", 'SConscript')):
#     group = group + SConscript(os.path.join("ports", 'SConscript'))

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
