Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd + '/fsp_cfg', cwd + '/fsp_cfg/bsp']

src = Glob('*.c')
group = DefineGroup('rafw_cfg', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
