Import('RTT_ROOT')
Import('rtconfig')
from building import *

if GetDepend('BOARD_USING_HYPERFLASH'):
    cwd = GetCurrentDir()
    src = Glob('*.c')
    CPPPATH = [cwd]

    if rtconfig.CROSS_TOOL == 'keil':
        LINKFLAGS  = '--keep=*(.boot_hdr.ivt)'
        LINKFLAGS += '--keep=*(.boot_hdr.boot_data)'
        LINKFLAGS += '--keep=*(.boot_hdr.dcd_data)'
        LINKFLAGS += '--keep=*(.boot_hdr.conf)'
    else:
        LINKFLAGS = '' 

    group = DefineGroup('xip', src, depend = [''], CPPPATH = CPPPATH, LINKFLAGS = LINKFLAGS) 
    Return('group') 

if GetDepend('BOARD_USING_QSPIFLASH'): 
    if rtconfig.CROSS_TOOL == 'iar':
        cwd = GetCurrentDir()     
        CPPPATH = [cwd]
        LINKFLAGS = ''
        src  = ['fsl_flexspi_nor_boot.c']
        src += ['imxrt1052_sdram_ini_dcd.c']
        src += ['imxrt1052_spiflash_config.c']
        group = DefineGroup('xip', src, depend = [''], CPPPATH = CPPPATH, LINKFLAGS = LINKFLAGS) 
    else:
	    group = []
	   
    Return('group') 
