Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

# Add soc depend pinmux driver
if GetDepend('SOC_SERIES_GD32F2'):
    src += ['_gd32f2xx_pinmux.c']

if GetDepend('SOC_SERIES_GD32F4'):
    src += ['_gd32f4xx_pinmux.c']

# add pin drivers.
if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']
    
if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_usart.c']

path =  [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
