from shutil import copy
from building import *

Import('rtconfig')

src   = []
cwd   = GetCurrentDir()
CPPPATH = [cwd]
group = []

if rtconfig.PLATFORM == 'gcc' and ('mips' in rtconfig.PREFIX): # identify mips gcc tool chain
    try:
        # There is no 'sys/select.h' in tthe mips gcc toolchain; it will be copied from 'nogcc/sys/select.h'
        copy("../../../common/nogcc/sys/select.h", "./sys/select.h")
    except:
        pass

    group = DefineGroup('libc', src, depend = [], CPPPATH = CPPPATH)

Return('group')
