scons.args: &scons
    scons_arg:
      - '--strict'

# ------ nano ------
nano:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_NANO=y
# ------ peripheral ------
peripheral.arduino:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_ARDUINO=y   
