from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

src = []

if GetDepend(['RT_CLOCK_TIMER_ROCKCHIP']):
    src += ['clock_timer-rockchip_timer.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
