import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = Split("""
main.c
lcd_init.c
""")

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
