import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
CMSIS/Device/ST/STM32L0xx/Source/Templates/system_stm32l0xx.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_comp.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_crc.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_crc_ex.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cryp.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cryp_ex.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rng.c
STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c
''')
 
if GetDepend(['RT_USING_SERIAL']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_usart.c']
    
if GetDepend(['RT_USING_I2C']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c']

if GetDepend(['RT_USING_SPI']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi_ex.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_qspi.c']

if GetDepend(['RT_USING_USB_HOST']) or GetDepend(['RT_USING_USB_DEVICE']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_hcd.c'] 
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd_ex.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_usb.c']

if GetDepend(['RT_USING_CAN']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_can.c']

if GetDepend(['RT_USING_HWTIMER']) or GetDepend(['RT_USING_PWM']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim_ex.c']

if GetDepend(['RT_USING_ADC']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc_ex.c']

if GetDepend(['RT_USING_RTC']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc_ex.c']

if GetDepend(['RT_USING_WDT']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_wwdg.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_sd.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_sd_ex.c']

if GetDepend(['RT_USING_AUDIO']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_sai.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_sai_ex.c']

if GetDepend(['RT_USING_MTD_NOR']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_nor.c']

if GetDepend(['RT_USING_MTD_NAND']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_nand.c']

if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c']
    src += ['STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c']

path = [cwd + '/STM32L0xx_HAL_Driver/Inc',
    cwd + '/CMSIS/Device/ST/STM32L0xx/Include',
    cwd + '/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('STM32_HAL', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
