obj-$(CONFIG_DRIVERS_SPINOR) += \
    hal_spinor.o \
    core.o \
    factory_gd.o \
    factory_mxic.o \
    factory_winbond.o \
    factory_esmt.o \
    factory_xtx.o \
    factory_fm.o \
    factory_xmc.o \
    factory_puya.o \
    factory_zetta.o 
obj-$(CONFIG_DRIVERS_SPINOR_CACHE) += cache.o
obj-$(CONFIG_DRIVERS_SPINOR_WRITE_LOCK) += wrlock.o
