from building import *
Import('rtconfig')

src   = []
cwd   = GetCurrentDir()

# add gt911 src files.
if GetDepend('BSP_USING_TOUCH'):
    src += Glob('src/gt911.c')

# add gt911 include path.
path  = [cwd + '/inc']

# add src and include to group.
group = DefineGroup('gt911', src, depend = ['BSP_USING_TOUCH'], CPPPATH = path)

Return('group')
