Import('RTT_ROOT')
Import('rtconfig')
from building import *
from gcc import *

cwd = GetCurrentDir()
src = []
group = []
CPPPATH = []

if rtconfig.PLATFORM in ['iccarm'] + GetGCCLikePLATFORM():
    if rtconfig.PLATFORM == 'iccarm' or GetOption('target') != 'mdk5':
        src = Glob('*.c')
        CPPPATH = [cwd, ]

group = DefineGroup('RA_gen', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
