from building import *

group = []

if not GetDepend(['RT_USING_PIN']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['dev_pin.c']

if GetDepend(['RT_USING_DM']):
    src += ['dev_pin_dm.c']

if GetDepend(['RT_USING_OFW']):
    src += ['dev_pin_ofw.c']

if GetDepend(['RT_PIN_PL061']):
    src += ['pin-pl061.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
