# for module compiling
import os
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
    main.c
""")

group = DefineGroup('Driver', src, depend = [''])

Return('group')
