Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'board')

# add the general drivers.
src = Split("""
board.c
clock_config.c
drv_uart.c
led.c
""")

# add Ethernet drivers.
if GetDepend('RT_USING_LWIP'):
    src += ['drv_emac.c', 'fsl_phy.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
