subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/uvc/Include/
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/core
obj-y += uvc.o
obj-y += uvc_driver.o
obj-y += uvc_v4l2.o
obj-y += uvc_video.o