import os
from building import *

Import('rtconfig')

cwd = GetCurrentDir()

src = Glob('src/*.c')
list = os.listdir(cwd + "/src")
if rtconfig.ARCH in list:
    if os.path.exists(cwd + "/src/" + rtconfig.ARCH + "/" + rtconfig.CPU):
        src += Glob("src/" + rtconfig.ARCH + "/" + rtconfig.CPU + "/*.c")
    else:
        src += Glob("src/" + rtconfig.ARCH + "/*.c")
CPPPATH = [cwd, cwd + "/inc"]
LOCAL_CCFLAGS = ''
if rtconfig.PLATFORM in ['gcc', 'armclang']:
    LOCAL_CCFLAGS += ' -std=gnu99'
elif rtconfig.PLATFORM in ['armcc']:
    LOCAL_CCFLAGS += ' --c99 --gnu'

group = DefineGroup('ktime', src, depend=['RT_USING_KTIME'], CPPPATH=CPPPATH, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
