import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
CMSIS/Device/ST/STM32WBxx/Source/Templates/system_stm32wbxx.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_comp.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cortex.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_crc.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_crc_ex.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cryp.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cryp_ex.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma_ex.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_exti.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr_ex.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc_ex.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rng.c
STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_gpio.c
''')
  
if GetDepend(['RT_USING_SERIAL']):
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart_ex.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_usart.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_usart_ex.c']
    
if GetDepend(['RT_USING_I2C']):
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_i2c_ex.c']

if GetDepend(['RT_USING_SPI']):
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_spi.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_spi_ex.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_qspi.c']

if GetDepend(['RT_USING_USB_HOST']) or GetDepend(['RT_USING_USB_DEVICE']):
#    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_hcd.c'] 
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pcd.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pcd_ex.c']
#    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_usb.c']

if GetDepend(['RT_USING_HWTIMER']) or GetDepend(['RT_USING_PWM']):
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_lptim.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim_ex.c']

if GetDepend(['RT_USING_ADC']):
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc_ex.c']

if GetDepend(['RT_USING_RTC']):
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc_ex.c']

if GetDepend(['RT_USING_WDT']):
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_iwdg.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_wwdg.c']

if GetDepend(['RT_USING_AUDIO']):
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_sai.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_sai_ex.c']

if GetDepend(['RT_USING_PM']):
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_lptim.c']

if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash.c']
    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash_ex.c']
#    src += ['STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash_ramfunc.c']
	
	
	

path = [cwd + '/STM32WBxx_HAL_Driver/Inc',
    cwd + '/CMSIS/Device/ST/STM32WBxx/Include',
    cwd + '/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('STM32_HAL', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
