from building import *
Import('rtconfig')

src   = []
cwd   = GetCurrentDir()

src += Glob('*.c')
path  = [cwd]

# add src and include to group.
group = DefineGroup('nu_pkgs_ili_tpc', src, depend = ['NU_PKG_USING_ILI_TPC'], CPPPATH = path)

Return('group')
