import sys

from building import *
from distutils.version import LooseVersion

sys.path = sys.path + [os.path.join(os.path.normpath(os.getcwd()), '../../../../tools')]
from iar import IARVersion

Import('rtconfig')

src   = Glob('*.c')
cwd   = GetCurrentDir()
group = []

CPPPATH = [cwd]
CPPDEFINES = ['RT_USING_DLIBC']

if rtconfig.PLATFORM == 'iar':

    if GetDepend('RT_USING_DFS'):
        CPPDEFINES = CPPDEFINES + ['_DLIB_FILE_DESCRIPTOR']

        if LooseVersion(IARVersion()) < LooseVersion("8.20.1"):
            CPPDEFINES = CPPDEFINES + ['_DLIB_THREAD_SUPPORT']

    group = DefineGroup('dlib', src, depend = ['RT_USING_LIBC'], 
        CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
