from building import *
Import('rtconfig')

src   = Glob('*.c')
group = []

if rtconfig.PLATFORM in ['iccarm']:
    CPPDEFINES = ['RT_USING_DLIBC', 'RT_USING_LIBC', '_DLIB_ADD_EXTRA_SYMBOLS=0']
    AddDepend(['RT_USING_DLIBC', 'RT_USING_LIBC'])

    if GetDepend('DFS_USING_POSIX'):
        from distutils.version import LooseVersion
        from iar import IARVersion

        CPPDEFINES = CPPDEFINES + ['_DLIB_FILE_DESCRIPTOR']
        iar_version = LooseVersion(IARVersion())
        if iar_version != LooseVersion("0.0") and iar_version < LooseVersion("8.20.1"):
            CPPDEFINES = CPPDEFINES + ['_DLIB_THREAD_SUPPORT']

    group = DefineGroup('Compiler', src, depend = [''], CPPDEFINES = CPPDEFINES)

Return('group')
