from building import *

group = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = []

if GetDepend(['RT_PWM_ROCKCHIP']):
    src += ['pwm-rockchip.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
