import rtconfig
Import('RTT_ROOT')
from building import *

src_bsp = ['application.c', 'startup.c', 'board.c']
src_drv = ['console.c']

if GetDepend('RT_USING_LED'):
	src_drv += ['led.c']

if GetDepend('RT_USING_SDIO'):
	src_drv += ['at91_mci.c']

if GetDepend('RT_USING_LWIP'):
	src_drv += ['macb.c']

if GetDepend('RT_USING_I2C') and GetDepend('RT_USING_I2C_BITOPS'):
	src_drv += ['at91_i2c_gpio.c']

src	= File(src_bsp + src_drv)
CPPPATH = [RTT_ROOT + '/bsp/at91sam9260']
group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
