import rtconfig
Import('RTT_ROOT')
from building import *

src_bsp = ['application.c', 'startup.c', 'board.c']
src_drv = ['console.c']

if GetDepend('RT_USING_LED'):
	src_drv += ['led.c']

#if GetDepend('RT_USING_DFS'):
	#src_drv += ['sdcard.c']

if GetDepend('RT_USING_LWIP'):
	src_drv += ['macb.c']


src	= File(src_bsp + src_drv)
CPPPATH = [RTT_ROOT + '/bsp/at91sam9260']
group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
