# RT-Thread building script for component

Import('RTT_ROOT')
from building import *

cwd     = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd, cwd+'/include/']
group = []

# USB driver constrain
group = DefineGroup('MTDDrv', src, depend = ['BSP_USING_FMINAND'], CPPPATH = CPPPATH)

Return('group')
