from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]

ft_src  = Split("""
focaltech_ts.c
""")

gt_src = Split("""
gt9xx.c
""")

src = ()
if GetDepend('RT_USING_FT6x06'):
	src = ft_src
if GetDepend('RT_USING_GT9XX'):
	src = gt_src
	
group = DefineGroup('drv_touch', src, depend = ['RT_USING_TOUCH'], CPPPATH = CPPPATH)

Return('group')
