Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd  = GetCurrentDir()

src = Glob('*.c')

path = [cwd, cwd + '/..']

group = DefineGroup('Drivers', src, depend = ['CONFIG_PLAT_V2'], CPPPATH = path)

Return('group')
