import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Glob('STM32F7xx_HAL_Driver/Src/*.c')
src += Split('''
CMSIS/Device/ST/STM32F7xx/Source/Templates/system_stm32f7xx.c
''')

path = [cwd + '/STM32F7xx_HAL_Driver/Inc',
    cwd + '/CMSIS/Device/ST/STM32F7xx/Include',
    cwd + '/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('STM32_HAL', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')

