Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'app')
src	= Glob('*.c')
path = [cwd,
	cwd + '/..',
	cwd + '/../board',
	cwd + '/../Drivers/CMSIS/Device/ST/STM32L0xx/Include',
	cwd + '/../Drivers/STM32L0xx_HAL_Driver/Inc',
	cwd + '/../Inc'
	]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
