import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
board_ms5611.c
''')

path =  [cwd]

CPPDEFINES = ['GD32F405', 'HXTAL_VALUE=8000000U']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
