scons.args: &scons
    scons_arg:
      - '--strict'

# ------ nano ------
nano:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_NANO=y
# ------ peripheral ------
peripheral.arduino:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_ARDUINO=y   

# ------ lvgl ------   
lvgl.v8.3.11:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_LVGL=y
    - CONFIG_BSP_USING_LVGL_DEMO=y
    - CONFIG_PKG_LVGL_USING_V080311=y
lvgl.v8.3latest:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_LVGL=y
    - CONFIG_BSP_USING_LVGL_DEMO=y
    - CONFIG_PKG_LVGL_USING_V8_3_LATEST=y
lvgl.v8.4latest:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_LVGL=y
    - CONFIG_BSP_USING_LVGL_DEMO=y
    - CONFIG_PKG_LVGL_USING_V8_4_LATEST=y
