# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if not GetDepend('BSP_USING_DW_SPI'):
    SrcRemove(src, ['drv_dw_spi.c'])

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
