Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
path = [cwd]

src += ['oneshot.c']

if GetDepend(['WM_USING_ONESHOT_DEMO']):
    src += ['oneshot_demo.c']

group = DefineGroup('oneshot', src, depend = ['WM_USING_ONESHOT'], CPPPATH = path)

Return('group')
