Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend(['RT_USING_SMP', 'UTEST_SMP_CALL_FUNC']):
    src += Glob('smp*.c')

group = DefineGroup('utestcases', src, depend = ['RT_USING_UTESTCASES'], CPPPATH = CPPPATH)

Return('group')
