import os
import subprocess
import sys
import rtconfig

if os.getenv('RTT_ROOT'):
    RTT_ROOT = os.getenv('RTT_ROOT')
else:
    RTT_ROOT = os.path.normpath(os.getcwd() + '/../../..')

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
from building import *
from env_package import find_package_path

TARGET = 'rtthread-pico.' + rtconfig.TARGET_EXT

DefaultEnvironment(tools=[])
env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CFLAGS = rtconfig.CFLAGS,
    CXX = rtconfig.CXX, CXXFLAGS = rtconfig.CXXFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)

Export('RTT_ROOT')
Export('rtconfig')


# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT)

ocwd = os.getcwd()
os.chdir(find_package_path(os.getcwd(), 'raspberrypi-pico-sdk-latest'))
print("Enter " + os.getcwd())
package_env = os.environ.copy()
package_env['RTT_EXEC_PATH'] = rtconfig.EXEC_PATH
package_command = [sys.executable, '-m', 'SCons']
if GetOption('clean'):
    package_command.append('-c')
try:
    package_result = subprocess.call(package_command, env=package_env)
finally:
    os.chdir(ocwd)
if package_result:
    Exit(package_result)

objs.extend(SConscript(os.path.join(os.getcwd(), 'board', 'ports', 'SConscript'), variant_dir='build/board/ports', duplicate=0))

objs.extend(SConscript(os.path.join(os.getcwd(), '..', 'libraries', 'Drivers', 'SConscript'), variant_dir='build/libraries/Drivers', duplicate=0))

# make a building
DoBuilding(TARGET, objs)
