Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd  = GetCurrentDir()
# The set of source files associated with this SConscript file.
src = Split("""
""")
CPPPATH = [cwd + '/StdPeriphDriver/inc', cwd + '/CMSIS/Include']

src += ['Startup/startup_ARMCM0.s']
src += Glob('StdPeriphDriver/*.c')

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
