Import('RTT_ROOT')
Import('rtconfig')
from building import *
from gcc import *

cwd = GetCurrentDir()
src = []
group = []
CPPPATH = []

if rtconfig.PLATFORM in ['iccarm']:
    print("\nThe current project does not support IAR build\n")
    Return('group')
elif rtconfig.PLATFORM in GetGCCLikePLATFORM():
    if GetOption('target') != 'mdk5':
        src = Glob('*.c')
        CPPPATH = [cwd+'/fsp_cfg', cwd + '/fsp_cfg/bsp']

group += DefineGroup('ra_cfg', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
