from building import *

cwd = GetCurrentDir()
src = ['arduino_pinout.c']
inc = [cwd]

group = DefineGroup('Arduino', src, depend = ['RT_USING_ARDUINO'], CPPPATH = inc)

src = ['arduino_main.cpp']
group += DefineGroup('Applications', src, depend = ['RT_USING_ARDUINO'])

Return('group')
