/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* UART0_rx */
#define UART0_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART0_rx_0_INBUF_ENABLED 1u
#define UART0_rx_0_INIT_DRIVESTATE 1u
#define UART0_rx_0_INIT_MUXSEL 18u
#define UART0_rx_0_INPUT_SYNC 2u
#define UART0_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART0_rx_0_NUM 0u
#define UART0_rx_0_PORT GPIO_PRT5
#define UART0_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART0_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART0_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART0_rx_INBUF_ENABLED 1u
#define UART0_rx_INIT_DRIVESTATE 1u
#define UART0_rx_INIT_MUXSEL 18u
#define UART0_rx_INPUT_SYNC 2u
#define UART0_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART0_rx_NUM 0u
#define UART0_rx_PORT GPIO_PRT5
#define UART0_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART0_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART0_tx */
#define UART0_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART0_tx_0_INBUF_ENABLED 0u
#define UART0_tx_0_INIT_DRIVESTATE 1u
#define UART0_tx_0_INIT_MUXSEL 18u
#define UART0_tx_0_INPUT_SYNC 2u
#define UART0_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART0_tx_0_NUM 1u
#define UART0_tx_0_PORT GPIO_PRT5
#define UART0_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART0_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART0_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART0_tx_INBUF_ENABLED 0u
#define UART0_tx_INIT_DRIVESTATE 1u
#define UART0_tx_INIT_MUXSEL 18u
#define UART0_tx_INPUT_SYNC 2u
#define UART0_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART0_tx_NUM 1u
#define UART0_tx_PORT GPIO_PRT5
#define UART0_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART0_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
