# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Libc', src, depend = ['RT_USING_POSIX_DELAY'], CPPPATH = CPPPATH)

Return('group')
