scons.args: &scons
    scons_arg:
      - '--strict'

# ------ nano ------
nano:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_NANO=y

devices.soft_i2c:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_I2C=y
    - CONFIG_RT_USING_SOFT_I2C=y
    - CONFIG_RT_USING_SOFT_I2C2=y
    - CONFIG_RT_SOFT_I2C2_SCL_PIN=26
    - CONFIG_RT_SOFT_I2C2_SDA_PIN=27
    - CONFIG_RT_SOFT_I2C2_BUS_NAME="swi2c2"
