from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include', cwd + '/../../../../components/drivers/serial/device/8250']

if GetDepend(['RT_SERIAL_8250_BCM2835AUX']):
    src += ['8250-bcm2835aux.c']

if GetDepend(['RT_SERIAL_8250_BCM7271']):
    src += ['8250-bcm7271.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
