import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
CMSIS/device/system_n32wb452.c
n32wb452_std_periph_driver/src/n32wb452_gpio.c
n32wb452_std_periph_driver/src/n32wb452_rcc.c
n32wb452_std_periph_driver/src/n32wb452_exti.c
n32wb452_std_periph_driver/src/misc.c
''')

if GetDepend(['RT_USING_SERIAL']):
    src += ['n32wb452_std_periph_driver/src/n32wb452_usart.c']

if GetDepend(['RT_USING_I2C']):
    src += ['n32wb452_std_periph_driver/src/n32wb452_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['n32wb452_std_periph_driver/src/n32wb452_spi.c']

if GetDepend(['RT_USING_CAN']):
    src += ['n32wb452_std_periph_driver/src/n32wb452_can.c']

if GetDepend(['RT_USING_ADC']):
    src += ['n32wb452_std_periph_driver/src/n32wb452_adc.c']

if GetDepend(['RT_USING_DAC']):
    src += ['n32wb452_std_periph_driver/src/n32wb452_dac.c']

if GetDepend(['RT_USING_HWTIMER']):
    src += ['n32wb452_std_periph_driver/src/n32wb452_tim.c']

if GetDepend(['RT_USING_RTC']):
    src += ['n32wb452_std_periph_driver/src/n32wb452_rtc.c']
    src += ['n32wb452_std_periph_driver/src/n32wb452_pwr.c']
    src += ['n32wb452_std_periph_driver/src/n32wb452_bkp.c']

if GetDepend(['RT_USING_WDT']):
    src += ['n32wb452_std_periph_driver/src/n32wb452_wwdg.c']
    src += ['n32wb452_std_periph_driver/src/n32wb452_iwdg.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['n32wb452_std_periph_driver/src/n32wb452_sdio.c']

if GetDepend(['RT_USING_BSP_USB']):
    path += [cwd + '/n32wb452_usbfs_driver/inc']
    src  += [cwd + '/n32wb452_usbfs_driver/src']

path = [
    cwd + '/CMSIS/device',
    cwd + '/CMSIS/core',
    cwd + '/n32wb452_std_periph_driver/inc',]

CPPDEFINES = ['USE_STDPERIPH_DRIVER']



group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
