from building import *

cwd = GetCurrentDir()

src = []

if GetDepend('BSP_USING_PIN'):
    src += ['drv_pin.c']

if  GetDepend('BSP_USING_UART'):
    src += ['drv_uart.c']

if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']

if  GetDepend('BSP_USING_SPI'):
    src += ['drv_spi.c']

if  GetDepend('BSP_USING_SDIO'):
    src += ['drv_sdif.c']

if  GetDepend('BSP_USING_I2C'):
    src += ['drv_i2c.c']

if  GetDepend('BSP_USING_MMA8562I2C'):
    src += ['drv_mma8562.c']

if  GetDepend('BSP_USING_ADC'):
    src += ['drv_adc.c']

if  GetDepend('BSP_USING_HWTIMER'):
    src += ['drv_hwtimer.c']

if  GetDepend('BSP_USING_WDT'):
    src += ['drv_wdt.c']

if  GetDepend('BSP_USING_PWM'):
    src += ['drv_pwm.c']

if  GetDepend('BSP_USING_I2S'):
    src += ['drv_i2s.c']

if  GetDepend('BSP_USING_WM8904'):
    src += ['drv_sound_wm8904.c']

if  GetDepend('BSP_USING_SOFT_I2C'):
    src += ['drv_soft_i2c.c']

if GetDepend('BSP_USING_SOFT_SPI'):
    src += ['drv_soft_spi.c']

if GetDepend('BSP_USING_LCD'):
    src += ['drv_st7796.c']
    src += ['sample/lcd_sample.c']

if GetDepend('BSP_USING_TOUCH'):
    src += ['drv_gt911.c']
    src += ['sample/touch_sample.c']

if GetDepend('BSP_USING_NXP_LCDM_S'):
    src += ['sample/lcd_touch_sample.c']

path =  [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
