from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = [cwd + '/../include']

if GetDepend(['RT_USING_ADC_V2']):
    src += ['adc_v2.c']

if GetDepend(['RT_USING_ADC_V2', 'RT_USING_FINSH', 'RT_ADC_V2_USING_MSH']):
    src += ['adc_v2_msh.c']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_ADC_V2'], CPPPATH = CPPPATH)

Return('group')
