from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['RT_USING_ADC']) and not GetDepend(['RT_USING_ADC_V2']):
    src += ['adc.c']

if GetDepend(['RT_USING_ADC_V2']):
    src += ['adc_v2.c']

if GetDepend(['RT_USING_ADC_V2', 'RT_ADC_USING_TRIGGER']):
    src += ['adc_v2_trigger.c']

if GetDepend(['RT_USING_ADC_V2', 'RT_USING_FINSH', 'RT_ADC_V2_USING_MSH']):
    src += ['adc_v2_msh.c']

if len(src):
    group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_ADC'], CPPPATH = CPPPATH)

Return('group')
