# RT-Thread building script for bridge

import os
from building import *

Import('rtconfig')

cwd   = GetCurrentDir()
group = []
list  = os.listdir(cwd)

# add common code files
if   rtconfig.CPU == "e906fd" :
    group = group
elif rtconfig.CPU == "e906f"  :
    group = group
elif rtconfig.CPU == "e906"   :
    group = group
elif rtconfig.CPU == "nuclei" :
    group = group
else :
    group = group + SConscript(os.path.join(cwd, 'common', 'SConscript'))

# cpu porting code files
group = group + SConscript(os.path.join(cwd, rtconfig.CPUCLASS, 'SConscript'))

Return('group')
