# RT-Thread building script for bridge

import os
from building import *

cwd = GetCurrentDir()
objs = []
folder_list = os.listdir(cwd)

for folder in folder_list:
    path = os.path.join(cwd, folder)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(folder, 'SConscript'))

Return('objs')
