
from building import *
import rtconfig

cwd     = GetCurrentDir()

src = []

src     += Glob('*.c')
if not GetDepend('BSP_USING_NORFLASH'):
    SrcRemove(src, ['fal_norflash_sfud_port.c'])

CPPPATH = [cwd]
LOCAL_CCFLAGS = ''

if rtconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=c99'
elif rtconfig.CROSS_TOOL == 'keil':
    LOCAL_CCFLAGS += ' --c99'

group = DefineGroup('fal', src, depend = ['RT_USING_FAL'], CPPPATH = CPPPATH, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
