# files format check exclude path, please follow the instructions below to modify;
# If you need to exclude an entire folder, add the folder path in dir_path;
# If you need to exclude a file, add the path to the file in file_path.

dir_path:
- APM32F0xx_Library
- APM32F10x_Library
- APM32F4xx_Library