scons.args: &scons
    scons_arg:
      - '--strict'
# ------ nano ------
nano:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_NANO=y
# ------ peripheral ------
peripheral.adruino:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_ARDUINO=y    
peripheral.usb2usart:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_GPIO=y
    - CONFIG_BSP_USING_UART=y
    - CONFIG_USING_SERIAL=y
