scons.args: &scons
    scons_arg:
      - '--strict'
# ------ nano ------
nano:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_NANO=y
# ------ peripheral ------
peripheral.arduino:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_ARDUINO=y   
peripheral.usbd:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_USBD=y   
# ------ devices ------ 
devices.uart1:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_GPIO=y
    - CONFIG_BSP_USING_UART=y
    - CONFIG_USING_SERIAL=y
devices.i2c1:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_I2C1=y
devices.pwm2:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_PWM=y
    - CONFIG_BSP_USING_PWM2=y
    - CONFIG_BSP_USING_PWM2_CH1=y
devices.spi2:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_SPI=y
    - CONFIG_BSP_USING_SPI2=y
devices.adc:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_ADC=y
    - CONFIG_BSP_USING_ADC1=y