from building import *

cwd = GetCurrentDir()
src = ['main.c']

if GetDepend('BSP_USING_SDRAM_HEAP_TEST'):
    src += ['sdram_heap_test.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = [cwd])

Return('group')
