from building import *

cwd = GetCurrentDir()
src = ['main.c']

if GetDepend('BSP_USING_SDRAM_HEAP_TEST'):
    src += ['sdram_heap_test.c']

if GetDepend('BSP_USING_FILESYSTEM_TEST'):
    src += ['filesystem_test.c']

if GetDepend('BSP_USING_PWM_DUAL_TEST'):
    src += ['pwm_dual_test.c']

if GetDepend('BSP_USING_RTC_ALARM_EXAMPLE'):
    src += ['rtc_alarm_example.c']

if GetDepend('BSP_USING_OV7670_PREVIEW'):
    src += ['ov7670_preview.c']

if GetDepend(['BSP_USING_GD32VW553_MQTT_DEMO', 'PKG_USING_KAWAII_MQTT']):
    src += ['gd32vw553_mqtt_demo.c']

if GetDepend(['BSP_USING_LVGL_BOARD_DEMO', 'PKG_USING_LVGL']):
    src += ['board_demo.c', 'board_demo_backend.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = [cwd])

Return('group')
