from building import *

group = []

if not GetDepend(['RT_USING_THERMAL']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['thermal.c', 'thermal_dm.c']

if GetDepend(['RT_THERMAL_COOL_PWM_FAN']):
    src += ['thermal-cool-pwm-fan.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
