from building import *

group = []

if not GetDepend(['RT_FIRMWARE_PSCI']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src = Glob('*.c')

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
