from building import *

cwd = GetCurrentDir()

src = []

if GetDepend('BSP_USING_GPIO'):
    src += ['drv_gpio.c']

if  GetDepend('BSP_USING_LPUART'):
    src += ['drv_uart.c']

if  GetDepend('BSP_USING_HWTIMER'):
    src += ['drv_hwtimer.c']

if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']

if  GetDepend('BSP_USING_SPI'):
    src += ['drv_spi.c']

if  GetDepend('BSP_USING_I2C'):
    src += ['drv_i2c.c']

if GetDepend('BSP_USING_WDT'):
    src += ['drv_wdt.c']

if GetDepend('BSP_USING_PWM'):
    src += ['drv_pwm.c']

if GetDepend('BSP_USING_ADC'):
    src += ['drv_adc.c']

if GetDepend('BSP_USING_CAN'):
    src += ['drv_can.c']
    
if GetDepend('BSP_USING_SDRAM'):
    src += ['drv_sdram.c']

if GetDepend('BSP_USING_LCD'):
    src += ['drv_lcd.c']

if GetDepend('BSP_USING_ETH'):
    src += ['drv_eth.c']

path =  [cwd,cwd + '/config']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
