from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

src = []

if GetDepend(['RT_HWTIMER_ROCKCHIP']):
    src += ['hwtimer-rockchip_timer.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
