# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

if not GetDepend('HAVE_SYS_SELECT_H'):
    CPPPATH += [cwd + '/select']

if not GetDepend('HAVE_SYS_SOCKET_H'):
    CPPPATH += [cwd + '/socket']

group = DefineGroup('Filesystem', src, depend = ['RT_USING_DFS', 'RT_USING_DFS_NET'], CPPPATH = CPPPATH)

Return('group')
