scons.args: &scons
    scons_arg:
      - '--strict'
devices.i2c:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_I2C=y
      - CONFIG_BSP_USING_I2C=y
      - CONFIG_BSP_USING_I2C0=y
devices.adc:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_ADC=y
      - CONFIG_BSP_USING_ADC=y
devices.hwtimer:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_HWTIMER=y
      - CONFIG_BSP_USING_TIMERS=y
      - CONFIG_BSP_USING_TIMER0=y
devices.pdma:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_PDMA=y
      - CONFIG_BSP_USING_PDMA=y
      - CONFIG_BSP_USING_PDMA_CHANNEL0=y
devices.pwm:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_PWM=y
      - CONFIG_BSP_USING_PWM=y
      - CONFIG_BSP_USING_PWM0=y
devices.rtc:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_RTC=y
      - CONFIG_BSP_USING_RTC=y
devices.ts:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_TS=y
      - CONFIG_BSP_USING_TS=y
devices.wdt:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_WDT=y
      - CONFIG_BSP_USING_WDT=y
      - CONFIG_BSP_USING_WDT0=y
