import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = Split("""
Device/System_ACM32F4.c
HAL_Driver/Src/HAL_EFlash.c
HAL_Driver/Src/HAL_DMA.c
HAL_Driver/Src/HAL_GPIO.c
HAL_Driver/Src/HAL_UART.c
HAL_Driver/Src/HAL_EXTI.c
""")


libpath = ['.', cwd + '/Device', cwd + '/HAL_Driver/Src']
libs = ['System_Accelerate', 'HAL_EFlash_EX']

if rtconfig.PLATFORM in ['gcc']:
    src += ['Device/startup_ACM32F4_gcc.s']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['Device/Startup_ACM32F4.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['Device/Startup_ACM32F4_iar.s']

path = [cwd + '/HAL_Driver/Inc',
    cwd + '/Device',
    cwd + '/CMSIS']

group = DefineGroup('ACM32_HAL', src, depend = [''], CPPPATH = path, LIBS = libs, LIBPATH = libpath)

Return('group')

