subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/hid/Include/
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/core

obj-y += Hid.o
obj-y += HidProtocol.o
obj-y += HidTransport.o
