from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

src = []

if GetDepend(['RT_CLK_ROCKCHIP_RK3568']):
    src += ['clk-rk3568.c']

if GetDepend(['RT_CLK_ROCKCHIP_RK3588']):
    src += ['clk-rk3588.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
