Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split("""
core/core.c
core/usbdevice.c
""")

if GetDepend('RT_USB_DEVICE_CDC'):
	src += Glob('class/cdc_vcom.c')

if GetDepend('RT_USB_DEVICE_MSTORAGE'):
	src += Glob('class/mstorage.c')

if GetDepend('RT_USB_DEVICE_RNDIS'):
	src += Glob('class/rndis.c')

CPPPATH = [cwd]

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_USB_DEVICE'], CPPPATH = CPPPATH)

Return('group')
