Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split("""
core/rt_core.c
core/rt_usbdevice.c
""")

if GetDepend('RT_USB_DEVICE_CDC'):
	src += Glob('class/rt_cdc_vcom.c')
	
if GetDepend('RT_USB_DEVICE_HID'):
    src += Glob('class/rt_hid.c')

if GetDepend('RT_USB_DEVICE_MSTORAGE'):
	src += Glob('class/rt_mstorage.c')

if GetDepend('RT_USB_DEVICE_ECM'):
	src += Glob('class/rt_ecm.c')

if GetDepend('RT_USB_DEVICE_RNDIS'):
	src += Glob('class/rt_rndis.c')

if GetDepend('RT_USB_DEVICE_WINUSB'):
	src += Glob('class/rt_winusb.c')

CPPPATH = [cwd]

group = DefineGroup('rt_usbd', src, depend = ['RT_USING_USB_DEVICE'], CPPPATH = CPPPATH)

Return('group')
