from building import *

group = []

if not GetDepend(['RT_USING_RPMSG']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['rpmsg.c', 'rpmsg_char.c', 'rpmsg_ns.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
