import glob
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
group = []
CPPPATH = []

file = glob.glob('*.tifcfg')
if len(file):
    if rtconfig.PLATFORM == 'iar':
        print("\nThe current project does not support iar build\n")
        Return('group')
    elif rtconfig.PLATFORM == 'gcc':
        src += ['qe_touch_config.c']
        src += ['qe_sample_rtthread.c']
        CPPPATH = [cwd, ]
    elif rtconfig.PLATFORM == 'armclang':
        src += ['qe_touch_config.c']
        src += ['qe_sample_rtthread.c']
        CPPPATH = [cwd, ]

    CPPDEFINES = ['QE_TOUCH_CONFIGURATION']
    group = DefineGroup('QE-Touch', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
