from building import *

group = []

if not GetDepend(['RT_USING_NVME']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['nvme.c']

if GetDepend(['RT_NVME_PCI']):
    src += ['nvme-pci.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
