# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Split('''
ftcbasic.c
ftccache.c
ftccmap.c
ftcglyph.c
ftcimage.c
ftcmanag.c
ftcmru.c
ftcsbits.c
''')
CPPPATH = [cwd]

group = DefineGroup('freetype', src, depend = ['RTGUI_USING_TTF'], CPPPATH = CPPPATH)

Return('group')
