# RT-Thread building script for FreeType

from building import *

cwd = GetCurrentDir()
src = Split('''
ftcbasic.c
ftccache.c
ftccmap.c
ftcglyph.c
ftcimage.c
ftcmanag.c
ftcmru.c
ftcsbits.c
''')
CPPPATH = [cwd]

group = DefineGroup('FreeType', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
