import rtconfig

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')

path =  [cwd]
path += [cwd + '/src']

src += Glob('src/lv_demo_music/*.c')
src += Glob('src/lv_demo_music/assets/*.c')

path += [cwd + '/src/lv_demo_music']
path += [cwd + '/src/lv_demo_music/assets']

group = DefineGroup('LVGL-demo', src, depend = ['BSP_USING_LVGL'], CPPPATH = path)

Return('group')
