Import('RTT_ROOT')
Import('rtconfig')
from building import *
import copy

cwd     = os.path.join(str(Dir('#')), 'drivers')
src = Glob('*.c')
CPPPATH = [cwd]

# remove no need file.
if GetDepend('RT_USING_LWIP') == False:
    src_need_remove = ['luminaryif.c'] # need remove file list.
    SrcRemove(src, src_need_remove)

if GetDepend('RT_USING_DFS') == False:
    src_need_remove = ['sdcard.c'] # need remove file list.
    SrcRemove(src, src_need_remove)

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
