Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
group = []
CPPPATH = []

if rtconfig.PLATFORM in ['iccarm']:
    print("\nThe current project does not support IAR build\n")
    Return('group')
elif rtconfig.PLATFORM in ['gcc', 'armclang']:
    src += Glob(cwd + '/TARGET_APP_KIT_XMC71_EVK_LITE_V2/*.c')
    src += Glob(cwd + '/TARGET_APP_KIT_XMC71_EVK_LITE_V2/config/GeneratedSource/*.c')

    CPPPATH = [ cwd + '/TARGET_APP_KIT_XMC71_EVK_LITE_V2',
                cwd + '/TARGET_APP_KIT_XMC71_EVK_LITE_V2/config/GeneratedSource']
    if rtconfig.PLATFORM in ['gcc']:
        src += [cwd + '/TARGET_APP_KIT_XMC71_EVK_LITE_V2/COMPONENT_CM7/system_cm7.c']
        src += [cwd + '/TARGET_APP_KIT_XMC71_EVK_LITE_V2/COMPONENT_CM7/startup_cm7.c']
    elif rtconfig.PLATFORM in ['armclang']:
        src += [cwd + '/TARGET_APP_KIT_XMC71_EVK_LITE_V2/COMPONENT_CM7/system_cm7.c']
        src += [cwd + '/TARGET_APP_KIT_XMC71_EVK_LITE_V2/COMPONENT_CM7/startup_cm7.c']

group = DefineGroup('libs', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
