# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = ['board.c', 'drv_uart.c', 'drv_ramdisk.c']
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
