Import('rtconfig')
from building import *

if GetDepend('RT_USING_NEWLIB') and rtconfig.CROSS_TOOL != 'gcc':
    print '================ERROR============================'
    print 'Please use GNU GCC compiler if using newlib'
    print '================================================='
    exit(0)

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

# link with libc and libm:
# libm is a frequently used lib. Newlib is compiled with -ffunction-sections in
# recent GCC tool chains. The linker would just link in the functions that have
# been referenced. So setting this won't result in bigger text size.
LIBS = ['c', 'm']

group = DefineGroup('newlib', src, depend = ['RT_USING_NEWLIB'],
                    CPPPATH = CPPPATH, LIBS = LIBS)

Return('group')
