/**
  ******************************************************************************
  * @file    bl616_romdriver_e907.c
  * @version V1.0
  * @date
  * @brief   This file is the standard driver c file
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; COPYRIGHT(c) 2021 Bouffalo Lab</center></h2>
  *
  * Redistribution and use in source and binary forms, with or without modification,
  * are permitted provided that the following conditions are met:
  *   1. Redistributions of source code must retain the above copyright notice,
  *      this list of conditions and the following disclaimer.
  *   2. Redistributions in binary form must reproduce the above copyright notice,
  *      this list of conditions and the following disclaimer in the documentation
  *      and/or other materials provided with the distribution.
  *   3. Neither the name of Bouffalo Lab nor the names of its contributors
  *      may be used to endorse or promote products derived from this software
  *      without specific prior written permission.
  *
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  *
  ******************************************************************************
  */
  
#include "bl616_romdriver_e907.h"
#include <string.h>

/** @addtogroup  BL616_Periph_Driver
 *  @{
 */

/** @defgroup ROMDRIVER
 *  @brief ROMDRIVER common functions
 *  @{
 */

/** @defgroup ROMDRIVER_Private_Type
 *  @{
 */

/*@} end of group ROMDRIVER_Private_Type*/

/** @defgroup ROMDRIVER_Private_Defines
 *  @{
 */

/*@} end of group ROMDRIVER_Private_Defines */

/** @defgroup ROMDRIVER_Private_Variables
 *  @{
 */                               

/*@} end of group ROMDRIVER_Private_Variables */

/** @defgroup ROMDRIVER_Global_Variables
 *  @{
 */ 
 

uint32_t const romDriverTable[]={
    0x06160001,
    0x00000000,
    0x00000000,
    0x00000000,


    [ROM_API_INDEX_AON_Power_Off_BG]                       = (uint32_t)AON_Power_Off_BG,
    [ROM_API_INDEX_AON_Power_Off_LDO15_RF]                 = (uint32_t)AON_Power_Off_LDO15_RF,
    [ROM_API_INDEX_AON_Power_Off_MBG]                      = (uint32_t)AON_Power_Off_MBG,
    [ROM_API_INDEX_AON_Power_Off_SFReg]                    = (uint32_t)AON_Power_Off_SFReg,
    [ROM_API_INDEX_AON_Power_Off_XTAL]                     = (uint32_t)AON_Power_Off_XTAL,
    [ROM_API_INDEX_AON_Power_On_BG]                        = (uint32_t)AON_Power_On_BG,
    [ROM_API_INDEX_AON_Power_On_LDO15_RF]                  = (uint32_t)AON_Power_On_LDO15_RF,
    [ROM_API_INDEX_AON_Power_On_MBG]                       = (uint32_t)AON_Power_On_MBG,
    [ROM_API_INDEX_AON_Power_On_SFReg]                     = (uint32_t)AON_Power_On_SFReg,
    [ROM_API_INDEX_AON_Power_On_XTAL]                      = (uint32_t)AON_Power_On_XTAL,
    [ROM_API_INDEX_AON_Set_Xtal_CapCode]                   = (uint32_t)AON_Set_Xtal_CapCode,
    [ROM_API_INDEX_AON_Trim_DcdcDis]                       = (uint32_t)AON_Trim_DcdcDis,
    [ROM_API_INDEX_AON_Trim_DcdcVoutSel]                   = (uint32_t)AON_Trim_DcdcVoutSel,
    [ROM_API_INDEX_AON_Trim_DcdcVoutTrim]                  = (uint32_t)AON_Trim_DcdcVoutTrim,
    [ROM_API_INDEX_AON_Trim_Ldo11socVoutTrim]              = (uint32_t)AON_Trim_Ldo11socVoutTrim,
    [ROM_API_INDEX_AON_Trim_Usb20RcalCode]                 = (uint32_t)AON_Trim_Usb20RcalCode,
    [ROM_API_INDEX_AON_Get_Xtal_CapCode]                   = (uint32_t)AON_Get_Xtal_CapCode,

    [ROM_API_INDEX_CPU_MTimer_Delay_MS]                    = (uint32_t)CPU_MTimer_Delay_MS,
    [ROM_API_INDEX_CPU_MTimer_Delay_US]                    = (uint32_t)CPU_MTimer_Delay_US,
    [ROM_API_INDEX_CPU_Reset_MTimer]                       = (uint32_t)CPU_Reset_MTimer,
    [ROM_API_INDEX_CPU_Set_MTimer_CLK]                     = (uint32_t)CPU_Set_MTimer_CLK,
    [ROM_API_INDEX_CPU_Set_MTimer_RST]                     = (uint32_t)CPU_Set_MTimer_RST,
    [ROM_API_INDEX_CPU_Get_MTimer_Clock]                   = (uint32_t)CPU_Get_MTimer_Clock,
    [ROM_API_INDEX_CPU_Get_MTimer_Source_Clock]            = (uint32_t)CPU_Get_MTimer_Source_Clock,

    [ROM_API_INDEX_Clock_Audio_ADC_Clock_Get]              = (uint32_t)Clock_Audio_ADC_Clock_Get,
    [ROM_API_INDEX_Clock_Get_ISP_Clk]                      = (uint32_t)Clock_Get_ISP_Clk,
    [ROM_API_INDEX_Clock_Get_PSRAMB_Clk]                   = (uint32_t)Clock_Get_PSRAMB_Clk,
    [ROM_API_INDEX_Clock_Peripheral_Clock_Get]             = (uint32_t)Clock_Peripheral_Clock_Get,
    [ROM_API_INDEX_Clock_System_Clock_Get]                 = (uint32_t)Clock_System_Clock_Get,

    [ROM_API_INDEX_SystemCoreClockGet]                     = (uint32_t)SystemCoreClockGet,

    [ROM_API_INDEX_CPU_Get_CPU_Cycle]                      = (uint32_t)CPU_Get_CPU_Cycle,
    [ROM_API_INDEX_CPU_Get_MTimer_Counter]                 = (uint32_t)CPU_Get_MTimer_Counter,
    [ROM_API_INDEX_CPU_Get_MTimer_MS]                      = (uint32_t)CPU_Get_MTimer_MS,
    [ROM_API_INDEX_CPU_Get_MTimer_US]                      = (uint32_t)CPU_Get_MTimer_US,

    [ROM_API_INDEX_EF_Ctrl_Crc_Result]                     = (uint32_t)EF_Ctrl_Crc_Result,
    [ROM_API_INDEX_EF_Ctrl_Get_Customer_PIDVID]            = (uint32_t)EF_Ctrl_Get_Customer_PIDVID,
    [ROM_API_INDEX_EF_Ctrl_Read_Chip_ID]                   = (uint32_t)EF_Ctrl_Read_Chip_ID,
    [ROM_API_INDEX_EF_Ctrl_Read_MAC_Address]               = (uint32_t)EF_Ctrl_Read_MAC_Address,
    [ROM_API_INDEX_EF_Ctrl_Read_MAC_Address_Raw]           = (uint32_t)EF_Ctrl_Read_MAC_Address_Raw,
    [ROM_API_INDEX_EF_Ctrl_AutoLoad_Done]                  = (uint32_t)EF_Ctrl_AutoLoad_Done,
    [ROM_API_INDEX_EF_Ctrl_Busy]                           = (uint32_t)EF_Ctrl_Busy,
    [ROM_API_INDEX_EF_Ctrl_Crc_Is_Busy]                    = (uint32_t)EF_Ctrl_Crc_Is_Busy,
    [ROM_API_INDEX_EF_Ctrl_Get_Trim_Parity]                = (uint32_t)EF_Ctrl_Get_Trim_Parity,
    [ROM_API_INDEX_EF_Ctrl_Is_All_Bits_Zero]               = (uint32_t)EF_Ctrl_Is_All_Bits_Zero,
    [ROM_API_INDEX_EF_Ctrl_Read_FlashDlyCoe]               = (uint32_t)EF_Ctrl_Read_FlashDlyCoe,
    [ROM_API_INDEX_EF_Ctrl_Clear]                          = (uint32_t)EF_Ctrl_Clear,
    [ROM_API_INDEX_EF_Ctrl_Crc_Enable]                     = (uint32_t)EF_Ctrl_Crc_Enable,
    [ROM_API_INDEX_EF_Ctrl_Crc_Set_Golden]                 = (uint32_t)EF_Ctrl_Crc_Set_Golden,
    [ROM_API_INDEX_EF_Ctrl_Load_Efuse_R0]                  = (uint32_t)EF_Ctrl_Load_Efuse_R0,
    [ROM_API_INDEX_EF_Ctrl_Program_Direct_R0]              = (uint32_t)EF_Ctrl_Program_Direct_R0,
    [ROM_API_INDEX_EF_Ctrl_Program_Efuse_0]                = (uint32_t)EF_Ctrl_Program_Efuse_0,
    [ROM_API_INDEX_EF_Ctrl_Read_ADC_Gain_Trim]             = (uint32_t)EF_Ctrl_Read_ADC_Gain_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_AES_Key]                   = (uint32_t)EF_Ctrl_Read_AES_Key,
    [ROM_API_INDEX_EF_Ctrl_Read_Dbg_Pwd]                   = (uint32_t)EF_Ctrl_Read_Dbg_Pwd,
    [ROM_API_INDEX_EF_Ctrl_Read_DcdcDis_Trim]              = (uint32_t)EF_Ctrl_Read_DcdcDis_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_DcdcVoutSel_Trim]          = (uint32_t)EF_Ctrl_Read_DcdcVoutSel_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_DcdcVoutTrim_Trim]         = (uint32_t)EF_Ctrl_Read_DcdcVoutTrim_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_Device_Info]               = (uint32_t)EF_Ctrl_Read_Device_Info,
    [ROM_API_INDEX_EF_Ctrl_Read_Direct_R0]                 = (uint32_t)EF_Ctrl_Read_Direct_R0,
    [ROM_API_INDEX_EF_Ctrl_Read_Ldo11socVoutTrim_Trim]     = (uint32_t)EF_Ctrl_Read_Ldo11socVoutTrim_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_Ldo18ioBypass_Trim]        = (uint32_t)EF_Ctrl_Read_Ldo18ioBypass_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_Ldo18ioVoutSel_Trim]       = (uint32_t)EF_Ctrl_Read_Ldo18ioVoutSel_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_Ldo18ioVoutTrim_Trim]      = (uint32_t)EF_Ctrl_Read_Ldo18ioVoutTrim_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_Ldo33VoutTrim_Trim]        = (uint32_t)EF_Ctrl_Read_Ldo33VoutTrim_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_RC32K_Trim]                = (uint32_t)EF_Ctrl_Read_RC32K_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_RC32M_Trim]                = (uint32_t)EF_Ctrl_Read_RC32M_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_Secure_Boot]               = (uint32_t)EF_Ctrl_Read_Secure_Boot,
    [ROM_API_INDEX_EF_Ctrl_Read_Secure_Cfg]                = (uint32_t)EF_Ctrl_Read_Secure_Cfg,
    [ROM_API_INDEX_EF_Ctrl_Read_Sw_Usage]                  = (uint32_t)EF_Ctrl_Read_Sw_Usage,
    [ROM_API_INDEX_EF_Ctrl_Read_TSEN_Trim]                 = (uint32_t)EF_Ctrl_Read_TSEN_Trim,
    [ROM_API_INDEX_EF_Ctrl_Read_Usb20RcalCode_Trim]        = (uint32_t)EF_Ctrl_Read_Usb20RcalCode_Trim,
    [ROM_API_INDEX_EF_Ctrl_Readlock_AES_Key]               = (uint32_t)EF_Ctrl_Readlock_AES_Key,
    [ROM_API_INDEX_EF_Ctrl_Readlock_Dbg_Pwd]               = (uint32_t)EF_Ctrl_Readlock_Dbg_Pwd,
    [ROM_API_INDEX_EF_Ctrl_Set_sf_key_re_sel]              = (uint32_t)EF_Ctrl_Set_sf_key_re_sel,
    [ROM_API_INDEX_EF_Ctrl_Sw_AHB_Clk_0]                   = (uint32_t)EF_Ctrl_Sw_AHB_Clk_0,
    [ROM_API_INDEX_EF_Ctrl_Write_AES_Key]                  = (uint32_t)EF_Ctrl_Write_AES_Key,
    [ROM_API_INDEX_EF_Ctrl_Write_Dbg_Pwd]                  = (uint32_t)EF_Ctrl_Write_Dbg_Pwd,
    [ROM_API_INDEX_EF_Ctrl_Write_MAC_Address]              = (uint32_t)EF_Ctrl_Write_MAC_Address,
    [ROM_API_INDEX_EF_Ctrl_Write_Secure_Boot]              = (uint32_t)EF_Ctrl_Write_Secure_Boot,
    [ROM_API_INDEX_EF_Ctrl_Write_Secure_Cfg]               = (uint32_t)EF_Ctrl_Write_Secure_Cfg,
    [ROM_API_INDEX_EF_Ctrl_Write_Sw_Usage]                 = (uint32_t)EF_Ctrl_Write_Sw_Usage,
    [ROM_API_INDEX_EF_Ctrl_Writelock_AES_Key]              = (uint32_t)EF_Ctrl_Writelock_AES_Key,
    [ROM_API_INDEX_EF_Ctrl_Writelock_Dbg_Pwd]              = (uint32_t)EF_Ctrl_Writelock_Dbg_Pwd,
    [ROM_API_INDEX_EF_Ctrl_Writelock_MAC_Address]          = (uint32_t)EF_Ctrl_Writelock_MAC_Address,
    [ROM_API_INDEX_EF_Ctrl_Writelock_Sw_Usage]             = (uint32_t)EF_Ctrl_Writelock_Sw_Usage,

    [ROM_API_INDEX_GLB_AHB_MCU_Software_Reset]             = (uint32_t)GLB_AHB_MCU_Software_Reset,
    [ROM_API_INDEX_GLB_AUPLL_Ref_Clk_Sel]                  = (uint32_t)GLB_AUPLL_Ref_Clk_Sel,
    [ROM_API_INDEX_GLB_BMX_TO_Init]                        = (uint32_t)GLB_BMX_TO_Init,
    [ROM_API_INDEX_GLB_Clr_BMX_TO_Status]                  = (uint32_t)GLB_Clr_BMX_TO_Status,
    [ROM_API_INDEX_GLB_Clr_EMI_Reset_Gate]                 = (uint32_t)GLB_Clr_EMI_Reset_Gate,
    [ROM_API_INDEX_GLB_Clr_Reset_Reason]                   = (uint32_t)GLB_Clr_Reset_Reason,
    [ROM_API_INDEX_GLB_Config_SDIO_Host_Interrupt_CPU]     = (uint32_t)GLB_Config_SDIO_Host_Interrupt_CPU,
    [ROM_API_INDEX_GLB_Config_SDIO_Host_Reset_SDU]         = (uint32_t)GLB_Config_SDIO_Host_Reset_SDU,
    [ROM_API_INDEX_GLB_Config_SDIO_Host_Reset_System]      = (uint32_t)GLB_Config_SDIO_Host_Reset_System,
    [ROM_API_INDEX_GLB_Get_Auto_Calc_Xtal_Type]            = (uint32_t)GLB_Get_Auto_Calc_Xtal_Type,
    [ROM_API_INDEX_GLB_Get_MCU_System_CLK_Div]             = (uint32_t)GLB_Get_MCU_System_CLK_Div,
    [ROM_API_INDEX_GLB_Get_Reset_Reason]                   = (uint32_t)GLB_Get_Reset_Reason,
    [ROM_API_INDEX_GLB_IR_RX_GPIO_Sel]                     = (uint32_t)GLB_IR_RX_GPIO_Sel,
    [ROM_API_INDEX_GLB_Invert_ETH_REF_O_CLK]               = (uint32_t)GLB_Invert_ETH_REF_O_CLK,
    [ROM_API_INDEX_GLB_Invert_ETH_RX_CLK]                  = (uint32_t)GLB_Invert_ETH_RX_CLK,
    [ROM_API_INDEX_GLB_Invert_ETH_TX_CLK]                  = (uint32_t)GLB_Invert_ETH_TX_CLK,
    [ROM_API_INDEX_GLB_MCU_SW_System_Reset]                = (uint32_t)GLB_MCU_SW_System_Reset,
    [ROM_API_INDEX_GLB_PER_Clock_Gate]                     = (uint32_t)GLB_PER_Clock_Gate,
    [ROM_API_INDEX_GLB_PER_Clock_UnGate]                   = (uint32_t)GLB_PER_Clock_UnGate,
    [ROM_API_INDEX_GLB_PLL_CGEN_Clock_Gate]                = (uint32_t)GLB_PLL_CGEN_Clock_Gate,
    [ROM_API_INDEX_GLB_PLL_CGEN_Clock_UnGate]              = (uint32_t)GLB_PLL_CGEN_Clock_UnGate,
    [ROM_API_INDEX_GLB_Platform_Wakeup_PDS_Enable]         = (uint32_t)GLB_Platform_Wakeup_PDS_Enable,
    [ROM_API_INDEX_GLB_Power_Off_AUPLL]                    = (uint32_t)GLB_Power_Off_AUPLL,
    [ROM_API_INDEX_GLB_Power_Off_WIFIPLL]                  = (uint32_t)GLB_Power_Off_WIFIPLL,
    [ROM_API_INDEX_GLB_Power_On_AUPLL]                     = (uint32_t)GLB_Power_On_AUPLL,
    [ROM_API_INDEX_GLB_Power_On_WIFIPLL]                   = (uint32_t)GLB_Power_On_WIFIPLL,
    [ROM_API_INDEX_GLB_Power_On_XTAL_And_PLL_CLK]          = (uint32_t)GLB_Power_On_XTAL_And_PLL_CLK,
    [ROM_API_INDEX_GLB_SPI_Sig_Swap_Set]                   = (uint32_t)GLB_SPI_Sig_Swap_Set,
    [ROM_API_INDEX_GLB_SW_CPU_Reset]                       = (uint32_t)GLB_SW_CPU_Reset,
    [ROM_API_INDEX_GLB_SW_POR_Reset]                       = (uint32_t)GLB_SW_POR_Reset,
    [ROM_API_INDEX_GLB_SW_System_Reset]                    = (uint32_t)GLB_SW_System_Reset,
    [ROM_API_INDEX_GLB_Sel_MCU_TMR_GPIO_Clock]             = (uint32_t)GLB_Sel_MCU_TMR_GPIO_Clock,
    [ROM_API_INDEX_GLB_Set_ADC_CLK]                        = (uint32_t)GLB_Set_ADC_CLK,
    [ROM_API_INDEX_GLB_Set_Audio_ADC_CLK]                  = (uint32_t)GLB_Set_Audio_ADC_CLK,
    [ROM_API_INDEX_GLB_Set_Audio_AUTO_CLK]                 = (uint32_t)GLB_Set_Audio_AUTO_CLK,
    [ROM_API_INDEX_GLB_Set_Audio_SOLO_CLK]                 = (uint32_t)GLB_Set_Audio_SOLO_CLK,
    [ROM_API_INDEX_GLB_Set_Auto_Calc_Xtal_Type]            = (uint32_t)GLB_Set_Auto_Calc_Xtal_Type,
    [ROM_API_INDEX_GLB_Set_CAM_CLK]                        = (uint32_t)GLB_Set_CAM_CLK,
    [ROM_API_INDEX_GLB_Set_CPU_Reset_Address]              = (uint32_t)GLB_Set_CPU_Reset_Address,
    [ROM_API_INDEX_GLB_Set_Chip_Clock_Out_Sel]             = (uint32_t)GLB_Set_Chip_Clock_Out_Sel,
    [ROM_API_INDEX_GLB_Set_DBI_CLK]                        = (uint32_t)GLB_Set_DBI_CLK,
    [ROM_API_INDEX_GLB_Set_DIG_32K_CLK]                    = (uint32_t)GLB_Set_DIG_32K_CLK,
    [ROM_API_INDEX_GLB_Set_DIG_512K_CLK]                   = (uint32_t)GLB_Set_DIG_512K_CLK,
    [ROM_API_INDEX_GLB_Set_DIG_CLK_Sel]                    = (uint32_t)GLB_Set_DIG_CLK_Sel,
    [ROM_API_INDEX_GLB_Set_DMA_CLK]                        = (uint32_t)GLB_Set_DMA_CLK,
    [ROM_API_INDEX_GLB_Set_EM_Sel]                         = (uint32_t)GLB_Set_EM_Sel,
    [ROM_API_INDEX_GLB_Set_ETH_REF_O_CLK_Sel]              = (uint32_t)GLB_Set_ETH_REF_O_CLK_Sel,
    [ROM_API_INDEX_GLB_Set_ETH_REF_O_CLK_Sel_2]            = (uint32_t)NULL,
    [ROM_API_INDEX_GLB_Set_I2C_CLK]                        = (uint32_t)GLB_Set_I2C_CLK,
    [ROM_API_INDEX_GLB_Set_I2S_CLK]                        = (uint32_t)GLB_Set_I2S_CLK,
    [ROM_API_INDEX_GLB_Set_IR_CLK]                         = (uint32_t)GLB_Set_IR_CLK,
    [ROM_API_INDEX_GLB_Set_ISP_Muxpll_80M_Sel]             = (uint32_t)GLB_Set_ISP_Muxpll_80M_Sel,
    [ROM_API_INDEX_GLB_Set_MCU_Muxpll_160M_Sel]            = (uint32_t)GLB_Set_MCU_Muxpll_160M_Sel,
    [ROM_API_INDEX_GLB_Set_MCU_Muxpll_80M_Sel]             = (uint32_t)GLB_Set_MCU_Muxpll_80M_Sel,
    [ROM_API_INDEX_GLB_Set_MCU_SPI_0_ACT_MOD_Sel]          = (uint32_t)GLB_Set_MCU_SPI_0_ACT_MOD_Sel,
    [ROM_API_INDEX_GLB_Set_MCU_System_CLK]                 = (uint32_t)GLB_Set_MCU_System_CLK,
    [ROM_API_INDEX_GLB_Set_MCU_System_CLK_Div]             = (uint32_t)GLB_Set_MCU_System_CLK_Div,
    [ROM_API_INDEX_GLB_Set_PDM_IO_Sel]                     = (uint32_t)GLB_Set_PDM_IO_Sel,
    [ROM_API_INDEX_GLB_Set_PKA_CLK_Sel]                    = (uint32_t)GLB_Set_PKA_CLK_Sel,
    [ROM_API_INDEX_GLB_Set_PSRAMB_CLK_Sel]                 = (uint32_t)GLB_Set_PSRAMB_CLK_Sel,
    [ROM_API_INDEX_GLB_Set_PWM1_IO_Sel]                    = (uint32_t)GLB_Set_PWM1_IO_Sel,
    [ROM_API_INDEX_GLB_Set_Peripheral_DMA_CN]              = (uint32_t)GLB_Set_Peripheral_DMA_CN,
    [ROM_API_INDEX_GLB_Set_SDH_CLK]                        = (uint32_t)GLB_Set_SDH_CLK,
    [ROM_API_INDEX_GLB_Set_SF_CLK]                         = (uint32_t)GLB_Set_SF_CLK,
    [ROM_API_INDEX_GLB_Set_SFlash2_IO_PARM]                = (uint32_t)GLB_Set_SFlash2_IO_PARM,
    [ROM_API_INDEX_GLB_Set_SFlash_IO_PARM]                 = (uint32_t)GLB_Set_SFlash_IO_PARM,
    [ROM_API_INDEX_GLB_Set_SPI_CLK]                        = (uint32_t)GLB_Set_SPI_CLK,
    [ROM_API_INDEX_GLB_Set_SRAM_PARM]                      = (uint32_t)GLB_Set_SRAM_PARM,
    [ROM_API_INDEX_GLB_Set_SRAM_RET]                       = (uint32_t)GLB_Set_SRAM_RET,
    [ROM_API_INDEX_GLB_Set_SRAM_SLP]                       = (uint32_t)GLB_Set_SRAM_SLP,
    [ROM_API_INDEX_GLB_Set_SSC_CLK_From_WIFIPLL]           = (uint32_t)GLB_Set_SSC_CLK_From_WIFIPLL,
    [ROM_API_INDEX_GLB_Set_Slave_Grp_0_CLK]                = (uint32_t)GLB_Set_Slave_Grp_0_CLK,
    [ROM_API_INDEX_GLB_Set_UART_CLK]                       = (uint32_t)GLB_Set_UART_CLK,
    [ROM_API_INDEX_GLB_Set_USB_CLK_From_WIFIPLL]           = (uint32_t)GLB_Set_USB_CLK_From_WIFIPLL,
    [ROM_API_INDEX_GLB_Swap_MCU_SPI_0_MOSI_With_MISO]      = (uint32_t)GLB_Swap_MCU_SPI_0_MOSI_With_MISO,
    [ROM_API_INDEX_GLB_Trim_Ldo18ioBypass]                 = (uint32_t)GLB_Trim_Ldo18ioBypass,
    [ROM_API_INDEX_GLB_Trim_Ldo18ioVoutSel]                = (uint32_t)GLB_Trim_Ldo18ioVoutSel,
    [ROM_API_INDEX_GLB_Trim_Ldo18ioVoutTrim]               = (uint32_t)GLB_Trim_Ldo18ioVoutTrim,
    [ROM_API_INDEX_GLB_UART_Fun_Sel]                       = (uint32_t)GLB_UART_Fun_Sel,
    [ROM_API_INDEX_GLB_UART_Sig_Swap_Set]                  = (uint32_t)GLB_UART_Sig_Swap_Set,
    [ROM_API_INDEX_GLB_WIFIPLL_Ref_Clk_Sel]                = (uint32_t)GLB_WIFIPLL_Ref_Clk_Sel,
    [ROM_API_INDEX_GLB_Get_Core_Type]                      = (uint32_t)GLB_Get_Core_Type,
    [ROM_API_INDEX_GLB_Get_MCU_Muxpll_160M_Sel]            = (uint32_t)GLB_Get_MCU_Muxpll_160M_Sel,
    [ROM_API_INDEX_GLB_Get_MCU_Muxpll_80M_Sel]             = (uint32_t)GLB_Get_MCU_Muxpll_80M_Sel,
    [ROM_API_INDEX_GLB_Get_SRAM_PARM]                      = (uint32_t)GLB_Get_SRAM_PARM,
    [ROM_API_INDEX_GLB_Get_SRAM_RET]                       = (uint32_t)GLB_Get_SRAM_RET,
    [ROM_API_INDEX_GLB_Get_SRAM_SLP]                       = (uint32_t)GLB_Get_SRAM_SLP,
    [ROM_API_INDEX_GLB_Get_BMX_TO_Status]                  = (uint32_t)GLB_Get_BMX_TO_Status,
    [ROM_API_INDEX_GLB_Clr_GPIO_IntStatus]                 = (uint32_t)GLB_Clr_GPIO_IntStatus,
    [ROM_API_INDEX_GLB_Embedded_Flash_Pad_Enable]          = (uint32_t)GLB_Embedded_Flash_Pad_Enable,
    [ROM_API_INDEX_GLB_GPIO_Clr]                           = (uint32_t)GLB_GPIO_Clr,
    [ROM_API_INDEX_GLB_GPIO_Fifo_Clear]                    = (uint32_t)GLB_GPIO_Fifo_Clear,
    [ROM_API_INDEX_GLB_GPIO_Fifo_Init]                     = (uint32_t)GLB_GPIO_Fifo_Init,
    [ROM_API_INDEX_GLB_GPIO_Fifo_IntClear]                 = (uint32_t)GLB_GPIO_Fifo_IntClear,
    [ROM_API_INDEX_GLB_GPIO_Fifo_IntMask]                  = (uint32_t)GLB_GPIO_Fifo_IntMask,
    [ROM_API_INDEX_GLB_GPIO_Fifo_Push]                     = (uint32_t)GLB_GPIO_Fifo_Push,
    [ROM_API_INDEX_GLB_GPIO_Func_Init]                     = (uint32_t)GLB_GPIO_Func_Init,
    [ROM_API_INDEX_GLB_GPIO_Init]                          = (uint32_t)GLB_GPIO_Init,
    [ROM_API_INDEX_GLB_GPIO_Input_Disable]                 = (uint32_t)GLB_GPIO_Input_Disable,
    [ROM_API_INDEX_GLB_GPIO_Input_Enable]                  = (uint32_t)GLB_GPIO_Input_Enable,
    [ROM_API_INDEX_GLB_GPIO_IntMask]                       = (uint32_t)GLB_GPIO_IntMask,
    [ROM_API_INDEX_GLB_GPIO_Int_Init]                      = (uint32_t)GLB_GPIO_Int_Init,
    [ROM_API_INDEX_GLB_GPIO_Output_Disable]                = (uint32_t)GLB_GPIO_Output_Disable,
    [ROM_API_INDEX_GLB_GPIO_Output_Enable]                 = (uint32_t)GLB_GPIO_Output_Enable,
    [ROM_API_INDEX_GLB_GPIO_Set]                           = (uint32_t)GLB_GPIO_Set,
    [ROM_API_INDEX_GLB_GPIO_Set_HZ]                        = (uint32_t)GLB_GPIO_Set_HZ,
    [ROM_API_INDEX_GLB_GPIO_Write]                         = (uint32_t)GLB_GPIO_Write,
    [ROM_API_INDEX_GLB_GPIO_Fifo_Disable]                  = (uint32_t)GLB_GPIO_Fifo_Disable,
    [ROM_API_INDEX_GLB_GPIO_Fifo_Enable]                   = (uint32_t)GLB_GPIO_Fifo_Enable,
    [ROM_API_INDEX_GLB_GPIO_Fifo_GetIntStatus]             = (uint32_t)GLB_GPIO_Fifo_GetIntStatus,
    [ROM_API_INDEX_GLB_Get_GPIO_IntStatus]                 = (uint32_t)GLB_Get_GPIO_IntStatus,
    [ROM_API_INDEX_GLB_GPIO_Fifo_GetCount]                 = (uint32_t)GLB_GPIO_Fifo_GetCount,
    [ROM_API_INDEX_GLB_GPIO_Read]                          = (uint32_t)GLB_GPIO_Read,
    [ROM_API_INDEX_GLB_GPIO_Get_Fun]                       = (uint32_t)GLB_GPIO_Get_Fun,

    [ROM_API_INDEX_HBN_32K_Sel]                            = (uint32_t)HBN_32K_Sel,
    [ROM_API_INDEX_HBN_Aon_Pad_Cfg]                        = (uint32_t)HBN_Aon_Pad_Cfg,
    [ROM_API_INDEX_HBN_Aon_Pad_Cfg_Set]                    = (uint32_t)HBN_Aon_Pad_Cfg_Set,
    [ROM_API_INDEX_HBN_Aon_Pad_Ctrl]                       = (uint32_t)HBN_Aon_Pad_Ctrl,
    [ROM_API_INDEX_HBN_Aon_Pad_WakeUpCfg]                  = (uint32_t)HBN_Aon_Pad_WakeUpCfg,
    [ROM_API_INDEX_HBN_Clear_Gpio_Keep]                    = (uint32_t)HBN_Clear_Gpio_Keep,
    [ROM_API_INDEX_HBN_Clear_IRQ]                          = (uint32_t)HBN_Clear_IRQ,
    [ROM_API_INDEX_HBN_Clear_PDS_Gpio_Keep]                = (uint32_t)HBN_Clear_PDS_Gpio_Keep,
    [ROM_API_INDEX_HBN_Clear_RTC_Counter]                  = (uint32_t)HBN_Clear_RTC_Counter,
    [ROM_API_INDEX_HBN_Clear_RTC_INT]                      = (uint32_t)HBN_Clear_RTC_INT,
    [ROM_API_INDEX_HBN_Disable_AComp0_IRQ]                 = (uint32_t)HBN_Disable_AComp0_IRQ,
    [ROM_API_INDEX_HBN_Disable_AComp1_IRQ]                 = (uint32_t)HBN_Disable_AComp1_IRQ,
    [ROM_API_INDEX_HBN_Disable_BOD_IRQ]                    = (uint32_t)HBN_Disable_BOD_IRQ,
    [ROM_API_INDEX_HBN_Enable_AComp0_IRQ]                  = (uint32_t)HBN_Enable_AComp0_IRQ,
    [ROM_API_INDEX_HBN_Enable_AComp1_IRQ]                  = (uint32_t)HBN_Enable_AComp1_IRQ,
    [ROM_API_INDEX_HBN_Enable_BOD_IRQ]                     = (uint32_t)HBN_Enable_BOD_IRQ,
    [ROM_API_INDEX_HBN_Enable_RTC_Counter]                 = (uint32_t)HBN_Enable_RTC_Counter,
    [ROM_API_INDEX_HBN_GPIO_INT_Disable]                   = (uint32_t)HBN_GPIO_INT_Disable,
    [ROM_API_INDEX_HBN_GPIO_INT_Enable]                    = (uint32_t)HBN_GPIO_INT_Enable,
    [ROM_API_INDEX_HBN_Get_Flash_Power_Delay]              = (uint32_t)HBN_Get_Flash_Power_Delay,
    [ROM_API_INDEX_HBN_Get_Gpio_Keep]                      = (uint32_t)HBN_Get_Gpio_Keep,
    [ROM_API_INDEX_HBN_Get_Ldo18io_Power_Delay_Config]     = (uint32_t)HBN_Get_Ldo18io_Power_Delay_Config,
    [ROM_API_INDEX_HBN_Get_PDS_Gpio_Keep]                  = (uint32_t)HBN_Get_PDS_Gpio_Keep,
    [ROM_API_INDEX_HBN_Get_RTC_Timer_Val]                  = (uint32_t)HBN_Get_RTC_Timer_Val,
    [ROM_API_INDEX_HBN_Get_Xtal_Type]                      = (uint32_t)HBN_Get_Xtal_Type,
    [ROM_API_INDEX_HBN_Hw_Pu_Pd_Cfg]                       = (uint32_t)HBN_Hw_Pu_Pd_Cfg,
    [ROM_API_INDEX_HBN_Keep_On_RC32K]                      = (uint32_t)HBN_Keep_On_RC32K,
    [ROM_API_INDEX_HBN_PIR_Disable]                        = (uint32_t)HBN_PIR_Disable,
    [ROM_API_INDEX_HBN_PIR_Enable]                         = (uint32_t)HBN_PIR_Enable,
    [ROM_API_INDEX_HBN_PIR_HPF_Sel]                        = (uint32_t)HBN_PIR_HPF_Sel,
    [ROM_API_INDEX_HBN_PIR_INT_Config]                     = (uint32_t)HBN_PIR_INT_Config,
    [ROM_API_INDEX_HBN_PIR_LPF_Sel]                        = (uint32_t)HBN_PIR_LPF_Sel,
    [ROM_API_INDEX_HBN_Pin_WakeUp_Mask]                    = (uint32_t)HBN_Pin_WakeUp_Mask,
    [ROM_API_INDEX_HBN_Power_Off_RC32K]                    = (uint32_t)HBN_Power_Off_RC32K,
    [ROM_API_INDEX_HBN_Power_Off_Xtal_32K]                 = (uint32_t)HBN_Power_Off_Xtal_32K,
    [ROM_API_INDEX_HBN_Power_On_Xtal_32K]                  = (uint32_t)HBN_Power_On_Xtal_32K,
    [ROM_API_INDEX_HBN_Reset]                              = (uint32_t)HBN_Reset,
    [ROM_API_INDEX_HBN_Set_BOD_Cfg]                        = (uint32_t)HBN_Set_BOD_Cfg,
    [ROM_API_INDEX_HBN_Set_BOD_Config]                     = (uint32_t)HBN_Set_BOD_Config,
    [ROM_API_INDEX_HBN_Set_Core_Reboot_Config]             = (uint32_t)HBN_Set_Core_Reboot_Config,
    [ROM_API_INDEX_HBN_Set_Flash_Power_Delay]              = (uint32_t)HBN_Set_Flash_Power_Delay,
    [ROM_API_INDEX_HBN_Set_GPADC_CLK_Sel]                  = (uint32_t)HBN_Set_GPADC_CLK_Sel,
    [ROM_API_INDEX_HBN_Set_Gpio_Keep]                      = (uint32_t)HBN_Set_Gpio_Keep,
    [ROM_API_INDEX_HBN_Set_HRAM_Ret]                       = (uint32_t)HBN_Set_HRAM_Ret,
    [ROM_API_INDEX_HBN_Set_HRAM_slp]                       = (uint32_t)HBN_Set_HRAM_slp,
    [ROM_API_INDEX_HBN_Set_Ldo11_All_Vout]                 = (uint32_t)HBN_Set_Ldo11_All_Vout,
    [ROM_API_INDEX_HBN_Set_Ldo11_Aon_Vout]                 = (uint32_t)HBN_Set_Ldo11_Aon_Vout,
    [ROM_API_INDEX_HBN_Set_Ldo11_Rt_Vout]                  = (uint32_t)HBN_Set_Ldo11_Rt_Vout,
    [ROM_API_INDEX_HBN_Set_Ldo11_Soc_Vout]                 = (uint32_t)HBN_Set_Ldo11_Soc_Vout,
    [ROM_API_INDEX_HBN_Set_Ldo18io_Power_Delay_Config]     = (uint32_t)HBN_Set_Ldo18io_Power_Delay_Config,
    [ROM_API_INDEX_HBN_Set_MCU_Root_CLK_Sel]               = (uint32_t)HBN_Set_MCU_Root_CLK_Sel,
    [ROM_API_INDEX_HBN_Set_MCU_XCLK_Sel]                   = (uint32_t)HBN_Set_MCU_XCLK_Sel,
    [ROM_API_INDEX_HBN_Set_PDS_Gpio_Keep]                  = (uint32_t)HBN_Set_PDS_Gpio_Keep,
    [ROM_API_INDEX_HBN_Set_PIR_Interval]                   = (uint32_t)HBN_Set_PIR_Interval,
    [ROM_API_INDEX_HBN_Set_PIR_Threshold]                  = (uint32_t)HBN_Set_PIR_Threshold,
    [ROM_API_INDEX_HBN_Set_RTC_Timer]                      = (uint32_t)HBN_Set_RTC_Timer,
    [ROM_API_INDEX_HBN_Set_Status_Flag]                    = (uint32_t)HBN_Set_Status_Flag,
    [ROM_API_INDEX_HBN_Set_UART_CLK_Sel]                   = (uint32_t)HBN_Set_UART_CLK_Sel,
    [ROM_API_INDEX_HBN_Set_User_Boot_Config]               = (uint32_t)HBN_Set_User_Boot_Config,
    [ROM_API_INDEX_HBN_Set_Wakeup_Addr]                    = (uint32_t)HBN_Set_Wakeup_Addr,
    [ROM_API_INDEX_HBN_Set_Xtal_Type]                      = (uint32_t)HBN_Set_Xtal_Type,
    [ROM_API_INDEX_HBN_Trim_Ldo33VoutTrim]                 = (uint32_t)HBN_Trim_Ldo33VoutTrim,
    [ROM_API_INDEX_HBN_Trim_RC32K]                         = (uint32_t)HBN_Trim_RC32K,
    [ROM_API_INDEX_HBN_Get_BOD_OUT_State]                  = (uint32_t)HBN_Get_BOD_OUT_State,
    [ROM_API_INDEX_HBN_Get_INT_State]                      = (uint32_t)HBN_Get_INT_State,
    [ROM_API_INDEX_HBN_Get_MCU_Root_CLK_Sel]               = (uint32_t)HBN_Get_MCU_Root_CLK_Sel,
    [ROM_API_INDEX_HBN_Get_MCU_XCLK_Sel]                   = (uint32_t)HBN_Get_MCU_XCLK_Sel,
    [ROM_API_INDEX_HBN_Get_PIR_Interval]                   = (uint32_t)HBN_Get_PIR_Interval,
    [ROM_API_INDEX_HBN_Get_PIR_Threshold]                  = (uint32_t)HBN_Get_PIR_Threshold,
    [ROM_API_INDEX_HBN_Get_Status_Flag]                    = (uint32_t)HBN_Get_Status_Flag,
    [ROM_API_INDEX_HBN_Get_Wakeup_Addr]                    = (uint32_t)HBN_Get_Wakeup_Addr,
    [ROM_API_INDEX_HBN_Get_Core_Unhalt_Config]             = (uint32_t)HBN_Get_Core_Unhalt_Config,
    [ROM_API_INDEX_HBN_Get_Pin_Wakeup_Mode]                = (uint32_t)HBN_Get_Pin_Wakeup_Mode,
    [ROM_API_INDEX_HBN_Get_User_Boot_Config]               = (uint32_t)HBN_Get_User_Boot_Config,
    [ROM_API_INDEX_HBN_Enable]                             = (uint32_t)HBN_Enable,
    [ROM_API_INDEX_HBN_Mode_Enter]                         = (uint32_t)HBN_Mode_Enter,
    [ROM_API_INDEX_HBN_Power_Down_Flash]                   = (uint32_t)HBN_Power_Down_Flash,

    [ROM_API_INDEX_L1C_DCache_Clean_All]                   = (uint32_t)L1C_DCache_Clean_All,
    [ROM_API_INDEX_L1C_DCache_Clean_By_Addr]               = (uint32_t)L1C_DCache_Clean_By_Addr,
    [ROM_API_INDEX_L1C_DCache_Clean_Invalid_All]           = (uint32_t)L1C_DCache_Clean_Invalid_All,
    [ROM_API_INDEX_L1C_DCache_Clean_Invalid_By_Addr]       = (uint32_t)L1C_DCache_Clean_Invalid_By_Addr,
    [ROM_API_INDEX_L1C_DCache_Disable]                     = (uint32_t)L1C_DCache_Disable,
    [ROM_API_INDEX_L1C_DCache_Enable]                      = (uint32_t)L1C_DCache_Enable,
    [ROM_API_INDEX_L1C_DCache_Invalid_All]                 = (uint32_t)L1C_DCache_Invalid_All,
    [ROM_API_INDEX_L1C_DCache_Invalid_By_Addr]             = (uint32_t)L1C_DCache_Invalid_By_Addr,
    [ROM_API_INDEX_L1C_ICache_Disable]                     = (uint32_t)L1C_ICache_Disable,
    [ROM_API_INDEX_L1C_ICache_Enable]                      = (uint32_t)L1C_ICache_Enable,
    [ROM_API_INDEX_L1C_ICache_Invalid_All]                 = (uint32_t)L1C_ICache_Invalid_All,
    [ROM_API_INDEX_L1C_ICache_Invalid_By_Addr]             = (uint32_t)L1C_ICache_Invalid_By_Addr,
    [ROM_API_INDEX_L1C_Set_Cache_Setting_By_ID]            = (uint32_t)L1C_Set_Cache_Setting_By_ID,
    [ROM_API_INDEX_L1C_Set_Wrap]                           = (uint32_t)L1C_Set_Wrap,
    [ROM_API_INDEX_L1C_DCache_Write_Set]                   = (uint32_t)L1C_DCache_Write_Set,

    [ROM_API_INDEX_PDS_Default_Level_Config]               = (uint32_t)PDS_Default_Level_Config,
    [ROM_API_INDEX_PDS_Disable_GPIO_Keep]                  = (uint32_t)PDS_Disable_GPIO_Keep,
    [ROM_API_INDEX_PDS_Enable]                             = (uint32_t)PDS_Enable,
    [ROM_API_INDEX_PDS_Force_Config]                       = (uint32_t)PDS_Force_Config,
    [ROM_API_INDEX_PDS_IntClear]                           = (uint32_t)PDS_IntClear,
    [ROM_API_INDEX_PDS_IntMask]                            = (uint32_t)PDS_IntMask,
    [ROM_API_INDEX_PDS_RAM_Config]                         = (uint32_t)PDS_RAM_Config,
    [ROM_API_INDEX_PDS_Set_Flash_Pad_Pull_None]            = (uint32_t)PDS_Set_Flash_Pad_Pull_None,
    [ROM_API_INDEX_PDS_Set_Flash_Pad_Pull_None_Fast]       = (uint32_t)PDS_Set_Flash_Pad_Pull_None_Fast,
    [ROM_API_INDEX_PDS_Set_GPIO_Pad_IntClr]                = (uint32_t)PDS_Set_GPIO_Pad_IntClr,
    [ROM_API_INDEX_PDS_Set_GPIO_Pad_IntMask]               = (uint32_t)PDS_Set_GPIO_Pad_IntMask,
    [ROM_API_INDEX_PDS_Set_GPIO_Pad_IntMode]               = (uint32_t)PDS_Set_GPIO_Pad_IntMode,
    [ROM_API_INDEX_PDS_Set_GPIO_Pad_Pn_Pu_Pd_Ie]           = (uint32_t)PDS_Set_GPIO_Pad_Pn_Pu_Pd_Ie,
    [ROM_API_INDEX_PDS_Set_MCU0_Clock_Disable]             = (uint32_t)PDS_Set_MCU0_Clock_Disable,
    [ROM_API_INDEX_PDS_Set_MCU0_Clock_Enable]              = (uint32_t)PDS_Set_MCU0_Clock_Enable,
    [ROM_API_INDEX_PDS_Set_MCU0_Reset_Address]             = (uint32_t)PDS_Set_MCU0_Reset_Address,
    [ROM_API_INDEX_PDS_Set_USB_Resume]                     = (uint32_t)PDS_Set_USB_Resume,
    [ROM_API_INDEX_PDS_Set_USB_Suspend]                    = (uint32_t)PDS_Set_USB_Suspend,
    [ROM_API_INDEX_PDS_Trim_RC32M]                         = (uint32_t)PDS_Trim_RC32M,
    [ROM_API_INDEX_PDS_Turn_Off_USB]                       = (uint32_t)PDS_Turn_Off_USB,
    [ROM_API_INDEX_PDS_Turn_On_USB]                        = (uint32_t)PDS_Turn_On_USB,
    [ROM_API_INDEX_PDS_Get_GPIO_Pad_IntStatus]             = (uint32_t)PDS_Get_GPIO_Pad_IntStatus,
    [ROM_API_INDEX_PDS_Get_IntStatus]                      = (uint32_t)PDS_Get_IntStatus,

    [ROM_API_INDEX_SF_Cfg_Deinit_Ext_Flash_Gpio]           = (uint32_t)SF_Cfg_Deinit_Ext_Flash_Gpio,
    [ROM_API_INDEX_SF_Cfg_Flash_Init]                      = (uint32_t)SF_Cfg_Flash_Init,
    [ROM_API_INDEX_SF_Cfg_Get_Flash_Cfg_Need_Lock]         = (uint32_t)SF_Cfg_Get_Flash_Cfg_Need_Lock,
    [ROM_API_INDEX_SF_Cfg_Init_Ext_Flash_Gpio]             = (uint32_t)SF_Cfg_Init_Ext_Flash_Gpio,
    [ROM_API_INDEX_SF_Cfg_Init_Flash2_Gpio]                = (uint32_t)SF_Cfg_Init_Flash2_Gpio,
    [ROM_API_INDEX_SF_Cfg_Init_Flash_Gpio]                 = (uint32_t)SF_Cfg_Init_Flash_Gpio,
    [ROM_API_INDEX_SF_Cfg_Sbus2_Flash_Init]                = (uint32_t)SF_Cfg_Sbus2_Flash_Init,
    [ROM_API_INDEX_SF_Cfg_Flash_Identify]                  = (uint32_t)SF_Cfg_Flash_Identify,
    [ROM_API_INDEX_SF_Ctrl_GetBusyState]                   = (uint32_t)SF_Ctrl_GetBusyState,
    [ROM_API_INDEX_SF_Ctrl_Is_AES_Enable]                  = (uint32_t)SF_Ctrl_Is_AES_Enable,
    [ROM_API_INDEX_SF_Ctrl_Is_Sbus2_Enable]                = (uint32_t)SF_Ctrl_Is_Sbus2_Enable,
    [ROM_API_INDEX_SF_Ctrl_Get_Flash_Image_Offset]         = (uint32_t)SF_Ctrl_Get_Flash_Image_Offset,
    [ROM_API_INDEX_SF_Ctrl_Get_Clock_Delay]                = (uint32_t)SF_Ctrl_Get_Clock_Delay,
    [ROM_API_INDEX_SF_Ctrl_Get_Wrap_Queue_Value]           = (uint32_t)SF_Ctrl_Get_Wrap_Queue_Value,
    [ROM_API_INDEX_SF_Ctrl_32bits_Addr_En]                 = (uint32_t)SF_Ctrl_32bits_Addr_En,
    [ROM_API_INDEX_SF_Ctrl_AES_Disable]                    = (uint32_t)SF_Ctrl_AES_Disable,
    [ROM_API_INDEX_SF_Ctrl_AES_Enable]                     = (uint32_t)SF_Ctrl_AES_Enable,
    [ROM_API_INDEX_SF_Ctrl_AES_Enable_BE]                  = (uint32_t)SF_Ctrl_AES_Enable_BE,
    [ROM_API_INDEX_SF_Ctrl_AES_Enable_LE]                  = (uint32_t)SF_Ctrl_AES_Enable_LE,
    [ROM_API_INDEX_SF_Ctrl_AES_Set_IV]                     = (uint32_t)SF_Ctrl_AES_Set_IV,
    [ROM_API_INDEX_SF_Ctrl_AES_Set_IV_BE]                  = (uint32_t)SF_Ctrl_AES_Set_IV_BE,
    [ROM_API_INDEX_SF_Ctrl_AES_Set_Key]                    = (uint32_t)SF_Ctrl_AES_Set_Key,
    [ROM_API_INDEX_SF_Ctrl_AES_Set_Key_BE]                 = (uint32_t)SF_Ctrl_AES_Set_Key_BE,
    [ROM_API_INDEX_SF_Ctrl_AES_Set_Mode]                   = (uint32_t)SF_Ctrl_AES_Set_Mode,
    [ROM_API_INDEX_SF_Ctrl_AES_Set_Region]                 = (uint32_t)SF_Ctrl_AES_Set_Region,
    [ROM_API_INDEX_SF_Ctrl_AES_XTS_Set_IV]                 = (uint32_t)SF_Ctrl_AES_XTS_Set_IV,
    [ROM_API_INDEX_SF_Ctrl_AES_XTS_Set_IV_BE]              = (uint32_t)SF_Ctrl_AES_XTS_Set_IV_BE,
    [ROM_API_INDEX_SF_Ctrl_AES_XTS_Set_Key]                = (uint32_t)SF_Ctrl_AES_XTS_Set_Key,
    [ROM_API_INDEX_SF_Ctrl_AES_XTS_Set_Key_BE]             = (uint32_t)SF_Ctrl_AES_XTS_Set_Key_BE,
    [ROM_API_INDEX_SF_Ctrl_Bank2_Enable]                   = (uint32_t)SF_Ctrl_Bank2_Enable,
    [ROM_API_INDEX_SF_Ctrl_Cmds_Set]                       = (uint32_t)SF_Ctrl_Cmds_Set,
    [ROM_API_INDEX_SF_Ctrl_Disable]                        = (uint32_t)SF_Ctrl_Disable,
    [ROM_API_INDEX_SF_Ctrl_Disable_Wrap_Access]            = (uint32_t)SF_Ctrl_Disable_Wrap_Access,
    [ROM_API_INDEX_SF_Ctrl_Enable]                         = (uint32_t)SF_Ctrl_Enable,
    [ROM_API_INDEX_SF_Ctrl_Flash2_Read_Icache_Set]         = (uint32_t)SF_Ctrl_Flash2_Read_Icache_Set,
    [ROM_API_INDEX_SF_Ctrl_Flash_Read_Icache_Set]          = (uint32_t)SF_Ctrl_Flash_Read_Icache_Set,
    [ROM_API_INDEX_SF_Ctrl_Lock_Flash_Image_Offset]        = (uint32_t)SF_Ctrl_Lock_Flash_Image_Offset,
    [ROM_API_INDEX_SF_Ctrl_Remap_Set]                      = (uint32_t)SF_Ctrl_Remap_Set,
    [ROM_API_INDEX_SF_Ctrl_Sbus2_Hold_Sram]                = (uint32_t)SF_Ctrl_Sbus2_Hold_Sram,
    [ROM_API_INDEX_SF_Ctrl_Sbus2_Release_Sram]             = (uint32_t)SF_Ctrl_Sbus2_Release_Sram,
    [ROM_API_INDEX_SF_Ctrl_Sbus2_Replace]                  = (uint32_t)SF_Ctrl_Sbus2_Replace,
    [ROM_API_INDEX_SF_Ctrl_Sbus2_Revoke_replace]           = (uint32_t)SF_Ctrl_Sbus2_Revoke_replace,
    [ROM_API_INDEX_SF_Ctrl_Sbus2_Set_Delay]                = (uint32_t)SF_Ctrl_Sbus2_Set_Delay,
    [ROM_API_INDEX_SF_Ctrl_Sbus_Select_Bank]               = (uint32_t)SF_Ctrl_Sbus_Select_Bank,
    [ROM_API_INDEX_SF_Ctrl_Select_Pad]                     = (uint32_t)SF_Ctrl_Select_Pad,
    [ROM_API_INDEX_SF_Ctrl_SendCmd]                        = (uint32_t)SF_Ctrl_SendCmd,
    [ROM_API_INDEX_SF_Ctrl_Set_Clock_Delay]                = (uint32_t)SF_Ctrl_Set_Clock_Delay,
    [ROM_API_INDEX_SF_Ctrl_Set_Flash_Image_Offset]         = (uint32_t)SF_Ctrl_Set_Flash_Image_Offset,
    [ROM_API_INDEX_SF_Ctrl_Set_IO_Delay]                   = (uint32_t)SF_Ctrl_Set_IO_Delay,
    [ROM_API_INDEX_SF_Ctrl_Set_Owner]                      = (uint32_t)SF_Ctrl_Set_Owner,

    [ROM_API_INDEX_SFlash_Blk32_Erase]                     = (uint32_t)SFlash_Blk32_Erase,
    [ROM_API_INDEX_SFlash_Blk64_Erase]                     = (uint32_t)SFlash_Blk64_Erase,
    [ROM_API_INDEX_SFlash_Chip_Erase]                      = (uint32_t)SFlash_Chip_Erase,
    [ROM_API_INDEX_SFlash_Erase]                           = (uint32_t)SFlash_Erase,
    [ROM_API_INDEX_SFlash_Erase_Security_Register]         = (uint32_t)SFlash_Erase_Security_Register,
    [ROM_API_INDEX_SFlash_IDbus_Read_Enable]               = (uint32_t)SFlash_IDbus_Read_Enable,
    [ROM_API_INDEX_SFlash_Program]                         = (uint32_t)SFlash_Program,
    [ROM_API_INDEX_SFlash_Program_Security_Register]       = (uint32_t)SFlash_Program_Security_Register,
    [ROM_API_INDEX_SFlash_Qspi_Disable]                    = (uint32_t)SFlash_Qspi_Disable,
    [ROM_API_INDEX_SFlash_Qspi_Enable]                     = (uint32_t)SFlash_Qspi_Enable,
    [ROM_API_INDEX_SFlash_RCV_Enable]                      = (uint32_t)SFlash_RCV_Enable,
    [ROM_API_INDEX_SFlash_Read]                            = (uint32_t)SFlash_Read,
    [ROM_API_INDEX_SFlash_Read_Reg]                        = (uint32_t)SFlash_Read_Reg,
    [ROM_API_INDEX_SFlash_Read_Reg_With_Cmd]               = (uint32_t)SFlash_Read_Reg_With_Cmd,
    [ROM_API_INDEX_SFlash_Read_Security_Register]          = (uint32_t)SFlash_Read_Security_Register,
    [ROM_API_INDEX_SFlash_Restore_From_Powerdown]          = (uint32_t)SFlash_Restore_From_Powerdown,
    [ROM_API_INDEX_SFlash_Sector_Erase]                    = (uint32_t)SFlash_Sector_Erase,
    [ROM_API_INDEX_SFlash_Set32BitsAddrMode]               = (uint32_t)SFlash_Set32BitsAddrMode,
    [ROM_API_INDEX_SFlash_SetSPIMode]                      = (uint32_t)SFlash_SetSPIMode,
    [ROM_API_INDEX_SFlash_Set_IDbus_Cfg]                   = (uint32_t)SFlash_Set_IDbus_Cfg,
    [ROM_API_INDEX_SFlash_Software_Reset]                  = (uint32_t)SFlash_Software_Reset,
    [ROM_API_INDEX_SFlash_Write_Enable]                    = (uint32_t)SFlash_Write_Enable,
    [ROM_API_INDEX_SFlash_Write_Reg]                       = (uint32_t)SFlash_Write_Reg,
    [ROM_API_INDEX_SFlash_Write_Reg_With_Cmd]              = (uint32_t)SFlash_Write_Reg_With_Cmd,
    [ROM_API_INDEX_SFlash_Busy]                            = (uint32_t)SFlash_Busy,
    [ROM_API_INDEX_SFlash_DisableBurstWrap]                = (uint32_t)SFlash_DisableBurstWrap,
    [ROM_API_INDEX_SFlash_GetDeviceId]                     = (uint32_t)SFlash_GetDeviceId,
    [ROM_API_INDEX_SFlash_GetJedecId]                      = (uint32_t)SFlash_GetJedecId,
    [ROM_API_INDEX_SFlash_GetUniqueId]                     = (uint32_t)SFlash_GetUniqueId,
    [ROM_API_INDEX_SFlash_IDbus_Read_Disable]              = (uint32_t)SFlash_IDbus_Read_Disable,
    [ROM_API_INDEX_SFlash_Init]                            = (uint32_t)SFlash_Init,
    [ROM_API_INDEX_SFlash_Powerdown]                       = (uint32_t)SFlash_Powerdown,
    [ROM_API_INDEX_SFlash_Release_Powerdown]               = (uint32_t)SFlash_Release_Powerdown,
    [ROM_API_INDEX_SFlash_Reset_Continue_Read]             = (uint32_t)SFlash_Reset_Continue_Read,
    [ROM_API_INDEX_SFlash_SetBurstWrap]                    = (uint32_t)SFlash_SetBurstWrap,
    [ROM_API_INDEX_SFlash_Volatile_Reg_Write_Enable]       = (uint32_t)SFlash_Volatile_Reg_Write_Enable,

    [ROM_API_INDEX_UART_AutoBaudDetection]                 = (uint32_t)UART_AutoBaudDetection,
    [ROM_API_INDEX_UART_ClrRtsValue]                       = (uint32_t)UART_ClrRtsValue,
    [ROM_API_INDEX_UART_ClrTxValue]                        = (uint32_t)UART_ClrTxValue,
    [ROM_API_INDEX_UART_DeInit]                            = (uint32_t)UART_DeInit,
    [ROM_API_INDEX_UART_Disable]                           = (uint32_t)UART_Disable,
    [ROM_API_INDEX_UART_Enable]                            = (uint32_t)UART_Enable,
    [ROM_API_INDEX_UART_FifoConfig]                        = (uint32_t)UART_FifoConfig,
    [ROM_API_INDEX_UART_GetBitWidth0X55]                   = (uint32_t)UART_GetBitWidth0X55,
    [ROM_API_INDEX_UART_Init]                              = (uint32_t)UART_Init,
    [ROM_API_INDEX_UART_IntClear]                          = (uint32_t)UART_IntClear,
    [ROM_API_INDEX_UART_IntMask]                           = (uint32_t)UART_IntMask,
    [ROM_API_INDEX_UART_IrConfig]                          = (uint32_t)UART_IrConfig,
    [ROM_API_INDEX_UART_RxFifoClear]                       = (uint32_t)UART_RxFifoClear,
    [ROM_API_INDEX_UART_SendData]                          = (uint32_t)UART_SendData,
    [ROM_API_INDEX_UART_SendDataBlock]                     = (uint32_t)UART_SendDataBlock,
    [ROM_API_INDEX_UART_SetAllowableError0X55]             = (uint32_t)UART_SetAllowableError0X55,
    [ROM_API_INDEX_UART_SetBaudrate]                       = (uint32_t)UART_SetBaudrate,
    [ROM_API_INDEX_UART_SetDeglitchCount]                  = (uint32_t)UART_SetDeglitchCount,
    [ROM_API_INDEX_UART_SetRS485]                          = (uint32_t)UART_SetRS485,
    [ROM_API_INDEX_UART_SetRtsValue]                       = (uint32_t)UART_SetRtsValue,
    [ROM_API_INDEX_UART_SetRxByteCount]                    = (uint32_t)UART_SetRxByteCount,
    [ROM_API_INDEX_UART_SetRxDataLength]                   = (uint32_t)UART_SetRxDataLength,
    [ROM_API_INDEX_UART_SetRxTimeoutValue]                 = (uint32_t)UART_SetRxTimeoutValue,
    [ROM_API_INDEX_UART_SetTxDataLength]                   = (uint32_t)UART_SetTxDataLength,
    [ROM_API_INDEX_UART_SetTxValue]                        = (uint32_t)UART_SetTxValue,
    [ROM_API_INDEX_UART_TxFifoClear]                       = (uint32_t)UART_TxFifoClear,
    [ROM_API_INDEX_UART_TxFreeRun]                         = (uint32_t)UART_TxFreeRun,
    [ROM_API_INDEX_UART_GetIntStatus]                      = (uint32_t)UART_GetIntStatus,
    [ROM_API_INDEX_UART_GetOverflowStatus]                 = (uint32_t)UART_GetOverflowStatus,
    [ROM_API_INDEX_UART_GetRxBusBusyStatus]                = (uint32_t)UART_GetRxBusBusyStatus,
    [ROM_API_INDEX_UART_GetTxBusBusyStatus]                = (uint32_t)UART_GetTxBusBusyStatus,
    [ROM_API_INDEX_UART_GetAutoBaudCount]                  = (uint32_t)UART_GetAutoBaudCount,
    [ROM_API_INDEX_UART_GetRxByteCount]                    = (uint32_t)UART_GetRxByteCount,
    [ROM_API_INDEX_UART_ReceiveData]                       = (uint32_t)UART_ReceiveData,
    [ROM_API_INDEX_UART_GetRxFifoCount]                    = (uint32_t)UART_GetRxFifoCount,
    [ROM_API_INDEX_UART_GetTxFifoCount]                    = (uint32_t)UART_GetTxFifoCount,

    [ROM_API_INDEX_XIP_SFlash_Erase_Need_Lock]             = (uint32_t)XIP_SFlash_Erase_Need_Lock,
    [ROM_API_INDEX_XIP_SFlash_GetDeviceId_Need_Lock]       = (uint32_t)XIP_SFlash_GetDeviceId_Need_Lock,
    [ROM_API_INDEX_XIP_SFlash_GetJedecId_Need_Lock]        = (uint32_t)XIP_SFlash_GetJedecId_Need_Lock,
    [ROM_API_INDEX_XIP_SFlash_GetUniqueId_Need_Lock]       = (uint32_t)XIP_SFlash_GetUniqueId_Need_Lock,
    [ROM_API_INDEX_XIP_SFlash_Read_Need_Lock]              = (uint32_t)XIP_SFlash_Read_Need_Lock,
    [ROM_API_INDEX_XIP_SFlash_Read_Via_Cache_Need_Lock]    = (uint32_t)XIP_SFlash_Read_Via_Cache_Need_Lock,
    [ROM_API_INDEX_XIP_SFlash_State_Restore]               = (uint32_t)XIP_SFlash_State_Restore,
    [ROM_API_INDEX_XIP_SFlash_State_Save]                  = (uint32_t)XIP_SFlash_State_Save,
    [ROM_API_INDEX_XIP_SFlash_Write_Need_Lock]             = (uint32_t)XIP_SFlash_Write_Need_Lock,
    [ROM_API_INDEX_XIP_SFlash_Opt_Enter]                   = (uint32_t)XIP_SFlash_Opt_Enter,
    [ROM_API_INDEX_XIP_SFlash_Opt_Exit]                    = (uint32_t)XIP_SFlash_Opt_Exit,

    [ROM_API_INDEX_MD_Clr_GPIO_IntStatus]                  = (uint32_t)MD_Clr_GPIO_IntStatus,
    [ROM_API_INDEX_MD_Embedded_Flash_Pad_Enable]           = (uint32_t)MD_Embedded_Flash_Pad_Enable,
    [ROM_API_INDEX_MD_GPIO_Clr]                            = (uint32_t)MD_GPIO_Clr,
    [ROM_API_INDEX_MD_GPIO_Init]                           = (uint32_t)MD_GPIO_Init,
    [ROM_API_INDEX_MD_GPIO_Input_Disable]                  = (uint32_t)MD_GPIO_Input_Disable,
    [ROM_API_INDEX_MD_GPIO_Input_Enable]                   = (uint32_t)MD_GPIO_Input_Enable,
    [ROM_API_INDEX_MD_GPIO_IntMask]                        = (uint32_t)MD_GPIO_IntMask,
    [ROM_API_INDEX_MD_GPIO_Int_Init]                       = (uint32_t)MD_GPIO_Int_Init,
    [ROM_API_INDEX_MD_GPIO_Output_Disable]                 = (uint32_t)MD_GPIO_Output_Disable,
    [ROM_API_INDEX_MD_GPIO_Output_Enable]                  = (uint32_t)MD_GPIO_Output_Enable,
    [ROM_API_INDEX_MD_GPIO_Set]                            = (uint32_t)MD_GPIO_Set,
    [ROM_API_INDEX_MD_GPIO_Set_HZ]                         = (uint32_t)MD_GPIO_Set_HZ,
    [ROM_API_INDEX_MD_GPIO_Write]                          = (uint32_t)MD_GPIO_Write,
    [ROM_API_INDEX_MD_Get_GPIO_IntStatus]                  = (uint32_t)MD_Get_GPIO_IntStatus,
    [ROM_API_INDEX_MD_GPIO_Read]                           = (uint32_t)MD_GPIO_Read,
    [ROM_API_INDEX_MD_GPIO_Get_Fun]                        = (uint32_t)MD_GPIO_Get_Fun,

    [ROM_API_INDEX_FUNC_EMPTY_START ... ROM_API_INDEX_FUNC_EMPTY_END] = 0xdeedbeef,
};


/*@} end of group ROMDRIVER_Global_Variables */

/** @defgroup ROMDRIVER_Private_FunctionDeclaration
 *  @{
 */

/*@} end of group ROMDRIVER_Private_FunctionDeclaration */

/** @defgroup ROMDRIVER_Private_Functions
 *  @{
 */

/*@} end of group ROMDRIVER_Private_Functions */

/** @defgroup ROMDRIVER_Public_Functions
 *  @{
 */

/*@} end of group ROMDRIVER_Public_Functions */

/*@} end of group ROMDRIVER_COMMON */

/*@} end of group BL616_Periph_Driver */


