# RT-Thread building script for component

from building import *
cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('arch', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
