from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

# remove no need file.
if GetDepend('RT_USING_LWIP') == False:
    SrcRemove(src, 'sam7x_emac.c')
if GetDepend('RT_USING_DFS') == False:
    SrcRemove(src, 'sd.c')

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
