from building import *
Import('rtconfig')

src   = Glob('*.c')
group = []

CPPDEFINES = ['RT_USING_ARM_LIBC']

if rtconfig.PLATFORM == 'armcc' or rtconfig.PLATFORM == 'armclang':
    group = DefineGroup('libc', src, depend = ['RT_USING_LIBC'], CPPDEFINES = CPPDEFINES)

Return('group')
