# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]
objs    = []

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
