Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']
    
if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_usart.c']
    
if GetDepend(['RT_USING_SPI']):
    src += ['drv_spi.c']

if GetDepend(['RT_USING_QSPI']):
    src += ['drv_qspi.c'] 

if GetDepend(['RT_USING_USB_DEVICE']):
    src += ['drv_usb.c']
    
if GetDepend(['RT_USING_SDCARD']):
    src += ['drv_sdcard.c']
    
if GetDepend(['RT_USING_I2C', 'RT_USING_I2C_BITOPS']):
    src += ['drv_soft_i2c.c']

if GetDepend(['RT_USING_WDT']):
    src += ['drv_iwg.c']

if GetDepend('RT_USING_LWIP'):
    src += ['drv_emac.c']

src += ['drv_common.c']

path = [cwd]
path +=[cwd + '/config']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
