import os
import rtconfig
from building import *

Import('SDK_LIB')

objs = []
cwd = GetCurrentDir()
list = os.listdir(cwd)

# add general drivers
src = Split('''
board.c
''')

if GetDepend(['BSP_USING_SPI3_SAMPLE']):
    src += Glob('ports/spi_sample.c')

if GetDepend(['BSP_USING_RW007']):
    src += Glob('ports/drv_rw007.c')

if GetDepend(['BSP_USING_SLIDER']):
    src += Glob('ports/slider_sample.c')

path = [cwd]
path += [cwd + '/ports']

startup_path_prefix = SDK_LIB
Tool_path = None
index = 'Infineon_mtb-pdl-cat1'

for filename in os.listdir(startup_path_prefix):
    if index in filename:
        Tool_path = os.path.join(startup_path_prefix, filename)

if rtconfig.PLATFORM in ['gcc']:
    src += [Tool_path +
            '/drivers/source/TOOLCHAIN_GCC_ARM/cy_syslib_ext.S']
elif rtconfig.PLATFORM in ['armclang']:
    src += [Tool_path +
            '/drivers/source/TOOLCHAIN_ARM/cy_syslib_ext.S']

CPPDEFINES = ['CY8C6244LQI_S4D92', 'CORE_NAME_CM0P_0', 'CORE_NAME_CM4_0', 'CY_USING_PREBUILT_CM0P_IMAGE', 'CY_USING_HAL', 'COMPONENT_CAT1A', 'COMPONENT_CAT1', 'COMPONENT_BSP_DESIGN_MODUS']
group = DefineGroup('Drivers', src, depend=[''], CPPPATH=path, CPPDEFINES=CPPDEFINES)

Return('group')
