import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
''')


path =  [cwd]

startup_path_prefix = SDK_LIB

# src += [startup_path_prefix + '/HAL_Drivers/drv_sci.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)
Return('group')
