include $(SDK_ROOT)/mk/common.mk


SOURCES = \
	src/abort_handler.c \
	src/arm_abort.S \
	src/armv7_cache.c \
	src/ccm_pll.c \
	src/cortexA9.s \
	src/gic.c \
	src/interrupt.c \
	src/mmu.c \
	src/startup.S \
	src/vectors.S


include $(SDK_ROOT)/mk/targets.mk
