subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/uvc/Include/
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/uvc/drv_webcam/
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/uvc/drv_webcam/dev_cfg/
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/uvc/drv_webcam/webcam_core/
subdir-ccflags-y += -I$(srctree)/include/melis/misc/

obj-y += drv_webcam.o
obj-y += webcam_core/dev_webcam.o
obj-y += webcam_core/webcam_linklist_manager.o
obj-y += dev_cfg/webcam_dev.o