Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split("""
start_gcc.S
dm365.c
dma.c
findbit.S
interrupt.c
psc.c
reset.c
system_clock.c
trap.c
""")

# The set of source files associated with this SConscript file.
path = [cwd]

group = DefineGroup('Startup', src, depend = [''], CPPPATH = path)

Return('group')
