# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('GPIO', src, depend = [], CPPPATH = CPPPATH)

Return('group')
