import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
''')

path =  [cwd]

startup_path_prefix = SDK_LIB

if rtconfig.PLATFORM in ['gcc']:
    src += [startup_path_prefix + '/N32WB452_Firmware_Library/CMSIS/device/startup/startup_n32wb452_gcc.s']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += [startup_path_prefix + '/N32WB452_Firmware_Library/CMSIS/device/startup/startup_n32wb452.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += [startup_path_prefix + '/N32WB452_Firmware_Library/CMSIS/device/startup/startup_n32wb452_EWARM.s']

CPPDEFINES = ['N32WB452']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
