# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Split('''
fttype1.c
ftbitmap.c
ftbase.c
ftbbox.c
ftfstype.c
ftglyph.c
ftinit.c
ftlcdfil.c
ftmm.c
ftpatent.c
''')
CPPPATH = [cwd]

group = DefineGroup('freetype', src, depend = ['RTGUI_USING_TTF'], CPPPATH = CPPPATH)

Return('group')
