# RT-Thread building script for FreeType

from building import *

cwd = GetCurrentDir()
src = Split('''
fttype1.c
ftbitmap.c
ftbase.c
ftbbox.c
ftfstype.c
ftglyph.c
ftinit.c
ftlcdfil.c
ftmm.c
ftpatent.c
''')
CPPPATH = [cwd]

group = DefineGroup('FreeType', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
