# RT-Thread building script for component

Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
SoC_Common = 'SoC/gd32vf103/Common'
SoC_Board = 'SoC/gd32vf103/Board/gd32vf103v_rvstar'

src = Glob(SoC_Common + '/Source/*.c')
src += Glob(SoC_Common + '/Source/Drivers/*.c')
src += Glob(SoC_Common + '/Source/Drivers/Usb/*.c')
src += Glob(SoC_Common + '/Source/Stubs/*.c')
src += Glob(SoC_Common + '/Source/GCC/*.S')

src += Glob(SoC_Board + '/Source/*.c')

CPPPATH = [ cwd + '/NMSIS/Core/Include',
            cwd + '/NMSIS/DSP/Include',
            cwd + '/NMSIS/NN/Include',
            cwd + '/', SoC_Common + '/Include',
            cwd + '/', SoC_Common + '/Include/Usb',
            cwd + '/', SoC_Common + '/Source/Stubs/',
            cwd + '/', SoC_Board + '/Include']

CPPDEFINES = ['-DDOWNLOAD_MODE=DOWNLOAD_MODE_FLASHXIP', '-DRTOS_RTTHREAD', '-DNUCLEI_BANNER=0']

group = DefineGroup('nuclei_sdk', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
