from building import *

cwd = GetCurrentDir()
src = Glob('*.c') #+ Glob('iomux/*.c')
# src = []

CPPPATH = [cwd]

objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for item in os.listdir(cwd):
    sconsfile = os.path.join(cwd, item, 'SConscript')
    if os.path.isfile(sconsfile):
        objs += SConscript(sconsfile)

Return('objs')
