from building import *

src	= Glob('*.c')
cwd = GetCurrentDir()

CPPPATH = [cwd]
CPPDEFINES = ['RT_USING_ARM_LIBC']

group = DefineGroup('libc', src, depend = ['RT_USING_LIBC'], 
	CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
