from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]
group   = []

group = DefineGroup('Utilities', src, depend = ['RT_USING_ADT_AVL'], CPPPATH = CPPPATH)
Return('group')
