Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

if rtconfig.CROSS_TOOL == 'keil':
    LINKFLAGS  = '--keep=*(.boot_hdr.ivt)'
    LINKFLAGS += '--keep=*(.boot_hdr.boot_data)'
    LINKFLAGS += '--keep=*(.boot_hdr.dcd_data)'
    LINKFLAGS += '--keep=*(.boot_hdr.conf)'
else:
    LINKFLAGS = ''

group = DefineGroup('xip', src, depend = [''], CPPPATH = CPPPATH, LINKFLAGS = LINKFLAGS) 
Return('group')
