from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src =  ['uart.c']
src +=  ['dw_uart_ll.c']

group = DefineGroup('startup', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
