from building import *

src = Split("""
tc_comm.c
thread_static.c
thread_dynamic.c
thread_priority.c
thread_same_priority.c
thread_static_simple.c
thread_dynamic_simple.c
thread_delete.c
thread_detach.c
thread_yield.c
thread_suspend.c
thread_resume.c
semaphore_static.c
semaphore_dynamic.c
semaphore_priority.c
semaphore_buffer_worker.c
semaphore_producer_consumer.c
mutex_simple.c
mutex_priority.c
event_simple.c
mbox_simple.c
mbox_send_wait.c
messageq_simple.c
timer_static.c
timer_dynamic.c
timer_stop_self.c
timer_control.c
timer_timeout.c
heap_malloc.c
heap_realloc.c
memp_simple.c
tc_sample.c
""")

group = DefineGroup('Examples', src,
                    depend = ['RT_USING_TC'],
                    CPPPATH=[GetCurrentDir()])

Return('group')
