Import('env')

src_local = Split("""
tc_comm.c
thread_static.c
thread_dynamic.c
thread_priority.c
thread_same_priority.c
thread_static_simple.c
thread_dynamic_simple.c
thread_delete.c
thread_detach.c
thread_yield.c
thread_suspend.c
thread_resume.c
semaphore_static.c
semaphore_dynamic.c
semaphore_priority.c
semaphore_buffer_worker.c
heap_malloc.c
heap_realloc.c
""")

# The set of source files associated with this SConscript file.
obj = env.Object(src_local)
env.Append(CPPDEFINES='RT_USING_TC')

Return('obj')
