# RT-Thread building script for component

Import('rtconfig')
from building import *

cwd = GetCurrentDir()



src = Split('''
chip_common/fpu_init.c
chip_common/iap.c
chip_common/ring_buffer.c
chip_common/rtc_ut.c

chip_5410x/chip_5410x.c
chip_5410x/clock_5410x.c
chip_5410x/crc_5410x.c
chip_5410x/fifo_5410x.c
chip_5410x/gpiogroup_5410x.c
chip_5410x/gpio_5410x.c
chip_5410x/hw_adc.c
chip_5410x/hw_dmaaltd.c
chip_5410x/hw_dmaaltd_rom_api.c
chip_5410x/hw_i2cmd.c
chip_5410x/hw_i2cmd_rom_api.c
chip_5410x/hw_i2cmond.c
chip_5410x/hw_i2cmond_rom_api.c
chip_5410x/hw_i2csd.c
chip_5410x/hw_i2csd_rom_api.c
chip_5410x/hw_spimd.c
chip_5410x/hw_spimd_rom_api.c
chip_5410x/hw_spisd.c
chip_5410x/hw_spisd_rom_api.c
chip_5410x/hw_uart.c
chip_5410x/iocon_5410x.c
chip_5410x/pinint_5410x.c
chip_5410x/pll_5410x.c
chip_5410x/ritimer_5410x.c
chip_5410x/romapi_adc.c
chip_5410x/romapi_dma.c
chip_5410x/romapi_i2cm.c
chip_5410x/romapi_i2cmon.c
chip_5410x/romapi_i2cs.c
chip_5410x/romapi_spim.c
chip_5410x/romapi_spis.c
chip_5410x/romapi_uart.c
chip_5410x/rtc_5410x.c
chip_5410x/sct_5410x.c
chip_5410x/sct_pwm_5410x.c
chip_5410x/stopwatch_5410x.c
chip_5410x/syscon_5410x.c
chip_5410x/sysinit_5410x.c
chip_5410x/timer_5410x.c
chip_5410x/utick_5410x.c
chip_5410x/wwdt_5410x.c
''')


#LIBS = [cwd + '/chip_5410x/power_lib/keil/lib_power']

#lpc_chip\chip_5410x\power_lib\lpcxpresso
# add for startup script
if rtconfig.PLATFORM in ['gcc']:
    LIBPATH = [cwd + '/chip_5410x/power_lib/lpcxpresso']
    LIBS = ['libpower']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    LIBPATH = [cwd + '/chip_5410x/power_lib/keil']
    LIBS = ['lib_power']

CPPPATH = [cwd + '/chip_common',cwd + '/chip_5410x',cwd + '/chip_5410x/config']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH,LIBS = LIBS,LIBPATH=LIBPATH)

Return('group')
