from building import *

cwd = GetCurrentDir()
src = []

if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_uart.c']

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']

if GetDepend(['RT_USING_ADC']):
    src += ['drv_adc.c']

if GetDepend(['RT_USING_DAC']):
    src += ['drv_dac.c']

if GetDepend(['RT_USING_CAN']):
    src += ['drv_can.c']

if GetDepend(['RT_USING_HWTIMER']):
    src += ['drv_hwtimer.c']

if GetDepend(['RT_USING_I2C']):
    src += ['drv_soft_i2c.c']

if GetDepend(['RT_USING_PWM']):
    src += ['drv_pwm.c']

if GetDepend(['RT_USING_RTC']):
    src += ['drv_rtc.c']

if GetDepend(['RT_USING_SPI']):
    src += ['drv_spi.c']

if GetDepend(['RT_USING_WDT']):
    src += ['drv_wdt.c']

if GetDepend(['RT_USING_HWCRYPTO']):
    src += ['drv_crypto.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['drv_sdio.c']

if GetDepend(['BSP_USING_SDRAM']):
    src += ['drv_sdram.c']

if GetDepend(['BSP_USING_RGB_LCD']):
    src += ['drv_rgb_lcd.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = [cwd])

Return('group')
