Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')
src	= Glob('*.c')
drvinc=os.path.abspath('%s/../../../components/drivers/include'%(cwd))
CPPPATH = [cwd, str(Dir('#')),drvinc]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
