Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'app')

src = Glob('./src/*.c')

path = [cwd + '/inc',
    cwd + '/..',
    ]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
