from building import *

group = []

if not GetDepend(['RT_TEE_OPTEE']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src = ['optee.c']

if GetDepend(['RT_TEE_OPTEE_EXAMPLES']):
    src += ['optee_examples.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
