from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, cwd + '/../include']
src = Glob('*.c')
if GetDepend('RT_USING_OFW') == False:
    SrcRemove(src, ['ofw.c'])

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_PHY'], CPPPATH = CPPPATH)

Return('group')
