from building import *

cwd     = GetCurrentDir()

src = ['phy.c']

if GetDepend(['RT_USING_DM']):
    src += ['phy_dm.c']

CPPPATH = [cwd + '/../include']
group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_PHY'], CPPPATH = CPPPATH)

Return('group')
