import copy
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src = Glob('source/*.c')
src += Glob('source/*.S')

CPPPATH = [cwd + '/include/']

group = DefineGroup('HALCoGen', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
