Import('env')
Import('projects')
Import('RTT_ROOT')
Import('rtconfig')

# group definitions
group = {}
group['name'] = 'Startup'
group['CCFLAGS'] = ''
group['CPPPATH'] = [RTT_ROOT + '/bsp/jz47xx']
group['CPPDEFINES'] = []
group['LINKFLAGS'] = ''

src_bsp   = ['application.c', 'startup.c', 'board.c']
src_drv   = ['uart.c']

group['src'] = File(src_bsp + src_drv)

# add group to project list
projects.append(group)

env.Append(CCFLAGS = group['CCFLAGS'])
env.Append(CPPPATH = group['CPPPATH'])
env.Append(CPPDEFINES = group['CPPDEFINES'])
env.Append(LINKFLAGS = group['LINKFLAGS'])

obj = env.Object(group['src'])

Return('obj')
