from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]


if GetDepend('RT_USING_RTGUI') == False:
    SrcRemove(src, 'touch.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = group + objs

Return('group')
