import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd]
src = Glob('board.c')

if not GetDepend('RT_USING_NANO'):
    src += Glob(cwd + 'drv_uart.c')

objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
