from building import *

cwd = GetCurrentDir()
group = []
src = []
CPPPATH =[]

src += Glob(cwd + '/ui/*.c')
CPPPATH += [cwd+'/ui']

if GetConfigValue('PKG_LVGL_VER_NUM') == '0x08020':
    src += Glob(cwd + '/legacy/*.c')
    CPPPATH += [cwd+'/legacy']

group = group + DefineGroup('LVGL-GUIGuider', src, depend = ['BSP_USING_LVGL', 'BSP_USING_NXP_GUIGUIDER'], CPPPATH = CPPPATH)

Return('group')
