Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = Glob('*.c')

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
