Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the startup files

src = Split('''
   startup.c
   trap.c
''')

if rtconfig.PLATFORM == 'gcc':
    src += [os.path.join('toolchains', 'gcc', 'start.S')]
    src += [os.path.join('toolchains', 'gcc', 'port_gcc.S')]

CPPPATH = [cwd]
CPPDEFINES=['D45', rtconfig.CHIP_NAME]

group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
