import os
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
objs = []
for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
