from building import *

group = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = []

if GetDepend(['RT_USING_ADC']):
    src += ['adc-rockchip_saradc.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
