# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []

CPPPATH = [cwd]
CPPDEFINES = []

src += Split("""
    std/startup/start.S
    std/startup/vector.S
    std/startup/riscv_fpu.S
    std/startup/start_load.c
    std/startup/system_bl616.c
    std/startup/interrupt.c
""")

src += Split("""
    std/src/bl616_common.c
    std/src/bl616_ef_cfg.c
    std/src/bl616_sdh.c
    std/src/bl616_tzc_sec.c
    std/src/bl616_psram.c
    std/src/bl616_aon.c
    std/src/bl616_pm.c
""")
src += ['std/port/bl616_clock.c']

CPPPATH += [cwd + r'/std/include',
        cwd + r'/std/include/hardware']

if GetDepend('BSP_USING_ROMAPI'):
    src += Split("""
        std/src/bl616_romapi_e907.c
        std/src/bl616_romapi_patch.c
    """)
    CPPDEFINES += ['BFLB_USE_ROM_DRIVER']
else:
    src += Split("""
        std/src/bl616_clock.c
        std/src/bl616_glb_gpio.c
        std/src/bl616_glb.c
        std/src/bl616_hbn.c
        std/src/bl616_l1c.c
        std/src/bl616_pds.c
    """)

CPPDEFINES += ['CONFIG_IRQ_NUM=80', 'BFLB_USE_HAL_DRIVER', 'BL616', 'default_interrupt_handler=SW_handler']
LOCAL_CFLAGS = ' -DARCH_RISCV'
group = DefineGroup('bl616', src, depend = ['BSP_USING_BL61X'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LOCAL_CFLAGS = LOCAL_CFLAGS)

Return('group')
