from building import *

cwd     = GetCurrentDir()
src     = Split('''
log_trace.c
''')
CPPPATH = [cwd]

if GetDepend('LOG_TRACE_USING_MEMLOG'):
    src += ['memlog.c']

if GetDepend('RT_USING_DFS'):
    src += ['log_file.c']

group = DefineGroup('Utilities', src, depend = ['RT_USING_LOGTRACE'], CPPPATH = CPPPATH)

Return('group')
