from building import *

cwd        = GetCurrentDir()
src        = []
inc        = [cwd]

# if GetDepend('RT_USING_POSIX_IPC_SYSTEM_V'):
#     src += Glob('system-v/*.c')
#     inc += [cwd + '/system-v']

if GetDepend('RT_USING_POSIX_MESSAGE_QUEUE'):
    src += ['mqueue.c']

if GetDepend('RT_USING_POSIX_MESSAGE_SEMAPHORE'):
    src += ['semaphore.c']

group = DefineGroup('POSIX', src, depend = [], CPPPATH = inc)

Return('group')
