# SConscript for sensor framework 

from building import *

cwd = GetCurrentDir()
src = ['sensor.c']
CPPPATH = [cwd, cwd + '/../include']

if GetDepend('RT_USING_SENSOR_TEST'):
    src += ['sensor_test.c'];

group = DefineGroup('Sensors', src, depend = ['RT_USING_SENSOR', 'RT_USING_DEVICE'], CPPPATH = CPPPATH)

Return('group')
