# SConscript for sensor framework 

from building import *

cwd = GetCurrentDir()
src = ['sensor.cpp']
CPPPATH = [cwd, cwd + '/../include']

if GetDepend('SENSOR_USING_MPU6050'):
    src += ['mpu6050_sensor.cpp'];

if GetDepend('SENSOR_USING_BMI055'):
    src += ['bmi055_sensor.cpp']

group = DefineGroup('Sensors', src, depend = ['RT_USING_SENSOR', 'RT_USING_DEVICE'], CPPPATH = CPPPATH)

Return('group')
