subdir-ccflags-y +=     -I$(srctree)/ekernel/drivers/hal/source/usb/storage/include
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/core
obj-y += mscProtocol.o
obj-y += mscTransport.o
obj-y += mscTransport_i.o
obj-y += usb_msc.o