# Audio Platform Common
obj-y += core/

# Sunxi Internal Codecs
obj-y += codecs/

# Sunxi Daudio
obj-y += platform/

# Audio Utils
obj-$(CONFIG_COMPONENTS_AW_ALSA_LIB) += component/

# Soundcards Register Select
obj-y += card_default.o

