devices.soft_i2c:
  kconfig:
    - CONFIG_RT_USING_I2C=y
    - CONFIG_RT_USING_SOFT_I2C=y
    - CONFIG_RT_USING_SOFT_I2C0=y
    - CONFIG_RT_SOFT_I2C0_SCL_PIN=0x19
    - CONFIG_RT_SOFT_I2C0_SDA_PIN=0x18
    - CONFIG_RT_SOFT_I2C0_BUS_NAME="swi2c0"
    - CONFIG_RT_USING_SOFT_I2C1=y
    - CONFIG_RT_SOFT_I2C1_SCL_PIN=0x0B
    - CONFIG_RT_SOFT_I2C1_SDA_PIN=0x0A
    - CONFIG_RT_SOFT_I2C1_BUS_NAME="swi2c1"
