Import('RTT_ROOT')
Import('rtconfig')
from building import *

if GetDepend('BSP_USING_QSPIFLASH'):
    cwd = GetCurrentDir()
    src = Glob('*.c')
    CPPPATH = [cwd]

    if rtconfig.PLATFORM in ['armcc', 'armclang']:
        LINKFLAGS  = ' --keep=*(.boot_hdr.ivt)'
        LINKFLAGS += ' --keep=*(.boot_hdr.boot_data)'
        LINKFLAGS += ' --keep=*(.boot_hdr.dcd_data)'
        LINKFLAGS += ' --keep=*(.boot_hdr.conf)'
        LINKFLAGS += ' --predefine="-DXIP_BOOT_HEADER_ENABLE=1"'
    else:
        LINKFLAGS = ''

    group = DefineGroup('xip', src, depend = [''], CPPPATH = CPPPATH, LINKFLAGS = LINKFLAGS)
    Return('group')
