import rtconfig
Import('RTT_ROOT')
from building import *

src_bsp = ['application.c', 'startup.c', 'board.c', 'led.c', 'cpuusage.c']
src_drv = ['adc.c', 'lcd.c', 'key.c']

if GetDepend('RT_USING_RTGUI'):
    src_drv += ['info.c']

src = src_bsp + src_drv
CPPPATH = [GetCurrentDir()]
CPPDEFINES = []
group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
