Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
group = []
CPPPATH = []

if rtconfig.PLATFORM in ['iccarm']:
    print("\nThe current project does not support IAR build\n")
    Return('group')
elif rtconfig.PLATFORM in ['gcc', 'armclang']:
    src += Glob(cwd + '/TARGET_CY8CKIT-062-WIFI-BT/*.c')
    src += Glob(cwd + '/TARGET_CY8CKIT-062-WIFI-BT/COMPONENT_CM4/*.c')
    src += Glob(cwd + '/TARGET_CY8CKIT-062-WIFI-BT/config/GeneratedSource/*.c')

    CPPPATH = [ cwd + '/TARGET_CY8CKIT-062-WIFI-BT',
                cwd + '/TARGET_CY8CKIT-062-WIFI-BT/config/GeneratedSource']
    if rtconfig.PLATFORM in ['gcc']:
        src += [cwd + '/TARGET_CY8CKIT-062-WIFI-BT/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/startup_psoc6_01_cm4.S']
    elif rtconfig.PLATFORM in ['armclang']:
        src += [cwd + '/TARGET_CY8CKIT-062-WIFI-BT/COMPONENT_CM4/TOOLCHAIN_ARM/startup_psoc6_01_cm4.s']

group = DefineGroup('libs', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
