from building import *
import rtconfig
cwd     = GetCurrentDir()
src	= Glob('CMSIS/DeviceSupport/*.c')
CPPPATH = [cwd + '/CMSIS/CoreSupport', cwd + '/CMSIS/DeviceSupport', cwd + '/SWM320_StdPeriph_Driver']

src += Glob('SWM320_StdPeriph_Driver/*.c')

if rtconfig.CROSS_TOOL == 'gcc':
    src += ['CMSIS/DeviceSupport/startup/gcc/startup_SWM320.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += ['CMSIS/DeviceSupport/startup/arm/startup_SWM320.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += ['CMSIS/DeviceSupport/startup/iar/startup_SWM320.s']
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
