Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'drivers')

# add the general drvers.
src = Split("""
board.c
usart.c
""")

# add Ethernet drvers.
if GetDepend('RT_USING_LED'):
    src += ['led.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
