from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

if GetDepend(['RT_THERMAL_ROCKCHIP_TSADC']):
    src += ['thermal-rockchip_tsadc.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
