import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Glob('VangoV85xx_standard_peripheral/Source/*.c')
src += [cwd + '/CMSIS/Vango/V85xx/Source/system_target.c']
src += [cwd + '/CMSIS/Vango/V85xx/Source/lib_CodeRAM.c']
src += [cwd + '/CMSIS/Vango/V85xx/Source/lib_cortex.c']
src += [cwd + '/CMSIS/Vango/V85xx/Source/lib_LoadNVR.c']

#add for startup script
if rtconfig.PLATFORM in ['gcc']:
    src += [cwd + '/CMSIS/Vango/V85xx/Source/GCC/startup_target.S']
if rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += [cwd + '/CMSIS/Vango/V85xx/Source/Keil5/startup_target.S']

path = [
    cwd + '/CMSIS/Vango/V85xx/Include',
    cwd + '/CMSIS',
    cwd + '/VangoV85xx_standard_peripheral/Include',]

CPPDEFINES = ['USE_STDPERIPH_DRIVER', 'V85xx','USE_TARGET_DRIVER']

group = DefineGroup('Vango_Lib', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
