import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
cmsis/cm4/device_support/system_at32a403a.c
drivers/src/at32a403a_acc.c
drivers/src/at32a403a_adc.c
drivers/src/at32a403a_bpr.c
drivers/src/at32a403a_can.c
drivers/src/at32a403a_crc.c
drivers/src/at32a403a_crm.c
drivers/src/at32a403a_dac.c
drivers/src/at32a403a_debug.c
drivers/src/at32a403a_dma.c
drivers/src/at32a403a_emac.c
drivers/src/at32a403a_exint.c
drivers/src/at32a403a_flash.c
drivers/src/at32a403a_gpio.c
drivers/src/at32a403a_i2c.c
drivers/src/at32a403a_misc.c
drivers/src/at32a403a_pwc.c
drivers/src/at32a403a_rtc.c
drivers/src/at32a403a_sdio.c
drivers/src/at32a403a_spi.c
drivers/src/at32a403a_tmr.c
drivers/src/at32a403a_usart.c
drivers/src/at32a403a_usb.c
drivers/src/at32a403a_wdt.c
drivers/src/at32a403a_wwdt.c
drivers/src/at32a403a_xmc.c
""")

path = [
    cwd + '/cmsis/cm4/device_support',
    cwd + '/cmsis/cm4/core_support',
    cwd + '/drivers/inc',]

CPPDEFINES = ['USE_STDPERIPH_DRIVER']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
