from building import *
import os

cwd = GetCurrentDir()

src = Split('''
main.c
''')

if GetDepend(['BSP_USING_SPI_LCD']):
    src += ['lcd_sample.c']

if GetDepend(['PKG_USING_NRF24L01']):
    src += ['nrf24l01_init.c']

CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
