from building import *
import os

cwd = GetCurrentDir()

src = ['main.c']

if GetDepend(['PKG_USING_NRF24L01']):
    src += ['nrf24l01_init.c']

CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
