# for network related component
import os
Import('RTT_ROOT')

objs = []
list = os.listdir(os.path.join(RTT_ROOT, 'components', 'net'))

for d in list:
    path = os.path.join(RTT_ROOT, 'components', 'net', d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
