# for network related component
import os
Import('RTT_ROOT')
from building import *

objs = []
cwd = GetCurrentDir()
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
