# for network related component
import os
Import('RTT_ROOT')
from building import *

objs = []
cwd = GetCurrentDir()
list = os.listdir(cwd)

# the default version of LWIP is 1.4.1
if not GetDepend('RT_USING_LWIP132') and not GetDepend('RT_USING_LWIP140') and not GetDepend('RT_USING_LWIP_HEAD'):
    AddDepend('RT_USING_LWIP141')

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
