scons.args: &scons
    scons_arg:
      - '--strict'
system.use_nano:
  <<: *scons
  kconfig:
    CONFIG_RT_USING_NANO=y
devices.uart:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_GPIO=y
    - CONFIG_BSP_USING_UART=y
    - CONFIG_USING_SERIAL=y
devices.servo:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_SERVO=y
