scons.args: &scons
    scons_arg:
      - '--strict'



devices.uart:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_GPIO=y
    - CONFIG_BSP_USING_UART=y
    - CONFIG_USING_SERIAL=y
devices.servo:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_SERVO=y
devices.pulse_encoder:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_PULSE_ENCODER=y
    - CONFIG_BSP_USING_PULSE_ENCODER1=y
