scons.args: &scons
    scons_arg:
      - '--strict'

devices.uart:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_GPIO=y
    - CONFIG_BSP_USING_UART=y
    - CONFIG_USING_SERIAL=y
devices.servo:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_SERVO=y
devices.pulse_encoder:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_PULSE_ENCODER=y
devices.adc:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_ADC=y
devices.i2c1:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_I2C1=y
devices.pwm2:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_PWM=y
    - CONFIG_BSP_USING_PWM2=y
devices.pwm3:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_PWM=y
    - CONFIG_BSP_USING_PWM3=y
devices.pwm4:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_PWM=y
    - CONFIG_BSP_USING_PWM4=y
