import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src  = Glob('*.cpp')

CPPPATH = [cwd]

group = DefineGroup('utestcases', src, depend = [], CPPPATH = CPPPATH)

Return('group')
