Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = Glob('*.c')

# add for startup script
if rtconfig.PLATFORM in ['gcc']:
    src = src + ['start_gcc.S']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src = src + ['start_rvds.S']
elif rtconfig.PLATFORM in ['iccarm']:
    src = src + ['start_iar.S']

CPPPATH = [GetCurrentDir()]

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH, LIBRARY = '')

Return('group')
