Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPDEFINES = []
if GetDepend('BOARD_GK7102C_EVB'):
    CPPDEFINES += ['-DGK7102C_EVB']
elif GetDepend('BOARD_GK7101_EVB'):
    CPPDEFINES += ['-DGK7101_EVB']
elif GetDepend('BOARD_GK7101S_EVB'):
    CPPDEFINES += ['-DGK7101S_EVB']
elif GetDepend('BOARD_GK7102_HZD_JXH42'):
    CPPDEFINES += ['-DDUSE_BOARD_HZD']
elif GetDepend('BOARD_GK7102S_HZD_JXH42'):
    CPPDEFINES += ['-DGK7102S_HZD_JXH42']
elif GetDepend('BOARD_GK7102C_JH'):
    CPPDEFINES += ['-DGK7102C_JH']
          
group = DefineGroup('platform', src, depend = [''], CPPDEFINES = CPPDEFINES)

Return('group')
