from building import *

cwd     = GetCurrentDir()

src = Split('''
main.c
''')

if GetDepend(['BSP_USING_ON_CHIP_FS']):
    src += ['mnt.c']


CPPPATH = [str(Dir('#')), cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')