from building import *
import os

# The set of source files associated with this SConscript file.
src = Glob('src/*.c') + Glob('src/*.cpp')
cwd = GetCurrentDir()
CPPPATH = [cwd + "/include"]

if not GetDepend('RT_USING_SMART'):
    SrcRemove(src, ['src/dfs_file_mmap.c'])

group = DefineGroup('Filesystem', src, depend = ['RT_USING_DFS', 'RT_USING_DFS_V2'], CPPPATH = CPPPATH)

if GetDepend('RT_USING_DFS') and GetDepend('RT_USING_DFS_V2'):
    # search in the file system implementation
    list = os.listdir(cwd)

    for item in list:
        if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
            group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
