Import('RTT_ROOT')
Import('rtconfig')
from building import *

if GetDepend('BSP_USING_QSPIFLASH'):
    cwd = GetCurrentDir()
    src = Glob('*.c')
    CPPPATH = [cwd]
    LINKFLAGS = ''

    if rtconfig.PLATFORM in ['armcc', 'armclang']:
        LINKFLAGS += ' --keep=*(.boot_hdr.container)'
        # LINKFLAGS += ' --keep=*(.boot_hdr.xmcd_data)'
        LINKFLAGS += ' --keep=*(.boot_hdr.conf)'
        LINKFLAGS += ' --entry=Reset_Handler '        
        LINKFLAGS += ' --predefine="-DXIP_BOOT_HEADER_ENABLE=1"'
        LINKFLAGS += ' --predefine="-DXIP_EXTERNAL_FLASH=1"'

    group = DefineGroup('xip', src, depend = [''], CPPPATH = CPPPATH, LINKFLAGS = LINKFLAGS)
    Return('group')
