scons.args: &scons
    scons_arg:
      - '--strict'
# ------ kernel CI ------

# ------ online-packages CI ------

# ------ peripheral CI ------
peripheral.uartv2:
    kconfig:
      - CONFIG_RT_USING_SERIAL_V1=n
      - CONFIG_RT_USING_SERIAL_V2=y
      - CONFIG_RT_SERIAL_USING_DMA=y
      - CONFIG_BSP_USART1_AFIO_MODE_PA9_PA10=y
      - CONFIG_BSP_UART1_RX_BUFSIZE=1024
      - CONFIG_BSP_UART1_TX_BUFSIZE=1024
      - CONFIG_BSP_USART2_AFIO_MODE_PD5_PD6=y
      - CONFIG_BSP_UART2_RX_USING_DMA=y
      - CONFIG_BSP_UART2_TX_USING_DMA=y
      - CONFIG_BSP_UART2_RX_BUFSIZE=1024
      - CONFIG_BSP_UART2_TX_BUFSIZE=1024


