CONFIG_RT_USING_SERIAL_V1=n
CONFIG_RT_USING_SERIAL_V2=y
CONFIG_RT_SERIAL_USING_DMA=y
CONFIG_BSP_USART1_AFIO_MODE_PA9_PA10=y
CONFIG_BSP_UART1_RX_BUFSIZE=1024
CONFIG_BSP_UART1_TX_BUFSIZE=1024
CONFIG_BSP_USING_USART2=y
CONFIG_BSP_USART2_AFIO_MODE_PD5_PD6=y
CONFIG_BSP_UART2_RX_USING_DMA=y
CONFIG_BSP_UART2_TX_USING_DMA=y
CONFIG_BSP_UART2_RX_BUFSIZE=1024
CONFIG_BSP_UART2_TX_BUFSIZE=1024
CONFIG_BSP_USING_USART3=y
CONFIG_BSP_USART3_AFIO_MODE_PB10_PB11=y
CONFIG_BSP_UART3_RX_USING_DMA=y
CONFIG_BSP_UART3_TX_USING_DMA=y
CONFIG_BSP_UART3_RX_BUFSIZE=1024
CONFIG_BSP_UART3_TX_BUFSIZE=1024
CONFIG_BSP_USING_UART4=y
CONFIG_BSP_UART4_AFIO_MODE_PC10_PC11=y
CONFIG_BSP_UART4_RX_USING_DMA=y
CONFIG_BSP_UART4_TX_USING_DMA=y
CONFIG_BSP_UART4_RX_BUFSIZE=1024
CONFIG_BSP_UART4_TX_BUFSIZE=1024
CONFIG_BSP_USING_UART5=y
CONFIG_BSP_UART5_AFIO_MODE_PC12_PD2=y
CONFIG_BSP_UART5_RX_USING_DMA=y
CONFIG_BSP_UART5_TX_USING_DMA=y
CONFIG_BSP_UART5_RX_BUFSIZE=4096
CONFIG_BSP_UART5_TX_BUFSIZE=4096
CONFIG_BSP_USING_UART6=y
CONFIG_BSP_UART6_AFIO_MODE_PB0_PB1=y
CONFIG_BSP_UART6_RX_USING_DMA=y
CONFIG_BSP_UART6_TX_USING_DMA=y
CONFIG_BSP_UART6_RX_BUFSIZE=1024
CONFIG_BSP_UART6_TX_BUFSIZE=1024
CONFIG_BSP_USING_UART7=y
CONFIG_BSP_UART7_AFIO_MODE_PC4_PC5=y
CONFIG_BSP_UART7_RX_USING_DMA=y
CONFIG_BSP_UART7_TX_USING_DMA=y
CONFIG_BSP_UART7_RX_BUFSIZE=2048
CONFIG_BSP_UART7_TX_BUFSIZE=2048
