from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

if GetDepend(['RT_INPUT_JOYSTICK_RPISENSE']):
    src += ['js-rpisense.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
