import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
cmsis/cm4/device_support/system_at32m412_416.c
drivers/src/at32m412_416_adc.c
drivers/src/at32m412_416_can.c
drivers/src/at32m412_416_cmp.c
drivers/src/at32m412_416_crc.c
drivers/src/at32m412_416_crm.c
drivers/src/at32m412_416_dac.c
drivers/src/at32m412_416_debug.c
drivers/src/at32m412_416_dma.c
drivers/src/at32m412_416_ertc.c
drivers/src/at32m412_416_exint.c
drivers/src/at32m412_416_flash.c
drivers/src/at32m412_416_gpio.c
drivers/src/at32m412_416_i2c.c
drivers/src/at32m412_416_misc.c
drivers/src/at32m412_416_op.c
drivers/src/at32m412_416_pwc.c
drivers/src/at32m412_416_scfg.c
drivers/src/at32m412_416_spi.c
drivers/src/at32m412_416_tmr.c
drivers/src/at32m412_416_usart.c
drivers/src/at32m412_416_wdt.c
drivers/src/at32m412_416_wwdt.c
""")

path = [
    cwd + '/cmsis/cm4/device_support',
    cwd + '/cmsis/cm4/core_support',
    cwd + '/drivers/inc',]

CPPDEFINES = ['USE_STDPERIPH_DRIVER']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
