import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

group = DefineGroup('LVGL-port', src, depend = ['BSP_USING_LVGL'], CPPPATH = [cwd])

for name in os.listdir(cwd):
    if os.path.isfile(os.path.join(cwd, name, 'SConscript')):
        group += SConscript(os.path.join(name, 'SConscript'))

Return('group')
