# RT-Thread building script for component

from building import *

src     = ['unistd.c']
cwd     = GetCurrentDir()
CPPPATH = [cwd]

if GetDepend('RT_USING_POSIX_STDIO'):
    src += ['libc.c']

if GetDepend('RT_USING_POSIX_DELAY'):
    src += ['delay.c']

if GetDepend('RT_USING_POSIX_POLL'):
    src += ['poll.c']

if GetDepend('RT_USING_POSIX_SELECT'):
    src += ['select.c']

if GetDepend('RT_USING_POSIX_MMAP'):
    src += ['mmap.c']

group = DefineGroup('POSIX', src, depend = ['RT_USING_POSIX'], CPPPATH = CPPPATH)

Return('group')
