# RT-Thread building script for component

from building import *

src     = Glob('*.c')
cwd     = GetCurrentDir()
CPPPATH = [cwd]

group = DefineGroup('POSIX', src, depend = ['RT_USING_POSIX'], CPPPATH = CPPPATH)

Return('group')
