# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')

if rtconfig.PLATFORM == 'gcc':
     src += Glob('*_gcc.S')

CPPPATH = [cwd]
ASFLAGS = ''

group = DefineGroup('CPU', src, depend = [''], CPPPATH = CPPPATH, ASFLAGS = ASFLAGS)

Return('group')
