Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
group = []

src = Split("""
lcd_fsa506.c
""")
CPPPATH = [cwd]

if GetDepend('NU_PKG_USING_FSA506_EBI'):
    src += Glob('fsa506_ebi.c')

if GetDepend('NU_PKG_USING_FSA506'):
    group = DefineGroup('nu_pkgs_fsa506', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

