import os
from building import *

objs = []
cwd  = GetCurrentDir()

# add general drivers
src = []
path =  [cwd]

if GetDepend(['BSP_USING_QSPI_FLASH']):
    src += Glob('drv_qspi_flash.c')

if GetDepend(['RT_USING_FAL']):
    src += Glob('qspi_mnt.c')

if GetDepend(['BSP_USING_TOUCH']):
    src += Glob('touch/drv_touch.c')
    path = [cwd + '/touch']

if GetDepend(['BSP_USING_SDCARD']):
    src += Glob('drv_sdcard.c')

if GetDepend(['BSP_USING_QSPI']):
    src += Glob('drv_qspi_flash.c')

if GetDepend(['BSP_USING_LCD']):
    src += Glob('ili9341.c')

CPPDEFINES = ['STM32F429xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
