from building import *
Import('rtconfig')

src   = []
cwd   = GetCurrentDir()
CPPPATH = [cwd]
group = []

if rtconfig.PLATFORM == 'armcc' or\
   rtconfig.PLATFORM == 'armclang' or\
   rtconfig.PLATFORM == 'iar' or\
   rtconfig.PLATFORM == 'cl': # msvc
    group = DefineGroup('Compiler', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
