from building import *
Import('rtconfig')

src   = []
cwd   = GetCurrentDir()
CPPPATH = [cwd]
group = []

if rtconfig.PLATFORM in ['armcc', 'armclang'] or\
   rtconfig.PLATFORM == 'iar' or\
   rtconfig.CROSS_TOOL == 'msvc':
    group = DefineGroup('Compiler', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
