from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('LwIP', src, depend = ['RT_USING_LWIP', 'LWIP_USING_NAT', 'LWIP_USING_IP4INPUT_HOOK'], CPPPATH = CPPPATH)

Return('group')
