import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = ['board.c']
src += ['drv_uart.c']
src += ['drv_virtio.c']

path =  [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)
Return('group')
