from building import *
import os

# The set of source files associated with this SConscript file.
src     = []
cwd     = GetCurrentDir()
CPPPATH = [cwd + "/include"]
group   = []

if GetDepend('RT_USING_DFS') and not GetDepend('RT_USING_DFS_V2'):
    src = ['src/dfs.c', 'src/dfs_file.c', 'src/dfs_fs.c']

    if GetDepend('DFS_USING_POSIX'):
        src += ['src/dfs_posix.c']

    group = DefineGroup('Filesystem', src, depend = ['RT_USING_DFS'], CPPPATH = CPPPATH)

    # search in the file system implementation
    list = os.listdir(cwd)

    for item in list:
        if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
            group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
