
from building import *
import rtconfig

cwd     = GetCurrentDir()

src = []

src     += Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('EasyFlash', src, depend = ['PKG_USING_EASYFLASH'], CPPPATH = CPPPATH)

Return('group')
