from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

if not GetDepend('RT_USING_LWIP'):
    SrcRemove(src, 'drv_eth.c')

if not GetDepend('RT_USING_DFS'):
    SrcRemove(src, 'drv_sdio_sd.c')
    SrcRemove(src, 'drv_spi_flash.c')

if not GetDepend('PKG_USING_GUIENGINE'):
    SrcRemove(src, 'drv_lcd.c')
    SrcRemove(src, 'drv_ft5x06.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
