from building import *
import os

cwd = GetCurrentDir()

src = Glob('*.c')
CPPPATH = [cwd]

CPPDEFINES = ['STM32F4']
objs = []
list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = DefineGroup('LVGL-port', src, depend = ['BSP_USING_LVGL'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('objs')
