from building import *

cwd = GetCurrentDir()

src = Glob('*.c')
CPPPATH = [cwd]

CPPDEFINES = ['STM32F4']

group = DefineGroup('LVGL-port', src, depend = ['BSP_USING_LVGL'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
Return('group')
