from building import *

cwd = GetCurrentDir()
path  = [cwd + '/arch/include']
path += [cwd]

src  = ['arch/sys_arch.c']
src += ['ethernetif.c']

group = DefineGroup('lwIP', src, depend = ['RT_USING_LWIP'], CPPPATH = path)

Return('group')
