Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = []

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']
    
if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_uart.c']

path =  [cwd]
path += [cwd + '/config', 
         cwd + '/CMSIS/Include']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
