from building import *

cwd = GetCurrentDir()
src = []

if GetDepend(['BSP_USING_ARDUINO_ST7789_ADAFRUIT_GFX_DEMO']):
    src += ['ST7789_adafruit_gfx_demo.cpp']
elif GetDepend(['BSP_USING_ARDUINO_ST7789_TFT_ESPI_DEMO']):
    src += ['ST7789_tft_espi_demo.cpp']

group = DefineGroup('RTduino-libraries', src, depend = ['BSP_USING_ARDUINO'])

Return('group')
