from building import *

cwd = GetCurrentDir()
src = []
inc = [cwd]

if GetDepend('RT_USING_ARDUINO_UNO_LAYOUT'):
    src += ['arduino_layout.c']

group = DefineGroup('Arduino', src, depend = ['RT_USING_ARDUINO'], CPPPATH = inc)

Return('group')
