from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
MCUX_Config/clock_config.c
MCUX_Config/pin_mux.c
""")

CPPPATH = [cwd,cwd + '/MCUX_Config',cwd + '/ports']
CPPDEFINES = ['CPU_MIMXRT1189CVM8C_cm7', 'MIMXRT1189_cm7_SERIES', 'FSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1', 'ARM_MATH_CM7']

if rtconfig.PLATFORM in ['gcc']:
    CPPDEFINES += ['__STARTUP_INITIALIZE_RAMFUNCTION']

if rtconfig.PLATFORM in ['armcc', 'armclang']:
    # CPPDEFINES += ['SDK_DEBUGCONSOLE']
    CPPDEFINES += ['NDEBUG']

if rtconfig.PLATFORM in ['iccarm']:
    CPPDEFINES += ['NDEBUG']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
