import os
import sys
import rtconfig
 
if os.getenv('RTT_ROOT'):
    RTT_ROOT = os.getenv('RTT_ROOT')
else:
    RTT_ROOT = os.path.normpath(os.getcwd() + '/../..')

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
from building import *
 
TARGET = 'rtthread-' + rtconfig.ARCH + '.' + rtconfig.TARGET_EXT
 
DefaultEnvironment(tools=[])
env = Environment(tools = ['mingw'],
   AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
   CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
   AR = rtconfig.AR, ARFLAGS = '-rc',
   LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)
 
Export('RTT_ROOT')
Export('rtconfig')
 
# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT)
 
# AVR32 software framework building script
objs = objs + SConscript(RTT_ROOT + '/bsp/avr32uc3b0/SOFTWARE_FRAMEWORK/SConscript', variant_dir='bsp/SOFTWARE_FRAMEWORK', duplicate=0)
 
# make a building
DoBuilding(TARGET, objs)
