import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()
src = []

if GetDepend('USE_MA35D1_SUBM'):
    src += ['Nuvoton/MA35D1/Source/system_ma35d1_subm.c']
    if rtconfig.CROSS_TOOL == 'gcc':
        src = src + ['Nuvoton/MA35D1/Source/GCC/startup_ma35d1_subm.S']
    elif rtconfig.CROSS_TOOL == 'keil':
        src = src + ['Nuvoton/MA35D1/Source/ARM/startup_ma35d1_subm.s']
    elif rtconfig.CROSS_TOOL == 'iar':
        src = src + ['Nuvoton/MA35D1/Source/IAR/startup_ma35d1_subm.s']

path = [cwd + '/Nuvoton/MA35D1/Include',]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
