from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd + '/../include']

if GetDepend(['RT_MBOX_ROCKCHIP']):
    src += ['mailbox-rockchip.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
