# scons.args: &scons
#     scons_arg:
#       - '--strict'

# ------ nano ------
nano:
  kconfig:
    - CONFIG_RT_USING_NANO=y

devices.soft_i2c:
  kconfig:
    - CONFIG_RT_USING_I2C=y
    - CONFIG_RT_USING_SOFT_I2C=y
    - CONFIG_RT_USING_SOFT_I2C1=y
    - CONFIG_RT_SOFT_I2C1_SCL_PIN=22
    - CONFIG_RT_SOFT_I2C1_SDA_PIN=25
    - CONFIG_RT_SOFT_I2C1_BUS_NAME="swi2c1"
