from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd + '/../include']

if GetDepend(['RT_PHYE_ROCKCHIP_NANENG_COMBO']):
    src += ['phye-naneng-combphy.c']

if GetDepend(['RT_PHYE_ROCKCHIP_SNPS_PCIE3']):
    src += ['phye-snps-pcie3.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
