from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd, cwd + '/../drivers', cwd + '/../libraries/inc']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
