# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('*_iar.S')
CPPPATH = [cwd]

group = DefineGroup('libcpu', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
