import rtconfig
from building import *

cwd = GetCurrentDir()

src = Glob('board.c')
src += Glob('CubeMX_Config/Src/STM32F0xx_hal_msp.c')

if GetDepend(['BSP_USING_SPI_FLASH']):
    src += Glob('ports/spi_flash_init.c')

path = [cwd]
path += [cwd + '/CubeMX_Config/Inc']
path += [cwd + '/ports']

if rtconfig.CROSS_TOOL == 'gcc':
    src += [cwd + '/../../libraries/STM32F0xx_HAL/CMSIS/Device/ST/STM32F0xx/Source/Templates/gcc/startup_stm32f030xc.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [cwd + '/../../libraries/STM32F0xx_HAL/CMSIS/Device/ST/STM32F0xx/Source/Templates/arm/startup_stm32f030xc.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += [cwd + '/../../libraries/STM32F0xx_HAL/CMSIS/Device/ST/STM32F0xx/Source/Templates/iar/startup_stm32f030xc.s']
    
CPPDEFINES = ['STM32F030xC']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
