from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd + '/../include', cwd + '/../../../../components/drivers/sdio']

if GetDepend(['RT_SDIO_SDHCI_SPACEMIT_K1X']):
    src += ['sdhci-k1x.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
