import os
from building import *

objs = []
cwd  = GetCurrentDir()

# add general drivers
src = []
path = [cwd]

if GetDepend(['BSP_USING_SPI_FLASH']):
    src += Glob('spi_flash_init.c')

if GetDepend(['BSP_USING_TF_CARD']):
    src += Glob('drv_filesystem.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
