Import('rtconfig')
from building import *

cwd = GetCurrentDir()
path = [cwd + '/../CMSIS/Core/Include',cwd + '/components/codec', cwd + '/MCXN947', cwd + '/MCXN947/drivers', cwd + '/middleware/sdmmc/inc', cwd + '/middleware/sdmmc/port']
src = Split('''
            MCXN947/system_MCXN947_cm33_core0.c
            ''')

if rtconfig.PLATFORM in ['gcc']:
    src += ['MCXN947/gcc/startup_MCXN947_cm33_core0.S']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['MCXN947/arm/startup_MCXN947_cm33_core0.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['MCXN947/iar/startup_MCXN947_cm33_core0.s']

src += ['MCXN947/drivers/fsl_cache.c']
src += ['MCXN947/drivers/fsl_cache_lpcac.c']
src += ['MCXN947/drivers/fsl_cdog.c']
src += ['MCXN947/drivers/fsl_clock.c']
src += ['MCXN947/drivers/fsl_cmc.c']
src += ['MCXN947/drivers/fsl_common.c']
src += ['MCXN947/drivers/fsl_common_arm.c']
src += ['MCXN947/drivers/fsl_crc.c']
src += ['MCXN947/drivers/fsl_ctimer.c']
src += ['MCXN947/drivers/fsl_dac.c']
src += ['MCXN947/drivers/fsl_dac14.c']
src += ['MCXN947/drivers/fsl_edma.c']
src += ['MCXN947/drivers/fsl_edma_soc.c']
src += ['MCXN947/drivers/fsl_eim.c']
src += ['MCXN947/drivers/fsl_enc.c']
src += ['MCXN947/drivers/fsl_enet.c']
src += ['MCXN947/drivers/fsl_erm.c']
src += ['MCXN947/drivers/fsl_evtg.c']
src += ['MCXN947/drivers/fsl_ewm.c']
src += ['MCXN947/drivers/fsl_flexcan.c']
src += ['MCXN947/drivers/fsl_flexio.c']
src += ['MCXN947/drivers/fsl_flexio_i2c_master.c']
src += ['MCXN947/drivers/fsl_flexio_mculcd.c']
src += ['MCXN947/drivers/fsl_flexio_mculcd_edma.c']
src += ['MCXN947/drivers/fsl_flexio_spi.c']
src += ['MCXN947/drivers/fsl_flexio_spi_edma.c']
src += ['MCXN947/drivers/fsl_flexio_uart.c']
src += ['MCXN947/drivers/fsl_flexio_uart_edma.c']
src += ['MCXN947/drivers/fsl_flexspi.c']
src += ['MCXN947/drivers/fsl_flexspi_edma.c']
src += ['MCXN947/drivers/fsl_gpio.c']
src += ['MCXN947/drivers/fsl_i3c.c']
src += ['MCXN947/drivers/fsl_irtc.c']
src += ['MCXN947/drivers/fsl_itrc.c']
src += ['MCXN947/drivers/fsl_lpadc.c']
src += ['MCXN947/drivers/fsl_lpflexcomm.c']
src += ['MCXN947/drivers/fsl_lpi2c.c']
src += ['MCXN947/drivers/fsl_lpi2c_edma.c']
src += ['MCXN947/drivers/fsl_lpspi.c']
src += ['MCXN947/drivers/fsl_lpspi_edma.c']
src += ['MCXN947/drivers/fsl_lptmr.c']
src += ['MCXN947/drivers/fsl_lpuart.c']
src += ['MCXN947/drivers/fsl_mrt.c']
src += ['MCXN947/drivers/fsl_reset.c']
src += ['MCXN947/drivers/fsl_spc.c']
src += ['MCXN947/drivers/fsl_vref.c']
src += ['MCXN947/drivers/fsl_usdhc.c']


group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
