Import('RTT_ROOT')
Import('rtconfig')
from building import *
from gcc import *

cwd = GetCurrentDir()
src = []
group = []
CPPPATH = [cwd]

group = DefineGroup('', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
