import os
from building import *

objs = []
cwd  = GetCurrentDir()

# add general drivers
src = []
path =  [cwd]

if GetDepend(['BSP_USING_QSPI_FLASH']):
    src += Glob('drv_qspi_flash.c')
    
if GetDepend(['BSP_USING_SDMMC']):
    src += Glob('drv_sdio.c')
    
if GetDepend(['BSP_USING_DCMI']):
    src += Glob('drv_dcmi.c')
    
if GetDepend(['BSP_USING_OV2640']):
    src += Glob('drv_ov2640.c')


CPPDEFINES = ['STM32H743xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
