Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

src = ['board.c']

# add uart driver.
src += ['uart.c']

# add EMAC driver for Lwip.
if GetDepend('RT_USING_LWIP') == True:
    src += ['emac.c', 'app_phy.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
