import os
from building import *
Import('rtconfig')

src = Glob('*.c')
cwd = GetCurrentDir()
group = []

if rtconfig.PLATFORM == 'gcc' and GetDepend('RT_USING_MUSL'):
    CPPDEFINES = ['__STDC_ISO_10646__=201206L', '_STDC_PREDEF_H']
    LIBS       = ['c', 'gcc']

    if os.path.exists(os.path.join(cwd, 'libc', 'lib', 'libc.a')):
        CFLAGS     = ' -nostdinc'
        CPPPATH    = [cwd, cwd + '/libc/include']
        LIBPATH    = [cwd + '/libc/lib']

        group = DefineGroup('musl', src, depend = ['RT_USING_LIBC', 'RT_USING_MUSL'], CFLAGS = CFLAGS, 
            CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LIBS = LIBS, LIBPATH = LIBPATH)
    else:
        LINKFLAGS = ' --specs=kernel.specs'
        group = DefineGroup('musl', src, depend = ['RT_USING_LIBC', 'RT_USING_MUSL'], LINKFLAGS = LINKFLAGS, 
            CPPDEFINES = CPPDEFINES, LIBS = LIBS)

Return('group')
