from building import *
Import('rtconfig')

src = Glob('*.c')
cwd = GetCurrentDir()
group = []

CFLAGS     = ' -nostdinc'
CPPPATH    = [cwd, cwd + '/libc/include']
CPPDEFINES = ['__STDC_ISO_10646__=201206L', '_STDC_PREDEF_H']
LIBS       = ['c', 'm', 'gcc']
LIBPATH    = [cwd + '/libc/lib']

if rtconfig.PLATFORM == 'gcc':
    group = DefineGroup('musl', src, depend = ['RT_USING_LIBC', 'RT_USING_MUSL'], CFLAGS = CFLAGS, 
        CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LIBS = LIBS, LIBPATH = LIBPATH)

Return('group')
