Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd  = GetCurrentDir()
CPPPATH = [cwd]

# The set of source files associated with this SConscript file.
if rtconfig.PLATFORM in ['armcc', 'armclang']:
    src = Glob('*.c') + Glob('*_rvds.S')

if rtconfig.PLATFORM in ['gcc']:
    src = Glob('*.c') + Glob('*_gcc.S') + Glob('*_init.S')

if rtconfig.PLATFORM in ['iccarm']:
    src = Glob('*.c') + Glob('*_iar.S')

if rtconfig.PLATFORM in ['cl', 'mingw']:
    src = Glob('*.c')

group = DefineGroup('Platform', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
