from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Src/stm32l4xx_hal_msp.c
''')

if GetDepend('BSP_USING_SPI_LCD'):
    src += ['ports/lcd/drv_lcd.c']

if GetDepend('BSP_USING_MPU6050'):
    src += ['ports/mpu6050_meas.c']

path =  [cwd]
path += [cwd + '/CubeMX_Config/Inc']
path += [cwd + '/ports/lcd']

CPPDEFINES = ['STM32L431xx']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
