Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drivers.
src = Split("""
board.c
led.c
key.c
uart.c
""")

if GetDepend('RT_USING_LWIP'):
	src += ['dm9000.c']

if GetDepend('RT_MINI2440_LCD_A70'):
    src += ['lcd_a70.c']
if GetDepend('RT_MINI2440_LCD_T43'):
    src += ['lcd_t43.c']
if GetDepend('RT_MINI2440_LCD_N35'):
    src += ['lcd_n35.c']
if GetDepend('RT_MINI2440_LCD_T35'):
    src += ['lcd_t35.c']
if GetDepend('RT_MINI2440_LCD_X35'):
    src += ['lcd_x35.c']

if GetDepend('PKG_USING_GUIENGINE'):
    src += ['touch.c']

if GetDepend('RT_USING_SDIO'):
    src += ['s3cmci.c']


CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

