Import('env')
Import('projects')
Import('RTT_ROOT')
Import('rtconfig')

# group definitions
group = {}
group['name'] = 'libdl'
group['src'] = Glob('*.c')
group['depend'] = 'RT_USING_LIBDL'
group['CCFLAGS'] = ''
group['CPPPATH'] = [RTT_ROOT + '/components/libdl']
group['CPPDEFINES'] = ''
group['LINKFLAGS'] = ''

# add group to project list
projects.append(group)

env.Append(CCFLAGS = group['CCFLAGS'])
env.Append(CPPPATH = group['CPPPATH'])
env.Append(CPPDEFINES = group['CPPDEFINES'])
env.Append(LINKFLAGS = group['LINKFLAGS'])

objs = env.Object(group['src'])

Return('objs')
