# for module compiling
import os
Import('rtconfig')
from building import *

objs = []

if GetDepend('SOC_GK7102C'):
    objs += SConscript(os.path.join('7102C', 'SConscript'))
elif GetDepend('SOC_GK7101') or GetDepend('SOC_GK7102'):
    objs += SConscript(os.path.join('710X', 'SConscript'))
elif GetDepend('SOC_GK7101S') or GetDepend('SOC_GK7102S'):
    objs += SConscript(os.path.join('710XS', 'SConscript'))

objs += SConscript(os.path.join('gnu_c', 'SConscript'))

Return('objs')
