# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

slcd_src = Split('''
drv_slcdc.c
''')
slcd_group = DefineGroup('drv_slcd', slcd_src, depend = ['RT_USING_SLCD'], CPPPATH = CPPPATH)

lcm_src = Split('''
dump_slcd.c
drv_slcd_ili9341.c
drv_slcd_ili9488.c
drv_slcd_otm4802.c
drv_slcd_rm68120.c
drv_slcd_truly_tft240240.c
''')
lcm_group = DefineGroup('drv_lcm', lcm_src, depend = ['RT_USING_SLCD'], CPPPATH = CPPPATH)

group = slcd_group + lcm_group
Return('group')
