from building import *

cwd     = GetCurrentDir()
src     = []

if GetDepend('BSP_USING_WIFI'):
    src += ['drv_wifi.c']

CPPPATH = [cwd]
group = DefineGroup('drv_wifi', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
