Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
group = []
src = ['drv_gpio.c']
path = [cwd]

if GetDepend(['RT_USING_CONSOLE']):
    src += ['drv_console.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
