# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = ['signalfd.c']

group = DefineGroup('POSIX', src, depend = ['RT_USING_SMART','RT_USING_POSIX_SIGNALFD'])

Return('group')
