Import('rtconfig')
from building import *

cwd = GetCurrentDir()
path = [cwd + '/../CMSIS/Core/Include', cwd + '/MCXC444', cwd + '/MCXC444/drivers']
src = Split('''
            MCXC444/system_MCXC444.c
            ''')

if rtconfig.PLATFORM in ['gcc']:
    src += ['MCXC444/gcc/startup_MCXC444.S']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['MCXC444/arm/startup_MCXC444.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['MCXC444/iar/startup_MCXC444.s']

src += ['MCXC444/drivers/fsl_adc16.c']
src += ['MCXC444/drivers/fsl_clock.c']
src += ['MCXC444/drivers/fsl_cmp.c']
src += ['MCXC444/drivers/fsl_common.c']
src += ['MCXC444/drivers/fsl_common_arm.c']
src += ['MCXC444/drivers/fsl_cop.c']
src += ['MCXC444/drivers/fsl_dac.c']
src += ['MCXC444/drivers/fsl_dma.c']
src += ['MCXC444/drivers/fsl_ftfx_controller.c']
src += ['MCXC444/drivers/fsl_ftfx_flexnvm.c']
src += ['MCXC444/drivers/fsl_gpio.c']
src += ['MCXC444/drivers/fsl_i2c.c']
src += ['MCXC444/drivers/fsl_i2c_dma.c']
src += ['MCXC444/drivers/fsl_lpuart.c']
src += ['MCXC444/drivers/fsl_lpuart_dma.c']
src += ['MCXC444/drivers/fsl_pit.c']
src += ['MCXC444/drivers/fsl_pmc.c']
src += ['MCXC444/drivers/fsl_rtc.c']
src += ['MCXC444/drivers/fsl_sai.c']
src += ['MCXC444/drivers/fsl_sai_dma.c']
src += ['MCXC444/drivers/fsl_sim.c']
src += ['MCXC444/drivers/fsl_slcd.c']
src += ['MCXC444/drivers/fsl_smc.c']
src += ['MCXC444/drivers/fsl_spi.c']
src += ['MCXC444/drivers/fsl_tpm.c']
src += ['MCXC444/drivers/fsl_uart.c']
src += ['MCXC444/drivers/fsl_uart_dma.c']


group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
