nano:
    scons_arg:
      - '--strict'
    kconfig: 
      - CONFIG_RT_USING_NANO=y
component.ulog:
  kconfig: 
    - CONFIG_RT_USING_ULOG=y
devices.on_chip:
  kconfig:
    - CONFIG_BSP_USING_ON_CHIP_FLASH=y
    - CONFIG_BSP_USING_ON_CHIP_FLASH_FATFS=y
    - CONFIG_RT_DFS_ELM_MAX_SECTOR_SIZE=2048
device.usb.cdc:
  kconfig: 
    - CONFIG_RT_USB_DEVICE_CDC=y
    - CONFIG_BSP_USING_USBD=y
pkg.tools.coremark:
  kconfig: 
    - CONFIG_PKG_USING_COREMARK=y
pkg.kernel_sample:
  kconfig: 
    - CONFIG_RT_USING_SIGNALS=y
    - CONFIG_PKG_USING_KERNEL_SAMPLES=y
    - CONFIG_PKG_USING_KERNEL_SAMPLES_ZH=y
    - CONFIG_KERNEL_SAMPLES_USING_THREAD=y
    - CONFIG_KERNEL_SAMPLES_USING_SEMAPHORE=y
    - CONFIG_KERNEL_SAMPLES_USING_MUTEX=y
    - CONFIG_KERNEL_SAMPLES_USING_MAILBOX=y
    - CONFIG_KERNEL_SAMPLES_USING_EVENT=y
    - CONFIG_KERNEL_SAMPLES_USING_MESSAGEQUEUE=y
    - CONFIG_KERNEL_SAMPLES_USING_TIMER=y
    - CONFIG_KERNEL_SAMPLES_USING_HEAP=y
    - CONFIG_KERNEL_SAMPLES_USING_MEMHEAP=y
    - CONFIG_KERNEL_SAMPLES_USING_MEMPOOL=y
    - CONFIG_KERNEL_SAMPLES_USING_IDLEHOOK=y
    - CONFIG_KERNEL_SAMPLES_USING_SIGNAL=y
    - CONFIG_KERNEL_SAMPLES_USING_INTERRUPT=y
    - CONFIG_KERNEL_SAMPLES_USING_PRI_INVERSION=y
    - CONFIG_KERNEL_SAMPLES_USING_TIME_SLICE=y
    - CONFIG_KERNEL_SAMPLES_USING_SCHEDULER_HOOK=y
    - CONFIG_KERNEL_SAMPLES_USING_PRODUCER_CONSUMER=y
pkg.kernel_en_sample:
  kconfig: 
    - CONFIG_RT_USING_SIGNALS=y
    - CONFIG_PKG_USING_KERNEL_SAMPLES=y
    - CONFIG_PKG_USING_KERNEL_SAMPLES_EN=y
    - CONFIG_KERNEL_SAMPLES_USING_THREAD=y
    - CONFIG_KERNEL_SAMPLES_USING_SEMAPHORE=y
    - CONFIG_KERNEL_SAMPLES_USING_MUTEX=y
    - CONFIG_KERNEL_SAMPLES_USING_MAILBOX=y
    - CONFIG_KERNEL_SAMPLES_USING_EVENT=y
    - CONFIG_KERNEL_SAMPLES_USING_MESSAGEQUEUE=y
    - CONFIG_KERNEL_SAMPLES_USING_TIMER=y
    - CONFIG_KERNEL_SAMPLES_USING_HEAP=y
    - CONFIG_KERNEL_SAMPLES_USING_MEMHEAP=y
    - CONFIG_KERNEL_SAMPLES_USING_MEMPOOL=y
    - CONFIG_KERNEL_SAMPLES_USING_IDLEHOOK=y
    - CONFIG_KERNEL_SAMPLES_USING_SIGNAL=y
    - CONFIG_KERNEL_SAMPLES_USING_INTERRUPT=y
    - CONFIG_KERNEL_SAMPLES_USING_PRI_INVERSION=y
    - CONFIG_KERNEL_SAMPLES_USING_TIME_SLICE=y
    - CONFIG_KERNEL_SAMPLES_USING_SCHEDULER_HOOK=y
    - CONFIG_KERNEL_SAMPLES_USING_PRODUCER_CONSUMER=y
pkg.peripheral.sample:
  kconfig:
    - CONFIG_PKG_USING_PERIPHERAL_SAMPLES=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_ADC=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_HWTIMER=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_I2C=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_IWDG=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_LED_BLINK=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_PIN=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_PWM=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_RTC=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_SD=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_SERIAL=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_SERIAL_DMA=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_SPI=y
    - CONFIG_PERIPHERAL_SAMPLES_USING_CAN=y
# ------ component CI ------
component.rtlink:
  kconfig: 
    - CONFIG_RT_USING_ULOG=y
    - CONFIG_RT_USING_RT_LINK=y
    - CONFIG_PKG_USING_RT_LINK_HW=y
    - CONFIG_PKG_PKG_RT_LINK_HW_DEVICE_NAME="lpuart1"
component.cherryusb_cdc:
  kconfig:
    - CONFIG_RT_USING_CHERRYUSB=y
    - CONFIG_RT_CHERRYUSB_DEVICE=y
    - CONFIG_RT_CHERRYUSB_DEVICE_DWC2_ST=y
    - CONFIG_RT_CHERRYUSB_DEVICE_CDC_ACM=y
    - CONFIG_RT_CHERRYUSB_DEVICE_TEMPLATE_CDC_ACM=y
