from building import *

'''
demo_view_dc_buffer.c
demo_fnview.c
demo_listview.c
demo_listview_icon.c
demo_panel_single.c
demo_view_box.c
demo_view_image.c
demo_view_module.c
'''

src = Split("""
demo_application.c
demo_view.c
demo_xml.c
demo_view_benchmark.c
demo_view_dc.c
demo_view_ttf.c
demo_view_dc_buffer.c
demo_view_animation.c
demo_view_buffer_animation.c
demo_view_instrument_panel.c
demo_view_window.c
demo_view_label.c
demo_view_button.c
demo_view_checkbox.c
demo_view_progressbar.c
demo_view_scrollbar.c
demo_view_radiobox.c
demo_view_textbox.c
demo_view_listbox.c
demo_view_menu.c
demo_view_listctrl.c
demo_view_combobox.c
demo_view_slider.c
demo_view_notebook.c
demo_view_mywidget.c
demo_view_box.c
demo_view_edit.c
demo_view_bmp.c
demo_plot.c
mywidget.c
""")



group = DefineGroup('gui_examples', src, depend = ['RT_USING_RTGUI'])

Return('group')
