Import('env')
Import('projects')

src = Split("""
demo_view_dc_buffer.c
demo_view_instrument_panel.c
demo_fnview.c
demo_listview.c
demo_listview_icon.c
demo_panel_single.c
demo_view.c
demo_view_animation.c
demo_view_buffer_animation.c
demo_view_box.c
demo_view_button.c
demo_view_checkbox.c
demo_view_dc.c
demo_view_image.c
demo_view_module.c
demo_view_label.c
demo_view_mywidget.c
demo_view_progressbar.c
demo_view_radiobox.c
demo_view_listbox.c
demo_view_slider.c
demo_view_scrollbar.c
demo_view_textbox.c
demo_view_window.c
demo_view_benchmark.c
demo_workbench.c
gui_init.c
mywidget.c
""")

group = {}
group['name'] = 'GUI demo'
group['src'] = File(src)
group['CCFLAGS'] = ''
group['CPPPATH'] = ['']
group['CPPDEFINES'] = ''
group['LINKFLAGS'] = ''

# add group to project list
projects.append(group)

env.Append(CCFLAGS = group['CCFLAGS'])
env.Append(CPPPATH = group['CPPPATH'])
env.Append(CPPDEFINES = group['CPPDEFINES'])
env.Append(LINKFLAGS = group['LINKFLAGS'])

objs = env.Object(group['src'])

Return('objs')
