# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
group = []
if GetDepend('BSP_USING_USBH'):
    src = Glob('*src/*.c') + Glob('src/*.cpp')
    CPPPATH = [cwd + '/inc']
    group = DefineGroup('ma35d1_usbhostlib', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
