# for module compiling
import os
Import('RTT_ROOT')
Import('env')
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

# (STM32F301x8) || (STM32F302x8) || (STM32F318xx)
# (STM32F302xC) || (STM32F303xC) || (STM32F358xx)
# (STM32F303x8) || (STM32F334x8) || (STM32F328xx)
# (STM32F302xE) || (STM32F303xE) || (STM32F398xx)
# (STM32F373xC) || (STM32F378xx)
# You can select chips from the list above
env.Append(CPPDEFINES = ['STM32F334x8'])

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
