from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

if GetDepend(['RT_DVFS_ROCKCHIP_CPUFREQ']):
    src += ['dvfs-rockchip-cpufreq.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
