# RT-Thread building script for component
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
libs = []
src = Glob('*src/*.c') + Glob('src/*.cpp')
cpppath = [cwd + '/inc']
libpath = [cwd + '/lib']

if not GetDepend('BSP_USE_STDDRIVER_SOURCE'):
	if rtconfig.CROSS_TOOL == 'keil':
		if GetOption('target') == 'mdk5' and os.path.isfile('./lib/libstddriver_keil.lib'):
			libs += ['libstddriver_keil']
		elif GetOption('target') == 'mdk4' and os.path.isfile('./lib/libstddriver_keil4.lib'):
			libs += ['libstddriver_keil4']
	elif rtconfig.CROSS_TOOL == 'gcc' and os.path.isfile('./lib/libstddriver_gcc.a'):
		libs += ['libstddriver_gcc']
	elif os.path.isfile('./lib/libstddriver_iar.a'):
		libs += ['libstddriver_iar']    

if not libs:
	group = DefineGroup('m480_stddriver', src, depend = [''], CPPPATH = cpppath)
else:
	src = []
	group = DefineGroup('m480_stddriver', src, depend = [''], CPPPATH = cpppath, LIBS = libs, LIBPATH = libpath)

Return('group')
