from building import *

Import('rtconfig')

src   = []
cwd   = GetCurrentDir()
CPPPATH = [cwd]
group = []
src += Glob('*.c')

if rtconfig.PLATFORM != 'gcc':
    group = DefineGroup('libc', src, depend = ['RT_USING_LIBC'], CPPPATH = CPPPATH)
Return('group')
