/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.c
**     Project     : FRDM-K66F
**     Processor   : MK66FN2M0VMD18
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     All Rights Reserved.
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.4
** @brief
**
*/
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/

/* MODULE pin_mux. */

#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "fsl_sim_hal.h"
#include "pin_mux.h"


void configure_enet_pins(uint32_t instance)
{
  /* Affects PORTC_PCR16 register */
  PORT_HAL_SetMuxMode(PORTC,16UL,kPortMuxAlt4);
  /* Affects PORTE_PCR26 register */
  PORT_HAL_SetMuxMode(PORTE,26UL,kPortMuxAlt2);
  /* Affects PORTB_PCR1 register */
  PORT_HAL_SetMuxMode(PORTB,1UL,kPortMuxAlt4);
  /* Affects PORTB_PCR0 register */
  PORT_HAL_SetMuxMode(PORTB,0UL,kPortMuxAlt4);
  /* Affects PORTA_PCR13 register */
  PORT_HAL_SetMuxMode(PORTA,13UL,kPortMuxAlt4);
  /* Affects PORTA_PCR12 register */
  PORT_HAL_SetMuxMode(PORTA,12UL,kPortMuxAlt4);
  /* Affects PORTA_PCR14 register */
  PORT_HAL_SetMuxMode(PORTA,14UL,kPortMuxAlt4);
  /* Affects PORTA_PCR5 register */
  PORT_HAL_SetMuxMode(PORTA,5UL,kPortMuxAlt4);
  /* Affects PORTA_PCR16 register */
  PORT_HAL_SetMuxMode(PORTA,16UL,kPortMuxAlt4);
  /* Affects PORTA_PCR17 register */
  PORT_HAL_SetMuxMode(PORTA,17UL,kPortMuxAlt4);
  /* Affects PORTA_PCR15 register */
  PORT_HAL_SetMuxMode(PORTA,15UL,kPortMuxAlt4);
  /* Affects PORTA_PCR18 register */
  PORT_HAL_SetMuxMode(PORTA,18UL,kPortPinDisabled);
}

void configure_ftm_pins(uint32_t instance)
{
  switch(instance) {
    case FTM2_IDX:                      /* FTM2_IDX */
      /* Affects PORTA_PCR11 register */
      PORT_HAL_SetOpenDrainCmd(PORTA,11UL,false);
      PORT_HAL_SetMuxMode(PORTA,11UL,kPortMuxAlt3);
      PORT_HAL_SetSlewRateMode(PORTA,11UL,kPortSlowSlewRate);
      /* Affects PORTB_PCR19 register */
      PORT_HAL_SetMuxMode(PORTB,19UL,kPortMuxAlt6);
      break;
    case FTM3_IDX:                      /* FTM3_IDX */
      /* Affects PORTE_PCR6 register */
      PORT_HAL_SetOpenDrainCmd(PORTE,6UL,false);
      PORT_HAL_SetMuxMode(PORTE,6UL,kPortMuxAlt6);
      PORT_HAL_SetSlewRateMode(PORTE,6UL,kPortSlowSlewRate);
      /* Affects PORTC_PCR9 register */
      PORT_HAL_SetOpenDrainCmd(PORTC,9UL,false);
      PORT_HAL_SetMuxMode(PORTC,9UL,kPortMuxAlt3);
      PORT_HAL_SetSlewRateMode(PORTC,9UL,kPortSlowSlewRate);
      break;
    default:
      break;
  }
}

void configure_gpio_pins(uint32_t instance)
{
  switch(instance) {
    case PORTA_IDX:                     /* PORTA_IDX */
      /* Affects PORTA_PCR10 register */
      PORT_HAL_SetMuxMode(PORTA,10UL,kPortMuxAsGpio);
      /* Affects PORTA_PCR11 register */
      PORT_HAL_SetMuxMode(PORTA,11UL,kPortMuxAsGpio);
      /* Affects PORTA_PCR28 register */
      PORT_HAL_SetMuxMode(PORTA,28UL,kPortMuxAsGpio);
      /* Affects PORTA_PCR29 register */
      PORT_HAL_SetMuxMode(PORTA,29UL,kPortMuxAsGpio);
      break;
    case PORTC_IDX:                     /* PORTC_IDX */
      /* Affects PORTC_PCR9 register */
      PORT_HAL_SetMuxMode(PORTC,9UL,kPortMuxAsGpio);
      /* Affects PORTC_PCR13 register */
      PORT_HAL_SetMuxMode(PORTC,13UL,kPortMuxAsGpio);
      /* Affects PORTC_PCR17 register */
      PORT_HAL_SetMuxMode(PORTC,17UL,kPortMuxAsGpio);
      break;
    case PORTD_IDX:                     /* PORTD_IDX */
      /* Affects PORTD_PCR10 register */
      PORT_HAL_SetMuxMode(PORTD,10UL,kPortMuxAsGpio);
      /* Affects PORTD_PCR11 register */
      PORT_HAL_SetMuxMode(PORTD,11UL,kPortMuxAsGpio);
      break;
    case PORTE_IDX:                     /* PORTE_IDX */
      /* Affects PORTE_PCR6 register */
      PORT_HAL_SetMuxMode(PORTE,6UL,kPortMuxAsGpio);
      break;
    default:
      break;
  }
}

void configure_i2c_pins(uint32_t instance)
{
  switch(instance) {
    case I2C0_IDX:                      /* I2C0_IDX */
      /* Affects PORTD_PCR8 register */
      PORT_HAL_SetMuxMode(PORTD,8UL,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTD,8UL,true);
      /* Affects PORTD_PCR9 register */
      PORT_HAL_SetMuxMode(PORTD,9UL,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTD,9UL,true);
      break;
    case I2C1_IDX:                      /* I2C1_IDX */
      /* Affects PORTC_PCR10 register */
      PORT_HAL_SetMuxMode(PORTC,10UL,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTC,10UL,true);
      /* Affects PORTC_PCR11 register */
      PORT_HAL_SetMuxMode(PORTC,11UL,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTC,11UL,true);
      break;
    case I2C3_IDX:                      /* I2C3_IDX */
      /* Affects PORTE_PCR11 register */
      PORT_HAL_SetMuxMode(PORTE,11UL,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTE,11UL,true);
      /* Affects PORTA_PCR1 register */
      PORT_HAL_SetMuxMode(PORTA,1UL,kPortMuxAlt4);
      PORT_HAL_SetOpenDrainCmd(PORTA,1UL,true);
      break;
    default:
      break;
  }
}

void configure_i2s_pins(uint32_t instance)
{
  /* Affects PORTC_PCR6 register */
  PORT_HAL_SetMuxMode(PORTC,6UL,kPortMuxAlt6);
  /* Affects PORTC_PCR9 register */
  PORT_HAL_SetMuxMode(PORTC,9UL,kPortMuxAlt4);
  /* Affects PORTE_PCR7 register */
  PORT_HAL_SetMuxMode(PORTE,7UL,kPortMuxAlt4);
  /* Affects PORTE_PCR12 register */
  PORT_HAL_SetMuxMode(PORTE,12UL,kPortMuxAlt4);
  /* Affects PORTE_PCR11 register */
  PORT_HAL_SetMuxMode(PORTE,11UL,kPortMuxAlt4);
  /* Affects PORTC_PCR1 register */
  PORT_HAL_SetMuxMode(PORTC,1UL,kPortMuxAlt6);
  /* Affects PORTE_PCR9 register */
  PORT_HAL_SetMuxMode(PORTE,9UL,kPortMuxAlt2);
}

void configure_jtag_pins(uint32_t instance)
{
  /* Affects PORTA_PCR0 register */
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortMuxAlt7);
  /* Affects PORTA_PCR1 register */
  PORT_HAL_SetMuxMode(PORTA,1UL,kPortMuxAlt7);
  /* Affects PORTA_PCR2 register */
  PORT_HAL_SetMuxMode(PORTA,2UL,kPortMuxAlt7);
  /* Affects PORTA_PCR3 register */
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortMuxAlt7);
}

void configure_llwu_pins(uint32_t instance)
{
  /* Affects PORTE_PCR6 register */
  PORT_HAL_SetMuxMode(PORTE,6UL,kPortMuxAsGpio);
  /* Affects PORTA_PCR10 register */
  PORT_HAL_SetMuxMode(PORTA,10UL,kPortMuxAsGpio);
  /* Affects PORTA_PCR11 register */
  PORT_HAL_SetMuxMode(PORTA,11UL,kPortMuxAsGpio);
  /* Affects PORTD_PCR11 register */
  PORT_HAL_SetMuxMode(PORTD,11UL,kPortMuxAsGpio);
}

void configure_osc_pins(uint32_t instance)
{
  /* Affects PORTA_PCR18 register */
  PORT_HAL_SetMuxMode(PORTA,18UL,kPortPinDisabled);
  /* Affects PORTA_PCR19 register */
  PORT_HAL_SetMuxMode(PORTA,19UL,kPortPinDisabled);
}

void configure_sdhc_pins(uint32_t instance)
{
  /* Affects PORTE_PCR3 register */
  PORT_HAL_SetMuxMode(PORTE,3UL,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE,3UL,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE,3UL,true);
  /* Affects PORTE_PCR1 register */
  PORT_HAL_SetMuxMode(PORTE,1UL,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE,1UL,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE,1UL,true);
  /* Affects PORTE_PCR0 register */
  PORT_HAL_SetMuxMode(PORTE,0UL,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE,0UL,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE,0UL,true);
  /* Affects PORTE_PCR5 register */
  PORT_HAL_SetMuxMode(PORTE,5UL,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE,5UL,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE,5UL,true);
  /* Affects PORTE_PCR4 register */
  PORT_HAL_SetMuxMode(PORTE,4UL,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE,4UL,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE,4UL,true);
  /* Affects PORTE_PCR2 register */
  PORT_HAL_SetMuxMode(PORTE,2UL,kPortMuxAlt4);
  PORT_HAL_SetPullMode(PORTE,2UL,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTE,2UL,true);

}

void configure_spi_pins(uint32_t instance)
{
  switch(instance) {
    case SPI0_IDX:                      /* SPI0_IDX */
      /* Affects PORTD_PCR0 register */
      PORT_HAL_SetMuxMode(PORTD,0UL,kPortMuxAlt2);
      /* Affects PORTD_PCR3 register */
      PORT_HAL_SetMuxMode(PORTD,3UL,kPortMuxAlt2);
      /* Affects PORTD_PCR1 register */
      PORT_HAL_SetMuxMode(PORTD,1UL,kPortMuxAlt2);
      /* Affects PORTD_PCR2 register */
      PORT_HAL_SetMuxMode(PORTD,2UL,kPortMuxAlt2);
      break;
    case SPI1_IDX:                      /* SPI1_IDX */
      /* Affects PORTD_PCR4 register */
      PORT_HAL_SetMuxMode(PORTD,4UL,kPortMuxAlt7);
      /* Affects PORTD_PCR7 register */
      PORT_HAL_SetMuxMode(PORTD,7UL,kPortMuxAlt7);
      /* Affects PORTD_PCR5 register */
      PORT_HAL_SetMuxMode(PORTD,5UL,kPortMuxAlt7);
      /* Affects PORTD_PCR6 register */
      PORT_HAL_SetMuxMode(PORTD,6UL,kPortMuxAlt7);
      break;
    default:
      break;
  }
}

void configure_tpiu_pins(uint32_t instance)
{
  /* Affects PORTA_PCR2 register */
  PORT_HAL_SetMuxMode(PORTA,2UL,kPortMuxAlt7);
}

void configure_tpm_pins(uint32_t instance)
{
  switch(instance) {
    case TPM2_IDX:                      /* TPM2_IDX */
      /* Affects PORTA_PCR11 register */
      PORT_HAL_SetOpenDrainCmd(PORTA,11UL,false);
      PORT_HAL_SetMuxMode(PORTA,11UL,kPortMuxAlt6);
      PORT_HAL_SetSlewRateMode(PORTA,11UL,kPortSlowSlewRate);
      break;
    default:
      break;
  }
}

void configure_uart_pins(uint32_t instance)
{
  switch(instance) {
    case UART0_IDX:                     /* UART0_IDX */
      /* Affects PORTB_PCR16 register */
      PORT_HAL_SetMuxMode(PORTB,16UL,kPortMuxAlt3);
      /* Affects PORTB_PCR17 register */
      PORT_HAL_SetMuxMode(PORTB,17UL,kPortMuxAlt3);
      break;
    default:
      break;
  }
}

/* END pin_mux. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
