# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('pthreads', src, 
    depend = ['RT_USING_POSIX_CLOCKTIME'], CPPPATH = CPPPATH)

Return('group')
