# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

#group = DefineGroup('pthreads', src, 
#    depend = ['RT_USING_PTHREADS'], CPPPATH = CPPPATH)

group = DefineGroup('pthreads', src, 
    depend = [''], CPPPATH = CPPPATH)

Return('group')
