# for module compiling
import os
Import('remove_components')
from building import *

objs = []
cwd  = GetCurrentDir()
entries = os.listdir(cwd)

for item in entries:
    if item in remove_components:
        continue

    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        result = SConscript(os.path.join(item, 'SConscript'))
        if isinstance(result, (list, tuple)):
            objs.extend(result)
        else:
            objs.append(result)

Return('objs')
