# for module compile 
Import('env')
Import('rtconfig')

# build each components
objs = ''

if 'RT_USING_MINILIBC' in dir(rtconfig) and rtconfig.RT_USING_MINILIBC:
	objs = objs + SConscript('libc/minilibc/SConscript')

if 'RT_USING_FINSH' in dir(rtconfig) and rtconfig.RT_USING_FINSH:
	objs = objs + SConscript('finsh/SConscript')

if 'RT_USING_DFS' in dir(rtconfig) and rtconfig.RT_USING_DFS:
	objs = objs + SConscript('dfs/SConscript')

if 'RT_USING_LWIP' in dir(rtconfig) and rtconfig.RT_USING_LWIP:
	objs = objs + SConscript('net/lwip/SConscript')

if 'RT_USING_MODBUS' in dir(rtconfig) and rtconfig.RT_USING_MODBUS:
	objs = objs + SConscript('net//freemodbus/SConscript')

if 'RT_USING_RTGUI' in dir(rtconfig) and rtconfig.RT_USING_RTGUI:
	objs = objs + SConscript('rtgui/SConscript')

# build each modules
if rtconfig.CROSS_TOOL == 'gcc':
	SConscript('hello/SConscript')
	SConscript('thread/SConscript')

Return('objs')
