Import('rtconfig')
from building import *

cwd = GetCurrentDir()
path = [cwd + '/CMSIS/Include',cwd + '/MIMXRT1176', cwd + '/MIMXRT1176/drivers', cwd + '/MIMXRT1176/drivers/cm7']
src = Split('''
            MIMXRT1176/drivers/fsl_anatop_ai.c
            MIMXRT1176/system_MIMXRT1176_cm7.c
            MIMXRT1176/drivers/fsl_common.c
            MIMXRT1176/drivers/fsl_common_arm.c
            MIMXRT1176/drivers/fsl_dcdc.c
            MIMXRT1176/drivers/fsl_pmu.c
            MIMXRT1176/drivers/fsl_clock.c
            MIMXRT1176/drivers/cm7/fsl_cache.c
            ''')

if rtconfig.PLATFORM in ['gcc']:
    src += ['MIMXRT1176/gcc/startup_MIMXRT1176_cm7.S']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['MIMXRT1176/arm/startup_MIMXRT1176_cm7.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['MIMXRT1176/iar/startup_MIMXRT1176_cm7.s']

if GetDepend(['BSP_USING_GPIO']):
    src += ['MIMXRT1176/drivers/fsl_gpio.c']

if GetDepend(['BSP_USING_LPUART']):
    src += ['MIMXRT1176/drivers/fsl_lpuart.c']

if GetDepend(['BSP_USING_RTC']):
    src += ['MIMXRT1176/drivers/fsl_snvs_hp.c']
    src += ['MIMXRT1176/drivers/fsl_snvs_lp.c']

if GetDepend(['BSP_USING_HWTIMER']) or GetDepend(['BSP_USING_PWM']):
    src += ['MIMXRT1176/drivers/fsl_gpt.c']

if GetDepend(['BSP_USING_PWM']):
    src += ['MIMXRT1176/drivers/fsl_pwm.c']

if GetDepend(['BSP_USING_SDIO']):
    src += ['MIMXRT1176/drivers/fsl_usdhc.c']

if GetDepend(['BSP_USING_SDRAM']):
    src += ['MIMXRT1176/drivers/fsl_semc.c']

if GetDepend(['BSP_USING_ETH']):
    src += ['MIMXRT1176/drivers/fsl_enet.c']

if GetDepend(['RT_USING_CAN']):
    src += ['MIMXRT1176/drivers/fsl_flexcan.c']

if GetDepend(['BSP_USING_FLEXSPI']):
    src += ['MIMXRT1176/drivers/fsl_flexspi.c']

if GetDepend(['BSP_USING_VGLITE']):
    src += ['MIMXRT1176/drivers/fsl_soc_src.c']
    src += ['MIMXRT1176/drivers/fsl_mipi_dsi.c']
    src += ['MIMXRT1176/drivers/fsl_video_common.c']
    src += ['MIMXRT1176/drivers/display_support.c']
    src += ['MIMXRT1176/drivers/fsl_fbdev.c']
    src += ['MIMXRT1176/drivers/fsl_mipi_dsi_cmd.c']
    
    if GetDepend(['VGLITE_USING_LCDIFV2']):
        src += ['MIMXRT1176/drivers/fsl_dc_fb_lcdifv2.c']
        src += ['MIMXRT1176/drivers/fsl_lcdifv2.c']
    else:
        src += ['MIMXRT1176/drivers/fsl_dc_fb_elcdif.c']
        src += ['MIMXRT1176/drivers/fsl_elcdif.c']

    if GetDepend(['VGLITE_USING_RK055AHD091']):
        src += ['MIMXRT1176/drivers/fsl_rm68200.c']
    elif GetDepend(['VGLITE_USING_RK055IQH091']):
        src += ['MIMXRT1176/drivers/fsl_rm68191.c']
    else:
        src += ['MIMXRT1176/drivers/fsl_hx8394.c']

    src += ['MIMXRT1176/drivers/mf_bwfont.c']
    src += ['MIMXRT1176/drivers/mf_encoding.c']
    src += ['MIMXRT1176/drivers/mf_font.c']
    src += ['MIMXRT1176/drivers/mf_justify.c']
    src += ['MIMXRT1176/drivers/mf_kerning.c']
    src += ['MIMXRT1176/drivers/mf_rlefont.c']
    src += ['MIMXRT1176/drivers/mf_scaledfont.c']
    src += ['MIMXRT1176/drivers/mf_wordwrap.c']
    
    src += ['MIMXRT1176/drivers/buf_reader.c']
    src += ['MIMXRT1176/drivers/rle_font_read.c']
    src += ['MIMXRT1176/drivers/vft_debug.c']
    src += ['MIMXRT1176/drivers/vft_draw.c']
    src += ['MIMXRT1176/drivers/vg_lite_text.c']
    
    src += ['MIMXRT1176/drivers/vg_lite_os.c']
    src += ['MIMXRT1176/drivers/vg_lite.c']
    src += ['MIMXRT1176/drivers/vg_lite_flat.c']
    src += ['MIMXRT1176/drivers/vg_lite_image.c']
    src += ['MIMXRT1176/drivers/vg_lite_matrix.c']
    src += ['MIMXRT1176/drivers/vg_lite_path.c']
    
    src += ['MIMXRT1176/drivers/vglite_support.c']
    src += ['MIMXRT1176/drivers/vglite_window.c']
    
    src += ['MIMXRT1176/drivers/vg_lite_hal.c']
    src += ['MIMXRT1176/drivers/vg_lite_kernel.c']
    
    if GetDepend(['VGLITE_USING_ELM']):
        src += ['MIMXRT1176/drivers/elm_buffer.c']
        src += ['MIMXRT1176/drivers/elm_draw.c']
        src += ['MIMXRT1176/drivers/elm_init.c']
        src += ['MIMXRT1176/drivers/elm_object.c']
        src += ['MIMXRT1176/drivers/elm_os.c']
        src += ['MIMXRT1176/drivers/elm_text.c']

#fsl os abstract files
src += ['MIMXRT1176/drivers/fsl_os_abstraction_rtthread.c']
src += ['MIMXRT1176/drivers/generic_list.c']

if rtconfig.PLATFORM in ['gcc']:
    group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, ASFLAGS = '$ASFLAGS -D __STARTUP_CLEAR_BSS')
else:
    group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
