Import('rtconfig')
from building import *

cwd = GetCurrentDir()
path = [cwd + '/CMSIS/Include',cwd + '/MIMXRT1171', cwd + '/MIMXRT1171/drivers', cwd + '/MIMXRT1171/periph']
src = Split('''
            MIMXRT1171/drivers/fsl_anatop_ai.c
            MIMXRT1171/system_MIMXRT1171.c
            MIMXRT1171/drivers/fsl_common.c
            MIMXRT1171/drivers/fsl_common_arm.c
            MIMXRT1171/drivers/fsl_dcdc.c
            MIMXRT1171/drivers/fsl_pmu.c
            MIMXRT1171/drivers/fsl_clock.c
            MIMXRT1171/drivers/fsl_cache.c
            MIMXRT1171/drivers/fsl_lpspi.c
            ''')

if rtconfig.PLATFORM in ['gcc']:
    src += ['MIMXRT1171/gcc/startup_MIMXRT1171.S']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['MIMXRT1171/arm/startup_MIMXRT1171.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['MIMXRT1171/iar/startup_MIMXRT1171.s']

if GetDepend(['BSP_USING_GPIO']):
    src += ['MIMXRT1171/drivers/fsl_gpio.c']

if GetDepend(['BSP_USING_LPUART']):
    src += ['MIMXRT1171/drivers/fsl_lpuart.c']

if GetDepend(['BSP_USING_RTC']):
    src += ['MIMXRT1171/drivers/fsl_snvs_hp.c']
    src += ['MIMXRT1171/drivers/fsl_snvs_lp.c']

if GetDepend(['BSP_USING_HWTIMER']) or GetDepend(['BSP_USING_PWM']):
    src += ['MIMXRT1171/drivers/fsl_gpt.c']

if GetDepend(['BSP_USING_PWM']):
    src += ['MIMXRT1171/drivers/fsl_pwm.c']

if GetDepend(['BSP_USING_SDIO']):
    src += ['MIMXRT1171/drivers/fsl_usdhc.c']

if GetDepend(['BSP_USING_SDRAM']):
    src += ['MIMXRT1171/drivers/fsl_semc.c']

if GetDepend(['BSP_USING_ETH']):
    src += ['MIMXRT1171/drivers/fsl_enet.c']

if GetDepend(['BSP_USING_SPI']):
    src += ['MIMXRT1171/drivers/fsl_lpspi.c']

if GetDepend(['RT_SERIAL_USING_DMA']):
    src += ['MIMXRT1171/drivers/fsl_edma.c']
    src += ['MIMXRT1171/drivers/fsl_lpuart_edma.c']

if rtconfig.PLATFORM in ['gcc']:
    group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, ASFLAGS = '$ASFLAGS -D __STARTUP_CLEAR_BSS')
else:
    group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
