import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
''')

path =  [cwd]
path += [cwd + '/ports/lcd']

if GetDepend(['BSP_USING_LVGL']):
    path += [cwd + '/ports/lcd']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
