from building import *
import os

src = []
path = []
cwd = GetCurrentDir()

if not GetDepend('PKG_USING_CMSIS_CORE'):
    path += [os.path.join(cwd, 'include')]

group = DefineGroup('cmsis', src, depend = [''], CPPPATH = path)

Return('group')
