from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include', cwd + '/../../../../components/drivers/serial/device/']

if GetDepend(['RT_SERIAL_PXA']):
    src += ['8250-pxa_k1x.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
