# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend('BSP_USING_HARDLOCK'):
    src += ['drv_hardlock.c']

group = DefineGroup('HARDLOCK', src, depend = [], CPPPATH = CPPPATH)

Return('group')
