
from building import *

cwd  = GetCurrentDir()

CPPPATH = [cwd]

# add general drivers
src = Split('''
board.c
board_config.c
''')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
