import rtconfig
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()

src = Split("""
source/udma_uart_driver.c
""")

if  GetDepend('SOC_RISCV_FAMILY_Core_V'):

    if GetDepend('BSP_USING_UART'):
        src += ['source/drv_usart.c']

path = [
	cwd + '/include']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
