Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')
src = Glob('*.c')
src.append('led/led.c')

CPPPATH = [cwd,
    str(Dir('#')),
    os.path.join(str(Dir('#')), 'freedom-e-sdk/bsp/env'),
    os.path.join(str(Dir('#')), 'freedom-e-sdk/bsp/env/freedom-e300-hifive1'),
    os.path.join(str(Dir('#')), 'freedom-e-sdk/include/sifive/devices'),
    os.path.join(cwd, 'led')]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
