# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = ['timerfd.c']

group = DefineGroup('POSIX', src, depend = ['RT_USING_DFS', 'RT_USING_POSIX_TIMERFD'])

Return('group')
