from building import *
import rtconfig

cwd = GetCurrentDir()
src_c = Glob('*.c')

# add for startup script
if rtconfig.PLATFORM in ['gcc']:
    src_asm = ['start_gcc.S', 'vectors_gcc.S', 'interrupts_gcc.S']
elif rtconfig.PLATFORM in ['iccarm']:
    src_asm = ['cstartup.asm']

src = File(src_c + src_asm)

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
