from building import *

group = []

if not GetDepend(['RT_USING_RESET']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['reset.c']

if GetDepend(['RT_RESET_SIMPLE']):
    src += ['reset-simple.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
