from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include',
           cwd + '/../../../../components/drivers/ethernet/synopsys']

if GetDepend(['RT_ETHERNET_DWMAC_ROCKCHIP']):
    src += ['dwmac-rockchip.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
