import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

# The set of source files associated with this SConscript file.    
if GetDepend(['BSP_USING_USBD']):
#    src += ['src/ht32_usbd_core.c']
#    src += ['src/ht32_usbd_int.c']
    src += ['src/usbd_code.c']
    src += ['src/usb_port.c']

path = [cwd + '/inc']

group = DefineGroup('usbd_library', src, depend = [''], CPPPATH = path)

Return('group')
