from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]

src     = ['core.c', 'early.c', '8250-dw.c', 'fiq-debugger.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
