from building import *

cwd = GetCurrentDir()
src = Glob('*.S')
src	+= Glob('*.c')
path = [cwd]
    
if GetDepend(['CUS_DEMO_BOARD']):
    src += Glob(cwd + '/cus_demo_board/fio_mux.c')
    path += [cwd + '/cus_demo_board/']

group = DefineGroup('Board', src, depend=[
                    ''], CPPPATH=path)

Return('group')
