Import('RTT_ROOT')
Import('rtconfig')
from building import *
import os

cwd = GetCurrentDir()
src = []
path = [cwd, cwd + '/config']

if GetDepend(['BSP_USING_GPIO', 'RT_USING_PIN']):
    src += ['drv_gpio.c']

if GetDepend(['BSP_USING_UART', 'RT_USING_SERIAL']):
    src += ['drv_uart.c']

if GetDepend(['BSP_USING_CAN', 'RT_USING_CAN']):
    src += ['drv_can.c']

if GetDepend(['BSP_USING_ECAP']):
    src += ['drv_ecap.c']

group = DefineGroup('HAL_Drivers', src, depend = [''], CPPPATH = path)

Return('group')
