Import('RTT_ROOT')
Import('rtconfig')
from building import *
import os

cwd = GetCurrentDir()
src = []
path = [cwd, cwd + '/config']

if GetDepend('BSP_USING_GPIO'):
    src += ['drv_gpio.c']

if GetDepend('BSP_USING_UART'):
    src += ['drv_uart.c']

if GetDepend('BSP_USING_CAN'):
    src += ['drv_can.c']

if GetDepend('BSP_USING_ECAP'):
    src += ['drv_ecap.c']

if GetDepend('BSP_USING_TIM'):
    src += ['drv_timer.c']

group = DefineGroup('HAL_Drivers', src, depend = [''], CPPPATH = path)

Return('group')
