Import('RTT_ROOT')
Import('rtconfig')
from building import *
import os

cwd = GetCurrentDir()
src = []
path = [cwd, cwd + '/config']

if GetDepend('BSP_USING_GPIO'):
    src += ['drv_gpio.c']

if GetDepend('BSP_USING_UART'):
    src += ['drv_uart.c']

if GetDepend('BSP_USING_CAN'):
    src += ['drv_can.c']

if GetDepend('BSP_USING_ECAP'):
    src += ['drv_ecap.c']

if GetDepend('BSP_USING_ADC'):
    src += ['drv_adc.c']

if GetDepend('BSP_USING_TIM'):
    src += ['drv_timer.c']

if GetDepend('BSP_USING_SPI'):
    src += ['drv_spi.c']
if GetDepend('BSP_USING_QSPI'):   
    src += ['drv_qspi.c']

if GetDepend('BSP_USING_WDT'):
    src += ['drv_iwdg.c']
    if GetDepend('BSP_USING_WWDG'):
        src += ['drv_wwdg.c']

if GetDepend('BSP_USING_EPWM'):
    src += ['drv_epwm.c']

group = DefineGroup('HAL_Drivers', src, depend = [''], CPPPATH = path)

Return('group')
