from building import *

group = []

if not GetDepend(['RT_USING_REGULATOR']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['regulator.c', 'regulator_dm.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
