from building import *

cwd     = GetCurrentDir()
src     = Split('''
shell.c
msh.c
''')

if GetDepend('MSH_USING_BUILT_IN_COMMANDS'):
    src += ['cmd.c']

if GetDepend('RT_USING_DFS'):
    src += ['msh_file.c']

CPPPATH = [cwd]

group = DefineGroup('msh', src, depend = ['RT_USING_MSH'], CPPPATH = CPPPATH)

Return('group')
