# RT-Thread building script for component

from building import *
import os
cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
""")

# add gpio driver code
if  GetDepend(['BSP_USING_GPIO']):
    src += ['drv_gpio.c']

# add serial driver code
if  GetDepend('BSP_USING_UART0') or GetDepend('BSP_USING_UART1') or GetDepend('BSP_USING_UART2') or GetDepend('BSP_USING_UART3'):
    src += ['drv_uart.c']

# add inter flash fal filesystem
if GetDepend('BSP_USING_INTER_FLASH'):
	src += Glob('ports/*.c')

path_ports = os.path.join(cwd,'ports')
CPPPATH = [cwd,path_ports]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
