from building import *

cwd     = GetCurrentDir()
src     = []

if GetDepend(['BSP_USING_TOUCH']):
    src    += Glob('drv_touch.c')
    src    += Glob('drv_touch_ft.c')

if GetDepend(['BSP_USING_TOUCH_V2']):
    src    += Glob('drv_touch_ft6x36.c')

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
