from building import *

cwd     = GetCurrentDir()
src     = []

if GetDepend(['BSP_USING_TOUCH_FT6206']):
    src    += Glob('drv_touch.c')
    src    += Glob('drv_touch_ft6206.c')

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
