Import('RTT_ROOT')
Import('rtconfig')
from building import *
from gcc import *

cwd = GetCurrentDir()
src = []
group = []
CPPPATH = []

if rtconfig.PLATFORM in ['iccarm'] + GetGCCLikePLATFORM():
    src = Glob('*.c')
    CPPPATH = [cwd+'/fsp_cfg', cwd + '/fsp_cfg/bsp']

group += DefineGroup('RA_cfg', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
