subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/uvc/Include/
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/usb/uvc/drv_webcam/

obj-y += usbWebcam.o
obj-y += usbWebcam_proc.o