Import('rtconfig')
from building import *

cwd = GetCurrentDir()
path = [cwd + '/CMSIS/Include',cwd + '/components/codec', cwd + '/LPC55S6X', cwd + '/LPC55S6X/drivers', cwd + '/middleware/sdmmc/inc', cwd + '/middleware/sdmmc/port']
src = Split('''
            LPC55S6X/system_LPC55S69_cm33_core0.c
            ''')

if rtconfig.CROSS_TOOL == 'gcc':
    src += ['LPC55S6X/gcc/startup_LPC55S69_cm33_core0.S']
elif rtconfig.CROSS_TOOL == 'keil':
    src += ['LPC55S6X/arm/startup_LPC55S69_cm33_core0.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += ['LPC55S6X/iar/startup_LPC55S69_cm33_core0.s']

src += ['LPC55S6X/drivers/fsl_anactrl.c']
src += ['LPC55S6X/drivers/fsl_casper.c']
src += ['LPC55S6X/drivers/fsl_clock.c']
src += ['LPC55S6X/drivers/fsl_cmp.c']
src += ['LPC55S6X/drivers/fsl_common.c']
src += ['LPC55S6X/drivers/fsl_crc.c']
src += ['LPC55S6X/drivers/fsl_ctimer.c']
src += ['LPC55S6X/drivers/fsl_flexcomm.c']
src += ['LPC55S6X/drivers/fsl_dma.c']
src += ['LPC55S6X/drivers/fsl_gint.c']
src += ['LPC55S6X/drivers/fsl_gpio.c']
src += ['LPC55S6X/drivers/fsl_hashcrypt.c']
src += ['LPC55S6X/drivers/fsl_i2c.c']
src += ['LPC55S6X/drivers/fsl_i2c_dma.c']
src += ['LPC55S6X/drivers/fsl_i2s.c']
src += ['LPC55S6X/drivers/fsl_i2s_dma.c']
src += ['LPC55S6X/drivers/fsl_iap.c']
src += ['LPC55S6X/drivers/fsl_inputmux.c']
src += ['LPC55S6X/drivers/fsl_lpadc.c']
src += ['LPC55S6X/drivers/fsl_mrt.c']
src += ['LPC55S6X/drivers/fsl_ostimer.c']
src += ['LPC55S6X/drivers/fsl_pint.c']
src += ['LPC55S6X/drivers/fsl_plu.c']
src += ['LPC55S6X/drivers/fsl_power.c']
src += ['LPC55S6X/drivers/fsl_powerquad_basic.c']
src += ['LPC55S6X/drivers/fsl_prince.c']
src += ['LPC55S6X/drivers/fsl_puf.c']
src += ['LPC55S6X/drivers/fsl_reset.c']
src += ['LPC55S6X/drivers/fsl_rng.c']
src += ['LPC55S6X/drivers/fsl_rtc.c']
src += ['LPC55S6X/drivers/fsl_sctimer.c']
src += ['LPC55S6X/drivers/fsl_sdif.c']
src += ['LPC55S6X/drivers/fsl_spi.c']
src += ['LPC55S6X/drivers/fsl_spi_dma.c']
src += ['LPC55S6X/drivers/fsl_sysctl.c']
src += ['LPC55S6X/drivers/fsl_usart.c']
src += ['LPC55S6X/drivers/fsl_usart_dma.c']
src += ['LPC55S6X/drivers/fsl_utick.c']
src += ['LPC55S6X/drivers/fsl_wwdt.c']
src += ['middleware/sdmmc/src/fsl_sd.c']
src += ['middleware/sdmmc/src/fsl_sdmmc_common.c']
src += ['middleware/sdmmc/port/sdif/rt_thread/fsl_sdmmc_event.c']
src += ['middleware/sdmmc/port/sdif/rt_thread/fsl_sdmmc_host.c']

if rtconfig.CROSS_TOOL == 'gcc':
    src += ['LPC55S6X/gcc/libpower_hardabi.a']
elif rtconfig.CROSS_TOOL == 'keil':
    src += ['LPC55S6X/arm/keil_lib_power_cm33_core0.lib']
elif rtconfig.CROSS_TOOL == 'iar':
    src += ['LPC55S6X/iar/iar_lib_power_cm33_core0.a']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
