from building import *

group = []

if not GetDepend(['RT_PCI_ENDPOINT']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src = ['endpoint.c', 'mem.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
