# RT-Thread building script for component

from building import *
Import('rtconfig')

cwd = GetCurrentDir()
src = Glob('*.cpp') + Glob('*.c')

CPPPATH = [cwd]

if rtconfig.PLATFORM == 'armclang' and GetDepend('RT_USING_CPLUSPLUS11'):
    src += Glob('armclang/*.cpp') + Glob('armclang/*.c')
    CPPPATH += [cwd + '/armclang']
elif rtconfig.PLATFORM == 'gcc' and GetDepend('RT_USING_CPLUSPLUS11'):
    src += Glob('gcc/*.cpp') + Glob('gcc/*.c')
    CPPPATH += [cwd + '/gcc']

group = DefineGroup('CPlusPlus', src, depend = ['RT_USING_CPLUSPLUS'], CPPPATH = CPPPATH)

Return('group')