Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'DbHelper')

src = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]
group = DefineGroup('DbHelper', src, depend = ['PKG_USING_SQLITE'], CPPPATH = CPPPATH)
Return('group')
