from building import *

cwd  = GetCurrentDir()
src  = ['system_MCIMX6Y2.c'] + Glob('drivers/*.c')
CPPDEFINES = ['CHIP_MX6UL', 'CPU_MCIMX6Y2DVM09']
path = [cwd, cwd + '/drivers']

src += Glob('drivers/usdhc/*.c')
path.append(cwd + '/drivers/usdhc')

group = DefineGroup('libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
