import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
""")

path = [cwd + '/Include',]

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = path)

Return('group')
