# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Split('''
src/hal_atomic.c
src/hal_cache.c
src/hal_interrupt.c
src/hal_mem.c
src/hal_mutex.c
src/hal_queue.c
src/hal_sem.c
src/hal_thread.c
src/hal_timer.c
src/hal_cfg.c
''')

CPPPATH = [cwd, cwd + '/../hal']
LOCAL_CPPDEFINES = []
LOCAL_CCFLAGS = ' -include %s/../hal/kconfig.h' % cwd

group = DefineGroup('hal', src, depend = [''], CPPPATH = CPPPATH, LOCAL_CPPDEFINES = LOCAL_CPPDEFINES, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
