scons.args: &scons
  scons_arg:
    - '--strict'

devices.dm.all:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_DM=y
    - CONFIG_RT_USING_OFW=y
    - CONFIG_RT_USING_RESET=y
    - CONFIG_RT_USING_PIN=y
    - CONFIG_RT_USING_PINCTRL=y
    - CONFIG_RT_USING_CLK=y
    - CONFIG_RT_USING_REGULATOR=y
    - CONFIG_RT_USING_PIC=y
    - CONFIG_RT_USING_MFD=y
    - CONFIG_RT_MFD_SYSCON=y
    - CONFIG_RT_MFD_RK8XX=y
    - CONFIG_RT_USING_ADC=y
    - CONFIG_RT_ADC_ROCKCHIP_SARADC=y
    - CONFIG_RT_USING_CAN=y
    - CONFIG_RT_CAN_USING_CANFD=y
    - CONFIG_RT_CAN_CANFD_ROCKCHIP=y
    - CONFIG_RT_USING_CLOCK_TIME=y
    - CONFIG_RT_CLOCK_TIMER_ROCKCHIP=y
    - CONFIG_RT_USING_I2C=y
    - CONFIG_RT_I2C_RK3X=y
    - CONFIG_RT_USING_PWM=y
    - CONFIG_RT_PWM_ROCKCHIP=y
    - CONFIG_RT_USING_RTC=y
    - CONFIG_RT_RTC_RK8XX=y
    - CONFIG_RT_RTC_RK_TIMER=y
    - CONFIG_RT_USING_SDIO=y
    - CONFIG_RT_SDIO_DW_MMC=y
    - CONFIG_RT_SDIO_DW_MMC_ROCKCHIP=y
    - CONFIG_RT_USING_SPI=y
    - CONFIG_RT_USING_QSPI=y
    - CONFIG_RT_USING_DMA=y
    - CONFIG_RT_SPI_ROCKCHIP=y
    - CONFIG_RT_SPI_ROCKCHIP_SFC=y
    - CONFIG_RT_USING_WDT=y
    - CONFIG_RT_WDT_RK8XX=y
    - CONFIG_RT_USING_HWCRYPTO=y
    - CONFIG_RT_HWCRYPTO_USING_RNG=y
    - CONFIG_RT_HWCRYPTO_RNG_ROCKCHIP=y
    - CONFIG_RT_USING_INPUT=y
    - CONFIG_RT_INPUT_MISC=y
    - CONFIG_RT_INPUT_MISC_PWRKEY_RK8XX=y
    - CONFIG_RT_USING_MBOX=y
    - CONFIG_RT_MBOX_ROCKCHIP=y
    - CONFIG_RT_USING_HWSPINLOCK=y
    - CONFIG_RT_HWSPINLOCK_ROCKCHIP=y
    - CONFIG_RT_USING_PHYE=y
    - CONFIG_RT_PHYE_ROCKCHIP_NANENG_COMBO=y
    - CONFIG_RT_PHYE_ROCKCHIP_SNPS_PCIE3=y
    - CONFIG_RT_MFD_RK8XX_I2C=y
    - CONFIG_RT_MFD_RK8XX_SPI=y
    - CONFIG_RT_REGULATOR_RK8XX=y
    - CONFIG_RT_PMDOMAIN_ROCKCHIP=y
    - CONFIG_RT_USING_THERMAL=y
    - CONFIG_RT_THERMAL_ROCKCHIP_TSADC=y
    - CONFIG_RT_USING_NVMEM=y
    - CONFIG_RT_NVMEM_ROCKCHIP_OTP=y
    - CONFIG_RT_USING_PCI=y
    - CONFIG_RT_PCI_DW=y
    - CONFIG_RT_PCI_DW_ROCKCHIP=y
    - CONFIG_RT_PIN_ROCKCHIP=y
    - CONFIG_RT_PINCTRL_ROCKCHIP_RK8XX=y
    - CONFIG_RT_PINCTRL_ROCKCHIP=y
    - CONFIG_RT_CLK_ROCKCHIP_RK8XX_CLKOUT=y
    - CONFIG_RT_CLK_ROCKCHIP_LINK=y
    - CONFIG_RT_CLK_ROCKCHIP=y
    - CONFIG_RT_CLK_ROCKCHIP_RK3308=y
    - CONFIG_RT_CLK_ROCKCHIP_RK3528=y
    - CONFIG_RT_CLK_ROCKCHIP_RK3568=y
    - CONFIG_RT_CLK_ROCKCHIP_RK3576=y
    - CONFIG_RT_CLK_ROCKCHIP_RK3588=y
    - CONFIG_RT_SOC_ROCKCHIP_FIQ_DEBUGGER=y
    - CONFIG_RT_SOC_ROCKCHIP_GRF=y
    - CONFIG_RT_SOC_ROCKCHIP_HW_DECOMPRESS=y
    - CONFIG_RT_SOC_ROCKCHIP_IODOMAIN=y
