scons.args: &scons
  scons_arg:
    - '--strict'

devices.spi:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_SPI=y
    - CONFIG_RT_USING_QSPI=y
    - CONFIG_RT_USING_DMA=y
    - CONFIG_RT_USING_PIN=y
    - CONFIG_RT_USING_PINCTRL=y
    - CONFIG_RT_SPI_ROCKCHIP=y
    - CONFIG_RT_SPI_ROCKCHIP_SFC=y
