from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
MCUX_Config/board/clock_config.c
MCUX_Config/board/pin_mux.c
""")

CPPPATH = [cwd,cwd + '/MCUX_Config/board']
CPPDEFINES = ['CPU_LPC55S69JBD100_cm33_core0']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
