# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Split('''
sfnt.c
''')
CPPPATH = [cwd]

group = DefineGroup('freetype', src, depend = ['RTGUI_USING_TTF'], CPPPATH = CPPPATH)

Return('group')
