import rtconfig
from building import *

cwd = GetCurrentDir()
src = Glob('main.c')
CPPPATH = [cwd]

# add for startup script
if rtconfig.PLATFORM in ['gcc']:
    CPPDEFINES = ['__START=entry']
else:
    CPPDEFINES = []

if  GetDepend('BSP_USING_SDIO'):
    src += ['mnt.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
