from building import *

group = []

if not GetDepend(['RT_INPUT_JOYSTICK']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src = []

if GetDepend(['RT_INPUT_JOYSTICK_ADC']):
    src += ['js-adc.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
