devices.gpio:
    kconfig: 
    - CONFIG_BSP_USING_GPIO=y
devices.adc:
    kconfig:
      - CONFIG_BSP_USING_SAADC=y
devices.i2c:
    kconfig:
      - CONFIG_BSP_USING_I2C=y
      - CONFIG_BSP_USING_I2C0=n
      - CONFIG_BSP_USING_I2C1=n
      - CONFIG_BSP_USING_I2C2=y
devices.spi:
    kconfig:
      - CONFIG_BSP_USING_SPI=y
      - CONFIG_BSP_USING_SPI0=n
      - CONFIG_BSP_USING_SPI1=n
      - CONFIG_BSP_USING_SPI2=y
devices.uart:
    kconfig:
      - CONFIG_BSP_USING_UART=y
devices.watchdog:
    kconfig:
      - CONFIG_BSP_USING_WDT=y
devices.pwm:
    kconfig:
      - CONFIG_BSP_USING_PWM=y
devices.rtc:
    kconfig:
      - CONFIG_BSP_USING_ONCHIP_RTC=y
devices.hwtimer:
    kconfig:
      - CONFIG_BSP_USING_TIM=y
      - CONFIG_BSP_USING_TIM1=y
# ------ SEGGER CI ------
segger:
    kconfig:
      - CONFIG_PKG_USING_SEGGER_RTT=y
      - CONFIG_RT_USING_SERIAL_V1=y