# RT-Thread building script for FreeType

from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = [ cwd,
            cwd + '/freetype',
            cwd + '/freetype/config',
            cwd + '/freetype/internal',
            cwd + '/freetype/internal/services']

group = DefineGroup('FreeType', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
