from building import *

group = []

if not GetDepend(['RT_USING_HWTIMER']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['hwtimer.c']

if GetDepend(['RT_HWTIMER_ARM_ARCH']):
    src += ['hwtimer-arm_arch.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
