import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = []

src += Glob('ES32F033x_ALD_StdPeriph_Driver/Source/*.c')

#add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
     src = src + ['CMSIS/Device/EastSoft/es32f033x/Startup/gcc/startup_es32f033x.s']
elif rtconfig.CROSS_TOOL == 'keil':
     src = src + ['CMSIS/Device/EastSoft/es32f033x/Startup/keil/startup_es32f033x.s']
elif rtconfig.CROSS_TOOL == 'iar':
     src = src + ['CMSIS/Device/EastSoft/es32f033x/Startup/iar/startup_es32f033x.s']

path = [cwd + '/CMSIS/Device/EastSoft/es32f033x/Include',
        cwd + '/CMSIS/Include',
        cwd + '/ES32F033x_ALD_StdPeriph_Driver/Include']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = ['ES32F033x'])

Return('group')
