import os
from building import *
Import('rtconfig')

cwd = GetCurrentDir()

src = Split('''
board.c
CubeMX_Config/Appli/Src/secure_nsc.c
CubeMX_Config/Appli/Src/stm32n6xx_hal_msp.c
''')

path = [cwd]
path += [os.path.join(cwd, 'CubeMX_Config', 'Appli', 'Inc')]
path += [os.path.join(cwd, 'CubeMX_Config', 'Secure_nsclib')]

# STM32N657xx
# You can select chips from the list above
CPPDEFINES = ['STM32N657xx']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
