from building import *
import rtconfig

cwd     = GetCurrentDir()

src	= [cwd + '/sys_config/sys_config.c']
src += [cwd + '/mss_gpio/mss_gpio.c']
src += [cwd + '/mss_uart/mss_uart.c']

CPPPATH = [cwd+'/sys_config']
CPPPATH += [cwd+'/mss_gpio']
CPPPATH += [cwd+'/mss_uart']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
