Import('RTT_ROOT')
Import('rtconfig')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
CME_M7/system_cmem7.c
""")

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    src += ['CME_M7/startup/gcc/startup_CME_M7.c']
elif rtconfig.CROSS_TOOL == 'keil':
    src += ['CME_M7/startup/arm/startup_cmem7.s']
elif rtconfig.CROSS_TOOL == 'iar':
    print('================ERROR============================')
    print('Not support IAR yet!')
    print('=================================================')
    exit(0)

path = [cwd + '/CME_M7']

path += [cwd + '/CMSIS/Include']

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = path)

Return('group')
