Import('RTT_ROOT')
Import('rtconfig')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
CME_M7/system_cmem7.c
""")

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    src += ['Device/Nuvoton/NUC472_442/Source/GCC/startup_NUC472_442.c']
elif rtconfig.CROSS_TOOL == 'keil':
    src += ['CME_M7/startup/arm/startup_cmem7.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += ['Device/Nuvoton/NUC472_442/Source/IAR/startup_NUC472_442.S']

path = [cwd + '/CME_M7']
#ath += [cwd + '/StdDriver/inc']

# if GetDepend(['RT_USING_BSP_CMSIS']):
    # path += [cwd + '/CMSIS/Include']
# elif GetDepend(['RT_USING_RTT_CMSIS']):
    # path += [RTT_ROOT + '/components/CMSIS/Include']

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = path)

Return('group')
