import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
CMSIS/GD/GD32F5xx/Source/system_gd32f5xx.c
GD32F5xx_standard_peripheral/Source/gd32f5xx_gpio.c
GD32F5xx_standard_peripheral/Source/gd32f5xx_rcu.c
GD32F5xx_standard_peripheral/Source/gd32f5xx_dma.c
GD32F5xx_standard_peripheral/Source/gd32f5xx_exti.c
GD32F5xx_standard_peripheral/Source/gd32f5xx_misc.c
GD32F5xx_standard_peripheral/Source/gd32f5xx_syscfg.c
''')

if GetDepend(['RT_USING_SERIAL']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_usart.c']

if GetDepend(['RT_USING_I2C']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_spi.c']

if GetDepend(['RT_USING_CAN']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_can.c']

if GetDepend(['BSP_USING_ETH']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_enet.c']

if GetDepend(['RT_USING_ADC']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_adc.c']

if GetDepend(['RT_USING_DAC']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_dac.c']

if GetDepend(['RT_USING_RTC']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_rtc.c']
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_pmu.c']

if GetDepend(['RT_USING_WDT']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_wwdgt.c']
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_fwdgt.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_sdio.c']
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_dma.c']

if GetDepend(['BSP_USING_SDRAM']):
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_fmc.c']
    src += ['GD32F5xx_standard_peripheral/Source/gd32f5xx_exmc.c']

path = [
    cwd + '/CMSIS/GD/GD32F5xx/Include',
    cwd + '/CMSIS',
    cwd + '/GD32F5xx_standard_peripheral/Include',]

CPPDEFINES = ['USE_STDPERIPH_DRIVER']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
