import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
CMSIS/Device/ST/STM32H7RSxx/Source/Templates/system_stm32h7rsxx.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_cec.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_cortex.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_crc.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_crc_ex.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_cryp.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_cryp_ex.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_dma.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_dma_ex.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_pwr.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_pwr_ex.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_rcc.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_rcc_ex.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_rng.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_sram.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_gpio.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_adc.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_adc_ex.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_xspi.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_flash.c
STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_flash_ex.c
''')

if GetDepend(['RT_USING_SERIAL']) or GetDepend(['RT_USING_NANO', 'RT_USING_CONSOLE']):
    src += ['STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_uart.c']
    src += ['STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_usart.c']
    src += ['STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_uart_ex.c']


path = [cwd + '/STM32H7RSxx_HAL_Driver/Inc',
    cwd + '/CMSIS/Device/ST/STM32H7RSxx/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')

