from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
drv_flexspi.c
""")

CPPPATH = [cwd]
CPPDEFINES = []

if GetDepend('PKG_USING_EASYFLASH'):
    src += ['ports/ef_fal_port.c'] 

if GetDepend('PKG_USING_FAL'):
    src += ['ports/fal_flexspi_nor_flash_port.c'] 

if GetDepend('PKG_USING_FAL') and GetDepend('PKG_USING_EASYFLASH'):
    src += ['ports/fal_flash_init.c', 'ports/ef_update.c'] 

CPPPATH += [cwd + '/ports']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
