Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'lib')
src	= Glob('./src/*.c')

src += Glob('./src/*.s')
path = [cwd + '/inc'
	]

CPPDEFINES = ['NV32', 'KEIL']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
