from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

# remove no need file.
if GetDepend('RT_USING_LWIP') == False:
    SrcRemove(src, 'emac.c')

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
