scons.args: &scons
    scons_arg:
      - '--strict'
# ------ nano CI ------
nano:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_NANO=y
# ------ kernel CI ------
kernel.klibc-stdlib:
    <<: *scons
    kconfig:
      - CONFIG_RT_KLIBC_USING_STDLIB=y
      - CONFIG_RT_KLIBC_USING_STDLIB_MEMORY=y
kernel.klibc-tinysize:
    <<: *scons
    kconfig:
      - CONFIG_RT_KLIBC_USING_TINY_SIZE=y
kernel.klibc-vsnprintf-std:
    <<: *scons
    kconfig:
      - CONFIG_RT_KLIBC_USING_VSNPRINTF_STANDARD=y
      - CONFIG_RT_KLIBC_USING_PRINTF_LONGLONG=y
      - CONFIG_RT_KLIBC_USING_VSNPRINTF_DECIMAL_SPECIFIERS=y
      - CONFIG_RT_KLIBC_USING_VSNPRINTF_EXPONENTIAL_SPECIFIERS=y
      - CONFIG_RT_KLIBC_USING_VSNPRINTF_WRITEBACK_SPECIFIER=y
      - CONFIG_RT_KLIBC_USING_VSNPRINTF_CHECK_NUL_IN_FORMAT_SPECIFIER=y
      - CONFIG_RT_KLIBC_USING_VSNPRINTF_MSVC_STYLE_INTEGER_SPECIFIERS=y
# ------ online-packages CI ------
online-packages.iot.at_devices:
    <<: *scons
    kconfig:
      - CONFIG_PKG_USING_AT_DEVICE=y
      # Quectel M26/MC20
      - CONFIG_AT_DEVICE_USING_M26=y
      - CONFIG_AT_DEVICE_M26_INIT_ASYN=y
      # Quectel EC20
      - CONFIG_AT_DEVICE_USING_EC20=y
      - CONFIG_AT_DEVICE_EC20_INIT_ASYN=y
      # Espressif ESP32
      - CONFIG_AT_DEVICE_USING_ESP32=y
      - CONFIG_AT_DEVICE_ESP32_INIT_ASYN=y
      # Espressif ESP8266
      - CONFIG_AT_DEVICE_USING_ESP8266=y
      - CONFIG_AT_DEVICE_ESP8266_INIT_ASYN=y
      # Realthread RW007
      - CONFIG_AT_DEVICE_USING_RW007=y
      - CONFIG_AT_DEVICE_RW007_INIT_ASYN=y
      # SIMCom SIM800C
      - CONFIG_AT_DEVICE_USING_SIM800C=y
      - CONFIG_AT_DEVICE_SIM800C_INIT_ASYN=y
      # SIMCom SIM76XX
      - CONFIG_AT_DEVICE_USING_SIM76XX=y
      - CONFIG_AT_DEVICE_SIM76XX_INIT_ASYN=y
      # Notion MW31
      - CONFIG_AT_DEVICE_USING_MW31=y
      - CONFIG_AT_DEVICE_MW31_INIT_ASYN=y
      # WinnerMicro W60X
      - CONFIG_AT_DEVICE_USING_W60X=y
      - CONFIG_AT_DEVICE_W60X_INIT_ASYN=y
      # Ai-Think A9G
      - CONFIG_AT_DEVICE_USING_A9G=y
      - CONFIG_AT_DEVICE_A9G_INIT_ASYN=y
      # Quectel BC26
      - CONFIG_AT_DEVICE_USING_BC26=y
      - CONFIG_AT_DEVICE_BC26_INIT_ASYN=y
      # luat Air720
      - CONFIG_AT_DEVICE_USING_AIR720=y
      - CONFIG_AT_DEVICE_AIR720_INIT_ASYN=y
      # Gosuncn ME3616
      - CONFIG_AT_DEVICE_USING_ME3616=y
      - CONFIG_AT_DEVICE_ME3616_INIT_ASYN=y
      # ChinaMobile M6315
      - CONFIG_AT_DEVICE_USING_M6315=y
      - CONFIG_AT_DEVICE_M6315_INIT_ASYN=y
      # Quectel BC28
      - CONFIG_AT_DEVICE_USING_BC28=y
      - CONFIG_AT_DEVICE_BC28_INIT_ASYN=y
      # Quectel EC200T/EC200S
      - CONFIG_AT_DEVICE_USING_EC200X=y
      - CONFIG_AT_DEVICE_EC200X_INIT_ASYN=y
      # Neoway N21
      - CONFIG_AT_DEVICE_USING_N21=y
      - CONFIG_AT_DEVICE_N21_INIT_ASYN=y
      # Neoway N58
      - CONFIG_AT_DEVICE_USING_N58=y
      - CONFIG_AT_DEVICE_N58_INIT_ASYN=y
      # ChinaMobile M5311
      - CONFIG_AT_DEVICE_USING_M5311=y
      - CONFIG_AT_DEVICE_M5311_INIT_ASYN=y
      # Fibocom L610
      - CONFIG_AT_DEVICE_USING_L610=y
      - CONFIG_AT_DEVICE_L610_INIT_ASYN=y
      # Neoway N720
      - CONFIG_AT_DEVICE_USING_N720=y
      - CONFIG_AT_DEVICE_N720_INIT_ASYN=y
      # Gosuncn ML305
      - CONFIG_AT_DEVICE_USING_ML305=y
      - CONFIG_AT_DEVICE_ML305_INIT_ASYN=y
online-packages.misc.misc:
    <<: *scons
    kconfig:
      - CONFIG_PKG_USING_MULTIBUTTON=y
online-packages.misc.vi:
    <<: *scons
    kconfig:
      - CONFIG_PKG_USING_VI=y
      # - CONFIG_VI_ENABLE_8BIT=y
      - CONFIG_VI_ENABLE_COLON=y
      - CONFIG_VI_ENABLE_COLON_EXPAND=y
      - CONFIG_VI_ENABLE_YANKMARK=y
      - CONFIG_VI_ENABLE_SEARCH=y
      - CONFIG_VI_ENABLE_DOT_CMD=y
      - CONFIG_VI_ENABLE_READONLY=y
      - CONFIG_VI_ENABLE_SETOPTS=y
      - CONFIG_VI_ENABLE_SET=y
      - CONFIG_VI_ENABLE_WIN_RESIZE=y
      - CONFIG_VI_ENABLE_VI_ASK_TERMINAL=y
      - CONFIG_VI_ENABLE_UNDO=y
      - CONFIG_VI_ENABLE_UNDO_QUEUE=y
      - CONFIG_VI_ENABLE_VERBOSE_STATUS=y
online-packages.multimedia.lvgl-v8.3-latest:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_LVGL=y
      - CONFIG_BSP_USING_LVGL_DEMO=y
      - CONFIG_PKG_LVGL_USING_V8_3_LATEST=y
online-packages.multimedia.lvgl-v8.3.11:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_LVGL=y
      - CONFIG_BSP_USING_LVGL_DEMO=y
      - CONFIG_PKG_LVGL_USING_V080311=y
online-packages.multimedia.lvgl-v8.4-latest:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_LVGL=y
      - CONFIG_BSP_USING_LVGL_DEMO=y
      - CONFIG_PKG_LVGL_USING_V8_4_LATEST=y
online-packages.system.enhanced-kservice:
    <<: *scons
    kconfig:
      - CONFIG_PKG_USING_RT_KPRINTF_THREADSAFE=y
      - CONFIG_PKG_USING_RT_MEMCPY_CM=y
online-packages.system.os-wrappers:
    <<: *scons
    kconfig:
      - CONFIG_PKG_USING_FREERTOS_WRAPPER=y
online-packages.ai.llmchat:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_RW007_WLAN=y
      - CONFIG_WEBCLIENT_USING_MBED_TLS=y
      - CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=6144
      - CONFIG_PKG_USING_LLMCHAT=y
      - CONFIG_PKG_USING_LLMCHAT_LATEST_VERSION=y
# ------ peripheral CI ------
peripheral.aht21:
    kconfig:
      - CONFIG_BSP_USING_AHT21=y
peripheral.ap3216c:
    kconfig:
      - CONFIG_BSP_USING_AP3216C=y
peripheral.ethernet_28j60:
    kconfig:
      - CONFIG_BSP_USING_ENC28j60=y
peripheral.fal_easyflash:
    kconfig:
      - CONFIG_BSP_USING_EASYFLASH=y
peripheral.filesystem:
    kconfig:
      - CONFIG_BSP_USING_FS=y
      - CONFIG_BSP_USING_FLASH_FATFS=y
peripheral.icm20608:
    kconfig:
      - CONFIG_BSP_USING_ICM20608=y
peripheral.lcd_st7787:
    kconfig:
      - CONFIG_BSP_USING_ONBOARD_LCD=y
peripheral.led_matrix:
    kconfig:
      - CONFIG_BSP_USING_ONBOARD_LED_MATRIX=y
peripheral.rs485:
    kconfig:
      - CONFIG_BSP_USING_RS485=y
peripheral.rw007:
    kconfig:
      - CONFIG_BSP_USING_RW007_WLAN=y
peripheral.spi_flash_w25q64:
    kconfig:
      - CONFIG_BSP_USING_SPI_FLASH=y
peripheral.sram:
    kconfig:
      - CONFIG_BSP_USING_SRAM=y
peripheral.usb_mouse:
    kconfig:
      - CONFIG_BSP_USING_USB_MOUSE=y
# ------ component CI ------
component.cherryusb_cdc:
    kconfig:
      - CONFIG_RT_USING_CHERRYUSB=y
      - CONFIG_RT_CHERRYUSB_DEVICE=y
      - CONFIG_RT_CHERRYUSB_DEVICE_DWC2_ST=y
      - CONFIG_RT_CHERRYUSB_DEVICE_CDC_ACM=y
      - CONFIG_RT_CHERRYUSB_DEVICE_TEMPLATE_CDC_ACM=y
