# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
drv_uart.c
drv_io_config.c
dmalock.c
''')
CPPPATH = [cwd]

if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']

if GetDepend('BSP_USING_LCD'):
    src += ['drv_lcd.c']
    src += ['drv_mpylcd.c']
    src += ['test/lcd_test.c']

if GetDepend('RT_USING_HWTIMER'):
    src += ['drv_hw_timer.c']

if GetDepend('RT_USING_CPUTIME'):
    src += ['drv_cputime.c']

if GetDepend('RT_USING_I2C'):
    src += ['drv_i2c.c']

if GetDepend('RT_USING_SPI'):
    src += ['drv_spi.c']

if GetDepend('RT_USING_PWM'):
    src += ['drv_pwm.c']

if GetDepend('RT_USING_WDT'):
    src += ['drv_wdt.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=['NNCASE_NO_EXCEPTIONS'])

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
