import rtconfig
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

#remove other no use files
if GetDepend('SAM_CAN_EXAMPLE') == False:
    SrcRemove(src, ['can_demo.c'])

if GetDepend('SAM_I2C_EXAMPLE') == False:
    SrcRemove(src, ['i2c_demo.c'])

if GetDepend('SAM_ADC_EXAMPLE') == False:
    SrcRemove(src, ['adc_demo.c'])

if GetDepend('SAM_LWIP_EXAMPLE') == False:
    SrcRemove(src, ['lwip_demo.c'])

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
