import os
import sys
import rtconfig

if os.getenv('RTT_ROOT'):
    RTT_ROOT = os.getenv('RTT_ROOT')
else:
    RTT_ROOT = os.path.normpath(os.getcwd() + '/../../..')

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
try:
    from building import *
except:
    print('Cannot found RT-Thread root directory, please check RTT_ROOT')
    print(RTT_ROOT)
    exit(-1)

TARGET = 'rtthread.' + rtconfig.TARGET_EXT

DefaultEnvironment(tools=[])
env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CFLAGS = rtconfig.CFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)

if rtconfig.PLATFORM in ['iccarm']:
    env.Replace(CCCOM = ['$CC $CFLAGS $CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS -o $TARGET $SOURCES'])
    env.Replace(ARFLAGS = [''])
    env.Replace(LINKCOM = env["LINKCOM"] + ' --map project.map')

Export('RTT_ROOT')
Export('rtconfig')

SDK_ROOT = os.path.abspath('./')
libraries_path_prefix = os.path.join(os.path.dirname(SDK_ROOT), 'libraries')

f327x_cmsis_path = os.path.join(SDK_ROOT, 'packages', 'mm32f3270x-cmsis-latest', 'CMSIS')
f327x_hal_path = os.path.join(SDK_ROOT, 'packages', 'mm32f3270x-hal-driver-latest')
if os.path.isdir(f327x_hal_path):
    env.AppendUnique(CPPPATH=[
        os.path.join(f327x_cmsis_path, 'Include'),
        os.path.join(f327x_cmsis_path, 'Device', 'MM32', 'MM32F3277', 'Include'),
        os.path.join(f327x_hal_path, 'Inc'),
    ])

# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT, has_libcpu=False)

# include drivers
objs.extend(SConscript(os.path.join(libraries_path_prefix, 'HAL_Drivers', 'SConscript'),
                       variant_dir='build/libraries/HAL_Drivers', duplicate=0))

# make a building
DoBuilding(TARGET, objs)
