# RT-Thread building script for component

Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Glob('drivers/*.c')

SrcRemove(src, 'drivers/dataqueue.c')
src += Glob('common/chip/*.c')
src += [cwd + '/system_MIMXRT1021.c']

CPPPATH = [ cwd, cwd + '/drivers', cwd + '/utilities', cwd + '/CMSIS/Include']
CPPDEFINES = ['CPU_MIMXRT1021DAG5A', 'EVK_MCIMXRM', 'FSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1']

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    src += [cwd + '/gcc/startup_MIMXRT1021.S']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [cwd + '/arm/startup_MIMXRT1021.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += [cwd + '/iar/startup_MIMXRT1021.s']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
