include $(SDK_ROOT)/mk/common.mk


# Export the target library name to all child make invocations.
TARGET_LIB_NAME = sdk
export TARGET_LIB_NAME


SUBDIRS = \
	drivers \
	common \
	core \
	utility


include $(SDK_ROOT)/mk/targets.mk
