Import('ES32_SDK_ROOT')

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
include_path  = [cwd]

group = DefineGroup('CMSIS2', src, depend = [''], CPPPATH = include_path)

Return('group')
