from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
SrcRemove(src, ['debug.c'])
path = [cwd]

libcwd = str(Dir('#'))
libinspath = libcwd + '/libraries/lib'

group = DefineGroup('gnu_c', src, depend = [''], CPPPATH = path, LIBINSPATH = libinspath)

Return('group')
