import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
debug.c
ch32v10x_it.c
software_irq.c
''')

path =  [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)
Return('group')
