# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
    board.c
    interrupt.c
    startup_gcc.S
''')
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
