import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = []

src += Glob('ES32F065x_ALD_StdPeriph_Driver/Source/*.c')


#add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
     src = src + ['CMSIS/Device/EastSoft/ES32F065x/Startup/gcc/startup_es32f065x.s']
elif rtconfig.CROSS_TOOL == 'keil':
     src = src + ['CMSIS/Device/EastSoft/ES32F065x/Startup/keil/startup_es32f065x.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src = src + ['CMSIS/Device/EastSoft/ES32F065x/Startup/iar/startup_es32f065x.s']

path = [cwd + '/CMSIS/Device/EastSoft/ES32F065x/Include', 
    cwd + '/CMSIS/Include',
    cwd + '/ES32F065x_ALD_StdPeriph_Driver/Include']

#CPPDEFINES = ['USE_STDPERIPH_DRIVER', rtconfig.STM32_TYPE]
# CPPDEFINES = ['USE_STDPERIPH_DRIVER']
group = DefineGroup('ES32F065x_StdPeriph', src, depend = [''], CPPPATH = path)

Return('group')
