import rtconfig
from building import *
import os

cwd = GetCurrentDir()

src = Split("""
main.c
""")

CPPPATH = [cwd]

# add for startup script
if rtconfig.PLATFORM in ['gcc']:
    CPPDEFINES = ['__START=entry']
else:
    CPPDEFINES = []

if GetDepend(['BSP_USE_MULTICORE']):
    src += Split("""
    multicore_thread.c
    """)

if GetDepend(['BSP_USING_ETHERCAT']):
    src += Split("""
    ecat_thread.c
    """)

if GetDepend(['BSP_USING_FS']):
    src += Split("""
    mnt.c
    """)

# Create application group
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
