from building import *

cwd  = GetCurrentDir()
objs = []

for d in os.listdir(os.path.join(cwd, '..')):
    if d not in ('M0', 'M4'):
        path = os.path.join(cwd, '..', d, 'SConscript')
        if os.path.isfile(path):
            objs = objs + SConscript(path)

for d in os.listdir(cwd):
    p = os.path.join(cwd, d, 'SConscript');
    if os.path.isfile(p):
        objs = objs + SConscript(p)

Return('objs')
