Import('rtconfig')
from building import *

cwd = GetCurrentDir()

LIBS    = []
LIBPATH = []
src = []

LIBPATH = [cwd]
if rtconfig.CROSS_TOOL == 'gcc':
    LIBS += ['wifi_6212_armcm7_2.1.2_gcc']
elif rtconfig.CROSS_TOOL == 'keil':
    LIBS += ['libwifi_6212_armcm7_2.1.2_armcc']

path = [cwd]

group = DefineGroup('WICED', src, depend = ['ART_PI_USING_WIFI_6212_LIB'], CPPPATH = path, LIBS = LIBS, LIBPATH = LIBPATH)

Return('group')
