subdir-ccflags-y +=     -I$(srctree)/ekernel/drivers/hal/source/usb/storage/include
subdir-ccflags-y +=     -I$(srctree)/ekernel/drivers/hal/source/usb/include

obj-y += usbh_buff_manager.o
obj-y += usbh_disk_info.o
obj-y += usbh_disk_remove_time.o