scons.args: &scons
    scons_arg:
      - '--strict'
devices.gpio:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_PIN=y
      - CONFIG_BSP_USING_GPIO=y
devices.uart:
    kconfig:
      - CONFIG_RT_USING_SERIAL=y
      - CONFIG_RT_USING_SERIAL_V1=y
      - CONFIG_BSP_USING_UART1=y
      - CONFIG_BSP_USING_UART2=y
      - CONFIG_BSP_USING_UART3=y
devices.adc:
    kconfig:
      - CONFIG_RT_USING_ADC=y
      - CONFIG_BSP_USING_ADC=y
      - CONFIG_BSP_USING_ADC1=y
      - CONFIG_BSP_USING_ADC2=y

