from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

if GetDepend(['RT_DVFS_EVENT_ROCKCHIP_DFI']):
    src += ['event-rockchip-dfi.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
