import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = Split("""

""")

# add for startup script
if rtconfig.PLATFORM in ['gcc']:
    src = src + ['gcc/' + 'startup_gcc.c']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src = src + ['arm/' + 'startup_keil.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src = src + ['iar/' + 'startup_iar.c']

path = [cwd]
path += [cwd + '/cmsis/include']

CPPDEFINES = ['AM_PACKAGE_BGA', 'AM_PART_APOLLO2']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
