from building import *

src   = []
cwd   = GetCurrentDir()
group = []
CPPPATH = [cwd]
CPPDEFINES = ['']

if GetDepend('RT_USING_LIBC'):
    src += Glob('*.c')
else:
    if GetDepend('RT_LIBC_USING_TIME') and not GetDepend('RT_USING_MINILIBC'):
        src += ['time.c']

if GetDepend('RT_USING_POSIX') == False:
    SrcRemove(src, ['unistd.c'])

if GetDepend('RT_USING_MUSL'):
    SrcRemove(src, ['time.c'])
    CPPDEFINES = ['_TIMEVAL_DEFINED']

if not GetDepend('RT_USING_MINILIBC') and not GetDepend('RT_USING_MUSL') and (GetDepend('RT_USING_LIBC') or GetDepend('RT_LIBC_USING_TIME')):
    group = DefineGroup('libc', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
