import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = Split("""
core_v_hal/source/hal_apb_i2cs.c
core_v_hal/source/hal_fc_event.c
core_v_hal/source/hal_fll.c
core_v_hal/source/hal_fll_pi.c
core_v_hal/source/hal_gpio.c
core_v_hal/source/hal_gpio_pulp.c
core_v_hal/source/hal_irq.c
core_v_hal/source/hal_pinmux.c
core_v_hal/source/hal_pinmux1.c
core_v_hal/source/hal_soc_eu.c
core_v_hal/source/hal_timer_irq.c
bmsis/core-v-mcu/source/core-v-mcu.c
bmsis/core-v-mcu/source/crt0.S
bmsis/core-v-mcu/source/vectors.S
bmsis/core-v-mcu/source/trap_gcc.S
core_v_udma_driver/source/udma_uart_driver.c
core_v_udma_driver/source/udma_cam_driver.c
core_v_udma_driver/source/udma_i2cm_driver.c
core_v_udma_driver/source/udma_qspi_driver.c
core_v_udma_driver/source/udma_sdio_driver.c
""")

path = [
    cwd + '/bmsis/core-v-mcu/include',
    cwd + '/core_v_hal/include',
    cwd + '/core_v_udma_driver/include']

group = DefineGroup('core_v_hal_lib', src, depend = [''], CPPPATH = path)

Return('group')
