# RT-Thread building script for bridge

import os
from building import *

Import('rtconfig')

cwd   = GetCurrentDir()
group = []
list  = os.listdir(cwd)

# add startup code files
if rtconfig.CPU in list :
    group = group + SConscript(os.path.join(rtconfig.CPU, 'SConscript'))

Return('group')
