
from building import *
import rtconfig

cwd     = GetCurrentDir()

src = []

CPPPATH = [cwd]
LOCAL_CFLAGS = ''

if rtconfig.PLATFORM in ['gcc', 'armclang']:
    LOCAL_CFLAGS += ' -std=c99'
elif rtconfig.PLATFORM in ['armcc']:
    LOCAL_CFLAGS += ' --c99'

group = DefineGroup('Drivers', src, depend = [], CPPPATH = CPPPATH, LOCAL_CFLAGS = LOCAL_CFLAGS)

Return('group')
