# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
board.c
drv_uart.c
''')
CPPPATH = [cwd]

if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
