from building import *

cwd = GetCurrentDir()
src = Split('''
cpu/mmap_table.S
''')

CPPPATH = [ cwd + '/cpu',
cwd + '/include',
]

group = DefineGroup('Platform', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
