import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = []

src += Glob('ALD/ES32VF2264/Source/*.c')

#add for startup script
if rtconfig.CROSS_TOOL == 'gcc':
     src = src + ['RV_CORE/Device/EastSoft/ES32VF2264/Startup/startup_es32vf2264.S']
     src = src + ['RV_CORE/Device/EastSoft/ES32VF2264/Startup/trap_c.c']
     src = src + ['RV_CORE/Device/EastSoft/ES32VF2264/Svc/es32vf2264.svc']

path = [cwd + '/RV_CORE/Device/EastSoft/ES32VF2264/Include',
        cwd + '/RV_CORE/Include',
        cwd + '/ALD/ES32VF2264/Include']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = ['ES32VF2264'])

Return('group')
