# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

if rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += Glob('*_rvds.S')

if rtconfig.PLATFORM in ['gcc']:
    src += Glob('*_init.S')
    src += Glob('*_gcc.S')

if rtconfig.PLATFORM in ['iccarm']:
    src += Glob('*_iar.S')

if rtconfig.CPU in ['cortex-m0','cortex-m0-dual','arm926', 'lpc214x', 'lpc24xx', 's3c24x0', 'AT91SAM7X']:
    SrcRemove(src, 'atomic_port.c')

group = DefineGroup('CPU', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
