import os
from building import *

cwd = GetCurrentDir()
src = ['board.c']

CPPPATH = [cwd]

if GetDepend('BSP_USING_GPIO'):
    src += ['drv_gpio.c']

if GetDepend('BSP_USING_UART'):
    src += ['drv_uart.c']

if GetDepend('BSP_USING_ADC'):
    src += ['drv_adc.c']

if GetDepend('BSP_USING_I2C'):
    src += ['drv_hw_i2c.c']
    
if GetDepend('BSP_USING_SW_I2C'):
    src += ['drv_sw_i2c.c']

if GetDepend('BSP_USING_PWM'):
    src += ['drv_pwm.c']

if GetDepend('BSP_USING_HWTIMER'):
    src += ['drv_hwtimer.c']

if GetDepend('BSP_USING_WIFI'):
    src += ['drv_wifi.c']

if GetDepend('BSP_USING_SPI'):
    src += ['drv_spi.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
