# RT-Thread building script for component

Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = [ 'bsp/drivers/plic/plic_driver.c',
        'bsp/env/start.S',
    'bsp/env/freedom-e300-hifive1/init.c']

CPPPATH = [ cwd + '/bsp/drivers', cwd + '/bsp/drivers/fe300prci', cwd + '/bsp/drivers/plic',
            cwd + '/bsp/env', cwd + '/bsp/env/freedom-e300-hifive1',
            cwd + '/bsp/include', cwd + '/bsp/include/sifive', cwd + '/bsp/include/sifive/devices']

CPPDEFINES = []

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
