import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Glob('Hal_lib/src/*.c')
src += [cwd + '/CMSIS_and_startup/sys.c']
src += [cwd + '/CMSIS_and_startup/startup_Tk499.s']

path = [
    cwd + '/CMSIS_and_startup/CMSIS',
    cwd + '/CMSIS_and_startup',
    cwd + '/Hal_lib/inc',]

CPPDEFINES = []

group = DefineGroup('TKM32_Lib', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
