from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

if GetDepend('RT_USING_LWIP') == False:
    SrcRemove(src, 'mii.c')
    SrcRemove(src, 'synopGMAC.c')
    SrcRemove(src, 'synopGMAC_Dev.c')
    SrcRemove(src, 'synopGMAC_plat.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)


Return('group')
