Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd + '/..']

src = Split('''
app.c
''')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
