# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*src/*.c') + Glob('src/*.cpp')
CPPPATH = [cwd + '/inc']

group = DefineGroup('M487_StdPeriph', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
