import os
from building import *
from gcc import *
Import('rtconfig')

group = []

libc_name, libc_version = GetGCCLibcNameVersion(rtconfig)

if libc_name == 'mlibc':
    print('mlibc version: ' + libc_version)

    cwd = GetCurrentDir()
    src = Glob('*.c')

    CPPPATH = [cwd]
    CPPDEFINES = ['RT_USING_MLIBC', 'RT_USING_LIBC']
    # LIBS = ['c', 'gcc']
    LIBS = []
    LINKFLAGS = ' -nostdlib' # for GCC toolchain with newlib
    AddDepend(['RT_USING_MLIBC', 'RT_USING_LIBC'])

    group = group + DefineGroup('Compiler', src, depend = [''], CPPPATH = CPPPATH, LINKFLAGS = LINKFLAGS, CPPDEFINES = CPPDEFINES, LIBS = LIBS)

    list = os.listdir(cwd)
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
