devices.gpio:
    kconfig:
      - CONFIG_BSP_USING_GPIO=y
    scons_arg:
      - '--strict'
devices.adc:
    kconfig:
      - CONFIG_BSP_USING_SAADC=y
devices.flash:
    kconfig:
      - CONFIG_BSP_USING_ON_CHIP_FLASH=y
devices.i2c:
    kconfig:
      - CONFIG_BSP_USING_I2C=y
devices.spi:    
    kconfig:
      - CONFIG_BSP_USING_SPI=y  
devices.uart:   
    kconfig:
      - CONFIG_BSP_USING_UART=y
devices.watchdog: 
    kconfig:
      - CONFIG_BSP_USING_WDT=y
devices.qspi_flash:
    kconfig:
      - CONFIG_BSP_USING_QSPI_FLASH=y
devices.pwm:
    kconfig:
      - CONFIG_BSP_USING_PWM=y
devices.rtc:
    kconfig:
      - CONFIG_BSP_USING_ONCHIP_RTC=y
devices.hwtimer:
    kconfig:
      - CONFIG_BSP_USING_TIM=y
      - CONFIG_BSP_USING_TIM0=y