
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd + '/include',]
LIBS    = ['libxil',]
LIBPATH = [cwd + '/lib']

group = DefineGroup('zynq_hal', [],
                    depend = [], 
                    CPPPATH = CPPPATH,
                    LIBS = LIBS,
                    LIBPATH = LIBPATH)

Return('group')
