Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend(['UTEST_MEMHEAP_TC']):
    src += ['memheap_tc.c']

if GetDepend(['UTEST_SMALL_MEM_TC']):
    src += ['mem_tc.c']

if GetDepend(['UTEST_SLAB_TC']):
    src += ['slab_tc.c']

if GetDepend(['UTEST_IRQ_TC']):
    src += ['irq_tc.c']

if GetDepend(['UTEST_SEMAPHORE_TC']):
    src += ['semaphore_tc.c']

if GetDepend(['UTEST_EVENT_TC']):
    src += ['event_tc.c']

if GetDepend(['UTEST_TIMER_TC']):
    src += ['timer_tc.c']

if GetDepend(['UTEST_MESSAGEQUEUE_TC']):
    src += ['messagequeue_tc.c']

if GetDepend(['UTEST_SIGNAL_TC']):
    src += ['signal_tc.c']

if GetDepend(['UTEST_MUTEX_TC']):
    src += ['mutex_tc.c', 'mutex_pi_tc.c']

if GetDepend(['UTEST_MAILBOX_TC']):
    src += ['mailbox_tc.c']

if GetDepend(['UTEST_THREAD_TC']):
    src += ['thread_tc.c']

if GetDepend(['UTEST_DEVICE_TC']):
    src += ['device_tc.c']

if GetDepend(['UTEST_ATOMIC_TC']):
    src += ['atomic_tc.c']

if GetDepend(['UTEST_HOOKLIST_TC']):
    src += ['hooklist_tc.c']

if GetDepend(['UTEST_MTSAFE_KPRINT_TC']):
    src += ['mtsafe_kprint_tc.c']

# Stressful testcase for scheduler (MP/UP)
if GetDepend(['UTEST_SCHEDULER_TC']):
    src += ['sched_timed_sem_tc.c']
    src += ['sched_timed_mtx_tc.c']
    src += ['sched_mtx_tc.c']
    src += ['sched_sem_tc.c', 'sched_thread_tc.c']

group = DefineGroup('utestcases', src, depend = ['RT_USING_UTESTCASES'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
