from shutil import copy
from building import *

Import('rtconfig')

src   = []
cwd   = GetCurrentDir()
CPPPATH = [cwd]
group = []

if rtconfig.PLATFORM == 'gcc' and GetDepend('SOC_LS'):
    try:
        # There is no 'sys/select.h' in these bsp's gcc toolchain; thus, we need to copy this file from 'nogcc/sys/select.h'
        copy("../../nogcc/sys/select.h", "./sys/select.h")
    except:
        pass

    if GetDepend('RT_USING_LIBC'):
        src += Glob('*.c')

    group = DefineGroup('libc', src, depend = [], CPPPATH = CPPPATH)

Return('group')
