import os
from building import *

objs = []
cwd  = GetCurrentDir()

# add general drivers
src = []
path =  [cwd]

if GetDepend('BSP_USING_LCD_SPI'):
    src = src + ['lcd/drv_lcd_spi.c']
    src = src + ['lcd/drv_lcd_spi_ext.c']
    path += [cwd + '/lcd']

if GetDepend('BSP_USING_DCMI'):
    src = src + ['camera/drv_dcmi.c']
    path += [cwd + '/camera']

if GetDepend('BSP_USING_OV2640'):
    src = src + ['camera/drv_ov2640.c']
    path += [cwd + '/camera']


CPPDEFINES = ['STM32H750xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
