from building import *

objs = []

if not GetDepend(['RT_USING_OFW']):
    Return('objs')

cwd     = GetCurrentDir()
list    = os.listdir(cwd)
CPPPATH = [cwd, cwd + '/../include']

src     = Glob('*.c')

if GetDepend('RT_USING_PIC') == False:
    SrcRemove(src, ['irq.c'])

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
