Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')
src	= Glob('*.c')

# remove no need file.
if GetDepend('RT_USING_LWIP') == False:
	SrcRemove(src, 'stm32_eth.c')

if GetDepend('RT_USING_SPI') == False:
	SrcRemove(src, 'rt_stm32f10x_spi.c')
	SrcRemove(src, 'msd.c')

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
