Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drivers.
src = Split("""
board.c
stm32f10x_it.c
usart.c
platform.c
""")

# add Ethernet drivers.
if GetDepend('RT_USING_LWIP'):
	src += ['stm32_eth.c']

if GetDepend('RT_USING_SPI'):
	src += ['rt_stm32f10x_spi.c'] 

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
