# RT-Thread building script for FreeType

from building import *

cwd = GetCurrentDir()
src = Split('''
psnames.c
''')
CPPPATH = [cwd]

group = DefineGroup('FreeType', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
