from building import *
import rtconfig

cwd = GetCurrentDir()
src_c = Glob('*.c')

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    src_asm = ['start_gcc.S', 'vectors_gcc.S', 'interrupts_gcc.S']
elif rtconfig.CROSS_TOOL == 'iar':
    src_asm = ['start_iar.asm', 'vectors_iar.asm', 'interrupts_iar.asm']

src = File(src_c + src_asm)

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
