import os
from building import *

objs = []
cwd  = GetCurrentDir()

# add general drivers
src = []
path =  [cwd]

if GetDepend(['BSP_SCB_ENABLE_I_CACHE']) or GetDepend(['BSP_SCB_ENABLE_D_CACHE']):
    src += Glob('drv_mpu.c')

if GetDepend(['BSP_USING_QSPI_FLASH']):
    src += Glob('drv_qspi_flash.c')

if GetDepend(['BSP_USING_SPI_LCD_ILI9488']):
    src += Glob('drv_spi_ili9488.c')

if GetDepend(['BSP_USING_SPI_FLASH']):
    src += Glob('spi_flash_init.c')

if GetDepend(['BSP_USING_FS']):
    src += Glob('filesystem.c')

if GetDepend(['BSP_USING_SDIO_ARTPI']):
    src += Glob('drv_sdio.c')

if GetDepend(['BSP_USING_WIFI']):
    src += Glob('wifi_config.c')
    src += Glob('drv_wlan.c')

if GetDepend(['BSP_USING_ETH_H750']):
    src += Glob('drv_eth.c')

if GetDepend(['PKG_USING_EASYFLASH']):
    src += Glob('ef_fal_port.c')

CPPDEFINES = ['STM32H750xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
