Import('env')
Import('projects')

src = Split("""
gui_init.c
demo_gui_main.c
demo_gui_benchmark.c
demo_gui_button.c
demo_gui_dc_buffer.c
demo_gui_buffer_animation.c
demo_gui_label.c
demo_gui_radiobox.c
demo_gui_window.c
demo_gui_checkbox.c
demo_gui_progressbar.c
demo_gui_scrollbar.c
demo_gui_textbox.c
demo_gui_listbox.c
demo_gui_combobox.c
demo_gui_menu.c
demo_gui_listctrl.c
demo_gui_slider.c
demo_gui_image.c
demo_gui_fnview.c
demo_gui_rttab.c
""")

group = {}
group['name'] = 'GUI demo'
group['src'] = File(src)
group['CCFLAGS'] = ''
group['CPPPATH'] = ['']
group['CPPDEFINES'] = ''
group['LINKFLAGS'] = ''

# add group to project list
projects.append(group)

env.Append(CCFLAGS = group['CCFLAGS'])
env.Append(CPPPATH = group['CPPPATH'])
env.Append(CPPDEFINES = group['CPPDEFINES'])
env.Append(LINKFLAGS = group['LINKFLAGS'])

objs = env.Object(group['src'])

Return('objs')
