Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend('RT_UTEST_USING_ALL_CASES'):

    if GetDepend('RT_UTEST_TC_USING_LWIP'):
        # Add lwIP test source if enabled
        src += ['tc_lwip.c']

    if GetDepend('RT_UTEST_TC_USING_NETDEV'):
        # Add netdev test source if enabled
        src += ['tc_netdev.c']

    if GetDepend('RT_UTEST_TC_USING_SAL'):
        src += ['tc_sal_socket.c']

# Define the test group with proper dependencies
group = DefineGroup('utestcases', src, depend = ['RT_USING_UTESTCASES'], CPPPATH = CPPPATH)

Return('group')
