# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
src/fsl_sd.c
src/fsl_sdmmc.c
''')
CPPPATH = [cwd + '/inc']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
