# RT-Thread building script for component

Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split('''
Device/ST/STM32F7xx/Source/Templates/system_stm32f7xx.c
''')
CPPPATH = [cwd + '/Device/ST/STM32F7xx/Include', cwd + '/Include']
CPPDEFINES = [rtconfig.STM32_TYPE]

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
	src += ['Device/ST/STM32F7xx/Source/Templates/gcc/startup_stm32f746xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
	src += ['Device/ST/STM32F7xx/Source/Templates/arm/startup_stm32f746xx.s']
elif rtconfig.CROSS_TOOL == 'iar':
	src += ['Device/ST/STM32F7xx/Source/Templates/iar/startup_stm32f746xx.s']

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
