from building import *

cwd = GetCurrentDir()
group = []
src = []
CPPPATH =[]

src += Glob(cwd + '/ui/*.c')
CPPPATH += [cwd+'/ui']

group = group + DefineGroup('LVGL-SquareLine', src, depend = ['BSP_USING_LVGL', 'BSP_USING_LVGL_SQUARELINE'], CPPPATH = CPPPATH)

Return('group')
