include $(SDK_ROOT)/mk/common.mk


SOURCES = \
	src/menu.c \
	src/spinlock.c \
	src/spinlock_lock_unlock.S \
	src/system_util.c \
	src/text_color.c \
	src/sdk_version.c \
	src/runtime_support.c \
	src/atomics.s


include $(SDK_ROOT)/mk/targets.mk
