# RT-Thread building script for component
Import('RTT_ROOT')
Import('rtconfig')
from building import *

# get current directory
cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

# The set of source files associated with this SConscript file.
if GetDepend('BSP_USING_USBOTG'):
    src += ['src/usb_core.c']

if GetDepend('RT_USING_USB_DEVICE'):
    src += ['src/usbd_core.c', 'src/usbd_int.c', 'src/usbd_sdr.c']

if GetDepend('RT_USING_USB_HOST'):
    src += ['src/usbh_core.c', 'src/usbh_int.c', 'src/usbh_ctrl.c']

CPPPATH = [cwd + '/inc']

group = DefineGroup('usbotg_library', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
