import os
import sys

EXEC_PATH = '/home/shaolin/CodeSourcery/Sourcery_G++_Lite/bin'
RTT_ROOT = os.path.normpath(os.getcwd() + '/../../..')
sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
PREFIX = 'arm-none-eabi-'
env = Environment(tools = ['mingw'],
	AS = PREFIX + 'gcc', 
	ASFLAGS = '',
	CC = PREFIX + 'gcc',
	CCFLAGS = '-mcpu=arm920t -O0 -fPIC' ,
	AR = PREFIX + 'ar', 
	ARFLAGS = '-rc',
	LINK = PREFIX + 'ld',
	LINKFLAGS = '-z max-page-size=0x4 -shared -fPIC -e 0 -nostdlib -s',
	CPPPATH = [
		RTT_ROOT + '/include',
		RTT_ROOT + '/bsp/mini2440'
		])
env.PrependENVPath('PATH', EXEC_PATH)

target = 'extension.so'
src = Glob('*.c')

env.Program(target, src) 

