Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

if GetDepend(['BSP_USING_UART']):
    src += ['drv_uart.c']
    
if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += ['drv_flash.c']

if GetDepend(['BSP_USING_QSPI_FLASH']):
    src += ['drv_qspi_flash.c']

if GetDepend(['BSP_USING_SPI']):
    src += ['drv_spi.c']
if GetDepend(['BSP_USING_GPIO']):
    src += ['drv_gpio.c']

path =  [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
