Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

if GetDepend(['BSP_USING_UART']):
    src += ['drv_uart.c']
    
if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += ['drv_flash.c']

path =  [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
