scons.args: &scons
    scons_arg:
      - '--strict'
# ------ C POSIX CI ------
component.cplusplus:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_CPLUSPLUS=y
# ------ online-packages CI ------
online-packages.rtduino.core:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
online-packages.rtduino.communication:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_PN532=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SI4713=y
online-packages.rtduino.devicecontrol:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_PCF8574=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_PCA9685=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_TPA2016=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_DRV2605=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_DS1841=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_DS3502=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_PCF85063TP=y
online-packages.rtduino.sensors.adafruit:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SENSOR=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SENSORLAB=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_ADXL375=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_VL53L0X=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_VL53L1X=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_VL6180X=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MAX31855=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MAX31865=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MAX31856=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MAX6675=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MLX90614=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LSM9DS1=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_AHTX0=y
      - CONFIG_ARDUINO_ADAFRUIT_AHTX0_USING_SENSOR_DEVICE=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LSM9DS0=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BMP280=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_ADT7410=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BMP085=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BME680=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MCP9808=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MCP4728=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_INA219=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LTR390=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_ADXL345=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_DHT=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MCP9600=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LSM6DS=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BNO055=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MAX1704X=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MMC56X3=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MLX90393=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MLX90395=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_ICM20X=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_DPS310=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_HTS221=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SHT4X=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SHT31=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_ADXL343=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BME280=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_AS726X=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_AMG88XX=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_AM2320=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_AM2315=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LTR329_LTR303=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BMP085_UNIFIED=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BMP183=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BMP183_UNIFIED=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BMP3XX=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MS8607=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LIS3MDL=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MLX90640=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MMA8451=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MSA301=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MPL115A2=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BNO08X=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BNO08X_RVC=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LIS2MDL=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LSM303DLH_MAG=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LC709203F=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_CAP1188=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_CCS811=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_NAU7802=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LIS331=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LPS2X=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LPS35HW=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LSM303_ACCEL=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_LIS3DH=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_PCF8591=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MPL3115A2=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MPR121=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MPRLS=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MPU6050=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_PCT2075=y
      # - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_PM25AQI=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_EMC2101=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_FXAS21002C=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SCD30=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_FXOS8700=y
      # - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_HMC5883_UNIFIED=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SGP30=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_TMP006=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_TLA202X=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_TCS34725=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SI7021=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SI1145=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SGP40=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SHTC3=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_HDC1000=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_HTU21DF=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_AS7341=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_HTU31D=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_INA260=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_TMP007_LIBRARY=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_L3GD20=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_TMP117=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_TSC2007=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_TSL2561=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_TSL2591_LIBRARY=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_VCNL4040=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_VEML6070=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_VEML6075=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_VEML7700=y
online-packages.rtduino.sensors.others:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
      - CONFIG_PKG_USING_ARDUINO_CAPACITIVESENSOR=y
online-packages.rtduino.sensors.seeed:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_LIS3DHTR=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_DHT=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_ADXL335=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_ADXL345=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_BME280=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_BMP280=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_H3LIS331DL=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_MMA7660=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_TSL2561=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_PAJ7620=y
      # - CONFIG_PKG_USING_ARDUINO_SEEED_VL53L0X=y
      # - CONFIG_PKG_USING_ARDUINO_SEEED_ITG3200=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_SHT31=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_HP20X=y
      # - CONFIG_PKG_USING_ARDUINO_SEEED_DRV2605L=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_BBM150=y
      # - CONFIG_PKG_USING_ARDUINO_SEEED_HMC5883L=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_LSM303DLH=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_TCS3414CS=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_MP503=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_BMP085=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_HIGHTEMP=y
      # - CONFIG_PKG_USING_ARDUINO_SEEED_VEML6070=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_SI1145=y
      # - CONFIG_PKG_USING_ARDUINO_SEEED_SHT35=y
      # - CONFIG_PKG_USING_ARDUINO_SEEED_AT42QT1070=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_LSM6DS3=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_HDC1000=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_HM3301=y
      # - CONFIG_PKG_USING_ARDUINO_SEEED_MCP9600=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_LTC2941=y
      - CONFIG_PKG_USING_ARDUINO_SEEED_LDC1612=y
online-packages.rtduino.display:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_GFX_LIBRARY=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_ILI9341=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SSD1306=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_ST7735=y

      # u8g2
      - CONFIG_PKG_USING_ARDUINO_U8G2=y
online-packages.rtduino.other:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MFRC630=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_SI5351=y
online-packages.rtduino.projects:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
      - CONFIG_PKG_USING_ARDUINO_SENSOR_KIT=y
      - CONFIG_PKG_USING_ARDUINO_ULTRASOUND_RADAR=y
      - CONFIG_PKG_USING_ARDUINO_MSGQ_C_CPP_DEMO=y
      - CONFIG_PKG_USING_ARDUINO_NINEINONE_SENSOR_SHIELD=y
online-packages.rtduino.signalio:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
      # Adafruit Signal IO Drivers
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BUSIO=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_TCA8418=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MCP23017=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_ADS1X15=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_AW9523=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MCP3008=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_MCP4725=y
      - CONFIG_PKG_USING_ARDUINO_ADAFRUIT_BD3491FS=y
online-packages.rtduino.timing:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_ARDUINO=y
      - CONFIG_PKG_USING_ARDUINO_RTCLIB=y
      - CONFIG_PKG_USING_ARDUINO_MSTIMER2=y
      # - CONFIG_PKG_USING_ARDUINO_TICKER=y
      - CONFIG_PKG_USING_ARDUINO_TASKSCHEDULER=y
online-packages.multimedia.lvgl-demo:
    <<: *scons
    kconfig:
      - CONFIG_BSP_USING_LVGL=y
      - CONFIG_BSP_USING_LVGL_DEMO=y