# RT-Thread building script for bridge

import os
from building import *

Import('rtconfig')

cwd = GetCurrentDir()
list = os.listdir(cwd)

# add common code files
group = SConscript(os.path.join('common', 'SConscript'))

# cpu porting code files
if rtconfig.CPU in list:
    group = group + SConscript(os.path.join(rtconfig.CPU, 'SConscript'))

Return('group')
