# RT-Thread building script for bridge

import os
from building import *

Import('rtconfig')

cwd   = GetCurrentDir()
group = []
list  = os.listdir(cwd)

# add common code files
group = group + SConscript(os.path.join(cwd, 'common', 'SConscript'))

# If rtconfig.SUBARCH exists, then join the SUBARCH directory
try:
    rtconfig.SUBARCH
except:
    # do nothing
    cwd = cwd
else:
    if rtconfig.SUBARCH in list:
        group = group + SConscript(os.path.join(cwd, rtconfig.SUBARCH, 'SConscript'))

# cpu porting code files
group = group + SConscript(os.path.join(cwd, rtconfig.CPU, 'SConscript'))

Return('group')
