from building import *
import rtconfig
cwd     = GetCurrentDir()
src = ['MM32F103/Source/system_MM32F103.c']
CPPPATH = [cwd + '/CMSIS/KEIL_CORE', cwd + '/MM32F103/Include',  cwd + '/MM32F103/Source', cwd + '/MM32F103/HAL_lib/inc']

src += Glob('MM32F103/HAL_lib/src/*.c')
CPPDEFINES = ['USE_STDPERIPH_DRIVER']

if rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['MM32F103/Source/KEIL_StartAsm/startup_MM32F103.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['MM32F103/Source/IAR_StartAsm/startup_MM32F103.s']
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
