from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include', cwd + '/../../../../components/drivers/ethernet']

if GetDepend(['RT_ETHERNET_K1X_EMAC']):
    src += ['eth-k1x-emac.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
