from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
mm32f3277g8p_msp.c
''')

if GetDepend(['BSP_USING_USER_KEY']):
    src += Glob("ports/user_key.c")

path =  [cwd]
path += [cwd + '/ports']

# You can select chips from the list above
CPPDEFINES = ['MM32F3277G']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
