
from building import *
import rtconfig
import os

cwd     = GetCurrentDir()
objs = []
src = []

if GetDepend(['BSP_USING_RW007']):
    src += Glob('drv_rw007.c')

CPPPATH = [cwd]
LOCAL_CFLAGS = ''

if rtconfig.PLATFORM in ['gcc', 'armclang']:
    LOCAL_CFLAGS += ' -std=c99'
elif rtconfig.PLATFORM in ['armcc']:
    LOCAL_CFLAGS += ' --c99'
objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')

