Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
#src_drv = ['']

# The set of source files associated with this SConscript file.
path = [cwd]

src = Split("""
davinci_serial.c
""")

if GetDepend('RT_USING_GPIO_DEVICE'):
	src += ['gpio.c']

if GetDepend('RT_USING_I2C_CONTROL'):
	src += ['i2c-davinci.c']

if GetDepend('RT_USING_SDIO_CONTROL'):
	src += ['mmcsd.c']

if GetDepend('RT_USING_SPI_CONTROL'):
	src += ['spi-davinci.c']

if GetDepend('RT_USING_EMAC'):
	src += ['davinci_emac.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
