scons.args: &scons
    scons_arg:
      - '--strict'
# ------ nano CI ------
nano:
    <<: *scons
    kconfig:
      - CONFIG_RT_USING_NANO=y
      
# ------ peripheral CI ------
peripheral.eth:
    kconfig:
      - CONFIG_BSP_USING_ETH_H750=y

# ------ on-line package CI ------
package.iot.zephyr_polling:
    kconfig:
      - CONFIG_BSP_USING_UART3=y
      - CONFIG_PKG_USING_ZEPHYR_POLLING=y
      - CONFIG_PKG_ZEPHYR_POLLING_CHIPSET_ARTPI_AP6212=y
      - CONFIG_PKG_ZEPHYR_POLLING_PORT_RTTHREAD_ARTPI=y
package.iot.btstack:
    kconfig:
      - CONFIG_BSP_USING_UART3=y
      - CONFIG_BSP_USING_SPI_FLASH=y
      - CONFIG_PKG_USING_BTSTACK=y
      - CONFIG_PKG_BTSTACK_SAMPLE_LE_COUNTER=y
      - CONFIG_PKG_USING_BTSTACK_LATEST_VERSION=y

devices.soft_i2c:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_I2C=y
    - CONFIG_RT_USING_SOFT_I2C=y
    - CONFIG_RT_USING_SOFT_I2C1=y
    - CONFIG_RT_SOFT_I2C1_SCL_PIN=22
    - CONFIG_RT_SOFT_I2C1_SDA_PIN=23
    - CONFIG_RT_SOFT_I2C1_BUS_NAME="swi2c1"
    - CONFIG_RT_USING_SOFT_I2C2=y
    - CONFIG_RT_SOFT_I2C2_SCL_PIN=127
    - CONFIG_RT_SOFT_I2C2_SDA_PIN=125
    - CONFIG_RT_SOFT_I2C2_BUS_NAME="swi2c2"
    - CONFIG_RT_USING_SOFT_I2C3=y
    - CONFIG_RT_SOFT_I2C3_SCL_PIN=123
    - CONFIG_RT_SOFT_I2C3_SDA_PIN=124
    - CONFIG_RT_SOFT_I2C3_BUS_NAME="swi2c3"
