devices.soft_i2c:
  kconfig:
    - CONFIG_RT_USING_I2C=y
    - CONFIG_RT_USING_SOFT_I2C=y
    - CONFIG_RT_USING_SOFT_I2C1=y
    - CONFIG_RT_SOFT_I2C1_SCL_PIN=0
    - CONFIG_RT_SOFT_I2C1_SDA_PIN=1
    - CONFIG_RT_SOFT_I2C1_BUS_NAME="swi2c1"
