# RT-Thread building script for bridge

import os
from building import *

Import('rtconfig')

cwd   = GetCurrentDir()
group = []
list  = os.listdir(cwd)

# add common code files
group = group + SConscript(os.path.join(cwd, 'common', 'SConscript'))

# If rtconfig.CORTEX exists, then join the CORTEX directory
try:
    rtconfig.CORTEX
except:
    # do nothing
    cwd = cwd
else:
    if rtconfig.CORTEX in list:
        group = group + SConscript(os.path.join(cwd, rtconfig.CORTEX, 'SConscript'))

Return('group')
