Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
group = []
if GetDepend('NU_PKG_USING_MAX31875'):
    src = Split("""
    libraries/max31875_c.c
    sensor_max31875.c
    """)
    CPPPATH = [cwd, cwd + '/libraries']
    group = DefineGroup('nu_pkgs_max31875', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
