
obj-y += platform_resource.o disp_board_config.o

obj-$(CONFIG_ARCH_SUN8IW19) += sun8iw19.o
obj-$(CONFIG_V459_PERF1) += v459_perf1.o

obj-$(CONFIG_ARCH_SUN20IW1) += sun20iw1.o
obj-$(CONFIG_F133_FPGA) += f133_fpga.o
obj-$(CONFIG_VVX07H005A10_MIPI) += VVX07H005A10_mipi_config.o
obj-$(CONFIG_TFT08006_MIPI)+= tft08006_mipi_config.o
obj-$(CONFIG_HE0801A068_MIPI)+= he0801a068_mipi_config.o
obj-$(CONFIG_DEFAULT_LVDS)+= f133_lvds.o

