# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src = ['drv_uart.c']
CPPPATH = [cwd]

if GetDepend('BSP_USING_GPIO'):
    src += ['drv_gpio.c']

if  GetDepend('BSP_USING_I2C'):
    src += ['drv_i2c.c']

if  GetDepend('BSP_USING_ADC'):
    src += ['drv_adc.c']

if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']

if GetDepend('RT_USING_PWM'):
    src += ['drv_pwm.c']

if GetDepend('RT_USING_WDT'):
    src += ['drv_wdt.c']

if GetDepend('BSP_USING_HWTIMER'):
    src += ['drv_hwtimer.c']

if GetDepend('BSP_USING_ON_CHIP_FLASH'):
    src += ['drv_flash.c']

group = DefineGroup('rt_drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
