# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src = ['drv_uart.c']
CPPPATH = [cwd]

if GetDepend('BSP_USING_GPIO'):
    src += ['drv_gpio.c']

if  GetDepend('BSP_USING_I2C'):
    src += ['drv_i2c.c']

group = DefineGroup('rt_drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
