# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src = ['drv_uart.c']
CPPPATH = [cwd]

if GetDepend('BSP_USING_GPIO'):
    src += ['drv_gpio.c']

if  GetDepend('BSP_USING_HW_I2C'):
    src += ['drv_i2c.c']

if  GetDepend('BSP_USING_SOFT_I2C1'):
    src += ['drv_soft_i2c.c']

if  GetDepend('BSP_USING_ADC'):
    src += ['drv_adc.c']

if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']

if GetDepend('BSP_USING_PWM'):
    src += ['drv_pwm.c']
    src += ['sample/pwm_led_sample.c']

if GetDepend('BSP_USING_WDT'):
    src += ['drv_wdt.c']
    src += ['sample/wdt_sample.c']

if GetDepend('BSP_USING_HWTIMER'):
    src += ['drv_hwtimer.c']
    src += ['sample/hwtimer_sample.c']

if GetDepend('BSP_USING_SPI'):
    src += ['drv_spi.c']
    src += ['sample/spi_sample.c']

if GetDepend('BSP_USING_ON_CHIP_FLASH'):
    src += ['drv_flash.c']

if GetDepend('BSP_USING_SDH'):
    src += ['drv_sdh.c']

if GetDepend('BSP_USING_SDH'):
    src += ['port/mnt.c']

group = DefineGroup('rt_drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
