Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend(['RT_USING_SMART','RT_UTEST_TMPFS_CP']):
    src += ['tmpfs.c']

if GetDepend(['RT_UTEST_DFS_RECORD_LOCK']):
    src += ['tc_record_lock.c']

group = DefineGroup('utestcases', src, depend = ['RT_USING_UTESTCASES'], CPPPATH = CPPPATH)

Return('group')
