from building import *

group = []

if not GetDepend(['RT_USING_SDIO']) and not GetDepend(['RT_USING_DM']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src = []

if GetDepend(['RT_SDIO_SDHCI_PCI']):
    src += ['sdhci-pci.c']

if GetDepend(['RT_SDIO_DW_MMC']):
    src += ['sdio-dw.c', 'sdio-dw-platform.c']

    if GetDepend(['RT_SDIO_DW_MMC_PCI']):
            src += ['sdio-dw-pci.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
