import os
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Common/System/system_stm32mp1xx.c
CubeMX_Config/CM4/Src/stm32mp1xx_hal_msp.c
''')

if GetDepend(['BSP_USING_ADC']):
    src += Glob('ports/drv_hard_i2c.c')
    src += Glob('ports/stpmic.c')

if GetDepend(['BSP_USING_DAC']):
    src += Glob('ports/drv_hard_i2c.c')
    src += Glob('ports/stpmic.c')

if GetDepend(['BSP_USING_WWDG']):
    src += Glob('ports/drv_wwdg.c')

if GetDepend(['BSP_USING_LPTIM']):
    src += Glob('ports/drv_lptim.c')

path =  [cwd]
path += [cwd + '/CubeMX_Config/CM4/Inc']
path += [cwd + '/ports']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
