from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, cwd + '/../include']

src = ['dev_audio.c', 'dev_audio_pipe.c']

if GetDepend(['RT_AUDIO_INTEL_HDA']):
    src += ['audio-hda.c']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_AUDIO'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
