from building import *

group = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = []

if GetDepend(['RT_ADC_SPACEMIT_PMIC']):
    src += ['adc-spacemit-pmic.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
