Import('RTT_ROOT')
Import('rtconfig')
from building import *

# The set of source files associated with this SConscript file.
cwd     = GetCurrentDir()
src = Glob('driverlib/*.c')

# cortex-m3 no FPU.
if rtconfig.PART_TYPE.startswith('PART_LM4F') != True:
	 SrcRemove(src, 'fpu.c')

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
	src += ['startup/gcc/start_gcc.c']
elif rtconfig.CROSS_TOOL == 'keil':
	src += ['startup/arm/start_rvds.S']
elif rtconfig.CROSS_TOOL == 'iar':
	src += ['startup/iar/start_iar.S']

CPPPATH = [cwd]

CPPDEFINES = [rtconfig.PART_TYPE]
if rtconfig.CROSS_TOOL == 'gcc':
	CPPDEFINES += ['gcc'];

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
