Import('RTT_ROOT')
Import('rtconfig')
from building import *

# The set of source files associated with this SConscript file.
cwd     = GetCurrentDir()
src = Glob('driverlib/*.c')
SrcRemove(src, 'onewire.c')
CFLAGS = ''

# add for startup script
if rtconfig.PLATFORM in ['gcc']:
    src += ['startup/startup_gcc.c']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['startup/startup_rvmdk.S']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['startup/startup_ewarm.c']
    CFLAGS += ' --diag_suppress=pe177'

CPPPATH = [cwd, cwd + '/inc', cwd + '/driverlib']


CPPDEFINES = [rtconfig.PART_TYPE]
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, CFLAGS = CFLAGS)

Return('group')
