import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
CMSIS/Device/ST/STM32F0xx/Source/Templates/system_stm32f0xx.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_irda.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_iwdg.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc_ex.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi_ex.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_usart.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_wwdg.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_adc.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_crc.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_dac.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_dma.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_exti.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_gpio.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_i2c.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_pwr.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_rcc.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_rtc.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_spi.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_tim.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_usart.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_ll_utils.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cec.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_can.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac_ex.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2s.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd.c
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd_ex.c
""")
#device options

path = [cwd + '/CMSIS/Device/ST/STM32F0xx/Include', 
	cwd + '/STM32F0xx_HAL_Driver/Inc',
    cwd + '/CMSIS/Include']

if GetDepend(['RT_USING_RTT_CMSIS']):
    path += [RTT_ROOT + '/components/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('STM32_HAL', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
