from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../include']

if not GetDepend('RT_USING_HEAP'):
    SrcRemove(src, 'dataqueue.c')
    SrcRemove(src, 'pipe.c')

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_DEVICE_IPC'], CPPPATH = CPPPATH)

Return('group')
