import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
startup_gcc.S
common/aes/ck_aes.c
common/crc/ck_crc.c
common/dmac/ck_dmac.c
common/eflash/ck_eflash.c
common/pwm/ck_pwm.c
common/rsa/ck_rsa.c
common/sha/ck_sha.c
common/trng/ck_trng.c
common/timer/dw_timer.c
common/gpio/dw_gpio.c
common/spi/dw_spi.c
common/iic/dw_iic.c
common/usart/dw_usart.c
common/wdt/dw_wdt.c
""")

path = [cwd + '/include',
    cwd + '/common/aes', 
    cwd + '/common/aes',
    cwd + '/common/crc',
    cwd + '/common/dmac',
    cwd + '/common/eflash',
    cwd + '/common/gpio',
    cwd + '/common/iic',
    cwd + '/common/pwm',
    cwd + '/common/rsa',
    cwd + '/common/rtc',
    cwd + '/common/sha',
    cwd + '/common/spi',
    cwd + '/common/timer',
    cwd + '/common/trng',
    cwd + '/common/usart',
    cwd + '/common/wdt'
]

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
