import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
cmsis/cm4/device_support/system_at32f415.c
drivers/src/at32f415_adc.c
drivers/src/at32f415_can.c
drivers/src/at32f415_cmp.c
drivers/src/at32f415_crc.c
drivers/src/at32f415_crm.c
drivers/src/at32f415_debug.c
drivers/src/at32f415_dma.c
drivers/src/at32f415_ertc.c
drivers/src/at32f415_exint.c
drivers/src/at32f415_flash.c
drivers/src/at32f415_gpio.c
drivers/src/at32f415_i2c.c
drivers/src/at32f415_misc.c
drivers/src/at32f415_pwc.c
drivers/src/at32f415_sdio.c
drivers/src/at32f415_spi.c
drivers/src/at32f415_tmr.c
drivers/src/at32f415_usart.c
drivers/src/at32f415_usb.c
drivers/src/at32f415_wdt.c
drivers/src/at32f415_wwdt.c
""")

path = [
    cwd + '/cmsis/cm4/device_support',
    cwd + '/cmsis/cm4/core_support',
    cwd + '/drivers/inc',]

CPPDEFINES = ['USE_STDPERIPH_DRIVER']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
