Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('DHCPD', src, depend = ['RT_USING_LWIP', 'RT_USING_DHCPD'], CPPPATH = CPPPATH)

Return('group')
