# RT-Thread building script for component

import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = ['board.c']
src += ['mm32_msp.c']

CPPPATH = [cwd]


group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
