from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]

src = Split('''
        dev_wlan.c
        ''')

if GetDepend(['RT_WLAN_MANAGE_ENABLE']):
    src += ['dev_wlan_mgnt.c']

if GetDepend(['RT_WLAN_MSH_CMD_ENABLE']):
    src += ['dev_wlan_cmd.c']

if GetDepend(['RT_WLAN_PROT_ENABLE']):
    src += ['dev_wlan_prot.c']

if GetDepend(['RT_WLAN_PROT_LWIP_ENABLE']):
    src += ['dev_wlan_lwip.c']

if GetDepend(['RT_WLAN_CFG_ENABLE']):
    src += ['dev_wlan_cfg.c']

if GetDepend(['RT_WLAN_WORK_THREAD_ENABLE']):
    src += ['dev_wlan_workqueue.c']

group   = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_WIFI'], CPPPATH = CPPPATH)

Return('group')
