import os
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c     
Cube_Config/USER/src/n32h49x_cfg.c   
''')

path =  [cwd]
path += [os.path.join(cwd, 'Cube_Config', 'USER', 'inc')]
path += [os.path.join(cwd, 'ports')]

# Capital X is intentional: N32H49X is the family marker used by the
# N32H4x USB fsdev port.
CPPDEFINES = ['N32H49X', 'CORE_CM4']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

# if os.path.isfile(os.path.join(cwd, "ports", 'SConscript')):
#     group = group + SConscript(os.path.join("ports", 'SConscript'))

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
