arm_nn_mat_mult_kernel_q7_q15_reordered.c File Reference
arm_nn_mat_mult_kernel_q7_q15_reordered.c File Reference
Functions
q7_t * arm_nn_mat_mult_kernel_q7_q15_reordered (const q7_t *pA, const q15_t *pInBuffer, const uint16_t ch_im_out, const uint16_t numCol_A, const uint16_t bias_shift, const uint16_t out_shift, const q7_t *bias, q7_t *pOut)
Matrix-multiplication function for convolution with reordered columns.
Function Documentation
q7_t* arm_nn_mat_mult_kernel_q7_q15_reordered (const q7_t * pA, const q15_t * pInBuffer, const uint16_t ch_im_out, const uint16_t numCol_A, const uint16_t bias_shift, const uint16_t out_shift, const q7_t * bias, q7_t * pOut)
Parameters
[in] pA pointer to operand A
[in] pInBuffer pointer to operand B, always conssists of 2 vectors
[in] ch_im_out numRow of A
[in] numCol_A numCol of A
[in] bias_shift amount of left-shift for bias
[in] out_shift amount of right-shift for output
[in] bias the bias
[in,out] pOut pointer to output
Returns
The function returns the incremented output pointer
This function assumes that data in pInBuffer are reordered
References NN_ROUND.
Referenced by arm_convolve_1x1_HWC_q7_fast_nonsquare(), arm_convolve_HWC_q7_fast(), and arm_convolve_HWC_q7_fast_nonsquare().