from building import *
Import('rtconfig')

cwd = GetCurrentDir()
src	= Glob('*.c')
path = [cwd + '/..']

if GetDepend('SOC_GK7101') or GetDepend('SOC_GK7102'):
    path += [cwd + '/../libraries/drv/710X/gh/inc', cwd + '/../libraries/drv/710X/gd/inc']
elif GetDepend('SOC_GK7101S') or GetDepend('SOC_GK7102S'):
    path += [cwd + '/../libraries/drv/710XS/gh/inc', cwd + '/../libraries/drv/710XS/gd/inc']
elif GetDepend('SOC_GK7102C'):
    path += [cwd + '/../libraries/drv/7102C/gh/inc', cwd + '/../libraries/drv/7102C/gd/inc']
	
path += [cwd + '/../../../components/drivers/include/drivers']
path += [cwd + '/../libraries/adi/inc']
path += [cwd + '/../platform/board']
path += [cwd + '/../platform']

libcwd = str(Dir('#'))

group = DefineGroup('drivers', src, depend = [''], CPPPATH = path)

Return('group')
