from building import *

src = []

if GetDepend('BSP_UTEST_DRIVERS'):
    src += ['test_gpio.c']
    src += ['test_gpio_irq.c']

    if GetDepend('BSP_USING_ADC'):
        src += ['test_adc.c']

    if GetDepend('BSP_USING_TIMERS'):
        src += ['test_timer.c']

    if GetDepend('BSP_USING_WDT'):
        src += ['test_wdt.c']

    if GetDepend('BSP_USING_PWM'):
        src += ['test_pwm.c']

    if GetDepend('BSP_USING_PDMA'):
        src += ['test_pdma.c']

    if GetDepend('BSP_USING_TS'):
        src += ['test_ts.c']

    if GetDepend('BSP_USING_UART'):
        src += ['test_uart.c']

    if GetDepend('BSP_USING_RTC'):
        src += ['test_rtc.c']

    if GetDepend('BSP_USING_I2C'):
        src += ['test_i2c.c']

    if GetDepend('BSP_USING_SPI'):
        src += ['test_spi.c']

group = DefineGroup('utestcases', src, depend = [''])

Return('group')