import os
import sys
Import('rtconfig')
from building import *

#get current directory
cwd = GetCurrentDir()

# Update include path
path = [ cwd, cwd + '/boot' ]

# The set of source files associated with this SConscript file.
src = Split('''
    system.c
    hpm_l1c_drv.c
    hpm_sysctl_drv.c
    hpm_clock_drv.c
    hpm_otp_drv.c
    boot/hpm_bootheader.c
''')

group = DefineGroup('SoC', src, depend = [''], CPPPATH = path)

Return ('group')
