devices.soft_i2c:
  kconfig:
    - CONFIG_RT_USING_I2C=y
    - CONFIG_RT_USING_SOFT_I2C=y
    - CONFIG_RT_USING_SOFT_I2C0=y
    - CONFIG_RT_SOFT_I2C0_SCL_PIN=129
    - CONFIG_RT_SOFT_I2C0_SDA_PIN=128
    - CONFIG_RT_SOFT_I2C0_BUS_NAME="swi2c0"
