Import('RTT_ROOT')
Import('rtconfig')
from building import *

src	= Split('''
tjpgd.c
''')

CPPPATH = [RTT_ROOT + '/components/external/tjpgd1a']

group = DefineGroup('RTGUI', src, depend = ['RT_USING_GUIENGINE', 'RTGUI_IMAGE_TJPGD'], CPPPATH = CPPPATH)

Return('group')

