# RT-Thread building script for gui

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('GuiEngine', src, depend = ['RTGUI_IMAGE_TJPGD'], CPPPATH = CPPPATH)

Return('group')
