Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
group = []
CPPPATH = []

if rtconfig.CROSS_TOOL == 'iar':
    print("\nThe current project does not support iar build\n")
    Return('group')

elif rtconfig.CROSS_TOOL == 'gcc':
    src = Glob('*.c')
    CPPPATH = [cwd+'/fsp_cfg', cwd + '/fsp_cfg/bsp']

group += DefineGroup('ra_cfg', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
