from building import *

cwd = GetCurrentDir()
src = []

if GetDepend('BSP_USING_PIN'):
    src += ['drv_pin.c']

if GetDepend('BSP_USING_UART'):
    src += ['drv_uart.c']

if GetDepend('BSP_USING_I2C'):
    src += ['drv_i2c.c']

if GetDepend('BSP_USING_SPI'):
    src += ['drv_spi.c']

if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']

if GetDepend('BSP_USING_WDT'):
    src += ['drv_wdt.c']

if GetDepend('BSP_USING_CLOCK_TIMER'):
    src += ['drv_hwtimer.c']

if GetDepend('BSP_USING_PWM'):
    src += ['drv_pwm.c']

group = DefineGroup('Drivers', src, depend=[''], CPPPATH=[cwd])

Return('group')
