import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]

src = []
if GetDepend(['RT_USING_LWIP']):
	src += Split('''
		wifi_test.c
		''')

group = DefineGroup('app_wifi', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
