subdir-ccflags-y +=     -I$(srctree)/ekernel/drivers/hal/source/usb/include
subdir-ccflags-y +=     -I$(srctree)/ekernel/drivers/hal/source/usb/core

obj-y += ehci-hcd.o
obj-y += sunxi-hci.o
obj-y += ehci-sunxi.o
obj-y += hal_hci.o
