# for module compiling
import os
Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
objs = []

objs = objs + SConscript(os.path.join(cwd, rtconfig.CHIP_NAME, 'SConscript'))
ASFLAGS = ' -I' + cwd

Return('objs')
