Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd, cwd + '/../../include']

if GetDepend('RT_UTEST_SDIO'):
    src += Glob('*.c')

group = DefineGroup('utestcases', src,
                    depend = ['RT_USING_UTESTCASES', 'RT_USING_SDIO'],
                    CPPPATH = CPPPATH)

Return('group')
