import rtconfig

from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPDEFINES=[]
CPPPATH = [cwd]

group = DefineGroup('board', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
