from building import *

cwd = GetCurrentDir()

src = Split("""
board.c
clock_config.c
drv_gpio.c
""")

CPPPATH = [cwd]

# add driver code
if GetDepend('BSP_USING_UART0'):
    src = src + ['drv_uart.c'] 

if GetDepend('BSP_USING_SPI2'):
    src = src + ['drv_spi.c'] 

if GetDepend('BSP_USING_I2C4'):
    src = src + ['drv_i2c.c'] 

if GetDepend('BSP_USING_ROMFS'):
    src = src + ['drv_romfs.c'] 

if GetDepend('BSP_USING_SDCARD'):
    src = src + ['drv_sdcard.c'] 

if GetDepend('BSP_USING_SPIFLASH'):
    src = src + ['drv_spi_flash.c'] 

if GetDepend('BSP_USING_AUDIO_REPLAY'):
    src = src + ['audio/drv_sound.c']
    src = src + ['audio/fsl_wm8904.c']

if GetDepend('BSP_USING_AUDIO_RECORD'):
    src = src + ['audio/drv_mic.c']

if GetDepend('BSP_USING_AUDIO_REPLAY') or GetDepend('BSP_USING_AUDIO_RECORD'):
    CPPPATH += [cwd+'audio']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
