from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]

src = Split("""
""")

if  GetDepend('SOC_XUANTIE'):

    if GetDepend('BSP_USING_UART'):
        src += ['drv_usart.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
