from building import *
import rtconfig

cwd = GetCurrentDir()

src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('rw007', src, depend = ['PKG_USING_RW007'], CPPPATH = CPPPATH)

Return('group')
