# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
board.c
drv_uart.c
mbox.c
''')
CPPPATH = [cwd]

if GetDepend('BSP_USING_SYSTIMER'):
    src += ['drv_timer.c']
if GetDepend('BSP_USING_PIN'):
    src += ['drv_gpio.c']
if GetDepend('BSP_USING_I2C'):
    src += ['drv_i2c.c']
if GetDepend('BSP_USING_WDT'):
    src += ['drv_wdt.c']
if GetDepend('BSP_USING_SPI'):
    src += ['drv_spi.c']
if GetDepend('BSP_USING_SDIO'):
    src += ['drv_sdio.c']
if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']
if GetDepend('BSP_USING_HDMI'):
    src += ['drv_fb.c']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
