import os
from building import *

cwd = GetCurrentDir()
src = []

if GetDepend('BSP_USING_GD32VW553_AT'):
    src += ['gd32vw553_at_port.c']

group = DefineGroup('BoardPorts', src, depend = [''], CPPPATH = [cwd])

if GetDepend('BSP_USING_OV7670'):
    group += SConscript(os.path.join('camera', 'SConscript'))

Return('group')
