# RT-Thread building script for component

from building import *
cwd     = GetCurrentDir()
src     = []
CPPPATH = []

src += Glob('*.c')
CPPPATH += [cwd]

group = DefineGroup('libcpu', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
