from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['RT_USING_PIN']):
    src = src + ['dev_pin.c']

if GetDepend(['RT_USING_ADC']):
    src = src + ['dev_adc.c']

if GetDepend(['RT_USING_DAC']):
    src = src + ['dev_dac.c']

if GetDepend(['RT_USING_PWM']):
    src = src + ['dev_pwm.c']

if GetDepend(['RT_USING_PULSE_ENCODER']):
    src = src + ['dev_pulse_encoder.c']

if GetDepend(['RT_USING_INPUT_CAPTURE']):
    src = src + ['dev_inputcapture.c']

if GetDepend(['RT_USING_DEV_BUS']):
    src = src + ['dev_bus.c']

if GetDepend(['RT_USING_NULL']):
    src = src + ['dev_null.c']

if GetDepend(['RT_USING_ZERO']):
    src = src + ['dev_zero.c']

if GetDepend(['RT_USING_RANDOM']):
    src = src + ['dev_random.c']

if len(src):
    group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
