from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['RT_USING_PIN']):
    src = src + ['pin.c']

if GetDepend(['RT_USING_ADC']):
    src = src + ['adc.c']

if GetDepend(['RT_USING_DAC']):
    src = src + ['dac.c']

if GetDepend(['RT_USING_PWM']):
    src = src + ['rt_drv_pwm.c']

if GetDepend(['RT_USING_PULSE_ENCODER']):
    src = src + ['pulse_encoder.c']

if GetDepend(['RT_USING_INPUT_CAPTURE']):
    src = src + ['rt_inputcapture.c']

if GetDepend(['RT_USING_DEV_BUS']):
    src = src + ['rt_dev_bus.c']

if GetDepend(['RT_USING_NULL']):
    src = src + ['rt_null.c']

if GetDepend(['RT_USING_ZERO']):
    src = src + ['rt_zero.c']

if GetDepend(['RT_USING_RANDOM']):
    src = src + ['rt_random.c']

if len(src):
    group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
