# RT-Thread building script for component

Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split('''
Device/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c
''')
CPPPATH = [cwd + '/Device/ST/STM32F4xx/Include', cwd + '/Include']
CPPDEFINES = [rtconfig.PART_TYPE] #stm32f411xe

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
     folder = 'gcc'
elif rtconfig.CROSS_TOOL == 'keil':
     folder = 'arm'
elif rtconfig.CROSS_TOOL == 'iar':
     folder = 'iar'
#Device/ST/STM32F4xx/Source/Templates/iar/startup_stm32f411xe.s     
src += ['Device/ST/STM32F4xx/Source/Templates/' + folder + '/startup_' + rtconfig.PART_TYPE+ '.s']

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
