Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Split('''
fsl_sd.c
fsl_sdmmc.c
fsl_host.c
fsl_sd_event.c
''')
#src    = Glob('*.c')

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
