import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
CMSIS/Device/ST/STM32G4xx/Source/Templates/system_stm32g4xx.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_crc.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cryp.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cryp_ex.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rng.c
STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c
''')
    
if GetDepend(['RT_USING_SERIAL']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_usart.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_usart_ex.c']

if GetDepend(['RT_USING_I2C']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2c.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2c_ex.c']

if GetDepend(['RT_USING_SPI']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_qspi.c']

if GetDepend(['RT_USING_USB_HOST']) or GetDepend(['RT_USING_USB_DEVICE']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pccard.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pcd.c'] 
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pcd_ex.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_hcd.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_usb.c']

if GetDepend(['RT_USING_CAN']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_can.c']

if GetDepend(['RT_USING_HWTIMER']) or GetDepend(['RT_USING_PWM']) or GetDepend(['RT_USING_PULSE_ENCODER']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_lptim.c']

if GetDepend(['BSP_USING_ETH']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_eth.c']

if GetDepend(['RT_USING_ADC']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c']

if GetDepend(['RT_USING_RTC']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rtc.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rtc_ex.c']

if GetDepend(['RT_USING_WDT']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_iwdg.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_wwdg.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_sdmmc.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_sd.c']

if GetDepend(['RT_USING_AUDIO']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2s.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_i2s_ex.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_sai.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_sai_ex.c']

if GetDepend(['RT_USING_MTD_NOR']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_nor.c']

if GetDepend(['RT_USING_MTD_NAND']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_nand.c']

if GetDepend(['BSP_USING_FMC']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_fmc.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_fsmc.c']

if GetDepend(['BSP_USING_SDRAM']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_sdram.c']

if GetDepend(['BSP_USING_EXT_FMC_IO']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_sram.c']

if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c']

if GetDepend(['BSP_USING_LTDC']):
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_ltdc.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_ltdc_ex.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma2d.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_dma2d.c']
    src += ['STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dsi.c']

path = [cwd + '/STM32G4xx_HAL_Driver/Inc',
    cwd + '/CMSIS/Device/ST/STM32G4xx/Include',
    cwd + '/CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
