Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = []

if rtconfig.CROSS_TOOL == 'iar':
    print("\nThe current project does not support iar build\n")
    Return('group')
elif rtconfig.CROSS_TOOL == 'gcc':
    CPPPATH = [cwd, ]
    src = Glob('*.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
