from building import *

cwd = GetCurrentDir()
src = Split("""
board.c
stm32h7xx_it.c
drv_mpu.c
""")

if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_usart.c']

if GetDepend('RT_USING_LWIP'):
    src += ['lan8742a.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
