# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
objs = []

for item in os.listdir(cwd):
    sconsfile = os.path.join(cwd, item, 'SConscript')
    if os.path.isfile(sconsfile):
        objs = objs + SConscript(sconsfile)

Return('objs')
