# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []
path    = [cwd]
path   += [cwd + '/config']

if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']

if GetDepend('RT_USING_SERIAL'):
    src += ['drv_usart.c']

if GetDepend('RT_USING_SDIO'):
    src += ['drv_sdio.c']

if GetDepend('RT_USING_I2C'):
    src += ['drv_soft_i2c.c']

if GetDepend('RT_USING_WDT'):
    src += ['drv_wdt.c']

if GetDepend('RT_USING_HWTIMER'):
    src += ['drv_hwtimer.c']

if GetDepend('RT_USING_PWM'):
    src += ['drv_pwm.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
