
from building import *
import rtconfig

cwd = GetCurrentDir()

src = []

src += Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_WIFI'], CPPPATH = CPPPATH)

Return('group')
