/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.c
**     Project     : FRDM-KV10Z
**     Processor   : MKV10Z32VLF7
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     All Rights Reserved.
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.4
** @brief
**
*/
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/

/* MODULE pin_mux. */

#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "fsl_sim_hal.h"
#include "pin_mux.h"

void configure_ftm_pins(uint32_t instance)
{
  switch(instance) {
    case FTM0_IDX:                      /* FTM0_IDX */
      /* Affects PORTD_PCR6 register */
      PORT_HAL_SetMuxMode(PORTD,6UL,kPortMuxAlt4);
      SIM_HAL_SetFtmChOutSrcMode(SIM,FTM0_IDX,0u,kSimFtmChOutSrc0);
      SIM_HAL_SetFtmChOutSrcMode(SIM,FTM0_IDX,1u,kSimFtmChOutSrc0);
      SIM_HAL_SetFtmChOutSrcMode(SIM,FTM0_IDX,2u,kSimFtmChOutSrc0);
      SIM_HAL_SetFtmChOutSrcMode(SIM,FTM0_IDX,3u,kSimFtmChOutSrc0);
      SIM_HAL_SetFtmChOutSrcMode(SIM,FTM0_IDX,4u,kSimFtmChOutSrc0);
      SIM_HAL_SetFtmChOutSrcMode(SIM,FTM0_IDX,5u,kSimFtmChOutSrc0);
      /* Affects PORTE_PCR25 register */
      PORT_HAL_SetMuxMode(PORTE,25UL,kPortMuxAlt3);
      /* Affects PORTE_PCR29 register */
      PORT_HAL_SetMuxMode(PORTE,29UL,kPortMuxAlt3);
      /* Affects PORTC_PCR4 register */
      PORT_HAL_SetMuxMode(PORTC,4UL,kPortMuxAlt4);
      /* Affects PORTD_PCR4 register */
      PORT_HAL_SetMuxMode(PORTD,4UL,kPortMuxAlt4);
      /* Affects PORTD_PCR5 register */
      PORT_HAL_SetMuxMode(PORTD,5UL,kPortMuxAlt4);
      break;
    case FTM1_IDX:                      /* FTM1_IDX */
      /* Affects PORTA_PCR2 register */
      PORT_HAL_SetMuxMode(PORTA,2UL,kPortMuxAlt6);
      SIM_HAL_SetFtmChSrcMode(SIM,FTM1_IDX,0u,kSimFtmChSrc0);
      /* Affects PORTA_PCR1 register */
      PORT_HAL_SetMuxMode(PORTA,1UL,kPortMuxAlt6);
      break;
    case FTM2_IDX:                      /* FTM2_IDX */
      /* Affects PORTC_PCR1 register */
      PORT_HAL_SetMuxMode(PORTC,1UL,kPortMuxAlt5);
      SIM_HAL_SetFtmChSrcMode(SIM,FTM2_IDX,0u,kSimFtmChSrc0);
      SIM_HAL_SetFtmChSrcMode(SIM,FTM2_IDX,1u,kSimFtmChSrc0);
      SIM_HAL_SetFtmChOutSrcMode(SIM,FTM2_IDX,0u,kSimFtmChOutSrc0);
      SIM_HAL_SetFtmChOutSrcMode(SIM,FTM2_IDX,1u,kSimFtmChOutSrc0);
      /* Affects PORTC_PCR2 register */
      PORT_HAL_SetMuxMode(PORTC,2UL,kPortMuxAlt5);
      break;
    default:
      break;
  }
}

void configure_gpio_pins(uint32_t instance)
{
  switch(instance) {
    case PORTA_IDX:                      /* PORTA_IDX */
      /* Affects PORTA_PCR2 register */
      PORT_HAL_SetMuxMode(PORTA,2u,kPortMuxAsGpio);
      /* Affects PORTA_PCR4 register */
      PORT_HAL_SetMuxMode(PORTA,4u,kPortMuxAsGpio);
      break;
    case PORTB_IDX:                      /* PORTB_IDX */
      /* Affects PORTB_PCR0 register */
      PORT_HAL_SetMuxMode(PORTB,0u,kPortMuxAsGpio);
      /* Affects PORTB_PCR3 register */
      PORT_HAL_SetMuxMode(PORTB,3u,kPortMuxAsGpio);
      break;
    case PORTC_IDX:                      /* PORTC_IDX */
      /* Affects PORTC_PCR1 register */
      PORT_HAL_SetDriveStrengthMode(PORTC,1u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTC,1u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTC,1u,kPortSlowSlewRate);
      /* Affects PORTC_PCR3 register */
      PORT_HAL_SetDriveStrengthMode(PORTC,3u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTC,3u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTC,3u,kPortSlowSlewRate);
      /* Affects PORTC_PCR4 register */
      PORT_HAL_SetDriveStrengthMode(PORTC,4u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTC,4u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTC,4u,kPortSlowSlewRate);
      break;
    case PORTD_IDX:                      /* PORTD_IDX */
      /* Affects PORTD_PCR4 register */
      PORT_HAL_SetDriveStrengthMode(PORTD,4u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTD,4u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTD,4u,kPortSlowSlewRate);
      /* Affects PORTD_PCR5 register */
      PORT_HAL_SetDriveStrengthMode(PORTD,5u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTD,5u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTD,5u,kPortSlowSlewRate);
      /* Affects PORTD_PCR6 register */
      PORT_HAL_SetDriveStrengthMode(PORTD,6u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTD,6u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTD,6u,kPortSlowSlewRate);
      /* Affects PORTD_PCR7 register */
      PORT_HAL_SetDriveStrengthMode(PORTD,7u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTD,7u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTD,7u,kPortSlowSlewRate);
    case PORTE_IDX:                      /* PORTE_IDX */
      /* Affects PORTE_PCR25 register */
      PORT_HAL_SetDriveStrengthMode(PORTE,25u,kPortLowDriveStrength);
      PORT_HAL_SetMuxMode(PORTE,25u,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTE,25u,kPortSlowSlewRate);
      break;
    default:
      break;
  }
}

void configure_i2c_pins(uint32_t instance)
{
  /* Affects PORTC_PCR6 register */
  PORT_HAL_SetMuxMode(PORTC,6UL,kPortMuxAlt7);
  /* Affects PORTC_PCR7 register */
  PORT_HAL_SetMuxMode(PORTC,7UL,kPortMuxAlt7);
}

void configure_spi_pins(uint32_t instance)
{
  switch(instance) {
    case SPI0_IDX:                       /* SPI0 */
      /* Affects PORTC_PCR4 register */
      PORT_HAL_SetMuxMode(PORTC,4UL,kPortMuxAlt2);
      /* Affects PORTD_PCR3 register */
      PORT_HAL_SetMuxMode(PORTD,3UL,kPortMuxAlt2);
      /* Affects PORTC_PCR5 register */
      PORT_HAL_SetMuxMode(PORTC,5UL,kPortMuxAlt2);
      /* Affects PORTD_PCR2 register */
      PORT_HAL_SetMuxMode(PORTD,2UL,kPortMuxAlt2);
      break;
    default:
      break;
  }
}

void configure_uart_pins(uint32_t instance)
{
  switch(instance) {
    case UART0_IDX:                      /* UART0 */
      /* Affects PORTB_PCR16 register */
      PORT_HAL_SetMuxMode(PORTB,16u,kPortMuxAlt3);
      /* Affects PORTB_PCR17 register */
      PORT_HAL_SetMuxMode(PORTB,17u,kPortMuxAlt3);
      break;
    case UART1_IDX:                      /* UART1 */
      /* Affects PORTD_PCR0 register */
      PORT_HAL_SetMuxMode(PORTD,0u,kPortMuxAlt5);
      /* Affects PORTD_PCR1 register */
      PORT_HAL_SetMuxMode(PORTD,1u,kPortMuxAlt5);
      break;
    default:
      break;
  }
}

void configure_gpio_i2c_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTC,6u,kPortMuxAsGpio);
  PORT_HAL_SetMuxMode(PORTC,7u,kPortMuxAsGpio);
}


void configure_cmp_pins(uint32_t instance)
{
  switch(instance) {
    case CMP0_IDX:                      /* CMP0 */
      /* Affects PORTC_PCR5 register -- CMP0_OUT*/
      PORT_HAL_SetMuxMode(PORTC,5u,kPortMuxAlt6);
      /* Affects PORTC_PCR6 register -- CMP0_IN0, KV10 J9-2*/
      PORT_HAL_SetMuxMode(PORTC,6u,kPortPinDisabled);
      /* Affects PORTC_PCR7 register -- CMP0_IN1*/
      PORT_HAL_SetMuxMode(PORTC,7u,kPortPinDisabled);
      break;
    case CMP1_IDX:                      /* CMP1 */
      /* Affects PORTC_PCR2 register -- CMP1_IN0, J6-15*/
      PORT_HAL_SetMuxMode(PORTC,2u,kPortPinDisabled);
      /* Affects PORTC_PCR3 register -- CMP1_IN1*/
      PORT_HAL_SetMuxMode(PORTC,3u,kPortPinDisabled);
      /* Affects PORTC_PCR4 register -- CMP1_OUT*/
      PORT_HAL_SetMuxMode(PORTC,4u,kPortMuxAlt6);
      break;
    default:
      break;
  }
}

void configure_dac_pins(uint32_t instance)
{
    switch (instance)
    {
        case DAC0_IDX:
            PORT_HAL_SetMuxMode(PORTE, 30U, kPortPinDisabled);
            break;
        default:
            break;
    }
}

/* END pin_mux. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/

