from building import *

src   = Glob('*.c')
if GetDepend(['RT_USING_PICOLIBC']):
    group = DefineGroup('UTest', src, depend = ['RT_USING_PTHREADS'])
else:
    group = DefineGroup('UTest', src, depend = ['RT_USING_NEWLIBC', 'RT_USING_PTHREADS'])

Return('group')
