from building import *
import os

cwd     = GetCurrentDir()

CPPPATH = [cwd]
CPPPATH += [cwd + '/include']
CPPPATH += [cwd + '/include/core']
CPPPATH += [cwd + '/include/drv']

src = Split("""
""")

group = DefineGroup('csi2_inc', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
