from building import *

cwd  = GetCurrentDir()
src = Glob('*.c')
if not GetDepend("USE_MEM_PROTECTION_EXAMPLES"):
    SrcRemove(src, 'mp_example_exclusive_region.c')
    SrcRemove(src, 'mp_example_ro_data.c')
    SrcRemove(src, 'mp_example_exception_hook.c')
CPPPATH = [cwd]

group = DefineGroup('mp', src, depend = ['RT_USING_MEM_PROTECTION'], CPPPATH = CPPPATH)

Return('group')
