utest.spi:
  kconfig:
    - CONFIG_BSP_USING_SPI=y
    - CONFIG_BSP_USING_SPI5=y
    - CONFIG_RT_USING_UTESTCASES=y
    - CONFIG_RT_CONSOLEBUF_SIZE=256
    - CONFIG_RT_UTEST_SPI_LOOPBACK=y
    - CONFIG_RT_UTEST_SPI_LOOPBACK_BUS_NAME="spi5"
    - CONFIG_RT_UTEST_SPI_LOOPBACK_DEV_NAME="spi_loop"
    - CONFIG_RT_UTEST_SPI_LOOPBACK_DATA_SIZE=512
    - CONFIG_RT_UTEST_SPI_LOOPBACK_MAX_HZ=10000000
    - CONFIG_RT_UTEST_SPI_LOOPBACK_API_SMOKE=y
    - CONFIG_RT_UTEST_SPI_FLASH=y
    - CONFIG_RT_UTEST_SPI_FLASH_SPI_DEV_NAME="spi50"
    - CONFIG_RT_UTEST_SPI_FLASH_BUS_NAME="spi5"
    - CONFIG_RT_UTEST_SPI_FLASH_CS_PIN=136
    - CONFIG_RT_UTEST_SPI_FLASH_DEV_NAME="GD25Q16B"
    - CONFIG_RT_UTEST_SPI_FLASH_MAX_HZ=10000000
