scons.args: &scons
    scons_arg:
      - '--strict'
devices.wifi:
    kconfig:
      - CONFIG_BSP_USING_WIFI=y
      - CONFIG_RT_USING_WIFI=y
      - CONFIG_RT_USING_LWIP=y
      - CONFIG_RT_USING_NETDEV=y