from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src = ['main.c']
src += ['mnt.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
