# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
board.c
ab32vg1_hal_msp.c
''')
CPPPATH = [cwd]
CPPPATH += [cwd + '/ports']

if GetDepend(['RT_USING_AUDIO']):
    src += Glob('ports/audio/drv_sound.c')

if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += Glob('ports/on_chip_flash_init.c')

group = DefineGroup('Board', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
