from building import *

cwd     = GetCurrentDir()
src     = list()
CPPPATH = [cwd]
group   = []

group = DefineGroup('Utilities', src, depend = ['RT_USING_ADT_HASHMAP'], CPPPATH = CPPPATH)
Return('group')
