Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

# add for startup script 
if rtconfig.CROSS_TOOL == 'iar':
    CPPDEFINES = ['_TIMESPEC_DEFINED']
else:
    CPPDEFINES = []

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
