from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

if GetDepend(['RT_GRAPHIC_FB_BCM2708']):
    src += ['fb-bcm2708.c']

if GetDepend(['RT_GRAPHIC_FB_RPISENSE']):
    src += ['fb-rpisense.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
