Import('RTT_ROOT')
from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd]
group = DefineGroup('Drivers', src, depend = ['RT_USING_USB_DEVICE'], CPPPATH = CPPPATH)

Return('group')
