from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

# remove no need file.
if GetDepend('RT_USING_LWIP') == False:
    SrcRemove(src, 'dm9161.c')
if GetDepend('RT_USING_DFS') == False:
    SrcRemove(src, 'sdcard.c')
if GetDepend('RT_USING_RTGUI') == False:
    SrcRemove(src, 'lcd.c')
    SrcRemove(src, 'lcdc.c')

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
