# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd, Dir('#')]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
