# RT-Thread building script for bridge

import os
from building import *

Import('rtconfig')

cwd  = GetCurrentDir()
objs = []
list = os.listdir(cwd)
CPPDEFINES = []

objs = objs + SConscript(os.path.join('drivers', 'SConscript'))
objs = objs + SConscript(os.path.join('utilities', 'SConscript'))

if rtconfig.PLATFORM in ['gcc']:
    objs = objs + SConscript(os.path.join('gcc', 'SConscript'))
    CPPDEFINES += ['__USE_CMSIS']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    objs = objs + SConscript(os.path.join('arm', 'SConscript'))
elif rtconfig.PLATFORM in ['iccarm']:
    objs = objs + SConscript(os.path.join('iar', 'SConscript'))

src = Split("""
system_LPC54114_cm4.c
""")

CPPPATH     = [cwd]
CPPDEFINES += ['CORE_M4', 'CPU_LPC54114', 'CPU_LPC54114J256BD64_cm4=1']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

objs = objs + group

Return('objs')
