from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd]

# remove no need file.
if GetDepend('RT_USING_LWIP') == False:
    SrcRemove(src, 'stm32f2_eth.c')
if GetDepend('RT_USING_DFS') == False:
    SrcRemove(src, 'sdio_sd.c')

#remove other no use files
#SrcRemove(src, 'FM25Lx.c')
#SrcRemove(src, '24LCxx.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
