from building import *

group   = []

if not GetDepend(['RT_GRAPHIC_BACKLIGHT']):
    Return('group')

cwd     = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src     = ['backlight.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
