import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
board_config.c
''')

path =  [cwd]
path += [cwd + '/ports']
path += [cwd + '/config']
path += [cwd + '/config/usb_config']

CPPDEFINES = ['HC32F4A8', '__DEBUG']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
