# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

if rtconfig.PLATFORM == 'armcc':
    src += Glob('*_rvds.S')

if rtconfig.PLATFORM == 'gcc':
    src += Glob('*_init.S')
    src += Glob('*_gcc.S')

if rtconfig.PLATFORM == 'iar':
    src += Glob('*_iar.S')

# There is no GIC in Raspi3, so remove it from source files.
if GetDepend('SOC_BCM283x'):
    SrcRemove(src, ['gic.c'])

group = DefineGroup('cpu', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
