Import('rtconfig')
from building import *

cwd = GetCurrentDir()
path = [cwd + '/../CMSIS/Core/Include',cwd + '/components/codec', cwd + '/MCXA153', cwd + '/MCXA153/drivers', cwd + '/middleware/sdmmc/inc', cwd + '/middleware/sdmmc/port']
src = Split('''
            MCXA153/system_MCXA153.c
            ''')

if rtconfig.PLATFORM in ['gcc']:
    src += ['MCXA153/gcc/startup_MCXA153.S']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['MCXA153/arm/startup_MCXA153.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['MCXA153/iar/startup_MCXA153.s']

src += ['MCXA153/drivers/fsl_aoi.c']
src += ['MCXA153/drivers/fsl_clock.c']
src += ['MCXA153/drivers/fsl_cmc.c']
src += ['MCXA153/drivers/fsl_common.c']
src += ['MCXA153/drivers/fsl_common_arm.c']
src += ['MCXA153/drivers/fsl_crc.c']
src += ['MCXA153/drivers/fsl_ctimer.c']
src += ['MCXA153/drivers/fsl_edma.c']
src += ['MCXA153/drivers/fsl_edma_soc.c']
src += ['MCXA153/drivers/fsl_eim.c']
src += ['MCXA153/drivers/fsl_eqdc.c']
src += ['MCXA153/drivers/fsl_erm.c']
src += ['MCXA153/drivers/fsl_freqme.c']
src += ['MCXA153/drivers/fsl_glikey.c']
src += ['MCXA153/drivers/fsl_gpio.c']
src += ['MCXA153/drivers/fsl_i3c.c']
src += ['MCXA153/drivers/fsl_i3c_edma.c']
src += ['MCXA153/drivers/fsl_inputmux.c']
src += ['MCXA153/drivers/fsl_lpadc.c']
src += ['MCXA153/drivers/fsl_lpcmp.c']
src += ['MCXA153/drivers/fsl_lpi2c.c']
src += ['MCXA153/drivers/fsl_lpi2c_edma.c']
src += ['MCXA153/drivers/fsl_lptmr.c']
src += ['MCXA153/drivers/fsl_lpuart.c']
src += ['MCXA153/drivers/fsl_lpuart_edma.c']
src += ['MCXA153/drivers/fsl_ostimer.c']
src += ['MCXA153/drivers/fsl_pwm.c']
src += ['MCXA153/drivers/fsl_reset.c']
src += ['MCXA153/drivers/fsl_spc.c']
src += ['MCXA153/drivers/fsl_utick.c']
src += ['MCXA153/drivers/fsl_vbat.c']
src += ['MCXA153/drivers/fsl_waketimer.c']
src += ['MCXA153/drivers/fsl_wuu.c']
src += ['MCXA153/drivers/fsl_wwdt.c']

if GetDepend('BSP_USING_SPI'):
    src += ['MCXA153/drivers/fsl_lpspi.c']
    src += ['MCXA153/drivers/fsl_lpspi_edma.c']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
