
from building import *
import rtconfig

cwd     = GetCurrentDir()

src = []

src     += Glob('*.c')
CPPPATH = [cwd]
LOCAL_CCFLAGS = ''

if rtconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=c99'
elif rtconfig.CROSS_TOOL == 'keil':
    if rtconfig.PLATFORM == 'armcc':
        LOCAL_CCFLAGS += ' --c99'
    elif rtconfig.PLATFORM == 'armclang':
        LOCAL_CCFLAGS += ' -std=c99'

group = DefineGroup('FAL', src, depend = ['PKG_USING_FAL'], CPPPATH = CPPPATH, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
