
from building import *
import rtconfig

cwd     = GetCurrentDir()

src = []

src     += Glob('*.c')
CPPPATH = [cwd]
LOCAL_CFLAGS = ''

if rtconfig.PLATFORM == 'gcc':
    LOCAL_CFLAGS += ' -std=c99'
elif rtconfig.PLATFORM == 'armcc':
    LOCAL_CFLAGS += ' --c99'
elif rtconfig.PLATFORM == 'armclang':
    LOCAL_CFLAGS += ' -std=c99'

group = DefineGroup('FAL', src, depend = ['RT_USING_FAL'], CPPPATH = CPPPATH, LOCAL_CFLAGS = LOCAL_CFLAGS)

Return('group')
