from building import *
import rtconfig

cwd  = GetCurrentDir()
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

if rtconfig.ASAN == True:
    LIBS = ['asan', 'ubsan']
    group = DefineGroup('asan', [], depend = [''], LIBS=LIBS)
    objs += group

Return('objs')
