import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
CMSIS/Device/ST/STM32F2xx/Source/Templates/system_stm32f2xx.c
STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_dma.c
STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_cortex.c
STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_crc.c
STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_pwr.c
STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_rcc.c
STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_rcc_ex.c
STM32F2xx_HAL_Driver/Src/stm32f2xx_hal.c
STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_sram.c
STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_gpio.c
""")

if GetDepend(['RT_USING_SERIAL']) or GetDepend(['RT_USING_NANO', 'RT_USING_CONSOLE']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_uart.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_usart.c']

if GetDepend(['RT_USING_I2C']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_spi.c']

if GetDepend(['RT_USING_USB']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_pccard.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_pcd.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_pcd_ex.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_ll_usb.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_hcd.c']

if GetDepend(['RT_USING_CAN']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_can.c']

if GetDepend(['RT_USING_HWTIMER']) or GetDepend(['RT_USING_PWM']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_tim.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_tim_ex.c']

if GetDepend(['BSP_USING_ETH']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_eth.c']

if GetDepend(['RT_USING_ADC']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_adc.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_adc_ex.c']

if GetDepend(['RT_USING_RTC']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_rtc.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_rtc_ex.c']

if GetDepend(['RT_USING_WDT']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_iwdg.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_wwdg.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_mmc.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_sd.c']

if GetDepend(['RT_USING_AUDIO']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_i2s.c']

if GetDepend(['RT_USING_MTD_NOR']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_nor.c']

if GetDepend(['RT_USING_MTD_NAND']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_nand.c']

if GetDepend(['BSP_USING_EXT_FMC_IO']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_sram.c']

if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_flash.c']
    src += ['STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_flash_ex.c']

path = [cwd + '/CMSIS/Device/ST/STM32F2xx/Include',
    cwd + '/STM32F2xx_HAL_Driver/Inc']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
