# RT-Thread building script for component

from building import *
cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('*_gcc.S')
CPPPATH = [cwd]

if GetDepend('ARCH_RISCV_VECTOR'):
    CPPPATH += [cwd + '/../../vector/rvv-1.0']

group = DefineGroup('libcpu', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
