import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = []
path = [cwd]

if GetDepend(['RT_USING_CHERRYUSB']):
    src += Glob('cherryusb_port.c')

group = DefineGroup('Platform', src, depend = ['RT_USING_CHERRYUSB'], CPPPATH = path)

Return('group')
