import rtconfig
Import('RTT_ROOT')
from building import *

src_bsp   = ['application.c', 'startup.c']

src = File(src_bsp)
CPPPATH = [ GetCurrentDir() ]
CPPDEFINES = []
group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
