from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = ['main.c']

if GetDepend(['RT_USING_DFS']):
    src += ['mnt.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
