import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd]
src = []

if GetDepend(['BSP_USING_LPM']):
    src += ['drv_pm.c']

objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
