# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
group = []
if GetDepend('BSP_USING_HSUSBH') or GetDepend('BSP_USING_USBH'):
    src = Glob('*src/*.c') + Glob('src/*.cpp')
    CPPPATH = [cwd + '/inc']
    group = DefineGroup('n9h30_usbhostlib', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
