from building import *
from utils import VersionCmp

cwd        = GetCurrentDir()
src        = Glob('*.c')
CPPPATH    = [cwd]

group = DefineGroup('POSIX', src, depend = ['RT_USING_PTHREADS'], CPPPATH = CPPPATH)

Return('group')
