from building import *
from utils import VersionCmp

cwd        = GetCurrentDir()
src        = Glob('*.c')
CPPPATH    = [cwd]
CPPDEFINES = []

group = DefineGroup('POSIX', src,
    depend = ['RT_USING_PTHREADS', 'RT_USING_LIBC'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
