from building import *

cwd     = GetCurrentDir()
src     = ["board.c"]
CPPPATH = [cwd, str(Dir('#'))]

if GetDepend(['BSP_USING_PL011']):
    src = src + ['drv_uart.c']

if GetDepend(['BSP_USING_SDHCI']):
    src = src + ['drv_sd.c']

group = DefineGroup('driver', src, depend = [''], CPPPATH = CPPPATH)

# build for sub-directory
list = os.listdir(cwd)
objs = []

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
group = group + objs

Return('group')
