from building import *

cwd = GetCurrentDir()
src = []

# add serial driver code
if  GetDepend('BSP_USING_UART0') or GetDepend('BSP_USING_UART1'):
   src += ['drv_uart.c']
if  GetDepend('BSP_USING_GPIO'):
   src += ['drv_gpio.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
