import os
from building import *

objs = []

cwd = GetCurrentDir()
list = os.listdir(cwd)

for d in list:
    if os.path.isfile(os.path.join(cwd, d, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
