devices.soft_i2c:
  kconfig:
    - CONFIG_RT_USING_I2C=y
    - CONFIG_RT_USING_SOFT_I2C=y
    - CONFIG_RT_USING_SOFT_I2C1=y
    - CONFIG_RT_SOFT_I2C1_SCL_PIN=38
    - CONFIG_RT_SOFT_I2C1_SDA_PIN=39
    - CONFIG_RT_SOFT_I2C1_BUS_NAME="swi2c1"
    - CONFIG_RT_USING_SOFT_I2C3=y
    - CONFIG_RT_SOFT_I2C3_SCL_PIN=32
    - CONFIG_RT_SOFT_I2C3_SDA_PIN=33
    - CONFIG_RT_SOFT_I2C3_BUS_NAME="swi2c3"
    - CONFIG_RT_USING_SOFT_I2C4=y
    - CONFIG_RT_SOFT_I2C4_SCL_PIN=54
    - CONFIG_RT_SOFT_I2C4_SDA_PIN=33
    - CONFIG_RT_SOFT_I2C4_BUS_NAME="swi2c4"
