from building import *

cwd = GetCurrentDir()
src = ['serial.c']

if GetDepend('RT_CHAT_AT'):
    src += ['chat-at.c']

CPPPATH = [cwd, cwd + '/../include']
group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SERIAL'], CPPPATH = CPPPATH)

Return('group')
