from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']
group = []
src = []

if not GetDepend(['RT_USING_SERIAL']):
    Return('group')

if GetDepend(['RT_USING_SMART']):
    src += Glob('serial_tty.c')

if GetDepend(['RT_USING_SERIAL_V2']):
    src += ['dev_serial_v2.c']
else:
    src += ['dev_serial.c']

if GetDepend(['RT_USING_DM']):
    src += ['serial_dm.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
