from building import *
import os
Import('rtconfig')

cwd     = GetCurrentDir()
src     = ['cxx_crt_init.c', 'cxx_crt.cpp']
CPPPATH = [cwd]

group = DefineGroup('CPP', src, depend=['RT_USING_CPLUSPLUS'], CPPPATH=CPPPATH)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
