Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Split("""
i2c_core.c
i2c_dev.c
""")

if GetDepend('RT_USING_I2C_BITOPS'):
    src = src + ['i2c-bit-ops.c']

# The set of source files associated with this SConscript file.
path = [cwd + '/../include']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_I2C'], CPPPATH = path)

Return('group')
