from building import *

cwd     = GetCurrentDir()
src     = list()
CPPPATH = [cwd]
group   = []

group = DefineGroup('LIBADT', src, depend = ['RT_USING_ADT_BITMAP'], CPPPATH = CPPPATH)
Return('group')
