from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('*.S')
CPPPATH = [cwd]

CPPDEFINES = [ 'CONFIG_ARCH_MAINSTACK=8192', 'CONFIG_ARCH_INTERRUPTSTACK=8192']
CPPDEFINES += ['CONFIG_PLIC_BASE=0x08000000']

group = DefineGroup('Board', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
