from building import *

cwd = GetCurrentDir()

src = ['board.c', 'mm32f3277g9p_msp.c']

CPPPATH = [cwd]

CPPDEFINES = ['MM32F3277G']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
