# RT-Thread building script for bridge

import os
from building import *

Import('rtconfig')

cwd   = GetCurrentDir()
group = []
list  = os.listdir(cwd)

# add common code files
group = group + SConscript(os.path.join(cwd, 'common', 'SConscript'))

# cpu porting code files
group = group + SConscript(os.path.join(cwd, rtconfig.CPU, 'SConscript'))

Return('group')
