# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
system.c
''')
CPPPATH = [cwd]


group = DefineGroup('JuiceVm_sdk', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
