Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

src	= Glob('*.c')

CPPPATH = [cwd, cwd + '/include', RTT_ROOT + '/components/drivers/include']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
