Import('RTT_ROOT')
Import('rtconfig')
from building import *
import os

cwd = GetCurrentDir()
group = []
src = []

uart_deps = ['BSP_USING_UART1', 'BSP_USING_UART2', 'BSP_USING_UART3',
             'BSP_USING_UART4', 'BSP_USING_UART5', 'BSP_USING_UART6',
             'BSP_USING_UART7', 'BSP_USING_UART8']

if GetDepend(['RT_USING_SERIAL']) or any([GetDepend(uart) for uart in uart_deps]):
    src += ['drv_uart.c']

gpio_series = ['SOC_SERIES_MM32F103', 'SOC_SERIES_MM32F327',
               'SOC_SERIES_MM32F3277', 'SOC_SERIES_MM32F526',
               'SOC_SERIES_MM32L3']

if (GetDepend(['RT_USING_PIN']) or GetDepend(['BSP_USING_GPIO'])) and any([GetDepend(series) for series in gpio_series]):
    src += ['drv_gpio.c']

adc_series = ['SOC_SERIES_MM32F327', 'SOC_SERIES_MM32F526']

if GetDepend(['BSP_USING_ADC']) and any([GetDepend(series) for series in adc_series]):
    src += ['drv_adc.c']

flash_series = ['SOC_SERIES_MM32F327', 'SOC_SERIES_MM32F3277', 'SOC_SERIES_MM32F526']

if GetDepend(['BSP_USING_OCFLASH']) and any([GetDepend(series) for series in flash_series]):
    src += ['drv_flash.c']

CPPPATH = [
    cwd,
    os.path.abspath(os.path.join(cwd, '..')),
    os.path.join(Dir('#').abspath, 'board'),
    os.path.join(cwd, 'config'),
]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
