from building import *

cwd  = GetCurrentDir()
src = []
if GetDepend("RT_USING_SMP"):
    src += Glob('*.c')
CPPPATH = [cwd]
group = DefineGroup('mprotect', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
