arm_math.h File Reference
arm_math.h File Reference
Data Structures
struct arm_fir_instance_q7
Instance structure for the Q7 FIR filter.
struct arm_fir_instance_q15
Instance structure for the Q15 FIR filter.
struct arm_fir_instance_q31
Instance structure for the Q31 FIR filter.
struct arm_fir_instance_f32
Instance structure for the floating-point FIR filter.
struct arm_biquad_casd_df1_inst_q15
Instance structure for the Q15 Biquad cascade filter.
struct arm_biquad_casd_df1_inst_q31
Instance structure for the Q31 Biquad cascade filter.
struct arm_biquad_casd_df1_inst_f32
Instance structure for the floating-point Biquad cascade filter.
struct arm_matrix_instance_f32
Instance structure for the floating-point matrix structure.
struct arm_matrix_instance_f64
Instance structure for the floating-point matrix structure.
struct arm_matrix_instance_q15
Instance structure for the Q15 matrix structure.
struct arm_matrix_instance_q31
Instance structure for the Q31 matrix structure.
struct arm_pid_instance_q15
Instance structure for the Q15 PID Control.
struct arm_pid_instance_q31
Instance structure for the Q31 PID Control.
struct arm_pid_instance_f32
Instance structure for the floating-point PID Control.
struct arm_linear_interp_instance_f32
Instance structure for the floating-point Linear Interpolate function.
struct arm_bilinear_interp_instance_f32
Instance structure for the floating-point bilinear interpolation function.
struct arm_bilinear_interp_instance_q31
Instance structure for the Q31 bilinear interpolation function.
struct arm_bilinear_interp_instance_q15
Instance structure for the Q15 bilinear interpolation function.
struct arm_bilinear_interp_instance_q7
Instance structure for the Q15 bilinear interpolation function.
struct arm_cfft_radix2_instance_q15
Instance structure for the Q15 CFFT/CIFFT function.
struct arm_cfft_radix4_instance_q15
Instance structure for the Q15 CFFT/CIFFT function.
struct arm_cfft_radix2_instance_q31
Instance structure for the Radix-2 Q31 CFFT/CIFFT function.
struct arm_cfft_radix4_instance_q31
Instance structure for the Q31 CFFT/CIFFT function.
struct arm_cfft_radix2_instance_f32
Instance structure for the floating-point CFFT/CIFFT function.
struct arm_cfft_radix4_instance_f32
Instance structure for the floating-point CFFT/CIFFT function.
struct arm_cfft_instance_q15
Instance structure for the fixed-point CFFT/CIFFT function.
struct arm_cfft_instance_q31
Instance structure for the fixed-point CFFT/CIFFT function.
struct arm_cfft_instance_f32
Instance structure for the floating-point CFFT/CIFFT function.
struct arm_rfft_instance_q15
Instance structure for the Q15 RFFT/RIFFT function.
struct arm_rfft_instance_q31
Instance structure for the Q31 RFFT/RIFFT function.
struct arm_rfft_instance_f32
Instance structure for the floating-point RFFT/RIFFT function.
struct arm_rfft_fast_instance_f32
Instance structure for the floating-point RFFT/RIFFT function.
struct arm_dct4_instance_f32
Instance structure for the floating-point DCT4/IDCT4 function.
struct arm_dct4_instance_q31
Instance structure for the Q31 DCT4/IDCT4 function.
struct arm_dct4_instance_q15
Instance structure for the Q15 DCT4/IDCT4 function.
struct arm_fir_decimate_instance_q15
Instance structure for the Q15 FIR decimator.
struct arm_fir_decimate_instance_q31
Instance structure for the Q31 FIR decimator.
struct arm_fir_decimate_instance_f32
Instance structure for the floating-point FIR decimator.
struct arm_fir_interpolate_instance_q15
Instance structure for the Q15 FIR interpolator.
struct arm_fir_interpolate_instance_q31
Instance structure for the Q31 FIR interpolator.
struct arm_fir_interpolate_instance_f32
Instance structure for the floating-point FIR interpolator.
struct arm_biquad_cas_df1_32x64_ins_q31
Instance structure for the high precision Q31 Biquad cascade filter.
struct arm_biquad_cascade_df2T_instance_f32
Instance structure for the floating-point transposed direct form II Biquad cascade filter.
struct arm_biquad_cascade_stereo_df2T_instance_f32
Instance structure for the floating-point transposed direct form II Biquad cascade filter.
struct arm_biquad_cascade_df2T_instance_f64
Instance structure for the floating-point transposed direct form II Biquad cascade filter.
struct arm_fir_lattice_instance_q15
Instance structure for the Q15 FIR lattice filter.
struct arm_fir_lattice_instance_q31
Instance structure for the Q31 FIR lattice filter.
struct arm_fir_lattice_instance_f32
Instance structure for the floating-point FIR lattice filter.
struct arm_iir_lattice_instance_q15
Instance structure for the Q15 IIR lattice filter.
struct arm_iir_lattice_instance_q31
Instance structure for the Q31 IIR lattice filter.
struct arm_iir_lattice_instance_f32
Instance structure for the floating-point IIR lattice filter.
struct arm_lms_instance_f32
Instance structure for the floating-point LMS filter.
struct arm_lms_instance_q15
Instance structure for the Q15 LMS filter.
struct arm_lms_instance_q31
Instance structure for the Q31 LMS filter.
struct arm_lms_norm_instance_f32
Instance structure for the floating-point normalized LMS filter.
struct arm_lms_norm_instance_q31
Instance structure for the Q31 normalized LMS filter.
struct arm_lms_norm_instance_q15
Instance structure for the Q15 normalized LMS filter.
struct arm_fir_sparse_instance_f32
Instance structure for the floating-point sparse FIR filter.
struct arm_fir_sparse_instance_q31
Instance structure for the Q31 sparse FIR filter.
struct arm_fir_sparse_instance_q15
Instance structure for the Q15 sparse FIR filter.
struct arm_fir_sparse_instance_q7
Instance structure for the Q7 sparse FIR filter.
Macros
#define __CMSIS_GENERIC
#define DELTA_Q31
Macros required for reciprocal calculation in Normalized LMS.
#define DELTA_Q15
#define INDEX_MASK
#define PI
#define FAST_MATH_TABLE_SIZE
Macros required for SINE and COSINE Fast math approximations.
#define FAST_MATH_Q31_SHIFT
#define FAST_MATH_Q15_SHIFT
#define CONTROLLER_Q31_SHIFT
#define TABLE_SPACING_Q31
#define TABLE_SPACING_Q15
#define INPUT_SPACING
Macros required for SINE and COSINE Controller functions.
#define ALIGN4
Macro for Unaligned Support.
#define __SIMD32(addr)
definition to read/write two 16 bit values.
#define __SIMD32_CONST(addr)
#define _SIMD32_OFFSET(addr)
#define __SIMD64(addr)
#define __PKHBT(ARG1, ARG2, ARG3)
definition to pack two 16 bit values.
#define __PKHTB(ARG1, ARG2, ARG3)
#define __PACKq7(v0, v1, v2, v3)
definition to pack four 8 bit values.
#define multAcc_32x32_keep32_R(a, x, y)
#define multSub_32x32_keep32_R(a, x, y)
#define mult_32x32_keep32_R(a, x, y)
#define multAcc_32x32_keep32(a, x, y)
#define multSub_32x32_keep32(a, x, y)
#define mult_32x32_keep32(a, x, y)
Typedefs
typedef int8_t q7_t
8-bit fractional data type in 1.7 format.
typedef int16_t q15_t
16-bit fractional data type in 1.15 format.
typedef int32_t q31_t
32-bit fractional data type in 1.31 format.
typedef int64_t q63_t
64-bit fractional data type in 1.63 format.
typedef float float32_t
32-bit floating-point type definition.
typedef double float64_t
64-bit floating-point type definition.
Enumerations
enum arm_status
Error status returned by some functions in the library.
Functions
CMSIS_INLINE __STATIC_INLINE q31_t clip_q63_to_q31 (q63_t x)
Clips Q63 to Q31 values.
CMSIS_INLINE __STATIC_INLINE q15_t clip_q63_to_q15 (q63_t x)
Clips Q63 to Q15 values.
CMSIS_INLINE __STATIC_INLINE q7_t clip_q31_to_q7 (q31_t x)
Clips Q31 to Q7 values.
CMSIS_INLINE __STATIC_INLINE q15_t clip_q31_to_q15 (q31_t x)
Clips Q31 to Q15 values.
CMSIS_INLINE __STATIC_INLINE q63_t mult32x64 (q63_t x, q31_t y)
Multiplies 32 X 64 and returns 32 bit result in 2.30 format.
CMSIS_INLINE __STATIC_INLINE
uint32_t arm_recip_q31 (q31_t in, q31_t *dst, q31_t *pRecipTable)
Function to Calculates 1/in (reciprocal) value of Q31 Data type.
CMSIS_INLINE __STATIC_INLINE
uint32_t arm_recip_q15 (q15_t in, q15_t *dst, q15_t *pRecipTable)
Function to Calculates 1/in (reciprocal) value of Q15 Data type.
CMSIS_INLINE __STATIC_INLINE
uint32_t __QADD8 (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __QSUB8 (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __QADD16 (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SHADD16 (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __QSUB16 (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SHSUB16 (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __QASX (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SHASX (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __QSAX (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SHSAX (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SMUSDX (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SMUADX (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
int32_t __QADD (int32_t x, int32_t y)
CMSIS_INLINE __STATIC_INLINE
int32_t __QSUB (int32_t x, int32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SMLAD (uint32_t x, uint32_t y, uint32_t sum)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SMLADX (uint32_t x, uint32_t y, uint32_t sum)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SMLSDX (uint32_t x, uint32_t y, uint32_t sum)
CMSIS_INLINE __STATIC_INLINE
uint64_t __SMLALD (uint32_t x, uint32_t y, uint64_t sum)
CMSIS_INLINE __STATIC_INLINE
uint64_t __SMLALDX (uint32_t x, uint32_t y, uint64_t sum)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SMUAD (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SMUSD (uint32_t x, uint32_t y)
CMSIS_INLINE __STATIC_INLINE
uint32_t __SXTB16 (uint32_t x)
CMSIS_INLINE __STATIC_INLINE
int32_t __SMMLA (int32_t x, int32_t y, int32_t sum)
void arm_fir_q7 (const arm_fir_instance_q7 *S, q7_t *pSrc, q7_t *pDst, uint32_t blockSize)
Processing function for the Q7 FIR filter.
void arm_fir_init_q7 (arm_fir_instance_q7 *S, uint16_t numTaps, q7_t *pCoeffs, q7_t *pState, uint32_t blockSize)
Initialization function for the Q7 FIR filter.
void arm_fir_q15 (const arm_fir_instance_q15 *S, q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Processing function for the Q15 FIR filter.
void arm_fir_fast_q15 (const arm_fir_instance_q15 *S, q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Processing function for the fast Q15 FIR filter for Cortex-M3 and Cortex-M4.
arm_status arm_fir_init_q15 (arm_fir_instance_q15 *S, uint16_t numTaps, q15_t *pCoeffs, q15_t *pState, uint32_t blockSize)
Initialization function for the Q15 FIR filter.
void arm_fir_q31 (const arm_fir_instance_q31 *S, q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Processing function for the Q31 FIR filter.
void arm_fir_fast_q31 (const arm_fir_instance_q31 *S, q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Processing function for the fast Q31 FIR filter for Cortex-M3 and Cortex-M4.
void arm_fir_init_q31 (arm_fir_instance_q31 *S, uint16_t numTaps, q31_t *pCoeffs, q31_t *pState, uint32_t blockSize)
Initialization function for the Q31 FIR filter.
void arm_fir_f32 (const arm_fir_instance_f32 *S, float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Processing function for the floating-point FIR filter.
void arm_fir_init_f32 (arm_fir_instance_f32 *S, uint16_t numTaps, float32_t *pCoeffs, float32_t *pState, uint32_t blockSize)
Initialization function for the floating-point FIR filter.
void arm_biquad_cascade_df1_q15 (const arm_biquad_casd_df1_inst_q15 *S, q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Processing function for the Q15 Biquad cascade filter.
void arm_biquad_cascade_df1_init_q15 (arm_biquad_casd_df1_inst_q15 *S, uint8_t numStages, q15_t *pCoeffs, q15_t *pState, int8_t postShift)
Initialization function for the Q15 Biquad cascade filter.
void arm_biquad_cascade_df1_fast_q15 (const arm_biquad_casd_df1_inst_q15 *S, q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Fast but less precise processing function for the Q15 Biquad cascade filter for Cortex-M3 and Cortex-M4.
void arm_biquad_cascade_df1_q31 (const arm_biquad_casd_df1_inst_q31 *S, q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Processing function for the Q31 Biquad cascade filter.
void arm_biquad_cascade_df1_fast_q31 (const arm_biquad_casd_df1_inst_q31 *S, q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Fast but less precise processing function for the Q31 Biquad cascade filter for Cortex-M3 and Cortex-M4.
void arm_biquad_cascade_df1_init_q31 (arm_biquad_casd_df1_inst_q31 *S, uint8_t numStages, q31_t *pCoeffs, q31_t *pState, int8_t postShift)
Initialization function for the Q31 Biquad cascade filter.
void arm_biquad_cascade_df1_f32 (const arm_biquad_casd_df1_inst_f32 *S, float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Processing function for the floating-point Biquad cascade filter.
void arm_biquad_cascade_df1_init_f32 (arm_biquad_casd_df1_inst_f32 *S, uint8_t numStages, float32_t *pCoeffs, float32_t *pState)
Initialization function for the floating-point Biquad cascade filter.
arm_status arm_mat_add_f32 (const arm_matrix_instance_f32 *pSrcA, const arm_matrix_instance_f32 *pSrcB, arm_matrix_instance_f32 *pDst)
Floating-point matrix addition.
arm_status arm_mat_add_q15 (const arm_matrix_instance_q15 *pSrcA, const arm_matrix_instance_q15 *pSrcB, arm_matrix_instance_q15 *pDst)
Q15 matrix addition.
arm_status arm_mat_add_q31 (const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst)
Q31 matrix addition.
arm_status arm_mat_cmplx_mult_f32 (const arm_matrix_instance_f32 *pSrcA, const arm_matrix_instance_f32 *pSrcB, arm_matrix_instance_f32 *pDst)
Floating-point, complex, matrix multiplication.
arm_status arm_mat_cmplx_mult_q15 (const arm_matrix_instance_q15 *pSrcA, const arm_matrix_instance_q15 *pSrcB, arm_matrix_instance_q15 *pDst, q15_t *pScratch)
Q15, complex, matrix multiplication.
arm_status arm_mat_cmplx_mult_q31 (const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst)
Q31, complex, matrix multiplication.
arm_status arm_mat_trans_f32 (const arm_matrix_instance_f32 *pSrc, arm_matrix_instance_f32 *pDst)
Floating-point matrix transpose.
arm_status arm_mat_trans_q15 (const arm_matrix_instance_q15 *pSrc, arm_matrix_instance_q15 *pDst)
Q15 matrix transpose.
arm_status arm_mat_trans_q31 (const arm_matrix_instance_q31 *pSrc, arm_matrix_instance_q31 *pDst)
Q31 matrix transpose.
arm_status arm_mat_mult_f32 (const arm_matrix_instance_f32 *pSrcA, const arm_matrix_instance_f32 *pSrcB, arm_matrix_instance_f32 *pDst)
Floating-point matrix multiplication.
arm_status arm_mat_mult_q15 (const arm_matrix_instance_q15 *pSrcA, const arm_matrix_instance_q15 *pSrcB, arm_matrix_instance_q15 *pDst, q15_t *pState)
Q15 matrix multiplication.
arm_status arm_mat_mult_fast_q15 (const arm_matrix_instance_q15 *pSrcA, const arm_matrix_instance_q15 *pSrcB, arm_matrix_instance_q15 *pDst, q15_t *pState)
Q15 matrix multiplication (fast variant) for Cortex-M3 and Cortex-M4.
arm_status arm_mat_mult_q31 (const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst)
Q31 matrix multiplication.
arm_status arm_mat_mult_fast_q31 (const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst)
Q31 matrix multiplication (fast variant) for Cortex-M3 and Cortex-M4.
arm_status arm_mat_sub_f32 (const arm_matrix_instance_f32 *pSrcA, const arm_matrix_instance_f32 *pSrcB, arm_matrix_instance_f32 *pDst)
Floating-point matrix subtraction.
arm_status arm_mat_sub_q15 (const arm_matrix_instance_q15 *pSrcA, const arm_matrix_instance_q15 *pSrcB, arm_matrix_instance_q15 *pDst)
Q15 matrix subtraction.
arm_status arm_mat_sub_q31 (const arm_matrix_instance_q31 *pSrcA, const arm_matrix_instance_q31 *pSrcB, arm_matrix_instance_q31 *pDst)
Q31 matrix subtraction.
arm_status arm_mat_scale_f32 (const arm_matrix_instance_f32 *pSrc, float32_t scale, arm_matrix_instance_f32 *pDst)
Floating-point matrix scaling.
arm_status arm_mat_scale_q15 (const arm_matrix_instance_q15 *pSrc, q15_t scaleFract, int32_t shift, arm_matrix_instance_q15 *pDst)
Q15 matrix scaling.
arm_status arm_mat_scale_q31 (const arm_matrix_instance_q31 *pSrc, q31_t scaleFract, int32_t shift, arm_matrix_instance_q31 *pDst)
Q31 matrix scaling.
void arm_mat_init_q31 (arm_matrix_instance_q31 *S, uint16_t nRows, uint16_t nColumns, q31_t *pData)
Q31 matrix initialization.
void arm_mat_init_q15 (arm_matrix_instance_q15 *S, uint16_t nRows, uint16_t nColumns, q15_t *pData)
Q15 matrix initialization.
void arm_mat_init_f32 (arm_matrix_instance_f32 *S, uint16_t nRows, uint16_t nColumns, float32_t *pData)
Floating-point matrix initialization.
void arm_pid_init_f32 (arm_pid_instance_f32 *S, int32_t resetStateFlag)
Initialization function for the floating-point PID Control.
void arm_pid_reset_f32 (arm_pid_instance_f32 *S)
Reset function for the floating-point PID Control.
void arm_pid_init_q31 (arm_pid_instance_q31 *S, int32_t resetStateFlag)
Initialization function for the Q31 PID Control.
void arm_pid_reset_q31 (arm_pid_instance_q31 *S)
Reset function for the Q31 PID Control.
void arm_pid_init_q15 (arm_pid_instance_q15 *S, int32_t resetStateFlag)
Initialization function for the Q15 PID Control.
void arm_pid_reset_q15 (arm_pid_instance_q15 *S)
Reset function for the Q15 PID Control.
void arm_mult_q7 (q7_t *pSrcA, q7_t *pSrcB, q7_t *pDst, uint32_t blockSize)
Q7 vector multiplication.
void arm_mult_q15 (q15_t *pSrcA, q15_t *pSrcB, q15_t *pDst, uint32_t blockSize)
Q15 vector multiplication.
void arm_mult_q31 (q31_t *pSrcA, q31_t *pSrcB, q31_t *pDst, uint32_t blockSize)
Q31 vector multiplication.
void arm_mult_f32 (float32_t *pSrcA, float32_t *pSrcB, float32_t *pDst, uint32_t blockSize)
Floating-point vector multiplication.
arm_status arm_cfft_radix2_init_q15 (arm_cfft_radix2_instance_q15 *S, uint16_t fftLen, uint8_t ifftFlag, uint8_t bitReverseFlag)
Initialization function for the Q15 CFFT/CIFFT.
void arm_cfft_radix2_q15 (const arm_cfft_radix2_instance_q15 *S, q15_t *pSrc)
Processing function for the fixed-point CFFT/CIFFT.
arm_status arm_cfft_radix4_init_q15 (arm_cfft_radix4_instance_q15 *S, uint16_t fftLen, uint8_t ifftFlag, uint8_t bitReverseFlag)
Initialization function for the Q15 CFFT/CIFFT.
void arm_cfft_radix4_q15 (const arm_cfft_radix4_instance_q15 *S, q15_t *pSrc)
Processing function for the Q15 CFFT/CIFFT.
arm_status arm_cfft_radix2_init_q31 (arm_cfft_radix2_instance_q31 *S, uint16_t fftLen, uint8_t ifftFlag, uint8_t bitReverseFlag)
Initialization function for the Q31 CFFT/CIFFT.
void arm_cfft_radix2_q31 (const arm_cfft_radix2_instance_q31 *S, q31_t *pSrc)
Processing function for the fixed-point CFFT/CIFFT.
void arm_cfft_radix4_q31 (const arm_cfft_radix4_instance_q31 *S, q31_t *pSrc)
Processing function for the Q31 CFFT/CIFFT.
arm_status arm_cfft_radix4_init_q31 (arm_cfft_radix4_instance_q31 *S, uint16_t fftLen, uint8_t ifftFlag, uint8_t bitReverseFlag)
Initialization function for the Q31 CFFT/CIFFT.
arm_status arm_cfft_radix2_init_f32 (arm_cfft_radix2_instance_f32 *S, uint16_t fftLen, uint8_t ifftFlag, uint8_t bitReverseFlag)
Initialization function for the floating-point CFFT/CIFFT.
void arm_cfft_radix2_f32 (const arm_cfft_radix2_instance_f32 *S, float32_t *pSrc)
Radix-2 CFFT/CIFFT.
arm_status arm_cfft_radix4_init_f32 (arm_cfft_radix4_instance_f32 *S, uint16_t fftLen, uint8_t ifftFlag, uint8_t bitReverseFlag)
Initialization function for the floating-point CFFT/CIFFT.
void arm_cfft_radix4_f32 (const arm_cfft_radix4_instance_f32 *S, float32_t *pSrc)
Processing function for the floating-point Radix-4 CFFT/CIFFT.
void arm_cfft_q15 (const arm_cfft_instance_q15 *S, q15_t *p1, uint8_t ifftFlag, uint8_t bitReverseFlag)
Processing function for the Q15 complex FFT.
void arm_cfft_q31 (const arm_cfft_instance_q31 *S, q31_t *p1, uint8_t ifftFlag, uint8_t bitReverseFlag)
Processing function for the fixed-point complex FFT in Q31 format.
void arm_cfft_f32 (const arm_cfft_instance_f32 *S, float32_t *p1, uint8_t ifftFlag, uint8_t bitReverseFlag)
Processing function for the floating-point complex FFT.
arm_status arm_rfft_init_q15 (arm_rfft_instance_q15 *S, uint32_t fftLenReal, uint32_t ifftFlagR, uint32_t bitReverseFlag)
Initialization function for the Q15 RFFT/RIFFT.
void arm_rfft_q15 (const arm_rfft_instance_q15 *S, q15_t *pSrc, q15_t *pDst)
Processing function for the Q15 RFFT/RIFFT.
arm_status arm_rfft_init_q31 (arm_rfft_instance_q31 *S, uint32_t fftLenReal, uint32_t ifftFlagR, uint32_t bitReverseFlag)
Initialization function for the Q31 RFFT/RIFFT.
void arm_rfft_q31 (const arm_rfft_instance_q31 *S, q31_t *pSrc, q31_t *pDst)
Processing function for the Q31 RFFT/RIFFT.
arm_status arm_rfft_init_f32 (arm_rfft_instance_f32 *S, arm_cfft_radix4_instance_f32 *S_CFFT, uint32_t fftLenReal, uint32_t ifftFlagR, uint32_t bitReverseFlag)
void arm_rfft_f32 (const arm_rfft_instance_f32 *S, float32_t *pSrc, float32_t *pDst)
Processing function for the floating-point RFFT/RIFFT.
arm_status arm_rfft_fast_init_f32 (arm_rfft_fast_instance_f32 *S, uint16_t fftLen)
Initialization function for the floating-point real FFT.
void arm_rfft_fast_f32 (arm_rfft_fast_instance_f32 *S, float32_t *p, float32_t *pOut, uint8_t ifftFlag)
Processing function for the floating-point real FFT.
arm_status arm_dct4_init_f32 (arm_dct4_instance_f32 *S, arm_rfft_instance_f32 *S_RFFT, arm_cfft_radix4_instance_f32 *S_CFFT, uint16_t N, uint16_t Nby2, float32_t normalize)
Initialization function for the floating-point DCT4/IDCT4.
void arm_dct4_f32 (const arm_dct4_instance_f32 *S, float32_t *pState, float32_t *pInlineBuffer)
Processing function for the floating-point DCT4/IDCT4.
arm_status arm_dct4_init_q31 (arm_dct4_instance_q31 *S, arm_rfft_instance_q31 *S_RFFT, arm_cfft_radix4_instance_q31 *S_CFFT, uint16_t N, uint16_t Nby2, q31_t normalize)
Initialization function for the Q31 DCT4/IDCT4.
void arm_dct4_q31 (const arm_dct4_instance_q31 *S, q31_t *pState, q31_t *pInlineBuffer)
Processing function for the Q31 DCT4/IDCT4.
arm_status arm_dct4_init_q15 (arm_dct4_instance_q15 *S, arm_rfft_instance_q15 *S_RFFT, arm_cfft_radix4_instance_q15 *S_CFFT, uint16_t N, uint16_t Nby2, q15_t normalize)
Initialization function for the Q15 DCT4/IDCT4.
void arm_dct4_q15 (const arm_dct4_instance_q15 *S, q15_t *pState, q15_t *pInlineBuffer)
Processing function for the Q15 DCT4/IDCT4.
void arm_add_f32 (float32_t *pSrcA, float32_t *pSrcB, float32_t *pDst, uint32_t blockSize)
Floating-point vector addition.
void arm_add_q7 (q7_t *pSrcA, q7_t *pSrcB, q7_t *pDst, uint32_t blockSize)
Q7 vector addition.
void arm_add_q15 (q15_t *pSrcA, q15_t *pSrcB, q15_t *pDst, uint32_t blockSize)
Q15 vector addition.
void arm_add_q31 (q31_t *pSrcA, q31_t *pSrcB, q31_t *pDst, uint32_t blockSize)
Q31 vector addition.
void arm_sub_f32 (float32_t *pSrcA, float32_t *pSrcB, float32_t *pDst, uint32_t blockSize)
Floating-point vector subtraction.
void arm_sub_q7 (q7_t *pSrcA, q7_t *pSrcB, q7_t *pDst, uint32_t blockSize)
Q7 vector subtraction.
void arm_sub_q15 (q15_t *pSrcA, q15_t *pSrcB, q15_t *pDst, uint32_t blockSize)
Q15 vector subtraction.
void arm_sub_q31 (q31_t *pSrcA, q31_t *pSrcB, q31_t *pDst, uint32_t blockSize)
Q31 vector subtraction.
void arm_scale_f32 (float32_t *pSrc, float32_t scale, float32_t *pDst, uint32_t blockSize)
Multiplies a floating-point vector by a scalar.
void arm_scale_q7 (q7_t *pSrc, q7_t scaleFract, int8_t shift, q7_t *pDst, uint32_t blockSize)
Multiplies a Q7 vector by a scalar.
void arm_scale_q15 (q15_t *pSrc, q15_t scaleFract, int8_t shift, q15_t *pDst, uint32_t blockSize)
Multiplies a Q15 vector by a scalar.
void arm_scale_q31 (q31_t *pSrc, q31_t scaleFract, int8_t shift, q31_t *pDst, uint32_t blockSize)
Multiplies a Q31 vector by a scalar.
void arm_abs_q7 (q7_t *pSrc, q7_t *pDst, uint32_t blockSize)
Q7 vector absolute value.
void arm_abs_f32 (float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Floating-point vector absolute value.
void arm_abs_q15 (q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Q15 vector absolute value.
void arm_abs_q31 (q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Q31 vector absolute value.
void arm_dot_prod_f32 (float32_t *pSrcA, float32_t *pSrcB, uint32_t blockSize, float32_t *result)
Dot product of floating-point vectors.
void arm_dot_prod_q7 (q7_t *pSrcA, q7_t *pSrcB, uint32_t blockSize, q31_t *result)
Dot product of Q7 vectors.
void arm_dot_prod_q15 (q15_t *pSrcA, q15_t *pSrcB, uint32_t blockSize, q63_t *result)
Dot product of Q15 vectors.
void arm_dot_prod_q31 (q31_t *pSrcA, q31_t *pSrcB, uint32_t blockSize, q63_t *result)
Dot product of Q31 vectors.
void arm_shift_q7 (q7_t *pSrc, int8_t shiftBits, q7_t *pDst, uint32_t blockSize)
Shifts the elements of a Q7 vector a specified number of bits.
void arm_shift_q15 (q15_t *pSrc, int8_t shiftBits, q15_t *pDst, uint32_t blockSize)
Shifts the elements of a Q15 vector a specified number of bits.
void arm_shift_q31 (q31_t *pSrc, int8_t shiftBits, q31_t *pDst, uint32_t blockSize)
Shifts the elements of a Q31 vector a specified number of bits.
void arm_offset_f32 (float32_t *pSrc, float32_t offset, float32_t *pDst, uint32_t blockSize)
Adds a constant offset to a floating-point vector.
void arm_offset_q7 (q7_t *pSrc, q7_t offset, q7_t *pDst, uint32_t blockSize)
Adds a constant offset to a Q7 vector.
void arm_offset_q15 (q15_t *pSrc, q15_t offset, q15_t *pDst, uint32_t blockSize)
Adds a constant offset to a Q15 vector.
void arm_offset_q31 (q31_t *pSrc, q31_t offset, q31_t *pDst, uint32_t blockSize)
Adds a constant offset to a Q31 vector.
void arm_negate_f32 (float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Negates the elements of a floating-point vector.
void arm_negate_q7 (q7_t *pSrc, q7_t *pDst, uint32_t blockSize)
Negates the elements of a Q7 vector.
void arm_negate_q15 (q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Negates the elements of a Q15 vector.
void arm_negate_q31 (q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Negates the elements of a Q31 vector.
void arm_copy_f32 (float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Copies the elements of a floating-point vector.
void arm_copy_q7 (q7_t *pSrc, q7_t *pDst, uint32_t blockSize)
Copies the elements of a Q7 vector.
void arm_copy_q15 (q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Copies the elements of a Q15 vector.
void arm_copy_q31 (q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Copies the elements of a Q31 vector.
void arm_fill_f32 (float32_t value, float32_t *pDst, uint32_t blockSize)
Fills a constant value into a floating-point vector.
void arm_fill_q7 (q7_t value, q7_t *pDst, uint32_t blockSize)
Fills a constant value into a Q7 vector.
void arm_fill_q15 (q15_t value, q15_t *pDst, uint32_t blockSize)
Fills a constant value into a Q15 vector.
void arm_fill_q31 (q31_t value, q31_t *pDst, uint32_t blockSize)
Fills a constant value into a Q31 vector.
void arm_conv_f32 (float32_t *pSrcA, uint32_t srcALen, float32_t *pSrcB, uint32_t srcBLen, float32_t *pDst)
Convolution of floating-point sequences.
void arm_conv_opt_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, q15_t *pScratch1, q15_t *pScratch2)
Convolution of Q15 sequences.
void arm_conv_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst)
Convolution of Q15 sequences.
void arm_conv_fast_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst)
Convolution of Q15 sequences (fast version) for Cortex-M3 and Cortex-M4.
void arm_conv_fast_opt_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, q15_t *pScratch1, q15_t *pScratch2)
Convolution of Q15 sequences (fast version) for Cortex-M3 and Cortex-M4.
void arm_conv_q31 (q31_t *pSrcA, uint32_t srcALen, q31_t *pSrcB, uint32_t srcBLen, q31_t *pDst)
Convolution of Q31 sequences.
void arm_conv_fast_q31 (q31_t *pSrcA, uint32_t srcALen, q31_t *pSrcB, uint32_t srcBLen, q31_t *pDst)
Convolution of Q31 sequences (fast version) for Cortex-M3 and Cortex-M4.
void arm_conv_opt_q7 (q7_t *pSrcA, uint32_t srcALen, q7_t *pSrcB, uint32_t srcBLen, q7_t *pDst, q15_t *pScratch1, q15_t *pScratch2)
Convolution of Q7 sequences.
void arm_conv_q7 (q7_t *pSrcA, uint32_t srcALen, q7_t *pSrcB, uint32_t srcBLen, q7_t *pDst)
Convolution of Q7 sequences.
arm_status arm_conv_partial_f32 (float32_t *pSrcA, uint32_t srcALen, float32_t *pSrcB, uint32_t srcBLen, float32_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of floating-point sequences.
arm_status arm_conv_partial_opt_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, uint32_t firstIndex, uint32_t numPoints, q15_t *pScratch1, q15_t *pScratch2)
Partial convolution of Q15 sequences.
arm_status arm_conv_partial_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q15 sequences.
arm_status arm_conv_partial_fast_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q15 sequences (fast version) for Cortex-M3 and Cortex-M4.
arm_status arm_conv_partial_fast_opt_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, uint32_t firstIndex, uint32_t numPoints, q15_t *pScratch1, q15_t *pScratch2)
Partial convolution of Q15 sequences (fast version) for Cortex-M3 and Cortex-M4.
arm_status arm_conv_partial_q31 (q31_t *pSrcA, uint32_t srcALen, q31_t *pSrcB, uint32_t srcBLen, q31_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q31 sequences.
arm_status arm_conv_partial_fast_q31 (q31_t *pSrcA, uint32_t srcALen, q31_t *pSrcB, uint32_t srcBLen, q31_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q31 sequences (fast version) for Cortex-M3 and Cortex-M4.
arm_status arm_conv_partial_opt_q7 (q7_t *pSrcA, uint32_t srcALen, q7_t *pSrcB, uint32_t srcBLen, q7_t *pDst, uint32_t firstIndex, uint32_t numPoints, q15_t *pScratch1, q15_t *pScratch2)
Partial convolution of Q7 sequences.
arm_status arm_conv_partial_q7 (q7_t *pSrcA, uint32_t srcALen, q7_t *pSrcB, uint32_t srcBLen, q7_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q7 sequences.
void arm_fir_decimate_f32 (const arm_fir_decimate_instance_f32 *S, float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Processing function for the floating-point FIR decimator.
arm_status arm_fir_decimate_init_f32 (arm_fir_decimate_instance_f32 *S, uint16_t numTaps, uint8_t M, float32_t *pCoeffs, float32_t *pState, uint32_t blockSize)
Initialization function for the floating-point FIR decimator.
void arm_fir_decimate_q15 (const arm_fir_decimate_instance_q15 *S, q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Processing function for the Q15 FIR decimator.
void arm_fir_decimate_fast_q15 (const arm_fir_decimate_instance_q15 *S, q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Processing function for the Q15 FIR decimator (fast variant) for Cortex-M3 and Cortex-M4.
arm_status arm_fir_decimate_init_q15 (arm_fir_decimate_instance_q15 *S, uint16_t numTaps, uint8_t M, q15_t *pCoeffs, q15_t *pState, uint32_t blockSize)
Initialization function for the Q15 FIR decimator.
void arm_fir_decimate_q31 (const arm_fir_decimate_instance_q31 *S, q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Processing function for the Q31 FIR decimator.
void arm_fir_decimate_fast_q31 (arm_fir_decimate_instance_q31 *S, q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Processing function for the Q31 FIR decimator (fast variant) for Cortex-M3 and Cortex-M4.
arm_status arm_fir_decimate_init_q31 (arm_fir_decimate_instance_q31 *S, uint16_t numTaps, uint8_t M, q31_t *pCoeffs, q31_t *pState, uint32_t blockSize)
Initialization function for the Q31 FIR decimator.
void arm_fir_interpolate_q15 (const arm_fir_interpolate_instance_q15 *S, q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Processing function for the Q15 FIR interpolator.
arm_status arm_fir_interpolate_init_q15 (arm_fir_interpolate_instance_q15 *S, uint8_t L, uint16_t numTaps, q15_t *pCoeffs, q15_t *pState, uint32_t blockSize)
Initialization function for the Q15 FIR interpolator.
void arm_fir_interpolate_q31 (const arm_fir_interpolate_instance_q31 *S, q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Processing function for the Q31 FIR interpolator.
arm_status arm_fir_interpolate_init_q31 (arm_fir_interpolate_instance_q31 *S, uint8_t L, uint16_t numTaps, q31_t *pCoeffs, q31_t *pState, uint32_t blockSize)
Initialization function for the Q31 FIR interpolator.
void arm_fir_interpolate_f32 (const arm_fir_interpolate_instance_f32 *S, float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Processing function for the floating-point FIR interpolator.
arm_status arm_fir_interpolate_init_f32 (arm_fir_interpolate_instance_f32 *S, uint8_t L, uint16_t numTaps, float32_t *pCoeffs, float32_t *pState, uint32_t blockSize)
Initialization function for the floating-point FIR interpolator.
void arm_biquad_cas_df1_32x64_q31 (const arm_biquad_cas_df1_32x64_ins_q31 *S, q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
void arm_biquad_cas_df1_32x64_init_q31 (arm_biquad_cas_df1_32x64_ins_q31 *S, uint8_t numStages, q31_t *pCoeffs, q63_t *pState, uint8_t postShift)
void arm_biquad_cascade_df2T_f32 (const arm_biquad_cascade_df2T_instance_f32 *S, float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Processing function for the floating-point transposed direct form II Biquad cascade filter.
void arm_biquad_cascade_stereo_df2T_f32 (const arm_biquad_cascade_stereo_df2T_instance_f32 *S, float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Processing function for the floating-point transposed direct form II Biquad cascade filter. 2 channels.
void arm_biquad_cascade_df2T_f64 (const arm_biquad_cascade_df2T_instance_f64 *S, float64_t *pSrc, float64_t *pDst, uint32_t blockSize)
Processing function for the floating-point transposed direct form II Biquad cascade filter.
void arm_biquad_cascade_df2T_init_f32 (arm_biquad_cascade_df2T_instance_f32 *S, uint8_t numStages, float32_t *pCoeffs, float32_t *pState)
Initialization function for the floating-point transposed direct form II Biquad cascade filter.
void arm_biquad_cascade_stereo_df2T_init_f32 (arm_biquad_cascade_stereo_df2T_instance_f32 *S, uint8_t numStages, float32_t *pCoeffs, float32_t *pState)
Initialization function for the floating-point transposed direct form II Biquad cascade filter.
void arm_biquad_cascade_df2T_init_f64 (arm_biquad_cascade_df2T_instance_f64 *S, uint8_t numStages, float64_t *pCoeffs, float64_t *pState)
Initialization function for the floating-point transposed direct form II Biquad cascade filter.
void arm_fir_lattice_init_q15 (arm_fir_lattice_instance_q15 *S, uint16_t numStages, q15_t *pCoeffs, q15_t *pState)
Initialization function for the Q15 FIR lattice filter.
void arm_fir_lattice_q15 (const arm_fir_lattice_instance_q15 *S, q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Processing function for the Q15 FIR lattice filter.
void arm_fir_lattice_init_q31 (arm_fir_lattice_instance_q31 *S, uint16_t numStages, q31_t *pCoeffs, q31_t *pState)
Initialization function for the Q31 FIR lattice filter.
void arm_fir_lattice_q31 (const arm_fir_lattice_instance_q31 *S, q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Processing function for the Q31 FIR lattice filter.
void arm_fir_lattice_init_f32 (arm_fir_lattice_instance_f32 *S, uint16_t numStages, float32_t *pCoeffs, float32_t *pState)
Initialization function for the floating-point FIR lattice filter.
void arm_fir_lattice_f32 (const arm_fir_lattice_instance_f32 *S, float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Processing function for the floating-point FIR lattice filter.
void arm_iir_lattice_f32 (const arm_iir_lattice_instance_f32 *S, float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Processing function for the floating-point IIR lattice filter.
void arm_iir_lattice_init_f32 (arm_iir_lattice_instance_f32 *S, uint16_t numStages, float32_t *pkCoeffs, float32_t *pvCoeffs, float32_t *pState, uint32_t blockSize)
Initialization function for the floating-point IIR lattice filter.
void arm_iir_lattice_q31 (const arm_iir_lattice_instance_q31 *S, q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Processing function for the Q31 IIR lattice filter.
void arm_iir_lattice_init_q31 (arm_iir_lattice_instance_q31 *S, uint16_t numStages, q31_t *pkCoeffs, q31_t *pvCoeffs, q31_t *pState, uint32_t blockSize)
Initialization function for the Q31 IIR lattice filter.
void arm_iir_lattice_q15 (const arm_iir_lattice_instance_q15 *S, q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Processing function for the Q15 IIR lattice filter.
void arm_iir_lattice_init_q15 (arm_iir_lattice_instance_q15 *S, uint16_t numStages, q15_t *pkCoeffs, q15_t *pvCoeffs, q15_t *pState, uint32_t blockSize)
Initialization function for the Q15 IIR lattice filter.
void arm_lms_f32 (const arm_lms_instance_f32 *S, float32_t *pSrc, float32_t *pRef, float32_t *pOut, float32_t *pErr, uint32_t blockSize)
Processing function for floating-point LMS filter.
void arm_lms_init_f32 (arm_lms_instance_f32 *S, uint16_t numTaps, float32_t *pCoeffs, float32_t *pState, float32_t mu, uint32_t blockSize)
Initialization function for floating-point LMS filter.
void arm_lms_init_q15 (arm_lms_instance_q15 *S, uint16_t numTaps, q15_t *pCoeffs, q15_t *pState, q15_t mu, uint32_t blockSize, uint32_t postShift)
Initialization function for the Q15 LMS filter.
void arm_lms_q15 (const arm_lms_instance_q15 *S, q15_t *pSrc, q15_t *pRef, q15_t *pOut, q15_t *pErr, uint32_t blockSize)
Processing function for Q15 LMS filter.
void arm_lms_q31 (const arm_lms_instance_q31 *S, q31_t *pSrc, q31_t *pRef, q31_t *pOut, q31_t *pErr, uint32_t blockSize)
Processing function for Q31 LMS filter.
void arm_lms_init_q31 (arm_lms_instance_q31 *S, uint16_t numTaps, q31_t *pCoeffs, q31_t *pState, q31_t mu, uint32_t blockSize, uint32_t postShift)
Initialization function for Q31 LMS filter.
void arm_lms_norm_f32 (arm_lms_norm_instance_f32 *S, float32_t *pSrc, float32_t *pRef, float32_t *pOut, float32_t *pErr, uint32_t blockSize)
Processing function for floating-point normalized LMS filter.
void arm_lms_norm_init_f32 (arm_lms_norm_instance_f32 *S, uint16_t numTaps, float32_t *pCoeffs, float32_t *pState, float32_t mu, uint32_t blockSize)
Initialization function for floating-point normalized LMS filter.
void arm_lms_norm_q31 (arm_lms_norm_instance_q31 *S, q31_t *pSrc, q31_t *pRef, q31_t *pOut, q31_t *pErr, uint32_t blockSize)
Processing function for Q31 normalized LMS filter.
void arm_lms_norm_init_q31 (arm_lms_norm_instance_q31 *S, uint16_t numTaps, q31_t *pCoeffs, q31_t *pState, q31_t mu, uint32_t blockSize, uint8_t postShift)
Initialization function for Q31 normalized LMS filter.
void arm_lms_norm_q15 (arm_lms_norm_instance_q15 *S, q15_t *pSrc, q15_t *pRef, q15_t *pOut, q15_t *pErr, uint32_t blockSize)
Processing function for Q15 normalized LMS filter.
void arm_lms_norm_init_q15 (arm_lms_norm_instance_q15 *S, uint16_t numTaps, q15_t *pCoeffs, q15_t *pState, q15_t mu, uint32_t blockSize, uint8_t postShift)
Initialization function for Q15 normalized LMS filter.
void arm_correlate_f32 (float32_t *pSrcA, uint32_t srcALen, float32_t *pSrcB, uint32_t srcBLen, float32_t *pDst)
Correlation of floating-point sequences.
void arm_correlate_opt_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, q15_t *pScratch)
Correlation of Q15 sequences.
void arm_correlate_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst)
Correlation of Q15 sequences.
void arm_correlate_fast_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst)
Correlation of Q15 sequences (fast version) for Cortex-M3 and Cortex-M4.
void arm_correlate_fast_opt_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, q15_t *pScratch)
Correlation of Q15 sequences (fast version) for Cortex-M3 and Cortex-M4.
void arm_correlate_q31 (q31_t *pSrcA, uint32_t srcALen, q31_t *pSrcB, uint32_t srcBLen, q31_t *pDst)
Correlation of Q31 sequences.
void arm_correlate_fast_q31 (q31_t *pSrcA, uint32_t srcALen, q31_t *pSrcB, uint32_t srcBLen, q31_t *pDst)
Correlation of Q31 sequences (fast version) for Cortex-M3 and Cortex-M4.
void arm_correlate_opt_q7 (q7_t *pSrcA, uint32_t srcALen, q7_t *pSrcB, uint32_t srcBLen, q7_t *pDst, q15_t *pScratch1, q15_t *pScratch2)
Correlation of Q7 sequences.
void arm_correlate_q7 (q7_t *pSrcA, uint32_t srcALen, q7_t *pSrcB, uint32_t srcBLen, q7_t *pDst)
Correlation of Q7 sequences.
void arm_fir_sparse_f32 (arm_fir_sparse_instance_f32 *S, float32_t *pSrc, float32_t *pDst, float32_t *pScratchIn, uint32_t blockSize)
Processing function for the floating-point sparse FIR filter.
void arm_fir_sparse_init_f32 (arm_fir_sparse_instance_f32 *S, uint16_t numTaps, float32_t *pCoeffs, float32_t *pState, int32_t *pTapDelay, uint16_t maxDelay, uint32_t blockSize)
Initialization function for the floating-point sparse FIR filter.
void arm_fir_sparse_q31 (arm_fir_sparse_instance_q31 *S, q31_t *pSrc, q31_t *pDst, q31_t *pScratchIn, uint32_t blockSize)
Processing function for the Q31 sparse FIR filter.
void arm_fir_sparse_init_q31 (arm_fir_sparse_instance_q31 *S, uint16_t numTaps, q31_t *pCoeffs, q31_t *pState, int32_t *pTapDelay, uint16_t maxDelay, uint32_t blockSize)
Initialization function for the Q31 sparse FIR filter.
void arm_fir_sparse_q15 (arm_fir_sparse_instance_q15 *S, q15_t *pSrc, q15_t *pDst, q15_t *pScratchIn, q31_t *pScratchOut, uint32_t blockSize)
Processing function for the Q15 sparse FIR filter.
void arm_fir_sparse_init_q15 (arm_fir_sparse_instance_q15 *S, uint16_t numTaps, q15_t *pCoeffs, q15_t *pState, int32_t *pTapDelay, uint16_t maxDelay, uint32_t blockSize)
Initialization function for the Q15 sparse FIR filter.
void arm_fir_sparse_q7 (arm_fir_sparse_instance_q7 *S, q7_t *pSrc, q7_t *pDst, q7_t *pScratchIn, q31_t *pScratchOut, uint32_t blockSize)
Processing function for the Q7 sparse FIR filter.
void arm_fir_sparse_init_q7 (arm_fir_sparse_instance_q7 *S, uint16_t numTaps, q7_t *pCoeffs, q7_t *pState, int32_t *pTapDelay, uint16_t maxDelay, uint32_t blockSize)
Initialization function for the Q7 sparse FIR filter.
void arm_sin_cos_f32 (float32_t theta, float32_t *pSinVal, float32_t *pCosVal)
Floating-point sin_cos function.
void arm_sin_cos_q31 (q31_t theta, q31_t *pSinVal, q31_t *pCosVal)
Q31 sin_cos function.
void arm_cmplx_conj_f32 (float32_t *pSrc, float32_t *pDst, uint32_t numSamples)
Floating-point complex conjugate.
void arm_cmplx_conj_q31 (q31_t *pSrc, q31_t *pDst, uint32_t numSamples)
Q31 complex conjugate.
void arm_cmplx_conj_q15 (q15_t *pSrc, q15_t *pDst, uint32_t numSamples)
Q15 complex conjugate.
void arm_cmplx_mag_squared_f32 (float32_t *pSrc, float32_t *pDst, uint32_t numSamples)
Floating-point complex magnitude squared.
void arm_cmplx_mag_squared_q31 (q31_t *pSrc, q31_t *pDst, uint32_t numSamples)
Q31 complex magnitude squared.
void arm_cmplx_mag_squared_q15 (q15_t *pSrc, q15_t *pDst, uint32_t numSamples)
Q15 complex magnitude squared.
CMSIS_INLINE __STATIC_INLINE
float32_t arm_pid_f32 (arm_pid_instance_f32 *S, float32_t in)
Process function for the floating-point PID Control.
CMSIS_INLINE __STATIC_INLINE q31_t arm_pid_q31 (arm_pid_instance_q31 *S, q31_t in)
Process function for the Q31 PID Control.
CMSIS_INLINE __STATIC_INLINE q15_t arm_pid_q15 (arm_pid_instance_q15 *S, q15_t in)
Process function for the Q15 PID Control.
arm_status arm_mat_inverse_f32 (const arm_matrix_instance_f32 *src, arm_matrix_instance_f32 *dst)
Floating-point matrix inverse.
arm_status arm_mat_inverse_f64 (const arm_matrix_instance_f64 *src, arm_matrix_instance_f64 *dst)
Floating-point matrix inverse.
CMSIS_INLINE __STATIC_INLINE void arm_clarke_f32 (float32_t Ia, float32_t Ib, float32_t *pIalpha, float32_t *pIbeta)
Floating-point Clarke transform.
CMSIS_INLINE __STATIC_INLINE void arm_clarke_q31 (q31_t Ia, q31_t Ib, q31_t *pIalpha, q31_t *pIbeta)
Clarke transform for Q31 version.
void arm_q7_to_q31 (q7_t *pSrc, q31_t *pDst, uint32_t blockSize)
Converts the elements of the Q7 vector to Q31 vector.
CMSIS_INLINE __STATIC_INLINE void arm_inv_clarke_f32 (float32_t Ialpha, float32_t Ibeta, float32_t *pIa, float32_t *pIb)
Floating-point Inverse Clarke transform.
CMSIS_INLINE __STATIC_INLINE void arm_inv_clarke_q31 (q31_t Ialpha, q31_t Ibeta, q31_t *pIa, q31_t *pIb)
Inverse Clarke transform for Q31 version.
void arm_q7_to_q15 (q7_t *pSrc, q15_t *pDst, uint32_t blockSize)
Converts the elements of the Q7 vector to Q15 vector.
CMSIS_INLINE __STATIC_INLINE void arm_park_f32 (float32_t Ialpha, float32_t Ibeta, float32_t *pId, float32_t *pIq, float32_t sinVal, float32_t cosVal)
Floating-point Park transform.
CMSIS_INLINE __STATIC_INLINE void arm_park_q31 (q31_t Ialpha, q31_t Ibeta, q31_t *pId, q31_t *pIq, q31_t sinVal, q31_t cosVal)
Park transform for Q31 version.
void arm_q7_to_float (q7_t *pSrc, float32_t *pDst, uint32_t blockSize)
Converts the elements of the Q7 vector to floating-point vector.
CMSIS_INLINE __STATIC_INLINE void arm_inv_park_f32 (float32_t Id, float32_t Iq, float32_t *pIalpha, float32_t *pIbeta, float32_t sinVal, float32_t cosVal)
Floating-point Inverse Park transform.
CMSIS_INLINE __STATIC_INLINE void arm_inv_park_q31 (q31_t Id, q31_t Iq, q31_t *pIalpha, q31_t *pIbeta, q31_t sinVal, q31_t cosVal)
Inverse Park transform for Q31 version.
void arm_q31_to_float (q31_t *pSrc, float32_t *pDst, uint32_t blockSize)
Converts the elements of the Q31 vector to floating-point vector.
CMSIS_INLINE __STATIC_INLINE
float32_t arm_linear_interp_f32 (arm_linear_interp_instance_f32 *S, float32_t x)
Process function for the floating-point Linear Interpolation Function.
CMSIS_INLINE __STATIC_INLINE q31_t arm_linear_interp_q31 (q31_t *pYData, q31_t x, uint32_t nValues)
Process function for the Q31 Linear Interpolation Function.
CMSIS_INLINE __STATIC_INLINE q15_t arm_linear_interp_q15 (q15_t *pYData, q31_t x, uint32_t nValues)
Process function for the Q15 Linear Interpolation Function.
CMSIS_INLINE __STATIC_INLINE q7_t arm_linear_interp_q7 (q7_t *pYData, q31_t x, uint32_t nValues)
Process function for the Q7 Linear Interpolation Function.
float32_t arm_sin_f32 (float32_t x)
Fast approximation to the trigonometric sine function for floating-point data.
q31_t arm_sin_q31 (q31_t x)
Fast approximation to the trigonometric sine function for Q31 data.
q15_t arm_sin_q15 (q15_t x)
Fast approximation to the trigonometric sine function for Q15 data.
float32_t arm_cos_f32 (float32_t x)
Fast approximation to the trigonometric cosine function for floating-point data.
q31_t arm_cos_q31 (q31_t x)
Fast approximation to the trigonometric cosine function for Q31 data.
q15_t arm_cos_q15 (q15_t x)
Fast approximation to the trigonometric cosine function for Q15 data.
CMSIS_INLINE __STATIC_INLINE
arm_status arm_sqrt_f32 (float32_t in, float32_t *pOut)
Floating-point square root function.
arm_status arm_sqrt_q31 (q31_t in, q31_t *pOut)
Q31 square root function.
arm_status arm_sqrt_q15 (q15_t in, q15_t *pOut)
Q15 square root function.
CMSIS_INLINE __STATIC_INLINE void arm_circularWrite_f32 (int32_t *circBuffer, int32_t L, uint16_t *writeOffset, int32_t bufferInc, const int32_t *src, int32_t srcInc, uint32_t blockSize)
floating-point Circular write function.
CMSIS_INLINE __STATIC_INLINE void arm_circularRead_f32 (int32_t *circBuffer, int32_t L, int32_t *readOffset, int32_t bufferInc, int32_t *dst, int32_t *dst_base, int32_t dst_length, int32_t dstInc, uint32_t blockSize)
floating-point Circular Read function.
CMSIS_INLINE __STATIC_INLINE void arm_circularWrite_q15 (q15_t *circBuffer, int32_t L, uint16_t *writeOffset, int32_t bufferInc, const q15_t *src, int32_t srcInc, uint32_t blockSize)
Q15 Circular write function.
CMSIS_INLINE __STATIC_INLINE void arm_circularRead_q15 (q15_t *circBuffer, int32_t L, int32_t *readOffset, int32_t bufferInc, q15_t *dst, q15_t *dst_base, int32_t dst_length, int32_t dstInc, uint32_t blockSize)
Q15 Circular Read function.
CMSIS_INLINE __STATIC_INLINE void arm_circularWrite_q7 (q7_t *circBuffer, int32_t L, uint16_t *writeOffset, int32_t bufferInc, const q7_t *src, int32_t srcInc, uint32_t blockSize)
Q7 Circular write function.
CMSIS_INLINE __STATIC_INLINE void arm_circularRead_q7 (q7_t *circBuffer, int32_t L, int32_t *readOffset, int32_t bufferInc, q7_t *dst, q7_t *dst_base, int32_t dst_length, int32_t dstInc, uint32_t blockSize)
Q7 Circular Read function.
void arm_power_q31 (q31_t *pSrc, uint32_t blockSize, q63_t *pResult)
Sum of the squares of the elements of a Q31 vector.
void arm_power_f32 (float32_t *pSrc, uint32_t blockSize, float32_t *pResult)
Sum of the squares of the elements of a floating-point vector.
void arm_power_q15 (q15_t *pSrc, uint32_t blockSize, q63_t *pResult)
Sum of the squares of the elements of a Q15 vector.
void arm_power_q7 (q7_t *pSrc, uint32_t blockSize, q31_t *pResult)
Sum of the squares of the elements of a Q7 vector.
void arm_mean_q7 (q7_t *pSrc, uint32_t blockSize, q7_t *pResult)
Mean value of a Q7 vector.
void arm_mean_q15 (q15_t *pSrc, uint32_t blockSize, q15_t *pResult)
Mean value of a Q15 vector.
void arm_mean_q31 (q31_t *pSrc, uint32_t blockSize, q31_t *pResult)
Mean value of a Q31 vector.
void arm_mean_f32 (float32_t *pSrc, uint32_t blockSize, float32_t *pResult)
Mean value of a floating-point vector.
void arm_var_f32 (float32_t *pSrc, uint32_t blockSize, float32_t *pResult)
Variance of the elements of a floating-point vector.
void arm_var_q31 (q31_t *pSrc, uint32_t blockSize, q31_t *pResult)
Variance of the elements of a Q31 vector.
void arm_var_q15 (q15_t *pSrc, uint32_t blockSize, q15_t *pResult)
Variance of the elements of a Q15 vector.
void arm_rms_f32 (float32_t *pSrc, uint32_t blockSize, float32_t *pResult)
Root Mean Square of the elements of a floating-point vector.
void arm_rms_q31 (q31_t *pSrc, uint32_t blockSize, q31_t *pResult)
Root Mean Square of the elements of a Q31 vector.
void arm_rms_q15 (q15_t *pSrc, uint32_t blockSize, q15_t *pResult)
Root Mean Square of the elements of a Q15 vector.
void arm_std_f32 (float32_t *pSrc, uint32_t blockSize, float32_t *pResult)
Standard deviation of the elements of a floating-point vector.
void arm_std_q31 (q31_t *pSrc, uint32_t blockSize, q31_t *pResult)
Standard deviation of the elements of a Q31 vector.
void arm_std_q15 (q15_t *pSrc, uint32_t blockSize, q15_t *pResult)
Standard deviation of the elements of a Q15 vector.
void arm_cmplx_mag_f32 (float32_t *pSrc, float32_t *pDst, uint32_t numSamples)
Floating-point complex magnitude.
void arm_cmplx_mag_q31 (q31_t *pSrc, q31_t *pDst, uint32_t numSamples)
Q31 complex magnitude.
void arm_cmplx_mag_q15 (q15_t *pSrc, q15_t *pDst, uint32_t numSamples)
Q15 complex magnitude.
void arm_cmplx_dot_prod_q15 (q15_t *pSrcA, q15_t *pSrcB, uint32_t numSamples, q31_t *realResult, q31_t *imagResult)
Q15 complex dot product.
void arm_cmplx_dot_prod_q31 (q31_t *pSrcA, q31_t *pSrcB, uint32_t numSamples, q63_t *realResult, q63_t *imagResult)
Q31 complex dot product.
void arm_cmplx_dot_prod_f32 (float32_t *pSrcA, float32_t *pSrcB, uint32_t numSamples, float32_t *realResult, float32_t *imagResult)
Floating-point complex dot product.
void arm_cmplx_mult_real_q15 (q15_t *pSrcCmplx, q15_t *pSrcReal, q15_t *pCmplxDst, uint32_t numSamples)
Q15 complex-by-real multiplication.
void arm_cmplx_mult_real_q31 (q31_t *pSrcCmplx, q31_t *pSrcReal, q31_t *pCmplxDst, uint32_t numSamples)
Q31 complex-by-real multiplication.
void arm_cmplx_mult_real_f32 (float32_t *pSrcCmplx, float32_t *pSrcReal, float32_t *pCmplxDst, uint32_t numSamples)
Floating-point complex-by-real multiplication.
void arm_min_q7 (q7_t *pSrc, uint32_t blockSize, q7_t *result, uint32_t *index)
Minimum value of a Q7 vector.
void arm_min_q15 (q15_t *pSrc, uint32_t blockSize, q15_t *pResult, uint32_t *pIndex)
Minimum value of a Q15 vector.
void arm_min_q31 (q31_t *pSrc, uint32_t blockSize, q31_t *pResult, uint32_t *pIndex)
Minimum value of a Q31 vector.
void arm_min_f32 (float32_t *pSrc, uint32_t blockSize, float32_t *pResult, uint32_t *pIndex)
Minimum value of a floating-point vector.
void arm_max_q7 (q7_t *pSrc, uint32_t blockSize, q7_t *pResult, uint32_t *pIndex)
Maximum value of a Q7 vector.
void arm_max_q15 (q15_t *pSrc, uint32_t blockSize, q15_t *pResult, uint32_t *pIndex)
Maximum value of a Q15 vector.
void arm_max_q31 (q31_t *pSrc, uint32_t blockSize, q31_t *pResult, uint32_t *pIndex)
Maximum value of a Q31 vector.
void arm_max_f32 (float32_t *pSrc, uint32_t blockSize, float32_t *pResult, uint32_t *pIndex)
Maximum value of a floating-point vector.
void arm_cmplx_mult_cmplx_q15 (q15_t *pSrcA, q15_t *pSrcB, q15_t *pDst, uint32_t numSamples)
Q15 complex-by-complex multiplication.
void arm_cmplx_mult_cmplx_q31 (q31_t *pSrcA, q31_t *pSrcB, q31_t *pDst, uint32_t numSamples)
Q31 complex-by-complex multiplication.
void arm_cmplx_mult_cmplx_f32 (float32_t *pSrcA, float32_t *pSrcB, float32_t *pDst, uint32_t numSamples)
Floating-point complex-by-complex multiplication.
void arm_float_to_q31 (float32_t *pSrc, q31_t *pDst, uint32_t blockSize)
Converts the elements of the floating-point vector to Q31 vector.
void arm_float_to_q15 (float32_t *pSrc, q15_t *pDst, uint32_t blockSize)
Converts the elements of the floating-point vector to Q15 vector.
void arm_float_to_q7 (float32_t *pSrc, q7_t *pDst, uint32_t blockSize)
Converts the elements of the floating-point vector to Q7 vector.
void arm_q31_to_q15 (q31_t *pSrc, q15_t *pDst, uint32_t blockSize)
Converts the elements of the Q31 vector to Q15 vector.
void arm_q31_to_q7 (q31_t *pSrc, q7_t *pDst, uint32_t blockSize)
Converts the elements of the Q31 vector to Q7 vector.
void arm_q15_to_float (q15_t *pSrc, float32_t *pDst, uint32_t blockSize)
Converts the elements of the Q15 vector to floating-point vector.
void arm_q15_to_q31 (q15_t *pSrc, q31_t *pDst, uint32_t blockSize)
Converts the elements of the Q15 vector to Q31 vector.
void arm_q15_to_q7 (q15_t *pSrc, q7_t *pDst, uint32_t blockSize)
Converts the elements of the Q15 vector to Q7 vector.
CMSIS_INLINE __STATIC_INLINE
float32_t arm_bilinear_interp_f32 (const arm_bilinear_interp_instance_f32 *S, float32_t X, float32_t Y)
Floating-point bilinear interpolation.
CMSIS_INLINE __STATIC_INLINE q31_t arm_bilinear_interp_q31 (arm_bilinear_interp_instance_q31 *S, q31_t X, q31_t Y)
Q31 bilinear interpolation.
CMSIS_INLINE __STATIC_INLINE q15_t arm_bilinear_interp_q15 (arm_bilinear_interp_instance_q15 *S, q31_t X, q31_t Y)
Q15 bilinear interpolation.
CMSIS_INLINE __STATIC_INLINE q7_t arm_bilinear_interp_q7 (arm_bilinear_interp_instance_q7 *S, q31_t X, q31_t Y)
Q7 bilinear interpolation.
Macro Definition Documentation
#define __CMSIS_GENERIC
#define __PACKq7 (v0, v1, v2, v3)
Referenced by arm_conv_opt_q7(), arm_conv_partial_opt_q7(), arm_fill_q7(), arm_fir_sparse_q7(), arm_mult_q7(), arm_offset_q7(), arm_q31_to_q7(), arm_scale_q7(), and arm_shift_q7().
#define __PKHBT (ARG1, ARG2, ARG3)
Referenced by arm_abs_q15(), arm_biquad_cascade_df1_fast_q15(), arm_biquad_cascade_df1_q15(), arm_cmplx_mult_real_q15(), arm_conv_fast_opt_q15(), arm_conv_fast_q15(), arm_conv_opt_q15(), arm_conv_opt_q7(), arm_conv_partial_fast_opt_q15(), arm_conv_partial_fast_q15(), arm_conv_partial_opt_q15(), arm_conv_partial_opt_q7(), arm_conv_partial_q15(), arm_conv_q15(), arm_correlate_fast_opt_q15(), arm_correlate_fast_q15(), arm_correlate_opt_q15(), arm_correlate_opt_q7(), arm_fill_q15(), arm_fir_fast_q15(), arm_fir_lattice_q15(), arm_fir_sparse_q15(), arm_iir_lattice_q15(), arm_mat_scale_q15(), arm_mult_q15(), arm_offset_q15(), arm_pid_init_q15(), arm_q15_to_q7(), arm_q7_to_q15(), arm_scale_q15(), arm_shift_q15(), and arm_split_rifft_q15().
#define __PKHTB (ARG1, ARG2, ARG3)
Referenced by arm_q15_to_q7(), arm_q31_to_q15(), and arm_q7_to_q15().
#define __SIMD32 (addr)
Referenced by arm_add_q15(), arm_add_q7(), arm_biquad_cascade_df1_fast_q15(), arm_biquad_cascade_df1_q15(), arm_cmplx_conj_q15(), arm_cmplx_mag_q15(), arm_cmplx_mag_squared_q15(), arm_cmplx_mult_real_q15(), arm_conv_fast_opt_q15(), arm_conv_fast_q15(), arm_conv_opt_q15(), arm_conv_opt_q7(), arm_conv_partial_fast_opt_q15(), arm_conv_partial_fast_q15(), arm_conv_partial_opt_q15(), arm_conv_partial_opt_q7(), arm_conv_partial_q15(), arm_conv_q15(), arm_copy_q15(), arm_copy_q7(), arm_correlate_fast_opt_q15(), arm_correlate_fast_q15(), arm_correlate_opt_q15(), arm_correlate_opt_q7(), arm_correlate_q15(), arm_dot_prod_q15(), arm_dot_prod_q7(), arm_fill_q15(), arm_fill_q7(), arm_fir_decimate_fast_q15(), arm_fir_fast_q15(), arm_fir_lattice_q15(), arm_fir_sparse_q15(), arm_fir_sparse_q7(), arm_iir_lattice_q15(), arm_lms_norm_q15(), arm_lms_q15(), arm_mat_add_q15(), arm_mat_cmplx_mult_q15(), arm_mat_mult_fast_q15(), arm_mat_mult_q15(), arm_mat_sub_q15(), arm_mat_trans_q15(), arm_mean_q15(), arm_mean_q7(), arm_mult_q15(), arm_mult_q7(), arm_negate_q7(), arm_offset_q15(), arm_offset_q7(), arm_power_q15(), arm_power_q7(), arm_q15_to_q31(), arm_q15_to_q7(), arm_q31_to_q15(), arm_q31_to_q7(), arm_q7_to_q15(), arm_q7_to_q31(), arm_radix4_butterfly_inverse_q15(), arm_radix4_butterfly_q15(), arm_rms_q15(), arm_scale_q15(), arm_scale_q7(), arm_shift_q15(), arm_shift_q7(), arm_split_rfft_q15(), arm_split_rifft_q15(), arm_std_q15(), arm_sub_q15(), arm_sub_q7(), and arm_var_q15().
#define __SIMD32_CONST (addr)
Referenced by arm_abs_q15(), and arm_pid_q15().
#define __SIMD64 (addr)
Referenced by arm_radix4_butterfly_inverse_q31(), and arm_radix4_butterfly_q31().
#define _SIMD32_OFFSET (addr)
Referenced by arm_cfft_radix4by2_inverse_q15(), arm_cfft_radix4by2_q15(), arm_conv_fast_opt_q15(), arm_conv_fast_q15(), arm_conv_opt_q15(), arm_conv_opt_q7(), arm_conv_partial_fast_opt_q15(), arm_conv_partial_fast_q15(), arm_conv_partial_opt_q15(), arm_conv_partial_opt_q7(), arm_conv_partial_q15(), arm_conv_q15(), arm_correlate_fast_opt_q15(), arm_correlate_fast_q15(), arm_correlate_opt_q15(), arm_correlate_opt_q7(), arm_correlate_q15(), arm_fir_fast_q15(), arm_mat_scale_q15(), arm_negate_q15(), arm_radix2_butterfly_inverse_q15(), arm_radix2_butterfly_q15(), arm_radix4_butterfly_inverse_q15(), and arm_radix4_butterfly_q15().
#define ALIGN4
#define CONTROLLER_Q31_SHIFT
Referenced by arm_sin_cos_q31().
#define DELTA_Q15
Referenced by arm_lms_norm_q15().
#define DELTA_Q31
Referenced by arm_lms_norm_q31().
#define FAST_MATH_Q15_SHIFT
Referenced by arm_cos_q15(), and arm_sin_q15().
#define FAST_MATH_Q31_SHIFT
Referenced by arm_cos_q31(), and arm_sin_q31().
#define FAST_MATH_TABLE_SIZE
Referenced by arm_cos_f32(), arm_sin_cos_f32(), and arm_sin_f32().
#define INDEX_MASK
Referenced by arm_recip_q15(), and arm_recip_q31().
#define INPUT_SPACING
#define mult_32x32_keep32 (a, x, y)
#define mult_32x32_keep32_R (a, x, y)
Referenced by arm_biquad_cascade_df1_fast_q31(), arm_cfft_radix4by2_inverse_q31(), arm_cfft_radix4by2_q31(), arm_radix2_butterfly_inverse_q31(), arm_radix2_butterfly_q31(), arm_split_rfft_q31(), and arm_split_rifft_q31().
#define multAcc_32x32_keep32 (a, x, y)
#define multAcc_32x32_keep32_R (a, x, y)
end of BilinearInterpolate group
Referenced by arm_biquad_cascade_df1_fast_q31(), arm_cfft_radix4by2_inverse_q31(), arm_cfft_radix4by2_q31(), arm_fir_fast_q31(), arm_radix2_butterfly_inverse_q31(), arm_radix2_butterfly_q31(), arm_split_rfft_q31(), and arm_split_rifft_q31().
#define multSub_32x32_keep32 (a, x, y)
#define multSub_32x32_keep32_R (a, x, y)
Referenced by arm_cfft_radix4by2_inverse_q31(), arm_cfft_radix4by2_q31(), arm_radix2_butterfly_inverse_q31(), arm_radix2_butterfly_q31(), arm_split_rfft_q31(), and arm_split_rifft_q31().
#define PI
#define TABLE_SPACING_Q15
#define TABLE_SPACING_Q31
Typedef Documentation
typedef float float32_t
typedef double float64_t
typedef int16_t q15_t
typedef int32_t q31_t
typedef int64_t q63_t
typedef int8_t q7_t
Enumeration Type Documentation
enum arm_status
Enumerator
ARM_MATH_SUCCESS
No error
ARM_MATH_ARGUMENT_ERROR
One or more arguments are incorrect
ARM_MATH_LENGTH_ERROR
Length of data buffer is incorrect
ARM_MATH_SIZE_MISMATCH
Size of matrices is not compatible with the operation.
ARM_MATH_NANINF
Not-a-number (NaN) or infinity is generated
ARM_MATH_SINGULAR
ARM_MATH_TEST_FAILURE
Test Failed
Function Documentation
CMSIS_INLINE __STATIC_INLINE int32_t __QADD (int32_t x, int32_t y)
References clip_q63_to_q31().
Referenced by arm_add_q31(), arm_clarke_q31(), arm_iir_lattice_q31(), arm_inv_park_q31(), arm_mat_add_q31(), arm_offset_q31(), arm_park_q31(), and arm_pid_init_q31().
CMSIS_INLINE __STATIC_INLINE uint32_t __QADD16 (uint32_t x, uint32_t y)
Referenced by arm_add_q15(), arm_mat_add_q15(), arm_offset_q15(), arm_pid_init_q15(), arm_radix2_butterfly_inverse_q15(), arm_radix2_butterfly_q15(), arm_radix4_butterfly_inverse_q15(), and arm_radix4_butterfly_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __QADD8 (uint32_t x, uint32_t y)
Referenced by arm_add_q7(), and arm_offset_q7().
CMSIS_INLINE __STATIC_INLINE uint32_t __QASX (uint32_t x, uint32_t y)
Referenced by arm_cmplx_conj_q15(), arm_radix4_butterfly_inverse_q15(), and arm_radix4_butterfly_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __QSAX (uint32_t x, uint32_t y)
Referenced by arm_cmplx_conj_q15(), arm_radix4_butterfly_inverse_q15(), and arm_radix4_butterfly_q15().
CMSIS_INLINE __STATIC_INLINE int32_t __QSUB (int32_t x, int32_t y)
References clip_q63_to_q31().
Referenced by arm_abs_q31(), arm_cfft_radix4by2_inverse_q15(), arm_cmplx_conj_q31(), arm_iir_lattice_q31(), arm_inv_clarke_q31(), arm_inv_park_q31(), arm_mat_sub_q31(), arm_negate_q31(), arm_park_q31(), arm_radix2_butterfly_inverse_q15(), and arm_sub_q31().
CMSIS_INLINE __STATIC_INLINE uint32_t __QSUB16 (uint32_t x, uint32_t y)
Referenced by arm_abs_q15(), arm_cfft_radix4by2_inverse_q15(), arm_cfft_radix4by2_q15(), arm_mat_sub_q15(), arm_negate_q15(), arm_radix2_butterfly_inverse_q15(), arm_radix2_butterfly_q15(), arm_radix4_butterfly_inverse_q15(), arm_radix4_butterfly_q15(), and arm_sub_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __QSUB8 (uint32_t x, uint32_t y)
Referenced by arm_abs_q7(), arm_negate_q7(), and arm_sub_q7().
CMSIS_INLINE __STATIC_INLINE uint32_t __SHADD16 (uint32_t x, uint32_t y)
Referenced by arm_cfft_radix4by2_inverse_q15(), arm_cfft_radix4by2_q15(), arm_radix2_butterfly_inverse_q15(), arm_radix2_butterfly_q15(), arm_radix4_butterfly_inverse_q15(), and arm_radix4_butterfly_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __SHASX (uint32_t x, uint32_t y)
Referenced by arm_radix4_butterfly_inverse_q15(), and arm_radix4_butterfly_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __SHSAX (uint32_t x, uint32_t y)
Referenced by arm_radix4_butterfly_inverse_q15(), and arm_radix4_butterfly_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __SHSUB16 (uint32_t x, uint32_t y)
Referenced by arm_radix4_butterfly_inverse_q15(), and arm_radix4_butterfly_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __SMLAD (uint32_t x, uint32_t y, uint32_t sum)
Referenced by arm_biquad_cascade_df1_fast_q15(), arm_conv_fast_opt_q15(), arm_conv_fast_q15(), arm_conv_opt_q7(), arm_conv_partial_fast_opt_q15(), arm_conv_partial_fast_q15(), arm_conv_partial_opt_q7(), arm_conv_partial_q7(), arm_conv_q7(), arm_correlate_fast_opt_q15(), arm_correlate_fast_q15(), arm_correlate_opt_q7(), arm_correlate_q7(), arm_dot_prod_q7(), arm_fir_decimate_fast_q15(), arm_fir_fast_q15(), arm_mat_mult_fast_q15(), arm_power_q7(), arm_split_rfft_q15(), and arm_split_rifft_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __SMLADX (uint32_t x, uint32_t y, uint32_t sum)
Referenced by arm_conv_fast_opt_q15(), arm_conv_fast_q15(), arm_conv_opt_q7(), arm_conv_partial_fast_opt_q15(), arm_conv_partial_fast_q15(), arm_conv_partial_opt_q7(), arm_correlate_fast_opt_q15(), arm_correlate_fast_q15(), arm_correlate_opt_q7(), arm_fir_fast_q15(), and arm_split_rfft_q15().
CMSIS_INLINE __STATIC_INLINE uint64_t __SMLALD (uint32_t x, uint32_t y, uint64_t sum)
Referenced by arm_biquad_cascade_df1_q15(), arm_conv_opt_q15(), arm_conv_partial_opt_q15(), arm_conv_partial_q15(), arm_conv_q15(), arm_correlate_opt_q15(), arm_correlate_q15(), arm_dot_prod_q15(), arm_iir_lattice_q15(), arm_lms_norm_q15(), arm_lms_q15(), arm_mat_mult_q15(), arm_pid_q15(), arm_power_q15(), arm_rms_q15(), arm_std_q15(), and arm_var_q15().
CMSIS_INLINE __STATIC_INLINE uint64_t __SMLALDX (uint32_t x, uint32_t y, uint64_t sum)
Referenced by arm_conv_opt_q15(), arm_conv_partial_opt_q15(), arm_conv_partial_q15(), arm_conv_q15(), arm_correlate_opt_q15(), and arm_correlate_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __SMLSDX (uint32_t x, uint32_t y, uint32_t sum)
Referenced by arm_split_rifft_q15().
CMSIS_INLINE __STATIC_INLINE int32_t __SMMLA (int32_t x, int32_t y, int32_t sum)
Referenced by arm_mat_mult_fast_q31().
CMSIS_INLINE __STATIC_INLINE uint32_t __SMUAD (uint32_t x, uint32_t y)
Referenced by arm_biquad_cascade_df1_fast_q15(), arm_biquad_cascade_df1_q15(), arm_cfft_radix4by2_q15(), arm_cmplx_mag_q15(), arm_cmplx_mag_squared_q15(), arm_pid_q15(), arm_radix2_butterfly_q15(), and arm_radix4_butterfly_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __SMUADX (uint32_t x, uint32_t y)
Referenced by arm_biquad_cascade_df1_fast_q15(), arm_biquad_cascade_df1_q15(), arm_cfft_radix4by2_inverse_q15(), arm_mat_cmplx_mult_q15(), arm_radix2_butterfly_inverse_q15(), arm_radix4_butterfly_inverse_q15(), and arm_split_rifft_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __SMUSD (uint32_t x, uint32_t y)
Referenced by arm_cfft_radix4by2_inverse_q15(), arm_mat_cmplx_mult_q15(), arm_radix2_butterfly_inverse_q15(), arm_radix4_butterfly_inverse_q15(), arm_split_rfft_q15(), and arm_split_rifft_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __SMUSDX (uint32_t x, uint32_t y)
Referenced by arm_cfft_radix4by2_q15(), arm_radix2_butterfly_q15(), arm_radix4_butterfly_q15(), and arm_split_rfft_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t __SXTB16 (uint32_t x)
Referenced by arm_dot_prod_q7(), arm_power_q7(), and arm_q7_to_q15().
CMSIS_INLINE __STATIC_INLINE void arm_circularRead_f32 (int32_t * circBuffer, int32_t L, int32_t * readOffset, int32_t bufferInc, int32_t * dst, int32_t * dst_base, int32_t dst_length, int32_t dstInc, uint32_t blockSize)
References blockSize.
Referenced by arm_fir_sparse_f32(), and arm_fir_sparse_q31().
CMSIS_INLINE __STATIC_INLINE void arm_circularRead_q15 (q15_t * circBuffer, int32_t L, int32_t * readOffset, int32_t bufferInc, q15_t * dst, q15_t * dst_base, int32_t dst_length, int32_t dstInc, uint32_t blockSize)
References blockSize.
Referenced by arm_fir_sparse_q15().
CMSIS_INLINE __STATIC_INLINE void arm_circularRead_q7 (q7_t * circBuffer, int32_t L, int32_t * readOffset, int32_t bufferInc, q7_t * dst, q7_t * dst_base, int32_t dst_length, int32_t dstInc, uint32_t blockSize)
References blockSize.
Referenced by arm_fir_sparse_q7().
CMSIS_INLINE __STATIC_INLINE void arm_circularWrite_f32 (int32_t * circBuffer, int32_t L, uint16_t * writeOffset, int32_t bufferInc, const int32_t * src, int32_t srcInc, uint32_t blockSize)
end of SQRT group
References blockSize.
Referenced by arm_fir_sparse_f32(), and arm_fir_sparse_q31().
CMSIS_INLINE __STATIC_INLINE void arm_circularWrite_q15 (q15_t * circBuffer, int32_t L, uint16_t * writeOffset, int32_t bufferInc, const q15_t * src, int32_t srcInc, uint32_t blockSize)
References blockSize.
Referenced by arm_fir_sparse_q15().
CMSIS_INLINE __STATIC_INLINE void arm_circularWrite_q7 (q7_t * circBuffer, int32_t L, uint16_t * writeOffset, int32_t bufferInc, const q7_t * src, int32_t srcInc, uint32_t blockSize)
References blockSize.
Referenced by arm_fir_sparse_q7().
CMSIS_INLINE __STATIC_INLINE uint32_t arm_recip_q15 (q15_t in, q15_t * dst, q15_t * pRecipTable)
References INDEX_MASK.
Referenced by arm_lms_norm_q15().
CMSIS_INLINE __STATIC_INLINE uint32_t arm_recip_q31 (q31_t in, q31_t * dst, q31_t * pRecipTable)
References clip_q63_to_q31(), and INDEX_MASK.
Referenced by arm_lms_norm_q31().
CMSIS_INLINE __STATIC_INLINE q15_t clip_q31_to_q15 (q31_t x)
CMSIS_INLINE __STATIC_INLINE q7_t clip_q31_to_q7 (q31_t x)
CMSIS_INLINE __STATIC_INLINE q15_t clip_q63_to_q15 (q63_t x)
CMSIS_INLINE __STATIC_INLINE q31_t clip_q63_to_q31 (q63_t x)
Referenced by __QADD(), __QSUB(), arm_add_q31(), arm_cmplx_mult_real_q31(), arm_float_to_q31(), arm_iir_lattice_q31(), arm_lms_norm_q31(), arm_lms_q31(), arm_mat_cmplx_mult_q31(), arm_mat_mult_q31(), arm_mult_q31(), arm_offset_q31(), arm_pid_init_q31(), arm_recip_q31(), arm_rms_q31(), arm_shift_q31(), arm_sin_cos_q31(), and arm_sub_q31().
CMSIS_INLINE __STATIC_INLINE q63_t mult32x64 (q63_t x, q31_t y)
Referenced by arm_biquad_cas_df1_32x64_q31().