arm_cfft_q31.c File Reference
arm_cfft_q31.c File Reference
Functions
void arm_radix4_butterfly_q31 (q31_t *pSrc, uint32_t fftLen, q31_t *pCoef, uint32_t twidCoefModifier)
Core function for the Q31 CFFT butterfly process.
void arm_radix4_butterfly_inverse_q31 (q31_t *pSrc, uint32_t fftLen, q31_t *pCoef, uint32_t twidCoefModifier)
Core function for the Q31 CIFFT butterfly process.
void arm_bitreversal_32 (uint32_t *pSrc, const uint16_t bitRevLen, const uint16_t *pBitRevTable)
void arm_cfft_radix4by2_q31 (q31_t *pSrc, uint32_t fftLen, const q31_t *pCoef)
void arm_cfft_radix4by2_inverse_q31 (q31_t *pSrc, uint32_t fftLen, const q31_t *pCoef)
void arm_cfft_q31 (const arm_cfft_instance_q31 *S, q31_t *p1, uint8_t ifftFlag, uint8_t bitReverseFlag)
Processing function for the fixed-point complex FFT in Q31 format.
Function Documentation
void arm_bitreversal_32 (uint32_t * pSrc, const uint16_t bitRevLen, const uint16_t * pBitRevTable)
Referenced by arm_cfft_q31().
void arm_cfft_radix4by2_inverse_q31 (q31_t * pSrc, uint32_t fftLen, const q31_t * pCoef)
References arm_radix4_butterfly_inverse_q31(), mult_32x32_keep32_R, multAcc_32x32_keep32_R, and multSub_32x32_keep32_R.
Referenced by arm_cfft_q31().
void arm_cfft_radix4by2_q31 (q31_t * pSrc, uint32_t fftLen, const q31_t * pCoef)
end of ComplexFFT group
References arm_radix4_butterfly_q31(), mult_32x32_keep32_R, multAcc_32x32_keep32_R, and multSub_32x32_keep32_R.
Referenced by arm_cfft_q31().
void arm_radix4_butterfly_inverse_q31 (q31_t * pSrc, uint32_t fftLen, q31_t * pCoef, uint32_t twidCoefModifier)
Parameters
[in,out] *pSrc points to the in-place buffer of Q31 data type.
[in] fftLen length of the FFT.
[in] *pCoef points to twiddle coefficient buffer.
[in] twidCoefModifier twiddle coefficient modifier that supports different size FFTs with the same twiddle factor table.
Returns
none.
References __SIMD64.
Referenced by arm_cfft_q31(), arm_cfft_radix4_q31(), and arm_cfft_radix4by2_inverse_q31().
void arm_radix4_butterfly_q31 (q31_t * pSrc, uint32_t fftLen, q31_t * pCoef, uint32_t twidCoefModifier)
end of ComplexFFT group
Parameters
[in,out] *pSrc points to the in-place buffer of Q31 data type.
[in] fftLen length of the FFT.
[in] *pCoef points to twiddle coefficient buffer.
[in] twidCoefModifier twiddle coefficient modifier that supports different size FFTs with the same twiddle factor table.
Returns
none.
References __SIMD64.
Referenced by arm_cfft_q31(), arm_cfft_radix4_q31(), and arm_cfft_radix4by2_q31().