from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
drv_uart.c
""")

CPPPATH = [cwd]
CPPDEFINES = []

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
