# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

sfc_src = Split('''
drv_sfc.c
''')
sfc_group = DefineGroup('drv_sfc', sfc_src, depend = ['RT_USING_MTD_NOR'], CPPPATH = CPPPATH)

part_src = Split('''
drv_sfc_gd25qxx_mtd_partition.c
drv_sfc_gd25qxx_mtd.c
mtd_nor_partition.c
''')
part_group = DefineGroup('sfc_part', part_src, depend = ['RT_USING_MTD_NOR'], CPPPATH = CPPPATH)

group = sfc_group + part_group
Return('group')
