Import('env')
Import('rtconfig')
Import('RTT_ROOT')

comm = rtconfig.ARCH + '/common'
path = rtconfig.ARCH + '/' + rtconfig.CPU

# The set of source files associated with this SConscript file.
if rtconfig.PLATFORM == 'armcc':
	src_local = Glob(path + '/*.c') + Glob(path + '/*_rvds.S') + Glob(comm + '/*.c')

if rtconfig.PLATFORM == 'gcc':
	src_local = Glob(path + '/*.c') + Glob(path + '/*_gcc.S') + Glob(comm + '/*.c') + Glob(path + '/*_init.S')

if rtconfig.PLATFORM == 'iar':
	src_local = Glob(path + '/*.c') + Glob(path + '/*_iar.S') + Glob(comm + '/*.c')

env.Append(CPPPATH = [RTT_ROOT + '/libcpu/' + rtconfig.ARCH + '/' + rtconfig.CPU])
obj = env.Object(src_local)

Return('obj')
