Import('rtconfig')
from building import *
import os
import glob

cwd = GetCurrentDir()

# Locate the nxp-imxrt-sdk package installed by 'pkgs --update'.
# The directory is named nxp-imxrt-sdk-<version> under packages/.
bsp_pkg_dir = os.path.normpath(os.path.join(cwd, '..', 'packages'))
sdk_candidates = glob.glob(os.path.join(bsp_pkg_dir, 'nxp-imxrt-sdk-*', 'MIMXRT1180', 'ethercat'))
if sdk_candidates:
    sdk_ethercat = sdk_candidates[0]
else:
    sdk_ethercat = os.path.join(bsp_pkg_dir, 'nxp-imxrt-sdk-latest', 'MIMXRT1180', 'ethercat')

# EtherCAT application sources
ecat_src = [
    os.path.join(sdk_ethercat, 'ethercat_init.c'),
    os.path.join(sdk_ethercat, 'digital_io.c'),
]

# SSC sources
ssc_src = Glob(os.path.join(sdk_ethercat, 'SSC', 'Src', '*.c'))

CPPPATH = [
    sdk_ethercat,
    os.path.join(sdk_ethercat, 'SSC', 'Src'),
]

CPPDEFINES = []

group = []

if GetDepend(['BSP_USING_ETHERCAT']):
    group += DefineGroup('EtherCAT_APP', ecat_src, depend=['BSP_USING_ETHERCAT'], CPPPATH=CPPPATH, CPPDEFINES=CPPDEFINES)
    group += DefineGroup('EtherCAT_SSC', ssc_src, depend=['BSP_USING_ETHERCAT'], CPPPATH=CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
