Import('rtconfig')
from building import *

cwd = GetCurrentDir()
path = [cwd + '/../CMSIS/Core/Include',cwd + '/components/codec', cwd + '/LPC55S06', cwd + '/LPC55S06/drivers', cwd + '/middleware/sdmmc/port']
src = Split('''
            LPC55S06/system_LPC55S06.c
            ''')

if rtconfig.PLATFORM in ['gcc']:
    src += ['LPC55S06/gcc/startup_LPC55S06.S']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['LPC55S06/arm/startup_LPC55S06.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['LPC55S06/iar/startup_LPC55S06.s']

src += ['LPC55S06/drivers/fsl_anactrl.c']
src += ['LPC55S06/drivers/fsl_casper.c']
src += ['LPC55S06/drivers/fsl_clock.c']
src += ['LPC55S06/drivers/fsl_cmp.c']
src += ['LPC55S06/drivers/fsl_common.c']
src += ['LPC55S06/drivers/fsl_common_arm.c']
src += ['LPC55S06/drivers/fsl_crc.c']
src += ['LPC55S06/drivers/fsl_ctimer.c']
src += ['LPC55S06/drivers/fsl_flexcomm.c']
src += ['LPC55S06/drivers/fsl_dma.c']
src += ['LPC55S06/drivers/fsl_gint.c']
src += ['LPC55S06/drivers/fsl_gpio.c']
src += ['LPC55S06/drivers/fsl_hashcrypt.c']
src += ['LPC55S06/drivers/fsl_i2c.c']
src += ['LPC55S06/drivers/fsl_i2c_dma.c']
src += ['LPC55S06/drivers/fsl_i2s.c']
src += ['LPC55S06/drivers/fsl_i2s_dma.c']
src += ['LPC55S06/drivers/fsl_iap.c']
src += ['LPC55S06/drivers/fsl_inputmux.c']
src += ['LPC55S06/drivers/fsl_lpadc.c']
src += ['LPC55S06/drivers/fsl_mrt.c']
src += ['LPC55S06/drivers/fsl_ostimer.c']
src += ['LPC55S06/drivers/fsl_pint.c']
src += ['LPC55S06/drivers/fsl_plu.c']
src += ['LPC55S06/drivers/fsl_power.c']
src += ['LPC55S06/drivers/fsl_puf.c']
src += ['LPC55S06/drivers/fsl_reset.c']
src += ['LPC55S06/drivers/fsl_rng.c']
src += ['LPC55S06/drivers/fsl_rtc.c']
src += ['LPC55S06/drivers/fsl_sctimer.c']
src += ['LPC55S06/drivers/fsl_spi.c']
src += ['LPC55S06/drivers/fsl_spi_dma.c']
src += ['LPC55S06/drivers/fsl_sysctl.c']
src += ['LPC55S06/drivers/fsl_usart.c']
src += ['LPC55S06/drivers/fsl_usart_dma.c']
src += ['LPC55S06/drivers/fsl_utick.c']
src += ['LPC55S06/drivers/fsl_wwdt.c']


group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
