import os
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Src/stm32u5xx_hal_msp.c
''')


path =  [cwd]
path += [cwd + '/CubeMX_Config/Inc']

# You can select chips from the list above
CPPDEFINES = ['STM32U585xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')

