Import('env')

target = 'thread.mo'

module_env = env.Clone(CPPDEFINE = 'RT_MODULE')
module_env.Replace(LINKFLAGS = ' -r -d -e rtm_main -nostdlib')

src_local = Glob('*.c')

module_env.Program(target, src_local)
