import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd]
src = Glob('*.c')

if GetDepend(['BSP_USING_FS']):
    src += Glob('ports/mnt.c')

CPPDEFINES = ['BSP_CFG_RTOS = 2']

objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
