/*
 * Copyright (c) 2006-2022, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __PCI_IDS_H__
#define __PCI_IDS_H__

#define PCI_VENDOR_ID_LOONGSON              0x0014
#define PCI_VENDOR_ID_TTTECH                0x0357
#define PCI_VENDOR_ID_DYNALINK              0x0675
#define PCI_VENDOR_ID_UBIQUITI              0x0777
#define PCI_VENDOR_ID_BERKOM                0x0871
#define PCI_VENDOR_ID_COMPAQ                0x0e11
#define PCI_VENDOR_ID_NCR                   0x1000
#define PCI_VENDOR_ID_ATI                   0x1002
#define PCI_VENDOR_ID_VLSI                  0x1004
#define PCI_VENDOR_ID_ADL                   0x1005
#define PCI_VENDOR_ID_NS                    0x100b
#define PCI_VENDOR_ID_TSENG                 0x100c
#define PCI_VENDOR_ID_WEITEK                0x100e
#define PCI_VENDOR_ID_DEC                   0x1011
#define PCI_VENDOR_ID_CIRRUS                0x1013
#define PCI_VENDOR_ID_IBM                   0x1014
#define PCI_VENDOR_ID_UNISYS                0x1018
#define PCI_VENDOR_ID_COMPEX2               0x101a
#define PCI_VENDOR_ID_WD                    0x101c
#define PCI_VENDOR_ID_AMI                   0x101e
#define PCI_VENDOR_ID_AMD                   0x1022
#define PCI_VENDOR_ID_TRIDENT               0x1023
#define PCI_VENDOR_ID_AI                    0x1025
#define PCI_VENDOR_ID_DELL                  0x1028
#define PCI_VENDOR_ID_MATROX                0x102b
#define PCI_VENDOR_ID_MOBILITY_ELECTRONICS  0x14f2
#define PCI_VENDOR_ID_CT                    0x102c
#define PCI_VENDOR_ID_MIRO                  0x1031
#define PCI_VENDOR_ID_NEC                   0x1033
#define PCI_VENDOR_ID_FD                    0x1036
#define PCI_VENDOR_ID_SI                    0x1039
#define PCI_VENDOR_ID_HP                    0x103c
#define PCI_VENDOR_ID_PCTECH                0x1042
#define PCI_VENDOR_ID_ASUSTEK               0x1043
#define PCI_VENDOR_ID_DPT                   0x1044
#define PCI_VENDOR_ID_OPTI                  0x1045
#define PCI_VENDOR_ID_ELSA                  0x1048
#define PCI_VENDOR_ID_STMICRO               0x104a
#define PCI_VENDOR_ID_BUSLOGIC              0x104b
#define PCI_VENDOR_ID_TI                    0x104c
#define PCI_VENDOR_ID_SONY                  0x104d
#define PCI_VENDOR_ID_ANIGMA                0x1051
#define PCI_VENDOR_ID_EFAR                  0x1055
#define PCI_VENDOR_ID_MOTOROLA              0x1057
#define PCI_VENDOR_ID_PROMISE               0x105a
#define PCI_VENDOR_ID_FOXCONN               0x105b
#define PCI_VENDOR_ID_UMC                   0x1060
#define PCI_VENDOR_ID_PICOPOWER             0x1066
#define PCI_VENDOR_ID_MYLEX                 0x1069
#define PCI_VENDOR_ID_APPLE                 0x106b
#define PCI_VENDOR_ID_YAMAHA                0x1073
#define PCI_VENDOR_ID_QLOGIC                0x1077
#define PCI_VENDOR_ID_CYRIX                 0x1078
#define PCI_VENDOR_ID_CONTAQ                0x1080
#define PCI_VENDOR_ID_OLICOM                0x108d
#define PCI_VENDOR_ID_SUN                   0x108e
#define PCI_VENDOR_ID_NI                    0x1093
#define PCI_VENDOR_ID_CMD                   0x1095
#define PCI_VENDOR_ID_BROOKTREE             0x109e
#define PCI_VENDOR_ID_SGI                   0x10a9
#define PCI_VENDOR_ID_WINBOND               0x10ad
#define PCI_VENDOR_ID_PLX                   0x10b5
#define PCI_VENDOR_ID_MADGE                 0x10b6
#define PCI_VENDOR_ID_3COM                  0x10b7
#define PCI_VENDOR_ID_AL                    0x10b9
#define PCI_VENDOR_ID_NEOMAGIC              0x10c8
#define PCI_VENDOR_ID_TCONRAD               0x10da
#define PCI_VENDOR_ID_ROHM                  0x10db
#define PCI_VENDOR_ID_NVIDIA                0x10de
#define PCI_VENDOR_ID_IMS                   0x10e0
#define PCI_VENDOR_ID_AMCC                  0x10e8
#define PCI_VENDOR_ID_INTERG                0x10ea
#define PCI_VENDOR_ID_REALTEK               0x10ec
#define PCI_VENDOR_ID_XILINX                0x10ee
#define PCI_VENDOR_ID_INIT                  0x1101
#define PCI_VENDOR_ID_CREATIVE              0x1102
#define PCI_VENDOR_ID_ECTIVA                PCI_VENDOR_ID_CREATIVE
#define PCI_VENDOR_ID_TTI                   0x1103
#define PCI_VENDOR_ID_SIGMA                 0x1105
#define PCI_VENDOR_ID_VIA                   0x1106
#define PCI_VENDOR_ID_SIEMENS               0x110a
#define PCI_VENDOR_ID_VORTEX                0x1119
#define PCI_VENDOR_ID_EF                    0x111a
#define PCI_VENDOR_ID_IDT                   0x111d
#define PCI_VENDOR_ID_FORE                  0x1127
#define PCI_VENDOR_ID_PHILIPS               0x1131
#define PCI_VENDOR_ID_EICON                 0x1133
#define PCI_VENDOR_ID_CISCO                 0x1137
#define PCI_VENDOR_ID_ZIATECH               0x1138
#define PCI_VENDOR_ID_SYSKONNECT            0x1148
#define PCI_VENDOR_ID_DIGI                  0x114f
#define PCI_VENDOR_ID_XIRCOM                0x115d
#define PCI_VENDOR_ID_SERVERWORKS           0x1166
#define PCI_VENDOR_ID_ALTERA                0x1172
#define PCI_VENDOR_ID_SBE                   0x1176
#define PCI_VENDOR_ID_TOSHIBA               0x1179
#define PCI_VENDOR_ID_TOSHIBA_2             0x102f
#define PCI_VENDOR_ID_ATTO                  0x117c
#define PCI_VENDOR_ID_RICOH                 0x1180
#define PCI_VENDOR_ID_DLINK                 0x1186
#define PCI_VENDOR_ID_ARTOP                 0x1191
#define PCI_VENDOR_ID_ZEITNET               0x1193
#define PCI_VENDOR_ID_FUJITSU_ME            0x119e
#define PCI_VENDOR_ID_MARVELL               0x11ab
#define PCI_VENDOR_ID_V3                    0x11b0
#define PCI_VENDOR_ID_ATT                   0x11c1
#define PCI_VENDOR_ID_SPECIALIX             0x11cb
#define PCI_VENDOR_ID_ANALOG_DEVICES        0x11d4
#define PCI_VENDOR_ID_ZORAN                 0x11de
#define PCI_VENDOR_ID_COMPEX                0x11f6
#define PCI_VENDOR_ID_PMC_Sierra            0x11f8
#define PCI_VENDOR_ID_RP                    0x11fe
#define PCI_VENDOR_ID_CYCLADES              0x120e
#define PCI_VENDOR_ID_ESSENTIAL             0x120f
#define PCI_VENDOR_ID_O2                    0x1217
#define PCI_VENDOR_ID_3DFX                  0x121a
#define PCI_VENDOR_ID_QEMU                  0x1234
#define PCI_VENDOR_ID_AVM                   0x1244
#define PCI_VENDOR_ID_STALLION              0x124d
#define PCI_VENDOR_ID_ESS                   0x125d
#define PCI_VENDOR_ID_SATSAGEM              0x1267
#define PCI_VENDOR_ID_ENSONIQ               0x1274
#define PCI_VENDOR_ID_TRANSMETA             0x1279
#define PCI_VENDOR_ID_ROCKWELL              0x127a
#define PCI_VENDOR_ID_ITE                   0x1283
#define PCI_VENDOR_ID_ALTEON                0x12ae
#define PCI_VENDOR_ID_NVIDIA_SGS            0x12d2
#define PCI_VENDOR_ID_PERICOM               0x12d8
#define PCI_VENDOR_ID_AUREAL                0x12eb
#define PCI_VENDOR_ID_ELECTRONICDESIGNGMBH  0x12f8
#define PCI_VENDOR_ID_ESDGMBH               0x12fe
#define PCI_VENDOR_ID_CB                    0x1307
#define PCI_VENDOR_ID_SIIG                  0x131f
#define PCI_VENDOR_ID_RADISYS               0x1331
#define PCI_VENDOR_ID_MICRO_MEMORY          0x1332
#define PCI_VENDOR_ID_DOMEX                 0x134a
#define PCI_VENDOR_ID_INTASHIELD            0x135a
#define PCI_VENDOR_ID_QUATECH               0x135c
#define PCI_VENDOR_ID_SEALEVEL              0x135e
#define PCI_VENDOR_ID_HYPERCOPE             0x1365
#define PCI_VENDOR_ID_DIGIGRAM              0x1369
#define PCI_VENDOR_ID_KAWASAKI              0x136b
#define PCI_VENDOR_ID_CNET                  0x1371
#define PCI_VENDOR_ID_LMC                   0x1376
#define PCI_VENDOR_ID_NETGEAR               0x1385
#define PCI_VENDOR_ID_APPLICOM              0x1389
#define PCI_VENDOR_ID_MOXA                  0x1393
#define PCI_VENDOR_ID_CCD                   0x1397
#define PCI_VENDOR_ID_EXAR                  0x13a8
#define PCI_VENDOR_ID_MICROGATE             0x13c0
#define PCI_VENDOR_ID_3WARE                 0x13c1
#define PCI_VENDOR_ID_IOMEGA                0x13ca
#define PCI_VENDOR_ID_ABOCOM                0x13d1
#define PCI_VENDOR_ID_SUNDANCE              0x13f0
#define PCI_VENDOR_ID_CMEDIA                0x13f6
#define PCI_VENDOR_ID_ADVANTECH             0x13fe
#define PCI_VENDOR_ID_MEILHAUS              0x1402
#define PCI_VENDOR_ID_LAVA                  0x1407
#define PCI_VENDOR_ID_TIMEDIA               0x1409
#define PCI_VENDOR_ID_ICE                   0x1412
#define PCI_VENDOR_ID_MICROSOFT             0x1414
#define PCI_VENDOR_ID_OXSEMI                0x1415
#define PCI_VENDOR_ID_CHELSIO               0x1425
#define PCI_VENDOR_ID_ADLINK                0x144a
#define PCI_VENDOR_ID_SAMSUNG               0x144d
#define PCI_VENDOR_ID_GIGABYTE              0x1458
#define PCI_VENDOR_ID_AMBIT                 0x1468
#define PCI_VENDOR_ID_MYRICOM               0x14c1
#define PCI_VENDOR_ID_MEDIATEK              0x14c3
#define PCI_VENDOR_ID_TITAN                 0x14d2
#define PCI_VENDOR_ID_PANACOM               0x14d4
#define PCI_VENDOR_ID_SIPACKETS             0x14d9
#define PCI_VENDOR_ID_AFAVLAB               0x14db
#define PCI_VENDOR_ID_AMPLICON              0x14dc
#define PCI_VENDOR_ID_BCM_GVC               0x14a4
#define PCI_VENDOR_ID_TOPIC                 0x151f
#define PCI_VENDOR_ID_MAINPINE              0x1522
#define PCI_VENDOR_ID_SYBA                  0x1592
#define PCI_VENDOR_ID_MORETON               0x15aa
#define PCI_VENDOR_ID_VMWARE                0x15ad
#define PCI_VENDOR_ID_ZOLTRIX               0x15b0
#define PCI_VENDOR_ID_MELLANOX              0x15b3
#define PCI_VENDOR_ID_DFI                   0x15bd
#define PCI_VENDOR_ID_QUICKNET              0x15e2
#define PCI_VENDOR_ID_PDC                   0x15e9
#define PCI_VENDOR_ID_FARSITE               0x1619
#define PCI_VENDOR_ID_ARIMA                 0x161f
#define PCI_VENDOR_ID_BROCADE               0x1657
#define PCI_VENDOR_ID_SIBYTE                0x166d
#define PCI_VENDOR_ID_ATHEROS               0x168c
#define PCI_VENDOR_ID_NETCELL               0x169c
#define PCI_VENDOR_ID_CENATEK               0x16ca
#define PCI_VENDOR_ID_SYNOPSYS              0x16c3
#define PCI_VENDOR_ID_USR                   0x16ec
#define PCI_VENDOR_ID_VITESSE               0x1725
#define PCI_VENDOR_ID_LINKSYS               0x1737
#define PCI_VENDOR_ID_ALTIMA                0x173b
#define PCI_VENDOR_ID_CAVIUM                0x177d
#define PCI_VENDOR_ID_TECHWELL              0x1797
#define PCI_VENDOR_ID_BELKIN                0x1799
#define PCI_VENDOR_ID_RDC                   0x17f3
#define PCI_VENDOR_ID_GLI                   0x17a0
#define PCI_VENDOR_ID_LENOVO                0x17aa
#define PCI_VENDOR_ID_QCOM                  0x17cb
#define PCI_VENDOR_ID_CDNS                  0x17cd
#define PCI_VENDOR_ID_ARECA                 0x17d3
#define PCI_VENDOR_ID_S2IO                  0x17d5
#define PCI_VENDOR_ID_SITECOM               0x182d
#define PCI_VENDOR_ID_TOPSPIN               0x1867
#define PCI_VENDOR_ID_COMMTECH              0x18f7
#define PCI_VENDOR_ID_SILAN                 0x1904
#define PCI_VENDOR_ID_RENESAS               0x1912
#define PCI_VENDOR_ID_SOLARFLARE            0x1924
#define PCI_VENDOR_ID_TDI                   0x192e
#define PCI_VENDOR_ID_FREESCALE             0x1957
#define PCI_VENDOR_ID_NXP                   PCI_VENDOR_ID_FREESCALE
#define PCI_VENDOR_ID_PASEMI                0x1959
#define PCI_VENDOR_ID_ATTANSIC              0x1969
#define PCI_VENDOR_ID_JMICRON               0x197b
#define PCI_VENDOR_ID_KORENIX               0x1982
#define PCI_VENDOR_ID_HUAWEI                0x19e5
#define PCI_VENDOR_ID_NETRONOME             0x19ee
#define PCI_VENDOR_ID_QMI                   0x1a32
#define PCI_VENDOR_ID_AZWAVE                0x1a3b
#define PCI_VENDOR_ID_REDHAT_QUMRANET       0x1af4
#define PCI_VENDOR_ID_ASMEDIA               0x1b21
#define PCI_VENDOR_ID_REDHAT                0x1b36
#define PCI_VENDOR_ID_SILICOM_DENMARK       0x1c2c
#define PCI_VENDOR_ID_AMAZON_ANNAPURNA_LABS 0x1c36
#define PCI_VENDOR_ID_CIRCUITCO             0x1cc8
#define PCI_VENDOR_ID_AMAZON                0x1d0f
#define PCI_VENDOR_ID_ZHAOXIN               0x1d17
#define PCI_VENDOR_ID_HYGON                 0x1d94
#define PCI_VENDOR_ID_FUNGIBLE              0x1dad
#define PCI_VENDOR_ID_HXT                   0x1dbf
#define PCI_VENDOR_ID_TEKRAM                0x1de1
#define PCI_VENDOR_ID_TEHUTI                0x1fc9
#define PCI_VENDOR_ID_SUNIX                 0x1fd4
#define PCI_VENDOR_ID_HINT                  0x3388
#define PCI_VENDOR_ID_3DLABS                0x3d3d
#define PCI_VENDOR_ID_NETXEN                0x4040
#define PCI_VENDOR_ID_AKS                   0x416c
#define PCI_VENDOR_ID_ACCESSIO              0x494f
#define PCI_VENDOR_ID_S3                    0x5333
#define PCI_VENDOR_ID_DUNORD                0x5544
#define PCI_VENDOR_ID_DCI                   0x6666
#define PCI_VENDOR_ID_INTEL                 0x8086
#define PCI_VENDOR_ID_SCALEMP               0x8686
#define PCI_VENDOR_ID_COMPUTONE             0x8e0e
#define PCI_VENDOR_ID_KTI                   0x8e2e
#define PCI_VENDOR_ID_ADAPTEC               0x9004
#define PCI_VENDOR_ID_ADAPTEC2              0x9005
#define PCI_VENDOR_ID_HOLTEK                0x9412
#define PCI_VENDOR_ID_NETMOS                0x9710
#define PCI_VENDOR_ID_3COM_2                0xa727
#define PCI_VENDOR_ID_DIGIUM                0xd161
#define PCI_VENDOR_ID_TIGERJET              0xe159
#define PCI_VENDOR_ID_XILINX_RME            0xea60
#define PCI_VENDOR_ID_XEN                   0x5853
#define PCI_VENDOR_ID_OCZ                   0x1b85
#define PCI_VENDOR_ID_NCUBE                 0x10ff

#endif /* __PCI_IDS_H__ */
