from building import *

objs = []

if not GetDepend(['RT_USING_PCI']):
    Return('objs')

cwd     = GetCurrentDir()
list    = os.listdir(cwd)
CPPPATH = [cwd + '/../include']

src = ['access.c', 'host-bridge.c', 'irq.c', 'pci.c', 'pme.c', 'probe.c']

if GetDepend(['RT_USING_OFW']):
    src += ['ofw.c']

if GetDepend(['RT_PCI_ECAM']):
    src += ['ecam.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
