from building import *

group = []
src = []
cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

if GetDepend(['RT_WDT_RK8XX']):
    src += ['watchdog-rk8xx.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
