from building import *

cwd = GetCurrentDir()
src = []


if GetDepend('RT_USING_SERIAL'):
    src += ['drv_uart.c']

if GetDepend('RT_USING_LWIP'):
    src += ['drv_eth.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
