from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
cherryusb_port.c
usb_phy.c
MCUX_Config/board/clock_config.c
MCUX_Config/board/pin_mux.c
""")

if GetDepend(['BSP_USING_SPI6_SAMPLE']):
    src += Glob('ports/spi_sample.c')

if GetDepend(['BSP_USING_RW007']):
    src += Glob('ports/drv_spi_sample_rw007.c')

if GetDepend(['RT_USING_SFUD']):
    src += Glob('ports/drv_filesystem_spi_flash.c')

if GetDepend(['PKG_USING_CJSON']) and GetDepend(['PKG_USING_WEBCLIENT']):
    src += Glob('ports/wifi_weather_sample.c')


CPPPATH = [cwd, cwd + '/MCUX_Config/board']
CPPDEFINES = ['DEBUG', 'CPU_MCXN947VDF_cm33_core0']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
