# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
group = []
if GetDepend('NU_PKG_USING_SPINAND'):
	src = Glob('*.c') + Glob('*.cpp')
	CPPPATH = [cwd]
	group = DefineGroup('nu_pkgs_spinand', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
