from building import *


cwd     = GetCurrentDir()
CPPPATH = [cwd+"/HAL_Driver/Inc",cwd+"/rt_drivers",cwd+"/rt_drivers/config"]
CPPDEFINES = ['__USE_XTL__']
# add general drivers
src = Split('''
HAL_Driver/Src/bsp_common.c
HAL_Driver/Src/core_uart.c
HAL_Driver/Src/core_dma.c
HAL_Driver/Src/core_gpio.c
HAL_Driver/Src/core_irq.c
HAL_Driver/Src/core_wdt.c
HAL_Driver/Src/core_spi.c
HAL_Driver/Src/core_i2c.c
HAL_Driver/Src/core_tick.c
HAL_Driver/Src/core_rtc.c
rt_drivers/drv_usart_v2.c
rt_drivers/drv_i2c.c
rt_drivers/drv_wdt.c
rt_drivers/drv_gpio.c
rt_drivers/drv_common.c
rt_drivers/drv_spi.c
rt_drivers/drv_rtc.c
''')
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
