from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
""")

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
