import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = ['board.c']

path =  [cwd]

CPPDEFINES = [
    'CONFIG_KERNEL_RTTHREAD=1',
    '__RT_KERNEL_SOURCE__=1',
    'CONFIG_CSI_V2=1',
    'CONFIG_CSI="csi2"',
    'CONFIG_SUPPORT_TSPEND=0',
    'CONFIG_SUPPORT_IRQ_NESTED=0',
    'CONFIG_XIP=1',
    'CONFIG_ARCH_MAINSTACK=8192',
    'CONFIG_ARCH_INTERRUPTSTACK=8192',
    'CONFIG_BOARD_XIAOHUI_EVB=1',
    'CLI_CONFIG_STACK_SIZE=8192',
    'CONFIG_PLIC_BASE=134217728',
    'CONFIG_VIC_TSPDR=201326592',
    'CONFIG_CLIC_BASE=201392128',
    'CONFIG_FPP_ENABLE=0',
    'CONFIG_INTC_CLIC_PLIC=1',
    'CONFIG_INIT_TASK_STACK_SIZE=8192',
    'CONFIG_APP_TASK_STACK_SIZE=8192',
    'CONFIG_SYSTICK_HZ=100',
    'CONFIG_DEBUG=1',
    'CONFIG_CPU_XUANTIE_C908X=1'
]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
