devices.soft_i2c:
  kconfig:
    - CONFIG_RT_USING_I2C=y
    - CONFIG_RT_USING_SOFT_I2C=y
    - CONFIG_RT_USING_SOFT_I2C1=y
    - CONFIG_RT_SOFT_I2C1_SCL_PIN=26
    - CONFIG_RT_SOFT_I2C1_SDA_PIN=27
    - CONFIG_RT_SOFT_I2C1_BUS_NAME="swi2c1"
    - CONFIG_RT_USING_SOFT_I2C2=y
    - CONFIG_RT_SOFT_I2C2_SCL_PIN=22
    - CONFIG_RT_SOFT_I2C2_SDA_PIN=23
    - CONFIG_RT_SOFT_I2C2_BUS_NAME="swi2c2"
