# RT-Thread building script for component

import os
import rtconfig
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = []

# add serial driver code
if  GetDepend('BSP_USING_UART1') or GetDepend('BSP_USING_UART2') or GetDepend('BSP_USING_UART3'):
    src += ['drv_uart.c']

# add gpio driver code
if  GetDepend(['BSP_USING_GPIO']):
    src += ['drv_gpio.c']

# add adc driver code
if  GetDepend(['BSP_USING_ADC']):
    src += ['drv_adc.c']

# add flash driver code
if  GetDepend(['BSP_USING_OCFLASH']):
    src += ['drv_flash.c']

CPPPATH = [cwd]


group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
