import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd]
src = Glob('*.c')

if GetDepend(['BSP_USING_FS']):
    src += Glob('ports/mnt.c')

if GetDepend(['BSP_USING_JPEG']):
    src += Glob('ports/drv_jpeg.c')

if GetDepend(['BSP_USING_G2D']):
    src += Glob('ports/drv_g2d.c')

objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
