Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drvers.
src = Split("""
board.c
usart.c
""")

# add Ethernet drvers.
if GetDepend('RT_USING_LED'):
    src += ['led.c']

if GetDepend('RT_USING_SDIO'):
    src += ['at91_mci.c']

if GetDepend('RT_USING_LWIP'):
    src += ['macb.c']

if GetDepend('RT_USING_I2C') and GetDepend('RT_USING_I2C_BITOPS'):
    src += ['at91_i2c_gpio.c']

if GetDepend('RT_USING_MTD_NAND'):
    src += ['at91_nand.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
