from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd + '/../include']
src     = Split('''
rt_cputime.c
''')

if GetDepend('RT_USING_CPUTIME_CORTEXM'):
    src += ['rt_cputime_cortexm.c']

group   = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_CPUTIME'], CPPPATH = CPPPATH)

Return('group')
