# for module compiling
import os
Import('rtconfig')
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

objs += SConscript(os.path.join('drv', 'SConscript'))
  
Return('objs')


