# ------ PERIPHERAL CI ------
peripheral.EMAC:
    kconfig:
      - CONFIG_BSP_DRV_EMAC=y
peripheral.LVGL:
    kconfig:
      - CONFIG_RT_USING_POSIX_SOCKET=y  
      - ONFIG_RT_USING_LWIP=y 
      - CONFIG_BSP_USING_LVGL=y     
      
# ------ online-packages CI ------
online-packages.misc.entertainment.tetris:
    kconfig:
      - CONFIG_PKG_USING_TETRIS=y
online-packages.misc.entertainment.2048:
    kconfig:
      - CONFIG_PKG_USING_2048=y
online-packages.ai.llmchat:
    kconfig:
      - CONFIG_PKG_USING_MBEDTLS=y
      - CONFIG_PKG_USING_LLMCHAT=y
      - CONFIG_PKG_LLMCHAT_PATH="/packages/ai/llmchat"
      - CONFIG_PKG_LLM_USING_QWEN_CLOUD=y
      - CONFIG_PKG_LLM_API_KEY="sk-**-**"
      - CONFIG_PKG_LLM_MODEL_NAME="qwen-plus"
      - CONFIG_PKG_LLM_QWEN_API_URL="https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
      - CONFIG_PKG_LLM_THREAD_STACK_SIZE=10240
      - CONFIG_PKG_LLM_CMD_BUFFER_SIZE=256
      - CONFIG_PKG_WEB_SORKET_BUFSZ=2048
      - CONFIG_PKG_LLMCHAT_STREAM=y