Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd  = GetCurrentDir()
CPPPATH = [cwd]

# The set of source files associated with this SConscript file.
src = Glob('*.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
