import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Glob('GD32F20x_standard_peripheral/Source/*.c')
src += [cwd + '/CMSIS/GD/GD32F20x/Source/system_gd32f20x.c']

#add for startup script
if rtconfig.CROSS_TOOL == 'gcc':
    src += [cwd + '/CMSIS/GD/GD32F20x/Source/GCC/isr_tab.s']
    src += [cwd + '/CMSIS/GD/GD32F20x/Source/GCC/startup_gd32.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [cwd + '/CMSIS/GD/GD32F20x/Source/ARM/startup_gd32f20x.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += [cwd + '/CMSIS/GD/GD32F20x/Source/IAR/startup_gd32f20x.s']

path = [
    cwd + '/CMSIS/GD/GD32F20x/Include',
    cwd + '/CMSIS',
    cwd + '/GD32F20x_standard_peripheral/Include',]

if GetDepend(['RT_USING_BSP_USB']):
    path += [cwd + '/GD32F20x_usbfs_driver/Include']
    src  += [cwd + '/GD32F20x_usbfs_driver/Source']

CPPDEFINES = ['USE_STDPERIPH_DRIVER', 'GD32F20X_CL']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
