import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Device/Nuvoton/NUC472_442/Source/system_NUC472_442.c
""")

src += Glob('StdDriver/src/*.c')

# starupt scripts for each STM32 kind
startup_scripts = {}
startup_scripts['STM32F10X_CL']     = 'startup_stm32f10x_cl.s'
startup_scripts['STM32F10X_HD']     = 'startup_stm32f10x_hd.s'
startup_scripts['STM32F10X_HD_VL']  = 'startup_stm32f10x_hd_vl.s'
startup_scripts['STM32F10X_LD']     = 'startup_stm32f10x_ld.s'
startup_scripts['STM32F10X_LD_VL']  = 'startup_stm32f10x_ld_vl.s'
startup_scripts['STM32F10X_MD']     = 'startup_stm32f10x_md.s'
startup_scripts['STM32F10X_MD_VL']  = 'startup_stm32f10x_md_vl.s'
startup_scripts['STM32F10X_XL']	    = 'startup_stm32f10x_xl.s'

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    src = src + ['Device/Nuvoton/NUC472_442/Source/GCC/startup.c']
elif rtconfig.CROSS_TOOL == 'keil':
    src = src + ['CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/arm/']
elif rtconfig.CROSS_TOOL == 'iar':
    src = src + ['CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/iar/']

path = [cwd + '/StdDriver/inc',
    cwd + '/CMSIS/Include',
    cwd + '/Device/Nuvoton/NUC472_442/Include']

if GetDepend(['RT_USING_BSP_CMSIS']):
    path += [cwd + '/CMSIS/CM3/CoreSupport']
    src += [cwd + '/CMSIS/CM3/CoreSupport/core_cm3.c']
elif GetDepend(['RT_USING_RTT_CMSIS']):
    path += [RTT_ROOT + '/components/CMSIS/Include']

group = DefineGroup('NUC472_StdPeriph', src, depend = [''], CPPPATH = path)

Return('group')
