from building import *
import rtconfig

cwd = GetCurrentDir()

src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('partition', src, depend = ['BSP_USING_SDMMC'], CPPPATH = CPPPATH)

Return('group')
