# SConscript for sensor framework

from building import *

src = ['sensor_v2.c']

if GetDepend('RT_USING_SENSOR_CMD'):
    src += ['sensor_cmd.c']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SENSOR_V2'])

Return('group')
