Import('RTT_ROOT')
Import('rtconfig')

from building import *
import os

cwd = GetCurrentDir()
parent = os.path.dirname(cwd)
src = ['drv_exti.c']

if GetDepend(['BSP_USING_GPIO']):
    src += ['drv_gpio.c']
path = [
    cwd,
    parent,
    os.path.join(parent, 'config'),
    os.path.join(RTT_ROOT, 'components', 'drivers', 'pin'),
]

group = []

group += DefineGroup('STM32 DM Drivers', src,
        depend = ['RT_USING_DM'],
        CPPPATH = path)

if rtconfig.PLATFORM == 'armclang':
    group += DefineGroup('STM32 DM FDT', ['builtin_fdt_ac6.c'],
            depend = ['RT_USING_BUILTIN_FDT'], CPPPATH = [cwd])

Return('group')
