import os
from building import *

group = []

if GetDepend('ARCH_ARM_CORTEX_A') or GetDepend('ARCH_ARMV8') or GetDepend('ARCH_RISCV64'):
    cwd  = GetCurrentDir()
    src = Glob('*.c') + Glob('*_gcc.S')
    if not GetDepend('RT_USING_MEMBLOCK'):
        SrcRemove(src, ['mm_memblock.c'])

    CPPPATH = [cwd]

    group = DefineGroup('mm', src, depend = ['ARCH_MM_MMU'], CPPPATH = CPPPATH)

Return('group')
