# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]
ASFLAGS = ''

if rtconfig.PLATFORM == 'armcc':
    src += Glob('*_rvds.S')
    ASFLAGS = ' --cpreproc'

if rtconfig.PLATFORM == 'gcc':
    src += Glob('*_init.S')
    src += Glob('*_gcc.S')

if rtconfig.PLATFORM == 'iar':
    src += Glob('*_iar.S')

if GetDepend(['RT_DEBUG_UNWIND']):
    linkflags = ' -funwind-tables '
    ccflags = ' -funwind-tables '
    cxxflags = ' -funwind-tables '
    asflags = ' -funwind-tables ' + ASFLAGS
else:
    linkflags = ''
    ccflags = ''
    cxxflags = ''
    asflags = ASFLAGS

group = DefineGroup('cpu', src, depend = [''], CPPPATH = CPPPATH, LINKFLAGS = linkflags, CCFLAGS = ccflags, ASFLAGS = asflags, CXXFLAGS = cxxflags)

Return('group')
