from building import *

group = []

if not GetDepend(['RT_USING_DVFS']):
    Return('group')

cwd = GetCurrentDir()
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
