from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
drv_irq.c
""")

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']
    
if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_usart.c']

if GetDepend(['RT_USING_I2C', 'RT_USING_I2C_BITOPS']):
    src += ['drv_soft_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['drv_spi.c'] 

if GetDepend(['RT_USING_QSPI']):
    src += ['drv_qspi.c']

if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']

if GetDepend('RT_USING_HWTIMER'):
    src += ['drv_hwtimer.c']

if GetDepend('RT_USING_PWM'):
    src += ['drv_pwm.c']

if GetDepend('RT_USING_PULSE_ENCODER'):
    src += ['drv_pulse_encoder.c']

CPPPATH = [cwd]
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
