Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd  = GetCurrentDir()
CPPPATH = [cwd]
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))


# The set of source files associated with this SConscript file.
src = Glob('*.c')

group = DefineGroup('platform', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
