import os
from building import *

cwd = GetCurrentDir()

# add general drivers
src = []
path =  []

if GetDepend(['RT_USING_CHERRYUSB']):
    src += Glob('cherryusb/cherryusb.c')
    path += [cwd + '/cherryusb']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')