scons.args: &scons
  scons_arg:
    - '--strict'

# ------ component CI ------

# ------ Peripheral CI ------
Peripheral.qspi_flash_FS:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_QSPI_FLASH_FS=y
Peripheral.lpadc1_dma:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_ADC=y
    - CONFIG_BSP_USING_DMA=y
    - CONFIG_BSP_USING_LPADC=y
    - CONFIG_BSP_USING_LPADC1=y
    - CONFIG_BSP_LPADC1_USING_DMA=y
Peripheral.lpadc1:
  <<: *scons
  kconfig:
    - CONFIG_RT_USING_ADC=y
    - CONFIG_BSP_USING_LPADC=y
    - CONFIG_BSP_USING_LPADC1=y
Peripheral.lpuart_device:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_LPUART=y
    - CONFIG_BSP_USING_DMA=y
Peripheral.i2c_device:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_I2C=y
    - CONFIG_BSP_USING_DMA=y
Peripheral.spi_device:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_SPI=y
    - CONFIG_BSP_USING_DMA=y
Peripheral.can_device:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_CAN=y
Peripheral.rtc_device:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_RTC=y
Peripheral.dwt_device:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_DWT=y
Peripheral.sdio_device:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_SDCARD_FATFS=y
Peripheral.usb_device:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USING_USB=y
Peripheral.multicore:
  <<: *scons
  kconfig:
    - CONFIG_BSP_USE_MULTICORE=y