from building import *

cwd     = GetCurrentDir()
src     = ['drv_uart.c']
CPPDEFINES = []

CPPPATH = [cwd]

if GetDepend('BSP_USING_CV1800B') or GetDepend('BSP_USING_C906_LITTLE'):
    CPPPATH += [cwd + r'/cv1800b']

if GetDepend('BSP_USING_CV1800B'):
    src += ['drv_gpio.c']

if GetDepend('BSP_USING_I2C'):
    src += ['drv_hw_i2c.c']

if GetDepend('BSP_USING_ADC'):
    src += ['drv_adc.c']

CPPDEFINES += ['-DCONFIG_64BIT']

group = DefineGroup('drivers', src, depend = [''], CPPDEFINES = CPPDEFINES, CPPPATH = CPPPATH)

Return('group')
