from building import *

cwd     = GetCurrentDir()
src     = Split('''
drv_uart.c
drv_por.c
''')
CPPDEFINES = []

CPPPATH = [cwd]

if GetDepend('BSP_USING_CV1800B') or GetDepend('BSP_USING_C906_LITTLE'):
    CPPPATH += [cwd + r'/cv1800b']

if GetDepend('BSP_USING_CV1800B'):
    src += ['drv_gpio.c']

if GetDepend('BSP_USING_I2C'):
    src += ['drv_hw_i2c.c']

if GetDepend('BSP_USING_ADC'):
    src += ['drv_adc.c']

if GetDepend('BSP_USING_WDT'):
    src += ['drv_wdt.c']

if GetDepend('BSP_USING_PWM'):
    src += ['drv_pwm.c']
    CPPPATH += [cwd + r'/cv1800b/pwm']
CPPDEFINES += ['-DCONFIG_64BIT']

if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']

group = DefineGroup('drivers', src, depend = [''], CPPDEFINES = CPPDEFINES, CPPPATH = CPPPATH)

Return('group')
