# SConscript for sensor framework 

from building import *

cwd = GetCurrentDir()
src = ['sensor.c']
CPPPATH = [cwd, cwd + '/../include']

if GetDepend('RT_USING_SENSOR_CMD'):
    src += ['sensor_cmd.c']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SENSOR', 'RT_USING_DEVICE'], CPPPATH = CPPPATH)

Return('group')
