from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd + '/../../include']

if GetDepend(['RT_POWER_RESET_REBOOT_SPACEMIT']):
    src += ['reboot-spacemit.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
