import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
''')

if GetDepend(['BSP_USING_SPI_FLASH']):
    src += Glob('ports/spi_flash_init.c')

path =  [cwd]
path += [cwd + '/ports']

startup_path_prefix = SDK_LIB

if rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += [startup_path_prefix + '/APM32S10x_Library/Device/Geehy/APM32S10x/Source/arm/startup_apm32s10x_md.s']

if rtconfig.PLATFORM in ['iccarm']:
    src += [startup_path_prefix + '/APM32S10x_Library/Device/Geehy/APM32S10x/Source/iar/startup_apm32s10x_md.s']

if rtconfig.PLATFORM in ['gcc']:
    src += [startup_path_prefix + '/APM32S10x_Library/Device/Geehy/APM32S10x/Source/gcc/startup_apm32s10x_md.S']

# You can select chips from the list above
CPPDEFINES = ['APM32S10X_MD']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
