import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
cmsis/cm4/device_support/system_at32f403a_407.c
drivers/src/at32f403a_407_acc.c
drivers/src/at32f403a_407_adc.c
drivers/src/at32f403a_407_bpr.c
drivers/src/at32f403a_407_can.c
drivers/src/at32f403a_407_crc.c
drivers/src/at32f403a_407_crm.c
drivers/src/at32f403a_407_dac.c
drivers/src/at32f403a_407_debug.c
drivers/src/at32f403a_407_dma.c
drivers/src/at32f403a_407_emac.c
drivers/src/at32f403a_407_exint.c
drivers/src/at32f403a_407_flash.c
drivers/src/at32f403a_407_gpio.c
drivers/src/at32f403a_407_i2c.c
drivers/src/at32f403a_407_misc.c
drivers/src/at32f403a_407_pwc.c
drivers/src/at32f403a_407_rtc.c
drivers/src/at32f403a_407_sdio.c
drivers/src/at32f403a_407_spi.c
drivers/src/at32f403a_407_tmr.c
drivers/src/at32f403a_407_usart.c
drivers/src/at32f403a_407_usb.c
drivers/src/at32f403a_407_wdt.c
drivers/src/at32f403a_407_wwdt.c
drivers/src/at32f403a_407_xmc.c
""")

path = [
    cwd + '/cmsis/cm4/device_support',
    cwd + '/cmsis/cm4/core_support',
    cwd + '/drivers/inc',]

CPPDEFINES = ['USE_STDPERIPH_DRIVER']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
