from building import *

cwd = GetCurrentDir()

embarc_arc_hal_SRCS = Split("""
arc/arc_cache.c
arc/arc_exc_asm.S
arc/arc_exception.c
arc/arc_timer.c
arc/startup/arc_cxx_support.c
arc/startup/arc_startup.S
device/designware/uart/dw_uart.c
device/designware/gpio/dw_gpio.c
""")


ASFLAGS = ' -I' + cwd

src = embarc_arc_hal_SRCS

path = [cwd,
	cwd + '/arc',
	cwd + '/arc/startup'
	]

group = DefineGroup('embarc', src, depend = [], CPPPATH = path, ASFLAGS = ASFLAGS)

Return('group')
