import os
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Glob('board.c')
src += Glob('CubeMX_Config/Src/stm32f7xx_hal_msp.c')

path = [cwd]
path += [cwd + '/CubeMX_Config/Inc']


group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)


Return('group')
