import os
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd + '/../include']

if not GetDepend('RT_USING_DM'):
    SrcRemove(src, ['can_dm.c'])

group   = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_CAN'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
