from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = [
    'dev_can.c',
    'can_tx.c',
    'can_rx.c',
]

if GetDepend('RT_USING_DM'):
    src.append('can_dm.c')

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_CAN'], CPPPATH = CPPPATH)

Return('group')
