peripheral.can0:
    kconfig:
      - CONFIG_BSP_USING_CAN=y
      - CONFIG_BSP_USING_CAN0=y
      - CONFIG_BSP_USING_CAN0=y
      - CONFIG_BSP_USING_CAN0=y
      - CONFIG_BSP_CAN0_TX_PD1=y
      - CONFIG_BSP_CAN0_RX_PD0=y