# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Split('''
autofit.c
''')
CPPPATH = [cwd]

group = DefineGroup('freetype', src, depend = ['RT_USING_GUIENGINE'], CPPPATH = CPPPATH)

Return('group')
