# RT-Thread building script for component
Import('RTT_ROOT')

from building import *

cwd = GetCurrentDir()

src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]
group = DefineGroup('nu_pkgs_ccap', src, depend = ['BSP_USING_CCAP'], CPPPATH = CPPPATH)

Return('group')
