import os
from building import *

objs = []
src = ["drv_sdram.c"]
cwd  = GetCurrentDir()
CPPPATH = [cwd]

if GetDepend(['BSP_USING_FS']):
    src += ['mnt.c']

objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
