Import('RTT_ROOT')
Import('rtconfig')
from building import *
import pdb
cwd     = os.path.join(str(Dir('#')), 'applications')
src = Glob('*.c') + Glob('*.cpp')
src_app = []
src_arduino = []
for f in src:
    if 'arduino' in f.name:
        src_arduino.append(f)
    else:
        src_app.append(f)
        
if GetDepend(['PKG_USING_RTDUINO']) and not GetDepend(['RTDUINO_NO_SETUP_LOOP']):
    src = src_app+src_arduino
else:
    src = src_app

CPPPATH = [cwd, str(Dir('#'))]
group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))
        
Return('group')
