from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]
LIBS = []
LIBPATH = [cwd]
list = os.listdir(GetCurrentDir())
print(list)
if 'libtouch_gcc.a' in list:
    LIBS = ['libtouch_gcc.a']
    src = []

group = DefineGroup('touch', src, depend = ['BSP_USING_TOUCH'],LIBS = LIBS, LIBPATH = LIBPATH, CPPPATH = CPPPATH)

Return('group')
