Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

if rtconfig.PLATFORM == 'gcc':
    src += Glob('*_gcc.S')

group = DefineGroup('LIBARCH', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
