from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
path = [cwd + '/inc']

libcwd = str(Dir('#'))
libinspath = libcwd + '/libraries/lib'

group = DefineGroup('gh', src, depend = [''], CPPPATH = path, LIBINSPATH = libinspath)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))
        
Return('group')
