scons.args: &scons
    scons_arg:
      - '--strict'
# ------ component CI ------
component.cherryusb_cdc:
    kconfig:
      - CONFIG_RT_USING_CHERRYUSB=y
      - CONFIG_RT_CHERRYUSB_DEVICE=y
      - CONFIG_RT_CHERRYUSB_DEVICE_KINETIS_MCX=y
      - CONFIG_RT_CHERRYUSB_DEVICE_CDC_ACM=y
      - CONFIG_RT_CHERRYUSB_DEVICE_TEMPLATE_CDC_ACM=y