peripheral.MMC:
    kconfig:
      - CONFIG_BSP_USING_DW_SPI=y
      - CONFIG_DW_SPI_IRQ_BASE=19
      - CONFIG_DW_SPI_BASE_ADDR=0x20320000
      - CONFIG_DW_SPI_MAX_FREQ=62500000
      - CONFIG_BSP_USING_MMC=y

rtsmart:
    kconfig:
      - CONFIG_RT_USING_SMART=y
      - CONFIG_KERNEL_VADDR_START=0xffffffc000000000
      - CONFIG_ARCH_REMAP_KERNEL=y
      - CONFIG_RT_USING_DFS_PTYFS=y
      - CONFIG_RT_USING_DFS_PROCFS=y
      - CONFIG_RT_USING_PAGECACHE=y
      - CONFIG_RT_PAGECACHE_COUNT=4096
      - CONFIG_RT_PAGECACHE_ASPACE_COUNT=1024
      - CONFIG_RT_PAGECACHE_PRELOAD=4
      - CONFIG_RT_PAGECACHE_HASH_NR=1024
      - CONFIG_RT_PAGECACHE_GC_WORK_LEVEL=90
      - CONFIG_RT_PAGECACHE_GC_STOP_LEVEL=70
      - CONFIG_RT_USING_POSIX_EPOLL=y
      - CONFIG_RT_USING_POSIX_SIGNALFD=y
      - CONFIG_RT_SIGNALFD_MAX_NUM=10
      - CONFIG_RT_USING_LWP=y
      - CONFIG_LWP_USING_RUNTIME=y
      - CONFIG_RT_LWP_MAX_NR=30
      - CONFIG_LWP_TASK_STACK_SIZE=16384
      - CONFIG_RT_CH_MSG_MAX_NR=1024
      - CONFIG_LWP_TID_MAX_NR=64
      - CONFIG_RT_LWP_SHM_MAX_NR=64
      - CONFIG_RT_USING_LDSO=y
      - CONFIG_LWP_USING_TERMINAL=y
      - CONFIG_LWP_PTY_MAX_PARIS_LIMIT=64
      - CONFIG_BSP_USING_DW_SPI=y
      - CONFIG_DW_SPI_IRQ_BASE=19
      - CONFIG_DW_SPI_BASE_ADDR=0x20320000
      - CONFIG_DW_SPI_MAX_FREQ=62500000
      - CONFIG_BSP_USING_MMC=y