Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

#remove other no use files
if GetDepend('SAM_I2C_EXAMPLE') == False:
    SrcRemove(src, ['sam_i2c.c'])

if GetDepend('SAM_LWIP_EXAMPLE') == False:
    SrcRemove(src, ['sam_gmac.c'])

# You can select chips from the list above
CPPDEFINES = []

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
