import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
cmsis/cm4/device_support/system_at32f402_405.c
drivers/src/at32f402_405_acc.c
drivers/src/at32f402_405_adc.c
drivers/src/at32f402_405_can.c
drivers/src/at32f402_405_crc.c
drivers/src/at32f402_405_crm.c
drivers/src/at32f402_405_debug.c
drivers/src/at32f402_405_dma.c
drivers/src/at32f402_405_ertc.c
drivers/src/at32f402_405_exint.c
drivers/src/at32f402_405_flash.c
drivers/src/at32f402_405_gpio.c
drivers/src/at32f402_405_i2c.c
drivers/src/at32f402_405_misc.c
drivers/src/at32f402_405_pwc.c
drivers/src/at32f402_405_qspi.c
drivers/src/at32f402_405_scfg.c
drivers/src/at32f402_405_spi.c
drivers/src/at32f402_405_tmr.c
drivers/src/at32f402_405_usart.c
drivers/src/at32f402_405_usb.c
drivers/src/at32f402_405_wdt.c
drivers/src/at32f402_405_wwdt.c
""")

path = [
    cwd + '/cmsis/cm4/device_support',
    cwd + '/cmsis/cm4/core_support',
    cwd + '/drivers/inc',]

CPPDEFINES = ['USE_STDPERIPH_DRIVER']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
