import os
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
CubeMX_Config/Src/stm32f1xx_hal_msp.c
''')


path =  [cwd]
path += [cwd + '/CubeMX_Config/Inc']
path += [cwd + '/ports']



group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)
Return('group')
