# Phytium Iot gitlab-ci.yml file

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" 

stages:
  - compile_stage           # 编译阶段
  - test_stage              # 测试阶段

variables:
  TERM: xterm  # 设置终端类型
  
all_soc_compile:
  stage: compile_stage
  script:
    - cd $CI_PROJECT_DIR/bsp/phytium/libraries/tools/auto_test
    - python3 auto_compile.py
  tags:
    - rtthread test
  allow_failure: true
  when: manual

all_soc_test:
  stage: test_stage
  script:
    - cd /home/gitlab-runner/test_tool
    - python3 set_common_info.py /home/gitlab-runner/test_tool/phytium-test-tools/test_tool/config_info/common.json rtthread
    - cd $CI_PROJECT_DIR/bsp/phytium/libraries/tools/auto_test
    - python3 auto_compile.py
    - cd /home/gitlab-runner/test_tool/phytium-test-tools/test_tool
    - python3 gitlab_pipeline_rtthread_board_test.py
  tags:
    - rtthread test
  allow_failure: true
  when: manual
