#
# Copyright (c) 2006-2023, RT-Thread Development Team
#
# SPDX-License-Identifier: Apache-2.0
#
# Change Logs:
# Date           Author       Notes
# 2025-05-15     Supper Thomas show the PR size 
#

name: PR status

# 这个ci主要用来显示当前的PR对于master节点上的增加的code size有多大
on:
  pull_request:
    branches:
      - master

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-24.04
    name: PR status show

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.8

      - name: fetch origin
        shell: bash
        run: |
          git config --global http.postBuffer 524288000
          git remote -v
          git fetch origin
          git branch
          git branch -a

      - name: PR status show
        if: ${{ success() }}
        shell: bash
        run: |
          python tools/ci/git_diff_status_show.py origin/master

