name: pkgs_test

on:
    push:
        branches:
          - master
        paths-ignore:
          - documentation/**
          - '**/README.md'
          - '**/README_zh.md'
    pull_request:
        branches:
          - master
        paths-ignore:
          - documentation/**
          - '**/README.md'
          - '**/README_zh.md'
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    change:
        uses: RT-Thread/pkgs-test/.github/workflows/pkgs-action.yml@main
        if: github.repository_owner == 'RT-Thread'
        with:
            rt-thread-versions: "branch:master"
            test-specific-pkgs: true
            pkgs: |
                hello