from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split('''
board.c
''')

# add gpio code
if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']

# add serial driver code
if  GetDepend('BSP_USING_UART1') or GetDepend('BSP_USING_UART2') or GetDepend('BSP_USING_UART3'):
    src += ['drv_uart.c']

# add spi driver code
if  GetDepend('BSP_USING_SPI1') or GetDepend('BSP_USING_SPI2'):
    src += ['drv_spi.c']

# add i2c driver code
if  GetDepend('BSP_USING_I2C1') or GetDepend('BSP_USING_I2C2'):
    src += ['drv_i2c.c']

# add pwm driver code
if GetDepend('BSP_USING_PWM1') or GetDepend('BSP_USING_PWM2') or GetDepend('BSP_USING_PWM3') or GetDepend('BSP_USING_PWM4') or GetDepend('BSP_USING_PWM_GP16C2T1') or GetDepend('BSP_USING_PWM_GP16C2T4'):
    src += ['drv_pwm.c']

# add hwtimer driver code
if GetDepend('BSP_USING_HWTIMER1'):
    src += ['drv_hwtimer.c']

# add rtc driver code
if GetDepend(['BSP_USING_RTC']):
    src += ['drv_rtc.c']

# add adc driver code
if GetDepend(['BSP_USING_ADC']):
    src += ['drv_adc.c']

CPPPATH = [cwd]
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
