from building import *

cwd = GetCurrentDir()
src = Split('''
startup_LPC54114_cm4.s
''')

group = DefineGroup('Libraries', src, depend = [''], LIBS=['libpower_cm4_hardabi'], LIBPATH=[cwd])

Return('group')
