from building import *

group = []

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include', cwd + '/../../../../components/drivers/pci', cwd + '/../../../../components/drivers/pci/host/dw']

src = []

if GetDepend(['RT_PCIE_ROCKCHIP']):
    src += ['pcie-rockchip-host.c']

if GetDepend(['RT_PCIE_ROCKCHIP_EP']):
    src += ['pcie-rockchip-ep.c']

if GetDepend(['RT_PCIE_ROCKCHIP']) or GetDepend(['RT_PCIE_ROCKCHIP_EP']):
    src += ['pcie-rockchip.c']

if GetDepend(['RT_PCI_DW_ROCKCHIP']):
    src += ['pcie-dw-rockchip.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
