from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
src += Glob('*.s')
path = [cwd, cwd + '../../../include', cwd + '/../libraries/inc', cwd + '/../drivers']

group = DefineGroup('CPU', src, depend = [''], CPPPATH = path)

Return('group')
