from building import *

cwd = GetCurrentDir()
src = Split('''
startup_LPC54114_cm4.s
''')

group = DefineGroup('Libraries', src, depend = [''], LIBS=['iar_lib_power'], LIBPATH=[cwd])

Return('group')
