# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]
group = []

# armv7-a files
group += SConscript(os.path.join(cwd, '../armv7-a/SConscript'))
# Specific cpu files
group += DefineGroup('cpu', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
