from building import *
Import('rtconfig')

src = Glob('*.c') + Glob('*.cpp') + Glob('arch/*.c')
cwd = GetCurrentDir()
group   = []
CPPPATH = [cwd]

if rtconfig.PLATFORM == 'gcc':
    group = DefineGroup('Libc', src, 
        depend = ['RT_USING_MODULE'], 
        CPPPATH = CPPPATH)

Return('group')
