from building import *
Import('rtconfig')

src = Glob('*.c') + Glob('*.cpp') + Glob('arch/*.c')
cwd = GetCurrentDir()
group   = []
CPPPATH = [cwd]

group = DefineGroup('libc', src, depend = ['RT_USING_MODULE'], CPPPATH = CPPPATH)

Return('group')
