import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
CMSIS/device/system_n32g45x.c
n32g45x_std_periph_driver/src/n32g45x_gpio.c
n32g45x_std_periph_driver/src/n32g45x_rcc.c
n32g45x_std_periph_driver/src/n32g45x_exti.c
n32g45x_std_periph_driver/src/misc.c
''')

if GetDepend(['RT_USING_SERIAL']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_usart.c']

if GetDepend(['RT_USING_I2C']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_spi.c']

if GetDepend(['RT_USING_CAN']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_can.c']

if GetDepend(['BSP_USING_ETH']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_eth.c']

if GetDepend(['RT_USING_ADC']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_adc.c']

if GetDepend(['RT_USING_DAC']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_dac.c']

if GetDepend(['RT_USING_HWTIMER']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_tim.c']

if GetDepend(['RT_USING_RTC']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_rtc.c']
    src += ['n32g45x_std_periph_driver/src/n32g45x_pwr.c']

if GetDepend(['RT_USING_WDT']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_wwdg.c']
    src += ['n32g45x_std_periph_driver/src/n32g45x_iwdg.c']

if GetDepend(['BSP_USING_RTC']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_bkp.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['n32g45x_std_periph_driver/src/n32g45x_sdio.c']

if GetDepend(['RT_USING_BSP_USB']):
    path += [cwd + '/n32g45x_usbfs_driver/inc']
    src  += [cwd + '/n32g45x_usbfs_driver/src']

path = [
    cwd + '/CMSIS/device',
    cwd + '/CMSIS/core',
    cwd + '/n32g45x_std_periph_driver/inc',]

CPPDEFINES = ['USE_STDPERIPH_DRIVER']



group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
