Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
src = ['Device/FUJISTU/MB9BF50x/Source/system_mb9bf50x.c']

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    src += ['Device/FUJISTU/MB9BF50x/Source/G++/startup_mb9bf50x.S']
elif rtconfig.CROSS_TOOL == 'keil':
    src += ['Device/FUJISTU/MB9BF50x/Source/ARM/startup_mb9bf50x.S']
elif rtconfig.CROSS_TOOL == 'iar':
    src += ['Device/FUJISTU/MB9BF50x/Source/IAR/startup_mb9bf50x.S']

CPPPATH = [cwd + '/Device/FUJISTU/MB9BF50x/Include']

CPPPATH += [cwd + '/CMSIS/Include']

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
