from building import *

cwd = GetCurrentDir()
src = []
path =  [cwd]

if  GetDepend('SOC_RISCV_FAMILY_CH32'):

    if GetDepend('BSP_USING_GPIO'):
        src += ['drv_gpio.c']

    if GetDepend('BSP_USING_UART'):
        src += ['drv_usart.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

Return('group')
