# ------ device CI ------
devices.adc:
    kconfig:
      - CONFIG_BSP_USING_ADC=y
      - CONFIG_BSP_USING_ADC1=y
      - CONFIG_BSP_ADC1_USING_DMA=y
devices.crypto:
    kconfig:
      - CONFIG_BSP_USING_HWCRYPTO=y
      - CONFIG_BSP_USING_UQID=y
      - CONFIG_BSP_USING_RNG=y
      - CONFIG_BSP_USING_CRC=y
      - CONFIG_BSP_USING_HASH=y
devices.dac:
    kconfig:
      - CONFIG_BSP_USING_DAC=y
      - CONFIG_BSP_USING_DAC1=y
devices.flash:
    kconfig:
      - CONFIG_BSP_USING_ON_CHIP_FLASH=y
      - CONFIG_RT_USING_FAL=y
      - CONFIG_RT_USING_SPI=y
      - CONFIG_RT_USING_SFUD=y
devices.gpio:
    kconfig: 
      - CONFIG_BSP_USING_GPIO=y
devices.hwtimer:
    kconfig:
      - CONFIG_BSP_USING_HWTIMER=y
      - CONFIG_BSP_USING_TMRA_1=y
devices.i2c:
    kconfig:
      - CONFIG_BSP_USING_I2C=y
      - CONFIG_BSP_USING_I2C1=y
      - CONFIG_BSP_I2C1_TX_USING_DMA=y
      - CONFIG_BSP_I2C1_RX_USING_DMA=y
devices.input_capture:
    kconfig:
      - CONFIG_BSP_USING_INPUT_CAPTURE=y
      - CONFIG_BSP_USING_INPUT_CAPTURE_TMR6=y
      - CONFIG_BSP_USING_INPUT_CAPTURE_TMR6_1=y
devices.mcan:
    kconfig:
      - CONFIG_BSP_USING_MCAN=y
      - CONFIG_BSP_USING_MCAN1=y
      - CONFIG_RT_CAN_USING_CANFD=y
      - CONFIG_RT_CAN_USING_HDR=y
devices.pm:
    kconfig:
      - CONFIG_BSP_USING_PM=y
      - CONFIG_IDLE_THREAD_STACK_SIZE=512
devices.pulse_encoder_tmr6:
    kconfig:
      - CONFIG_BSP_USING_PULSE_ENCODER=y
      - CONFIG_BSP_USING_TMR6_PULSE_ENCODER=y
      - CONFIG_BSP_USING_PULSE_ENCODER_TMR6_1=y
devices.pulse_encoder_tmra:
    kconfig:
      - CONFIG_BSP_USING_PULSE_ENCODER=y
      - CONFIG_BSP_USING_TMRA_PULSE_ENCODER=y
      - CONFIG_BSP_USING_PULSE_ENCODER_TMRA_1=y
devices.pwm_tmr4:
    kconfig:
      - CONFIG_BSP_USING_PWM=y
      - CONFIG_BSP_USING_PWM_TMR4=y
      - CONFIG_BSP_USING_PWM_TMR4_1=y
      - CONFIG_BSP_USING_PWM_TMR4_1_OUH=y
      - CONFIG_BSP_USING_PWM_TMR4_1_OUL=y
devices.pwm_tmr6:
    kconfig:
      - CONFIG_BSP_USING_PWM=y
      - CONFIG_BSP_USING_PWM_TMR6=y
      - CONFIG_BSP_USING_PWM_TMR6_1=y
      - CONFIG_BSP_USING_PWM_TMR6_1_A=y
      - CONFIG_BSP_USING_PWM_TMR6_1_B=y
devices.pwm_tmra:
    kconfig:
      - CONFIG_BSP_USING_PWM=y
      - CONFIG_BSP_USING_PWM_TMRA=y
      - CONFIG_BSP_USING_PWM_TMRA_1=y
      - CONFIG_BSP_USING_PWM_TMRA_1_CH1=y
      - CONFIG_BSP_USING_PWM_TMRA_1_CH2=y
devices.qspi:
    kconfig:
      - CONFIG_BSP_USING_QSPI=y
      - CONFIG_BSP_QSPI_USING_DMA=y
      - CONFIG_BSP_QSPI_USING_SOFT_CS=y
devices.rtc:
    kconfig:
      - CONFIG_BSP_USING_RTC=y
      - CONFIG_RT_USING_ALARM=y
devices.soft_i2c:
    kconfig:
      - CONFIG_BSP_USING_I2C=y
      - CONFIG_BSP_USING_I2C1_SW=y
devices.spi:
    kconfig:
      - CONFIG_BSP_USING_SPI=y
      - CONFIG_BSP_USING_SPI1=y
      - CONFIG_BSP_SPI1_TX_USING_DMA=y
      - CONFIG_BSP_SPI1_RX_USING_DMA=y
      - CONFIG_BSP_SPI_USING_DMA=y
      - CONFIG_RT_USING_DFS=y
      - CONFIG_RT_USING_DFS_ELMFAT=y
devices.uart_v1:
    kconfig:
      - CONFIG_RT_USING_SERIAL_V1=y
      - CONFIG_BSP_USING_UART=y
      - CONFIG_BSP_USING_UART1=y
      - CONFIG_RT_SERIAL_USING_DMA=y
      - CONFIG_BSP_UART1_RX_USING_DMA=y
      - CONFIG_BSP_UART1_TX_USING_DMA=y
devices.uart_v2:
    kconfig:
      - CONFIG_RT_USING_SERIAL_V2=y
      - CONFIG_BSP_USING_UART=y
      - CONFIG_BSP_USING_UART1=y
      - CONFIG_RT_SERIAL_USING_DMA=y
      - CONFIG_BSP_UART1_RX_USING_DMA=y
      - CONFIG_BSP_UART1_TX_USING_DMA=y
devices.watchdog_swdt:
    kconfig:
      - CONFIG_BSP_USING_WDT_TMR=y
      - CONFIG_BSP_USING_SWDT=y
devices.watchdog_wdt:
    kconfig:
      - CONFIG_BSP_USING_WDT_TMR=y
      - CONFIG_BSP_USING_WDT=y

# ------ peripheral CI ------
peripheral.spi_flash:
    kconfig:
      - CONFIG_BSP_USING_SPI_FLASH=y
