import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = []

src += Glob('ES32F36xx_ALD_StdPeriph_Driver/Source/*.c')

#add for startup script
if rtconfig.PLATFORM in ['gcc']:
     src = src + ['CMSIS/Device/EastSoft/ES32F36xx/Startup/gcc/startup_es32f36xx.S']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
     src = src + ['CMSIS/Device/EastSoft/ES32F36xx/Startup/keil/startup_es32f36xx.s']
elif rtconfig.PLATFORM in ['iccarm']:
     src = src + ['CMSIS/Device/EastSoft/ES32F36xx/Startup/iar/startup_es32f36xx.s']

path = [cwd + '/CMSIS/Device/EastSoft/ES32F36xx/Include',
        cwd + '/CMSIS/Include',
        cwd + '/ES32F36xx_ALD_StdPeriph_Driver/Include']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, CPPDEFINES = ['ES32F36xx'])

Return('group')
