from building import *

src = []
cwd = GetCurrentDir()
path = [cwd]
CPPDEFINES = []

if GetDepend(['BSP_USING_LCD_MIPI']):

    path += [cwd + '/display', cwd + '/display/dc', cwd + '/display/fbdev', cwd + '/display/mipi_dsi_cmd']

    src += ['fsl_video_common.c']
    src += ['display/fbdev/fsl_fbdev.c']
    src += ['display/mipi_dsi_cmd/fsl_mipi_dsi_cmd.c']

    if GetDepend(['BSP_USING_LCDIFV2']):
        src += ['display/dc/lcdifv2/fsl_dc_fb_lcdifv2.c']
        path += [cwd + '/display/dc/lcdifv2']
    elif GetDepend(['BSP_USING_ELCDIF']):
        src += ['display/dc/elcdif/fsl_dc_fb_elcdif.c']
        path += [cwd + '/display/dc/elcdif']

    if GetDepend(['DISPLAY_USING_RK055AHD091']):
        src += ['display/rm68200/fsl_rm68200.c']
        path += [cwd + '/display/rm68200']
    elif GetDepend(['DISPLAY_USING_RK055IQH091']):
        src += ['display/rm68191/fsl_rm68191.c']
        path += [cwd + '/display/rm68191']
    elif GetDepend(['DISPLAY_USING_RK055MHD091']):
        src += ['display/hx8394/fsl_hx8394.c']
        path += [cwd + '/display/hx8394']

    group = DefineGroup('video', src, depend = [''], CPPPATH = path, CPPDEFINES=CPPDEFINES)

    Return('group')
else:
    empty_list = []
    Return('empty_list')