from building import *

group   = []

if not GetDepend(['RT_GRAPHIC_FB']):
    Return('group')

cwd     = GetCurrentDir()
list    = os.listdir(cwd)
CPPPATH = [cwd + '/../../include']

src     = []

if GetDepend(['RT_GRAPHIC_FB_SIMPLE']):
    src += ['fb-simple.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
