Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()

# add the general drivers.
src     = Glob("*.c") + Glob("*.cpp") + Glob("*.S")

CPPPATH = [cwd]
group   = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
