# RT-Thread building script for component

from building import *


Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [ cwd ]

group = DefineGroup('board', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
